### ISSUE TITLE
Are W3C hosts members of W3C?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#10]
Transferred from https://www.w3.org/community/w3process/track/issues/168
State: Open

**Comment by dwsinger** [comment]
section 2.2 of https://www.w3.org/2017/Process-20170301/ says:

"Note: W3C is not currently incorporated. For legal contracts, W3C is represented by four "Host" institutions: Beihang University, the European Research Consortium for Informatics and Mathematics (ERCIM), Keio University, and the Massachusetts Institute of Technology (MIT). Within W3C, the Host institutions are governed by hosting agreements; the Hosts themselves are not W3C Members."

Which means that the question as posed is decided. However, if they are not members but hosts, then what are the consequences? One assumes that they do not get to vote on questions that are posed to Members, but maybe (at some point) we should work out what they can and can't do (and why they have AC reps, etc.)

**Comment by dwsinger** [comment]
We need to differentiate clearly when actions are reserved to Members and when actions are reserved to the Advisory Committee. There are contradictions: 2.1 says that the AC has a rep. from each Member organization. I would suggest that the Hosts should discuss this at their next decennial meeting? What do they think is the right state?

**Comment by dbaron** [comment]
Another related issue is whether the [patent licensing requirements](https://www.w3.org/Consortium/Patent-Policy-20170801/#sec-W3C-RF-license) that apply to Team representatives in a working group require licensing of patents owned by the hosts (rather than individually by the Team representative)

**Comment by dwsinger** [comment]
at least three issues here (a) IPR commitments; (b) voting (c) can host employees join WGs etc.?

we leave for the team to explore with the hosts how to resolve the IPR question.

**Comment by jeffjaffe** [comment]
I plan to focus on (a) first.

I believe our practice is that hosts do not vote.  We may want to clarify in Process 2019.

We should look at (c) after we have looked at (a).

**Comment by Kometo2** [comment]
More patent info is needed!

**Comment by jeffjaffe** [comment]
I propose that we close this issue for now.  In the time it takes to resolve it we might become a legal entity.

We may open a new issue for the legal entity time frame.  Status of "legal entity" and status of "Host partners of legal entity".  We can open that issue now, but it might make sense to wait until we have further approved definition for the legal entity.

**Comment by chaals** [comment]
The issue of hosts "voting" as members should be addressed - since it was what gave rise to this issue.

I would suggest that while the hosts do not make the IPR commitment of members, they do not have the rights of members to advise the W3C.

**Comment by michaelchampion** [comment]
I would suggest that the right to influence W3C should be purchased with a patent commitment.  Until the hosts participate as members, thus making patent commitments on everything the team participates in, I strongly oppose giving them voting rights.

I agree with Jeff the best way to address this problem is to launch the legal entity that employs the team.

**Comment by caribouW3** [comment]
Not sure I understand your POV: are you saying that any staff contact employer should make a PP commitment when the staff joins a WG, instead of an individual commitment from the person?

Non-Staff people employed by W3C hosts already join WGs with the same level of PP commitment as any other member representative (the host AC rep formally joins and nominates them).

**Comment by michaelchampion** [comment]
> are you saying that any staff contact employer should make a PP commitment when the staff joins a WG, instead of an individual commitment from the person?

Yes.  The hosts are research institutions that presumably have lots of patents.   Since they are not W3C members, they do not make royalty-free patent commitments when their employees (the team) participate in working groups. It would be extremely destructive to W3C's reputation if one of the hosts filed an infringement suit on someone implementing a Recommendation that touches on a host's patents.   I would prefer to avoid this scenario by getting the employers of the staff contacts to make the same RF patent commitments that employers of other WG members make.

**Comment by dwsinger** [comment]
Given that we may be hybrid even after the LE, for some period, I fear we need to leave this open to remind us that we have concerns over host (a) voting and (b) IPR commitments, at least

**Comment by caribouW3** [comment]
> It would be extremely destructive to W3C's reputation if one of the hosts filed an infringement suit on someone implementing a Recommendation that touches on a host's patents. I would prefer to avoid this scenario by getting the employers of the staff contacts to make the same RF patent commitments that employers of other WG members make.

I think W3C fellows might be a more problematic case. I don't know exactly what's the legal contract between their employer and W3C. 
It is also important to note that not all Staff is employed by a host, so having explicit commitments in some cases and not in others would reveal private information about their employment status, which is certainly not desirable.

**Comment by dwsinger** [comment]
Universities sell patents, or sell rights to exercise and enforce, to other entities. That sale needs to come with the RF commitment to the W3C. So even if the Uni wouldn't do anything, that's not assured with those who acquire -- unless the commitment is explicit.

**Comment by michaelchampion** [comment]
@caribouW3 -- good point about W3C Fellows.  Presumably, the team should not accept the services of a Fellow if their employer is not willing to join WGs or otherwise make patent commitments to the groups they participate in at W3C.

**Comment by caribouW3** [comment]
Explicit commitment means that each staff would have to be nominated by an AC rep instead of joining groups by themselves. @swickr might be able to say more on host AC role and potential consequences of new legal obligations. It certainly makes sense to have this when the LE exists, but currently it might be already covered by host agreements.

**Comment by jeffjaffe** [comment]
@caribouW3 @michaelchampion Fellows come from W3C Member organizations.

https://www.w3.org/Consortium/Recruitment/Fellows

**Comment by caribouW3** [comment]
Sure, but when they join a group their affiliation is W3C Staff.

**Comment by michaelchampion** [comment]
The question at hand is whether the member organization sponsoring a fellow is making an RF patent commitment to the specs the fellow works on. There’s no mention of patents in the link below.  I agree that is orthogonal to the issue as formulated.

**Comment by jeffjaffe** [comment]
Should be superseded by legal entity discussion.

**Comment by dwsinger** [comment]
closing as overtaken by circumstances (the Legal Entity work means that this will, we hope, soon no longer be relevant)
