### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by nrooney** [w3c/w3process#116]
After speaking with a few people in the community it seems "Transparency" is a hot topic. Largely, these individuals are stating that either the process or W3C isn't transparent enough. This may or may not be the case; I actually think the process allows for transparency but the overhead of reading and understanding the process is leading to lack-of-transparency assumption.

I currently reviewing the process; so I can make some comments on the transparency when done. I am also writing a "Process Doc for Busy People" where I can add something about transparency in the document there. I also volunteer to write some stuff on Transparency in the Process generally, which can be promoted, spoken at meetings, put the blog, or discussed and shared in other forums to help people understand transparency in W3C.

Please leave other comments related to transparency in this issue; especially if you have read the process document and do not believe the process allows the w3c to be transparent enough.

**Comment by vfournier17** [comment]
"Transparency" is one of those "buzz words" that, when you ask people what it means in a particular scenario, they have no idea.  We should find out from people in the community what needs to be more "transparent" - what are they not seeing, what needs to be more transparent, and how.  If it's not transparent because they aren't taking the time to read information, look at the W3C website, or attend meetings, that's not the W3C's fault.  I don't think just offering up writings on "transparency" would be particularly helpful, without finding out what the community wants to know.

**Comment by nrooney** [comment]
@torgo mentioned this at some point, maybe he can elaborate.

**Comment by michaelchampion** [comment]
Overall W3C is pretty transparent as standards organizations go.  There is some member-confidential stuff, but not nearly as much as 20 years ago.  

I recall a couple complaints about "transparency" recently, all having to do with the operation of the team (or the "Director", which is in fact the team in most cases):
- The processing of charter comments to produce a final charter is done opaquely by the team
- The "Director" discussions about the resolution of formal objections are opaque
- The team does not share any data about elections except the identity of the winners

The last one is something I find annoying, but a) this isn't discussed in the Process Document so it arguably is out of scope of this CG and b) some people have a principled concern that if more data were shared, it could embarass losing candidates / discourage people from running for fear of embarassment.

**Comment by frivoal** [comment]
> The processing of charter comments to produce a final charter is done opaquely by the team

discussed in: https://github.com/w3c/w3process/issues/182

> The "Director" discussions about the resolution of formal objections are opaque

I think that's largely the same topic as the previous one when it relates to charters. But this is also relevant on specs. Do we need to open a separate issue for that?

> The team does not share any data about elections except the identity of the winners

That's a subset of the whole voting topic, which should be discussed in the AB.

----

This issue is very broad, I think we should close it, and open sub issues on specific points, as needed. (I do not mean we don't need transparency, I just want things to be actionable).

**Comment by frivoal** [comment]
agenda+ to propose what I said in the above comment.

**Comment by chaals** [comment]
@frivoal 

> This issue is very broad, I think we should close it, and open sub issues on specific points, as needed. (I do not mean we don't need transparency, I just want things to be actionable).

Agreed.
