### ISSUE TITLE
Revert section 3.4 default in WG voting rules to Process 2017

### ISSUE THREAD

**Issue by tantek** [w3c/w3process#121]
In resolving issue issue #24 it appears we introduced (likely) unintended changes to the default voting rules for *in* working groups from one per organization to one per participant.

Since no substantial use-case or convincing reasoning was provided for *this* aspect of that change, it should be immediately reverted, and advocates for making such a change explicit in process 2018 should open a separate (new) issue to explain and justify such a change.

Thanks to @dbaron for noticing. cc: @michaelchampion @chaals

**Comment by riannella** [comment]
Fully support the revision back to one vote per member.

**Comment by chaals** [comment]
It was not unintended. It was proposed by @michaelchampion (although he seems to have changed his mind since), noted in the PR and explicitly pointed out in the changes section.

I'm personally in favour of the change, but don't think it is critical. I do not plan to revert it immediately, waiting on the consensus after AC review.

**Comment by tantek** [comment]
Hmm, it may not have been unintended by the committer, however, I'm fairly certain (would bet a beverage) that everyone else on the AB proposing/agreeing/reviewing this change (including @michaelchampion) intended *only* to impact the STV related voting wording e.g. for AB and TAG elections, and NOT have *any* impact on in-WG voting procedures, defaults etc. That's why I think this aspect ought to be reverted - this aspect did not have consensus to be changed thus was changed in error.

**Comment by dwsinger** [comment]
Yes, let's change the formal *vote* to per-org, and mention "straw polls" for other minor operational decisions, which the chair can structure and run to suit the question.

**Comment by gsnedders** [comment]
If we're doing votes on a per-org basis, how do Invited Experts fit into this? Do they count as individual orgs, do they have no input, or do the Invited Experts collectively have one vote (and then how would it be decided how that vote is cast)?

**Comment by dbaron** [comment]
I think what the [current process says](https://www.w3.org/2017/Process-20170301/#Votes) is fine, which is that invited experts get individual votes unless the WG's charter says otherwise.

**Comment by michaelchampion** [comment]
The proposed language for 3.4 doesn't specify whether invited experts not affiliated with an organization would get to vote, just that invited experts who are affiliated with an org get one vote per org.  As I understand it, this discussion is about default voting rules if a charter doesn't specify them.   I think it depends very much on the specific community gathered in a WG whether invited experts should get a formal vote or not.  As I recall from long-ago groups that did use voting regularly, invited experts didn't get a formal vote, but did participate in informal consensus assessments.   Other communities might depend so much on invited experts that this would distort the idea of using voting to assess consensus. 

I think we should not make changes to 3.4 in Process 2018 because there are too many contentious issues here.  
- Obviously there is much pushback on changing from one vote per member to one vote per participant.  @chaals, I believe I made the proposal for one person, one vote in https://github.com/w3c/w3process/issues/24#issuecomment-328568983 BUT that was in the context of proposing a whole list of things.  I could live with one vote per participant if all those other default voting rules were adopted, but not if it is cherrypicked from the list.
- I continue to be skeptical that the process document should specify default voting rules when the appropriate voting process depends very much on the culture and composition of specific WGs.
- If the process document does specify defaults, I strongly believe the defaults for substantive voting should be quite onerous so as to discourage using voting except as a last resort, e.g. with high quorums and/or supermajorities..  See https://github.com/w3c/w3process/issues/24#issuecomment-328568983 
- Process 2017 is adequately clear that straw polls to assess the distribution of opinion or make decisions on procedural matters ("when do we go to lunch", "where do we meet") are OK.

**Comment by dwsinger** [comment]
see my comments on the original issue; I think we should not change any other aspect of 3.4 than simply stating what the defaults are for things that are variable by charter.

**Comment by dwsinger** [comment]
the revert was accepted
