### ISSUE TITLE
When are tests required?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#129]
Currently WGs can transition a Rec track document to CR without having defined tests. However this means that either test creation never happens and the spec can never exit CR. It also means that there's a missed opportunity to double-check every normative requirement with a test, which is good practice for establishing clearly what the requirement is.

Conversely, requiring tests raises the bar for transition to CR, which people likely don't want.

Regardless, I propose to require the test suite to be complete for transition to CR, as part of the exit criteria, and to recommend a good practice that whenever any feature or normative requirement is introduced or modified, an accompanying test is generated.

**Comment by nrooney** [comment]
Ah! We're having this discussion in #157! I'll add your thoughts to this issue, and close this one. Apologies I should have started to add my original comments here rather than start a new issue, but as I have circulated that issue to interested parties, it seems sensible to keep that one going and close this one.
