### ISSUE TITLE
Rationale for relying on GitHub

### ISSUE THREAD

**Issue by retog** [w3c/w3process#132]
I was wondering about the discussions that took place when choosing GitHub. 

On https://www.w3.org/wiki/GitHub I found only the unanswered question:
"Is there a policy document (or similar) covering the use of Github versus W3C-hosted version control?"

Especially interested in a discussion on whether it is acceptable for the work of W3C to depend on a company that "has the right to suspend or terminate your access to all or any part of the Website at any time, with or without cause, with or without notice".

A related question: is a backup strategy that includes issues and PR implemented?

**Comment by tguild** [comment]
The adoption of GH was more from W3C community grassroots instead of a top down decision. Instead of pushing back we transitioned from acceptance to support and heading towards requiring it for consistency across groups. We do have a complete backup strategy implemented.

**Comment by dwsinger** [comment]
@retog is there a process document action or question here, or should we defer this to the AB for governance in general?

**Comment by chaals** [comment]
> whether it is acceptable for the work of W3C to depend on a company that "has the right to suspend or terminate your access to all or any part of the Website at any time, with or without cause, with or without notice"

seems like a specific example of a class of questions about what obligations W3C will allow working groups to impose on participants beyond those already in the member agreement, Process, etc.

(I don't have a proposed answer at this stage, but note that there various practical issues in this vein arise...)

**Comment by retog** [comment]
@dwsinger I'm not sure, that I understand your question. If there was a policy discussion then it should be documented, if there was none then I think we should have such a discussion. 

I think beside @chaals question about the obligations imposed by working group on participants it also raises  questions about the state of the Web. Is the Web itself a tool for collaboration and sharing or mainly a mean providing access to services like GitHub that allow collaboration and sharing?

**Comment by dwsinger** [comment]
@retog sorry; this GitHub repo is about managing the words in the Process Document itself. My suspicion is that this is a general issue that needs AB and AC debate on the general policy question, and is unlikely to affect the Process Document. The AB has already started (before your issue) struggling with the question of what external tools and associated agreements may be required by the consortium, by the way. So, I think we should refer this to the AB as a policy question and close it here, as it's not a Process Document question.

**Comment by nrooney** [comment]
@tguild stated that a backup strategy is implemented, if there is a request for more information on this then please do ask him (@tguild maybe something to give as a blog post to point to when this question gets asked?). 

@retog I've asked before about whether this move to github is a hard-policy or a soft one; the answer I got (and support) is that it is "encouraged but not enforced". If people feel otherwise to this then it's probably a discussion to bring to AC, as it'll be the right place to debate it there. Then, if the AC believe something on the process needs to change to reflect this we can bring it in here. 

In which case I'll close this case. I will also bring this us on the next AB call as a suggested item for the AC meeting, would that be ok?

**Comment by retog** [comment]
@tguild having ab blog post on the backup strategy that includes links to the used tools and scripts would be nice.
