### ISSUE TITLE
Concerns about Amended Recommendations

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#137]
From Andreas in AC review:

### Change
* Section 6.7.2
* URL: https://www.w3.org/2017/11/Process-20171102#revised-rec
* Description: W3C can produce an Amended Recommendation to update a Recommendation, without adding new features analogous to the way a Working Group produces an Edited Recommendation.

### Comment
Although this is not marked as blocking comment (to not disrupt the process), there are strong concerns regarding this change. The intent, to bug fix a recommendation when the responsible working group does not exist anymore, is understandable. But the current form leaves a lot of questions open and possibly also gives to much freedom to the W3C team to change a recommendation. The context for an Amended Recommendation need to be better defined. It should be defined which requirements could lead to an Amended Recommendation. What attempts have been made to re-charter a Working Group or at least what have been the reasons to not start such an attempt. The W3C team may not always have the subject matter experts. How do they decide to adopt a change or not? Can an Amended Specification supersede an existing recommendation or make it obsolete?

**Comment by dbaron** [comment]
I wouldn't want to make things too hard, since I feel that good maintenance of specifications is important, and the desire for maintenance is what I think led to the creation of Amended Recommendation.

I would think the goal would be for changes (e.g., incorporation of errata) that are small enough that chartering a new working group wouldn't be appropriate.  Maybe that should be stated explicitly if it isn't already?

Maybe some additional protection might be appropriate, such as:
* explicit sign-off on the changes by a technical reviewer (or two) who was not involved in writing them? (to help address the common problem of "everybody thinks these changes are good at a high level, but nobody actually read them")
* a slightly longer minimum duration for the AC review?

**Comment by dwsinger** [comment]
I think we're going to run with the formal process for the next year, and see how well we do in clearing backlogged maintenance without causing more problems than we're solving. I encourage everyone to watch the process and see whether things slip through cracks.

**Comment by frivoal** [comment]
I share @dwsinger 's concerns about Amended RECs. But also, as far as I know, since the idea was introduced, the W3C has never actually issued an Amended REC. As there have been complaints about the Process being too long, a controversial area that isn't getting used seems to be a good candidate for removal to me.

It was for a time a trendy idea that working groups should be shutdown once they've have accomplished their main goal. I don't believe this is a popular view any more, and that we now generally prefer to keep working groups around when the technology they've specified is in active use, so that they can do maintenance. A number of changes in Process 2020 should make that easier too.

If we really want some way for the Team to do something with specs that no longer have a working group, we could still do away with Amended RECs, and allow the team to annotate out-of-charter RECs with [candidate corrections](https://w3c.github.io/w3process/#candidate-changes)

**Comment by plehegar** [comment]
The Amended Recommendation path was indeed never exercised so far. WebCrypto was the prime example for it but lhas been lacking an individual to do the actual work. Spatial also came close to use it but then is choosing the path to recreate a Working Group instead. I also concur that the latest thiinking is to swiotch WGs into maintenance mode rather than closing them.

**Comment by fantasai** [comment]
@frivoal Don't Candidate Changes also require a WG? I think we should make it easier for WGs to be chartered to or transitioned to maintenance mode, but in cases where there is no one interested in participating in a WG and the Team concludes that a change is necessary, it seems reasonable to allow it. But wouldn't we need to add some allowance in the Process for the Team to make such annotations then?

**Comment by frivoal** [comment]
Candidate changes are class 2 changes, and based on sections 6.2.11.2, the Team can do publish new RECs with class 2 changes:

> … A Working Group, provided there are no votes against the resolution to publish, may request publication of a Recommendation **or W3C may publish a Recommendation** to make this class of change …

I think this could use a bit of editorial tweaking, to say "The Team" instead of "W3C", and probably split it into two sentences to make it easier to read. 6.2.11.1 has similar phrasing, which could be tweaked for readbility as well.

----
6.2.11.1

Current:
>A Working group may request republication of a Recommendation, or if there is no Working Group chartered to maintain a Recommendation W3C may republish the Recommendation, to make corrections that do not result in any changes to the text of the specification. (See class 1 changes.)

Proposed:
>A Working group may request republication of a Recommendation to make corrections that do not result in any changes to the text of the specification. If there is no Working Group chartered to maintain a Recommendation, the Team may republish the Recommendation with such changes on its own initiative. (See class 1 changes.)

----
6.2.11.2

Current:
> Editorial changes to a Recommendation require no technical review of the intended changes. A Working Group, provided there are no votes against the resolution to publish, may request publication of a Recommendation or W3C may publish a Recommendation to make this class of change without passing through earlier maturity levels. (See class 2 changes.)

Proposed:
> A Working Group, provided there are no votes against the resolution to publish, may request publication of a Recommendation to make changes that do not affect conformance (including candidate changes) without passing through earlier maturity levels. If there is no Working Group chartered to maintain a Recommendation, the Team may republish the Recommendation with such changes on its own initiative. (See class 2 changes.)

**Comment by frivoal** [comment]
Maybe this also need the following insertion in 6.1.5
> An erratum may be accompanied by an informative, candidate correction approved by the consensus of the Working Group<ins>, or by the Team If there is no Working Group chartered to maintain this technical report</ins>.

**Comment by frivoal** [comment]
Maybe we also need something in 6.1.4 allowing the Team to maintain errata when there's no WG. This could be done by adding this at the end of the last paragraph (or as a new paragraph after it)

> If there is no Working Group chartered to maintain a technical report, the Team may maintain errata for that technical report.

**Comment by frivoal** [comment]
Resolution recorded at https://www.w3.org/2020/09/16-w3process-minutes.html#x030
