### ISSUE TITLE
Representativity on the TAG

### ISSUE THREAD

**Issue by ylafon** [w3c/w3process#163]
Hi,
The Process2018 text says in 2.5.1:
`A Member organization is permitted at most one participant on the TAG except when having more than one participant is caused by a change of affiliation of an existing participant.`
What happens if a non-member organisation manage to have two people elected ?
Striking 'Member' would solve that.

@chaals added in #118 the following:
> Another aspect of that issue is when an organisation nominates an employee one year, and a non-employee the next. This is not uncommon.

**Comment by dwsinger** [comment]
The nomination-of-others question is thorny. What happens if an org. nominates and agrees to support an IE for the good of the community but is otherwise hands-off? I think that asking people to give reasonable transparency to relationships is the best we can do (for example, what happens if one member places contracts that are a major source of funding for another member?).

I'm fine with striking "member"...

**Comment by jeffjaffe** [comment]
+1 to David's comments.

**Comment by dwsinger** [comment]
we probably need to talk about transparency in relationships and so on as well

**Comment by dwsinger** [comment]
Let's strike "member" for now.

**Comment by dwsinger** [comment]
closed via #185
