### ISSUE TITLE
Does a spec need to be Rec-ready to be a CR? Align defn with process

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#172]
https://www.w3.org/2018/Process-20180201/#candidate-rec sets out requirements for advancement to CR. It does not require any statement of reasons why a CR may [update: instating omitted text from original issue filing, with apologies] _not_ advance to Rec. [/update]

However https://www.w3.org/2018/Process-20180201/#RecsCR defines what a CR is and adds informatively:

> Note: Candidate Recommendations are expected to be acceptable as Recommendations. Announcement of a different next step should include the reasons why the change in expectations comes at so late a stage.

This (first part) is not tested in the requirements for advancing to CR, and in fact it is not unusual for substantive changes to be made after first CR, on the path to Rec. The second part is very reasonable, however it omits an important real world case, which is non-advancement for an unreasonably long period. 

As a minimum, the two sections should be aligned so that the tests for advancement clearly verify the requirements.

My preference for achieving the alignment would be to remove or modify the expectation from the note, since I don't think it reflects reality or is particularly helpful. It is obvious enough that a CR is a step along the path to Rec and that there are extra steps needed if making substantive changes between CR and Rec. Conversely, if the substantive content of a CR is acceptable as a Rec, there are good reasons why we do not just publish it as a Rec: the "acceptability" depends not on the document in itself, but rather on the demonstration that implementers and the AC and Director agree that it is acceptable. So the statement of expectation doesn't seem to be clear enough.

I would propose:

> Note: Candidate Recommendations are expected to be advanced to Recommendation. Announcement of a different next step should include the reasons why the change in expectations comes at so late a stage.

Handling the second problem, omission of what should happen if a document stays in CR for an unreasonably long time, is harder to fix and probably needs some discussion. Automatically revert the CR to a Note? I imagine that would be unacceptable to some people, but it might focus attention on tests and implementation reports... If it is going to be picked up for discussion, probably better for someone to raise a new issue for tracking purposes.

**Comment by michaelchampion** [comment]
The phrase "Candidate Recommendations are expected to be acceptable as Recommendations" was put in the Maturity Levels section during the major revision in 2014, but I don't recall what purpose it was supposed to serve. It's been there for 4 years, what problem is it causing?

The larger question of why things get stuck in CR is an interesting one.  It's not clear to me it's a problem -- it shows the world that some feature is reasonably well-defined and there's agreement on how it would work if it got broadly implemented, but it's not widely implemented yet.  Or maybe there's some disagreement between groups that prevents it from getting advanced.  Or, as is often the case I believe, it documents a feature that is widely used in practice but nobody has found the time to formally test it.

So my sense is that this issue isn't high enough priority to invest in, and it would be non-trivial to build consensus on how to fix the larger problems it touches on if we pursued it.

**Comment by nigelmegitt** [comment]
Thanks @michaelchampion 

> what problem is it causing?

It "raised an eyebrow" when a WG wanted to move to CR on a deadline basis rather than a functionality basis, with at least half an expectation that there would be a second CR. Either the eyebrow raise should be a clear "no you can't" or the eyebrow should not need to be raised. The actual cost of this? A few minutes of avoidable conversation.

> it documents a feature that is widely used in practice but nobody has found the time to formally test it.

My understanding of this state is that "it" is used and implemented but no statement of interoperability can be made, since the interop status is unknown, due to lack of tests. I get very worried when we build specs that depend on other specs where this situation exists. In my view, that's a big long term problem - it's not something that has hit us hard _yet_ so we are psychologically likely to underestimate the potential impact (this is a "recency" bias I think). 

I would argue that the potential cost of reworking implementations or specs or both to deal with dependency on a spec where interoperability is later shown not to exist could be very high, and we should actively try to prevent that situation from arising.

> it would be non-trivial to build consensus on how to fix the larger problems it touches on if we pursued it

I fear you're only too right! Of course the problems only get bigger over time though, so it's  cheapest in the long run to fix it now rather than later.

**Comment by wseltzer** [comment]
Propose removing the first sentence of the note, https://github.com/w3c/w3process/pull/181

**Comment by fantasai** [comment]
Counter-propose accepting @nigelmegitt’s proposed wording in the OP.

**Comment by dwsinger** [comment]
some unease about relaxing this; perhaps we should go the other way, and make it explicit that a CR should be in good enough shape that if implementation experience confirms it is well written, it could be published as-is.

**Comment by michaelchampion** [comment]
@dwsinger, does that imply strongly discouraging "deadline driven" CRs? A WG should never EXPECT another CR, and publish one just to appear to be making more progress than they really are?

I think I'm OK with that. But I can vaguely imagine going to CR just to have an exclusion opportunity and shake out any patent issues. I dont recall this ever happening however.

**Comment by dwsinger** [comment]
I guess it does. I can't see what the point is of a CR where the group knows it'll make substantive changes. What are you asking implementers in this case? To check that something you know you'l change can be implemented, or something you know is incomplete can be implemented?

**Comment by nigelmegitt** [comment]
> I can't see what the point is of a CR where the group knows it'll make substantive changes.

@dwsinger It signals progress and that now would be a good time to implement, as well as triggering the patent exclusion period. Substantive changes may be made in a future CR anyway, based on implementation feedback; implementers should not be expecting that a CR is final, and the SOTD explicitly says that. 

> What are you asking implementers in this case? 

We, and the Process, can not predict all the substantive but reasonable changes that a WG might make after a CR publication; for example there could be additive changes that do not invalidate any implementation work based on an earlier CR.

By the way, TTWG recently published TTML2 CR1 in the knowledge that changes in CR2 were likely, and as Chair, that seemed completely reasonable to me. Maybe that's not the wider view.

**Comment by dwsinger** [comment]
@nigelmegitt OK, we seem to be meeting in the middle. I can envisage situations where the group believes that the spec. is consistent and implementable, and some might think it complete; but it knows that some substantial portion of the population will argue that there is another feature which is needed. I don't think that negates the view that a CR should be in good enough shape that it *could* be published as a Recommendation, even if the expectation is that more will be added and a second CR issued. A CR that couldn't be published as a Rec. has some sort of problem -- incompleteness, under-specification, inconsistency -- and I don't think we should be asking the community to implement something like that, and give us feedback. Maybe we expect the feedback to be (for example) "look, this spec. really needs a JS API to allow introspection, in addition to the signals", but OK, that doesn't stop the spec. being implemented without it.

**Comment by nigelmegitt** [comment]
> ...a CR should be in good enough shape that it _could_ be published as a Recommendation...

@dwsinger +1. I think we're there. 

Now returning to the original proposal, can we agree to change

> to be acceptable as Recommendations

to

> to be advanced to Recommendation

?

**Comment by fantasai** [comment]
Actually was just having a discussion with @frivoal on this point. My response was

> I don't think “Candidate Recommendations are expected to be acceptable as Recommendations” is a really good explanation of what CR is in reality -- the goal of CR is to be a call for implementations, and if you don't have completed implementations *at* the transition to CR, you cannot expect your CR to be acceptable as a Recommendation because the process of implementation pretty much always reveals things that need to change. I think the best description of CR, the one we've been using [in the CSSWG], is “Call for Implementations: the spec has been reviewed and improved as much as it can be in the abstract, and cannot be improved further without implementation experience”.

We (those of us with experience developing standards) _expect_ there to be changes in CR. If we wanted to get to a point where we truly expected no changes, CR would have to be merely an administrative step that could only apply to a spec that was already ready to be accepted as REC, with two implementations, a test suite, and implementation reports with two passes for each test. At which point we might as well merge CR into PR and do all the administrivia at once.

We don't anticipate any changes, though, in the sense that the spec has been reviewed widely and deeply, and there's nothing specific we believe is likely to change. The spec's has gone through sufficient design-review cycles that it's stabilized, and all the feedback we've collected has been addressed. Implementers who wait until a spec hits CR can, if the WG has done its work thoroughly, feel comfortable implementing without worrying about needing to rewrite their implementation (possibly multiple times) in response to major design changes down the line. And also, they can know that if they run into significant problems with the spec, their feedback can prompt the spec to change to accommodate their experience.

If REC is a release, PR is Release Candidate (like, if there's any changes to an RC, somebody messed up big time), CR is beta-testing, and WD is alpha/pre-alpha. We expect problems to come up once an engineered thing encounters the real world, so we should expect to be fixing them, too.

**Comment by michaelchampion** [comment]
@fantasai wrote 
> Call for Implementations: the spec has been reviewed and improved as much as it can be in the abstract, and cannot be improved further without implementation experience”.

I'm not sure about CSS, but in general, specs are being implemented earlier in the process than they once were.  So I think the point is something like "improved as much as it can be without product-quality implementation experience and testing on real websites."     I don't want to quibble about words, but I want the words in the process to correspond to actual practice.

For me, the key point in this issue is to discourage WGs from going to CR on what @nigelmegitt called "deadline basis rather than a functionality basis". It's OK to expect that draft specs will change in response to the real world, but it's not OK to issue a CR to create the appearance of more progress on WG consensus building than there actually is.

**Comment by fantasai** [comment]
Was gonna respond, but @frivoal beat me to it and said everything I wanted to say better than I would have. :) +1

**Comment by nigelmegitt** [comment]
I agree with @frivoal and @fantasai that specs should be based on agreed functionality; my implicit assumption in the "deadline basis" approach is that any parts of the spec for which there is not consensus are moved out to a later spec version to allow progress to be made. I've seen this done successfully in CSS as an example and it looks like good practice.

Seems like a good idea to write down that transitions are based on functional maturity, but possibly to note that the scope of the functionality may be restricted by a WG in order to meet desired publishing timescales.

**Comment by frivoal** [comment]
Another point I would like to add is that the criteria for entering CR and for updating CR should be different.
I've earlier said that entering CR should mean something like: "we may not be completely done, but this is as far as we can go without (additional) real world feedback". Which in practice means 0 open issues after having got sufficiently broad review.

If we hold the same criteria for updating a CR, we run the risk that CR stay out of date for long periods of time, and that EDs are the more useful document: as implementation driven feedback comes in, we find new issues, and address them. The ED progressively gets better, but even the CR may now be know-be-wrong, and the ED is known-to-be-better, we hold off until we reach 0 open issues again. That's bad.

So, I think that WGs should be explicitly allowed and encouraged to update CRs with open issues when there's a consensus in the WG that the state of the document is better than the previously published CR. Sure, it is not ready to advance to REC since there are open issues, but neither is the document already in CR after all, since issues have been found and fixed.

I don't this allowance for known problems should not cover feature additions since the previous CR. Also groups should strongly consider adding features in separate modules / newer levels, but I that may not need to be featured in the process.

**Comment by chaals** [comment]
@nigelmegitt 

> I don't know if there's anything that can be done to streamline the process and allow small but substantive in-progress updates to CRs to be made and reduce the impact on time-to-Rec

Well, if you can convince the W3C that there won't be an exclusion on the change, and get instant turnaround of transitions and WG approval e.g. by asking "if there are no objections, we agree to request on day X", you can shorten time-to rec to a theoretical 56 days from last publication, just inside the exclusion deadline. I note exclusions are in my experience usually made on the last day of the 60-day period.

If you want to get shorter than that you just need to convince the W3C that the WG should be allowed to make substantive changes during an exclusion period and not reset the 28-day minimum CR. I believe that could be done, but it seems less fun than eating hot gravel and likely to take years.

More importantly I suspect shaving more time from CR to Rec, relying on zero-day turnarounds and less or no review through 2 transitions for a feature so critical it has to go in on the in-progress timeline is a pretty rare edge case. For me it is indicative of a WG problem.

For all those reasons, I don't think the effort is justified, but I don't have an objection to someone else having a go... 

I note that the edge case was anticipated in opening AC review at CR publication, but the 4+4 weeks of CR and PR review were reinstated before the idea got out of editors' drafts, and the early starting review was removed more recently.

**Comment by chaals** [comment]
@frivoal WGs are explicitly allowed to update CRs. I think encouragement is a matter of procedure more than process, although the process tries to encourage groups to get useful work done and publish things rather than waiting for perfection.

The patent policy doesn't help there, but in practice I don't think it is nrealy as much of a drag as the fact that Working Groups rarely work as fast as they want to think they can.

**Comment by nigelmegitt** [comment]
> if you can convince the W3C that there won't be an exclusion on the change

@chaals Thanks for this hint - actually we have a case where we are updating both TTML1 and TTML2 and the change we want to back-port into TTML1 is already in TTML2 and the exclusion period has already begun. So this is actually a reasonably path to try to take, arguably.

> it is indicative of a WG problem

Possibly. It would be a classic time and effort vs scope problem, here. The change ideally would have been made before, but external drivers pushed our timescales and a couple of substantive things slipped through the net.

**Comment by chaals** [comment]
Whether the path is reasonable is tricky, given the patent policy applies to recommendations and backporting technically covers a different Rec. On the other hand, I think these days most partiicpants are unlikely to have any interest in going into the level of legal detail, and that may itself be a sound argument.

To be clear, I don't think "we want to get stuff shipped, and we realise there may well be bugs" is a WG problem so much as a characteristic of reality. But thanks for pointing out the legitimate case explicitly.

**Comment by frivoal** [comment]
> WGs are explicitly allowed to update CRs. I think encouragement is a matter of procedure more than process, although the process tries to encourage groups to get useful work done and publish things rather than waiting for perfection.

Right. I think it's a bit fuzzy now, and the fuzziness can be used for good purposes. But if we start being more explicit that CRs must be REC-ready, that seems to get in the way of updating a CR 6 months in, after implementation experience has reveal a few issues, and some have been fixed.

To me "Must be REC ready" implies that known issues have been addressed. Which again, I think is fine for entering CR, but would force us to wait for perfection for CR updates.

Updating faster than the patent policy allows seems hard and not particularly useful. But avoiding many months or years of drift between the ED and the last CR seem desirable.

So, to try an summarize, to me:
- Criteria for entering CR:
  - has received wide review
  - all known issues have been addressed
- Criteria for CR:
  - substantive changes have been done to the ED since the previous CR (typically based on implementation experience)
  - The changes have received wide review
  - The changes are such that reading the previous CR rather than the ED would be misleading
  - No requirement that all issues found since the last CR have been addressed yet

**Comment by dwsinger** [comment]
> On Jul 17, 2018, at 16:42 , Florian Rivoal <notifications@github.com> wrote:
> 
> WGs are explicitly allowed to update CRs. I think encouragement is a matter of procedure more than process, although the process tries to encourage groups to get useful work done and publish things rather than waiting for perfection.
> 
> Right. I think it's a bit fuzzy now, and the fuzziness can be used for good purposes. But if we start being more explicit that CRs must be REC-ready, that seems to get in the way of updating a CR 6 months in, after implementation experience has reveal a few issues, and some have been fixed.

I don’t think so. I think the intention is that if you get super-lucky (or you were incredibly skillful, or the spec. is short), then the document you made at CR is verified by implementation and is then published as a Rec.  The *document quality* should always be good enough for that. We should not be asking people to implement something that has contradictions, ambiguities, or other known deficiencies.

Nonetheless, if a spec. is complex, or we’re unlucky, or it’s so long that our imagination can’t get around all the combinations, we’ll probably find technical fixes we need to make during CR. And we may need to delete as unimplemented/unimplementable some features, and so on. Such technical change requires a second CR and exclusion period, doesn’t it, becuase it’s well, a technical change.

> 
> To me "Must be REC ready" implies that known issues have been addressed. Which again, I think is fine for entering CR, but would force us to wait for perfection for CR updates.

Don’t agree, as outlined above.

> 
> Updating faster than the patent policy allows seems hard and not particularly useful. But avoiding many months or years of drift between the ED and the last CR seem desirable.
> 
> So, to try an summarize, to me:
> 
> 	• Criteria for entering CR:
> 		• has received wide review
> 		• all known issues have been addressed
* the spec. is well enough written that it can be (trial) implemented, and if it’s super-well written and implementation throws up no bugs, could be published

> 	• Criteria for CR:
> 		• substantive changes have been done to the ED since the previous CR (typically based on implementation experience)
> 		• The changes have received wide review
> 		• The changes are such that reading the previous CR rather than the ED would be misleading
> 		• No requirement that all issues found since the last CR have been addressed yet

Not sure what this list is of.  I think the WG is at liberty to maintain a revised WD, and when they decide, push that as a second CR, no?

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by chaals** [comment]
A Recommendation does not have to be perfect. It has to be fit for purpose. If you have major known bugs, there is nothing to stop you saying "yes, that is a problem we do not agree on how to fix, and we do not expect that waiting for the answer before we ship a Recommendation will improve the world. We do expecct to reach agreement and fix it for some future version, and here is how we have addressed it in the meantime... [some warning about dragons and implementation details]". 

(Or in bug tracker terms: "Later")

Shipping is a feature. The process allows groups to be pretty flexible about whether they never produce a Recommendation as they wait for perfection, or produce a series of Recommendations as they try to iteratively improve, or have specifications that they will move to Recommendation as reality catches up.

The membership says, through chartering, what they are OK with - and as far as I can see that guidance isn't constrained by any sense that some rigid measure of coherence is crucial.

**Comment by dwsinger** [comment]
This was marked Pending Review in April but I am not sure we have consensus on the changes (if any)?

**Comment by dwsinger** [comment]
I think that to enter CR, where we are asking for implementation experience, the rough expectations are 
* that it's implementable, technically consistent, well enough written, etc. for people to try implementation
* that if that implementation experience goes really well, and everybody says "terrific, I implemented it without question and we interoperate without hiccup" we could plausibly publish the text, unchanged, as a Rec.

I *think* that's the intention of the sentence. Not that you're prohibited from improving the writing, or revising the technical content, after CR (and therefore, possibly, doing a second CR), but that you should not enter CR with the clear knowledge that the spec. is incomplete, inconsistent, unclear, or generally unimplementable.

**Comment by frivoal** [comment]
I agree with everything you just said. But this is all about **entering** CR. What I am questioning are the criteria for **updating** a CR

To me, the question is if you've entered CR while meeting the criteria you just described, and implementation experience shows major flaws that make you realize that it's not, after all, implementable, technically consistent, etc. Are you allowed to update the CR when the spec is understood to be better than the previous CR even if you know that it is still not implementable, technically consistent, etc because you have fixed some but not all of the big flaws that you've found, or do you have to wait until it is "implementable, technically consistent, etc" based on your new understanding?

I'm arguing that the former is useful, because the later leads to CRs that are significantly behind the Editor's draft. You could republish as a WD in that case, but people are reluctant to downgrade the status for an improved spec, so generally it doesn't happen in my experience.

Same thing for RECs. With no change to the criteria for getting to REC, if you later find issues that would have been bad enough to prevent the spec from getting to REC had they been found in time, do you have to fix them all before you can republish as a REC, or can you update the REC as each problematic area is fixed, even if others are not yet?

If that sounds reasonable with you, I suggest defining the criteria of **advancing to** CR as has been done above, and add a separate statement that revising a CR / REC is acceptable in the circumstances I've outlined above.

Maybe phrased something like:

> When revising a CR or a REC, Technical Reports are expected to meet the same maturity criteria as when they are first published under that status. However, in the interest of replacing stale documents with improved ones in a timely manner, if flaws have been discovered in the technical report after its initial publication as a CR or REC that would have been severe enough to reject that publication had they be known in time, it is permissible to publish a revised CR or REC, following the usual process, even if only some of these flaws have been satisfactorily addressed.

**Comment by dwsinger** [comment]
@frivoal indeed I was answering (one of?) the orginal questions (which happens to be the title of the isue ;-)).
1. Does a spec need to be Rec-ready to be a CR?
2. Can a CR be issued to meet a deadline, or must it wait until it reaches a state that's "acceptable as a CR"?
3. What are the criteria for updating a CR?
4. What should we do, if anything, about specs that languish in CR indefinitely?

My answers, for what they are worth
1. Yes (see above).
2. No.
3. WG consensus, and the same quality requirements as for entering CR
4. If it's clear that indefinite is likely to be eternity, re-publish as a Note.

**Comment by frivoal** [comment]
I agree on 1, 2, and 4. I mostly agree with 3, with the caveat I mentioned:

> [...] same quality requirements as for entering CR

> However, in the interest of replacing stale documents with improved ones in a timely manner, if flaws have been discovered in the technical report after its initial publication as a CR or REC that would have been severe enough to reject that publication had they be known in time, it is permissible to publish a revised CR or REC, following the usual process, even if only some of these flaws have been satisfactorily addressed.

**Comment by nigelmegitt** [comment]
>  if flaws have been discovered in the technical report after its initial publication as a CR or REC

@frivoal is it your intent in your proposal at https://github.com/w3c/w3process/issues/172#issuecomment-413541675 to constrain CR revisions so that the delta is _only_ spec bug-fixes? At present it would be possible for a WG to, say, add a new feature in an updated CR, if they could demonstrate wide review. For example implementation experience of an API spec might say "we really need some additional API call [for some reason]" and the WG might want to adopt that proposal prior to getting to Rec.

I would not like to see a more restrictive set of criteria for publishing a revised CR than exists now.

**Comment by dwsinger** [comment]
I think he's saying that if a CR is later discovered to have bugs A, and B and be missing feature C:
* then a revised CR that fixes A should not be required also to fix B (even though entering CR would have been disallowed had B been known about at the time of the original entry).

But, should I be allowed to add C, and not fix A or B?

**Comment by nigelmegitt** [comment]
> But, should I be allowed to add C, and not fix A or B?

I'm struggling to think of any reason why a WG would not take the opportunity to fix A and B while publishing a new CR. If there is no consensus on what the fixes should be then that suggests a whole other level of problem. I seem to be leading myself down the path of "if known problems exist with the previous CR, a new CR must/should resolve those problems". 

There's always a grey area though, stuff that may be slightly unclear, or implementation dependent, or simply too small in scope to worry about now, so WGs might want to defer to a later edition. 

In the end the answer is probably "deal with it on a case by case basis".

**Comment by nigelmegitt** [comment]
Re https://github.com/w3c/w3process/issues/172#issuecomment-413602446 :

1. Not necessarily - it should have the form of a Rec in terms of editing etc but if it has to be as-good-as-a-Rec already then there is no point in having the CR and PR maturity levels. It only has to be "Rec ready" in the restricted (but possible) scenario that no implementation feedback is received that requires a change and all CR exit criteria are met. It may also be possible to publish a CR with normative references to other specs that haven't yet reached the required maturity and stability level but which are expected to before transition to PR.

2. A CR can be issued to meet a deadline if and only if the WG has maintained the pre-CR draft in such a way as to ensure consensus for publication at the deadline date. In other words, the _timing_ is a WG decision, the quality must meet CR criteria, whatever they are according to the Process.

3. WG Consensus, and any new features demonstrated to have wide review (as they would do if transitioning from WD to CR).

4. Specs that languish in CR indefinitely suggest a problem with the WG - that should be addressed between W3, the WG Chair(s) and the WG, and if the result is that the spec is removed from the WG's Charter, then follow existing procedures to republish as a WG Note and cease working on it. For example if the reason is "nobody can be bothered to complete the test suite even though everyone thinks the spec is stable and implementations have shipped" then some kind of a fuss needs to be kicked up to sort that out and get to Rec or drop it from the Charter.

**Comment by frivoal** [comment]
> I'm struggling to think of any reason why a WG would not take the opportunity to fix A and B while publishing a new CR.

Because both A and B could be difficult and time consuming to fix, and the WG may determine that it is better to have an updated CR with A fixed (but not yet B) published now, instead of having an outdated CR on TR for many more months.

> I seem to be leading myself down the path of "if known problems exist with the previous CR, a new CR must/should resolve those problems".

"should" yes, but "must" either means that CR with known problems, most (but not all) of which have known solutions occasionally stay unfixed for extended periods for time on TR (which is bad and leads to people ignoring TR entirely and working exclusively out of editors drafts), or to an expectation that CRs should regress to WD when some but not all issues have been addressed.

In my experience, groups have no issue bringing back a CR to WD if it had to be significantly redesigned, but tend not to do it just for the sake of publishing (incomplete sets of) bug fixes.

> But, should I be allowed to add C, and not fix A or B?

If new feature C is there to fix an issue, and it does mean CR criteria, I don't think it is terribly different from A or B, so that should be allowed if fixing A but not B is allowed (which I think should be).

If new feature C is just a new feature because someone had a good idea (even if it does mean CR criteria), it really ought to be in a separate document (new level, new module, whatever), but I believe that this can be left up to the good sense of the chairs and team contacts, and does not need to be explicitly distinguished from the previous case as far as the Process is concerned.

> In the end the answer is probably "deal with it on a case by case basis".

Right, but to be able to deal with it on a case by case basis, something must be allowed. If something is allowed, but seems like a terrible idea, you can always object to it. If the process explicitly requires that certain criteria must be met, then they must be met.

That's what I'm trying to aim for: make it clear that it is allowed to do updates that only partially fix things, so that we can deal with it on a case by case basis.

**Comment by nigelmegitt** [comment]
> make it clear that it is allowed to do updates that only partially fix things, so that we can deal with it on a case by case basis.

+1

**Comment by dwsinger** [comment]
@nigelmegitt I have a feeling that we might be appearing to disagree when in fact we agree. 

The point of the CR transition is to ask for implementations, implementer feedback, testing, and so on. In the miraculous case that this all goes 100% perfectly, the *text of the document* should be good enough to publish as a Recommendation. That's what I think that the Process requires, and should be required. I think it irresponsible to ask people to implement and give feedback on something that is not well enough written, consistent, or technically complete enough to publish (and hence, not enough to implement thoroughly either). So, I think the sentence should stand.

**Comment by nigelmegitt** [comment]
@dwsinger Yes, I think we do agree on the point of the CR transition and the "happy path" result, but somehow arrive at different conclusions about the Process text.

As it stands, the text "Candidate Recommendations are expected to be acceptable as Recommendations" _could_ be taken in the way that you explained at https://github.com/w3c/w3process/issues/172#issuecomment-420732732 but could also be taken to be stating a much stricter "Recommendation in all but name", suggesting that it would be a sign of failure to take the available options for addressing implementation feedback, rather than the acceptable working method which it is.

It leaves too much unsaid, where the unsaid stuff is actually in the criteria for advancement to PR and then on to Rec, or to an updated CR.

In addition to my initial proposal, I wouldn't be against adding some sort of an informative note along the lines: 

> "If implementation experience demonstrates that the CR can be advanced to PR without substantive change, the CR is expected to be of adequate quality to need minimal editorial changes prior to advancement." 

or more briefly, 

> "Significant editorial changes are not expected when transitioning from CR to PR".

**Comment by dwsinger** [comment]
Sorry to have been slow in understanding...

maybe we need to simply insert a word or two?  

Note: The [text | content | body] of a Candidate Recommendation is expected to be acceptable as a Recommendation. Announcement of a different next step should include the reasons why the change in expectations comes at so late a stage.

Do we need to open a separate issue on the criteria for revising a CR?

**Comment by dwsinger** [comment]
cloned the 'requirements to update a CR' into a separate Issue #207, so this one can focus on the original question

**Comment by frivoal** [comment]
I've made an attempt at solving this in https://github.com/w3c/w3process/pull/214 (not including the changes discussed in #207)

**Comment by frivoal** [comment]
removing the agenda+ label, as we did discuss this. The PR needs more work. Let's put back the label when we've reached a conclusion, or have concluded that we need to talk through it by voice.

**Comment by wseltzer** [comment]
Several on the W3C Team reviewed this proposal and do not support the insertion in #214  Among the concerns:
* specs are allowed to advance to CR with known editorial issues;
* delaying a CR (imposing more prerequisites) delays the Patent Policy-mandated call for exclusions, which a group may reasonably want and otherwise be ready to commence;
* the additional statement on scheduling considerations and dropping features is not necessarily good advice for all groups, e.g., in some cases, participants may explicitly prefer that a set of features advances together.

We believe the Director and WGs haven't had difficulty with CR advancement criteria in practice, and we're happy to share guidance elsewhere, e.g. in the WG Effectiveveness TF, rather than in Process.

**Comment by frivoal** [comment]
> specs are allowed to advance to CR with known editorial issues;

CRs are expected to be acceptable as Recs, which is stricter that the text I proposed. So I don't understand how relaxing this requirement is perceived as imposing additional constraints.

> delaying a CR delays the Patent Policy-mandated call for exclusions, which a group may reasonably want and otherwise be ready to commence;

Sure, but initiating the patent  protection machinery about a text that is known to be wrong, and that we know will have to be replaced, is only moderately useful.

> in some cases, participants may explicitly prefer that a set of features advances together.

Sure, but if that is the case, they should not advance until the features are ready. If a spec is known to be immature, buggy, problematic, or otherwise not ready, publishing it as a CR as is is the wrong thing to do, and the choice is either to finish everything and then publish, or to publish the parts that are finished now, and the rest later.

And by that, I don't mean that a document needs to perfectly define everything before it is considered ready. It is absoltely acceptable in my opinion for a group to decide to accept a certain level of fuzziness and to leave certain things undefined in the spec. But it is not OK for a Working Group to have a draft with known significant substantive errors to declare that they are done, even though they know they are not.

**Comment by dwsinger** [comment]
> Several on the W3C Team reviewed this proposal and do not support the insertion in #214 Among the concerns:
> 
> * specs are allowed to advance to CR with known editorial issues;

why? We currently require that they should be acceptable as Recs, and we don't accept editorial issues in Recs. And editorial issues are the most easily fixed.

> * delaying a CR (imposing more prerequisites) delays the Patent Policy-mandated call for exclusions, which a group may reasonably want and otherwise be ready to commence;

I don't see how getting the wrong analysis done, as the spec. is wrong, is going to help here.

> * the additional statement on scheduling considerations and dropping features is not necessarily good advice for all groups, e.g., in some cases, participants may explicitly prefer that a set of features advances together.

The group can tie features together for sure, but then they move at the pace of the slowest; isn't that obvious? If a feature isn't ready, and must be in the CR, then the CR isn't ready.

> 
> We believe the Director and WGs haven't had difficulty with CR advancement criteria in practice, and we're happy to share guidance elsewhere, e.g. in the WG Effectiveveness TF, rather than in Process.

We're trying to be clear what the existing requirement means, and I think we're getting that clarity. A CR needs to be well-enough written that people can try to implement it, without wasting their time on poorly-thought-out or incomplete features, bad writing, and so on; and that if that implementation experience yields the result "yup, it's good, we can all implement this" then the CR text needs only light editing to become a Rec.

There's a famous skit where someone is a candidate to play Tarzan in a movie -- but they have only one leg. They are clearly *not* a candidate in any reasonable sense. Nor are documents that are known by the WG to be wrong, incomplete, not thought out, containing editorial errors, and so on.

**Comment by nigelmegitt** [comment]
> * specs are allowed to advance to CR with known editorial issues;

Are they also allowed to advance to Rec with known editorial issues?

> * the additional statement on scheduling considerations and dropping features is not necessarily good advice for all groups, e.g., in some cases, participants may explicitly prefer that a set of features advances together.

I don't understand this objection. That statement is clearly an example based on a hypothetical scenario ("should faster advancement to meet scheduling considerations be desired") and doesn't remotely look like something that is supposed to be good advice for all groups.

> * delaying a CR (imposing more prerequisites) delays the Patent Policy-mandated call for exclusions, which a group may reasonably want and otherwise be ready to commence;

@wseltzer If you want to clarify in a different direction, i.e. that CRs are only required to contain the substantive content for which exclusions may be requested, that could resolve the issue too, in which case a change to the Process text is still needed. Plus you'll have to convince a number of people who have responded to this issue who seem to have a very different concept of what a CR should be!

**Comment by chaals** [comment]
Aside: this thread is very long. It is tempting to split some of the issues into bite-sized chunks.

On the question of "editorial issues":

I think it is reasonable to make editorial changes while in CR. It may be the case that a group is simply unsure of the most helpful way to phrase something, because there has been disagreement while in WD maturity level. Allowing the group to settle one one, or settle on a combination of approaches, with the explicit review question of which makes more sense (and for whom), seems reasonable.

Likewise issues such as "more examples would be helpful" are editorial. And probably true forever. Blocking CR on this is different to "this is impossible to understand without an example, please add one or two".

My conclusion is that there should not be a prohibition on going to CR with known editorial issues, but that the language in the process needs to clearly state that the CR must be a document the Working Group is prepared to request published as a Rec, absent feedback that says there is a reason not to do so.

**Comment by frivoal** [comment]
I've made editorial tweaks to the proposed phrasing in the PR based on the comments received.

https://github.com/w3c/w3process/pull/214/files

I believe that we should merge this.

As far as I can tell, this is a strict improvement over the previous text, which was so strict as to be impossible to apply without making CR and REC synonymous. Although it may have been ambiguous at earlier stages, I don't believe the concerns expressed by @wseltzer are warranted with the currently proposed wording, especially when compared with the original text.

**Comment by dwsinger** [comment]
LGTM

**Comment by wseltzer** [comment]
I noted my disagreement with the third addition in the PR. 
https://github.com/w3c/w3process/pull/214/files#r231712502

**Comment by swickr** [comment]
This molehill sure has grown

@michaelchampion [observed](https://github.com/w3c/w3process/issues/172#issuecomment-372092868)

> The phrase "Candidate Recommendations are expected to be acceptable as Recommendations" was put in the Maturity Levels section during the major revision in 2014, but I don't recall what purpose it was supposed to serve. It's been there for 4 years, what problem is it causing?

One of the big 2014 changes was the merge of the "Last Call" maturity level with "Candidate Recommendation".   As I recall, the intent of the note "Candidate Recommendations are expected to be acceptable as Recommendations." was to advise Working Groups that their consensus to move to CR is a signal that the WG believes the spec satisfies their technical requirements and the group should not continue to tweak the spec in the ways some groups had previously done after publishing a "Last Call" Working Draft.

So, the purpose was to say "don't treat CR the way you previously (mis)treated Last Call".

I think that rather than trying to create a more refined definition of CR we could safely drop this Note as an historical artifact that no longer serves a purpose.  This resolves the apparent inconsistency for which Nigel opened this issue, leaving [6.4](https://www.w3.org/2018/Process-20180201/#candidate-rec) as the normative requirements for entering CR and [6.4.1](https://www.w3.org/2018/Process-20180201/#revised-cr) as the normative requirements for a Working Group to revise a CR.

**Comment by fantasai** [comment]
@swickr Nonetheless, I think the "note" changes/additions in the PR for this issue are worthwhile, and I would advocate for folding them in.

**Comment by dwsinger** [comment]
@fantasai I agree. I think @swickr  (or anyone) could have argued that 6.4 should list as a requirement "MUST present a document that would be acceptable as a Recommendation", but this advice is overall helpful (and asked for).
