### ISSUE TITLE
The team/director should be removed from being in-loop on spec. obsoletion

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#174]
A year after trying two 'easy' specs for obsoletion, they are still pending in the team (for no obvious reason; there has been no recourse to the originator, TAG or AB as far as I know). Since obsoletion is voted on and reversible, I suggest that if the TAG or originating WG (as appropriate) agree, then the AC ballot happens and its result is definitive. If the team feels it's a mistake, persuade the WG, TAG and/or AC.

**Comment by michaelchampion** [comment]
One way to address the problem would be to make Recommendations auto-obsolete themselves after something like 10 years UNLESS a WG (or the team, or perhaps the TAG in case the WG no longer exists) re-affirms them.  This is similar to what happens in JTC1 with the PAS submissions from organizations such as W3C. 

I wouldn't make it a high bar to re-affirm an old Recommendation, but someone should have to document why they think it is in active use and still "recommended" as good practice to implement and use. Perhaps the AC could be informed about who is recommending re-affirmation, where the rationale is, and is given a "silence means assent" opportunity to disagree and request a vote or decision from the Director.

**Comment by LJWatson** [comment]
@dwsinger <Since obsoletion is voted on and reversible, I suggest that if the TAG or originating WG (as appropriate) agree, then the
AC ballot happens and its result is definitive.<

Agree, but suggest it should be "originating or currently responsible WG".

**Comment by dwsinger** [comment]
apparently some are also in the TAG's hands...

another alternative is to have a timeout on the team; the problem is that it's the team that has to start the AC ballot...

**Comment by chaals** [comment]
Given the need for the Team to implement a lot of this, taking them out of the loop seems a bit pointless.

The idea of an automatic obsoletion date is interesting, but I am not at this stage convinced: XML seems unlikely to be updated significantly (although there is a possibility) in the next decade or so. But it is widely used in systems that seem reasonably likely to be maintained and developed over the next couple of decades. I am not sure that it is helpful to the world if we suddenly declare that it is obsolete, just because we who **develop** it no longer find that work interesting enough to keep thinking about it.

I note that even product software like Windows XP - officially dead for some time, and with multiple generations of replacements out there - is still in wide use, and while it makes sense for Microsoft to try and "recall it" instead of supporting it, reality doesn't support that goal as well as they might like...

**Comment by dwsinger** [comment]
yes, I am not in favor of auto-obsoletion. we *could* move to the ISO-like system where someone has to re-affirm specs on a 5-year calendar, but my experience with that is that we rubber-stamp re-affirm everything. So I am back to my original question: why do we need to have the team in-loop *before* the ballot is issued?

**Comment by dwsinger** [comment]
The blockage seems cleared; closing in the hope it stays that way
