### ISSUE TITLE
address/recognize funding barriers to elected bodies?

### ISSUE THREAD

**Issue by bkardell** [w3c/w3process#189]
In theory, anyone can serve on these bodies - you don't even have to belong to a W3C member org - you just have to get nominated and elected.  However, as someone who has actively tried to recruit nominees and cares a lot about the health of both of them I want to share some observations/challenges and what seem to be some systemic impacts.

In order to serve, at least, effectively, the way we want - you need to be both willing and able to.  As small, elected bodies (5-6 people), these are tighter in practice than a normal working group even - we really need everyone to make the full commitment.  This has been summarized as "about 1 day per week plus travel for the face to face meetings, for two years".  I'd like to stress that this is with the current roles/responsibilities, and I feel like realistically some proposals to change those might have to change one or more variables there.  In any case, this means someone has to come up with or cover 136 days of your work over 2 years, plus 8 weeks travel time/budget while you are away from whatever it was you did before you were elected.  

That's a pretty big ask, actually and I'd like to observe a few things related:  While there are ~400 "member orgs," very few of feel like "that's fine, it's why we're here".  In practice, for various reasons, the number of orgs who are willing to even consider that are a small fraction of that 400.  Let's be very generous (I think) and say 100 of them would, ever.

Note I say "ever" because even if an org were willing to fund  someone's participation for 2 years, that doesn't mean they're willing to do it every time, forever nor that they have multiple people who can (and would be interested/willing to) do that.  And those are orgs.  There are participants who aren't even from member orgs - in the past few elections we've even elected some.  Consider the burden on them and what an impossibly huge ask this is.

It seems that in practice, we have something like 10-20 orgs at any one given who really _might_.  I'd also like to offer than on the whole, probably more than half of these are kind of... similar.  They're big.  They're deeply invested.  

There is also a tendency (a not entirely terrible one), among those doing the electing, to be generally kind of pro having folks who are well funded and shown their willingness and ability to be active and productive, and folks from orgs that we know practically speaking are good to have at the table (even if you aren't representing your org, the fact that your org is sponsoring your participation says something).

All of this plays together in a ton of ways in my opinion.  It's well beyond just 'they largely come from the same kinds of orgs' it's also that, for example, virtually every aspect of diversity winds up ultimately governed by who they are funding for nomination. Combine this with the fact that running twice is often a good thing - we don't want all elections to reboot things entirely.  There's value in carryover.

Balancing all these things is really hard, and I believe that there is no way to remove these barriers entirely, but lowering them would be good and it feels like they can't get better without discussion, so I'm bringing it up.  We lose out on a lot of good nominees because it's a little like suggesting someone take public office without pay or facility to carry out their new duties of any kind.  Getting to those worldwide meetings without vehicles and sponsoring state dinners would be a lot harder without a budget.  Some would be willing to, even some really good folks, but I feel like it is safe to say that a lot of really good folks, who would be great in that position, simply couldn't.

**Comment by dwsinger** [comment]
see also https://github.com/w3c/AB/issues/14

**Comment by bkardell** [comment]
Is this the link you intended?  It's 404

**Comment by gsnedders** [comment]
There's more to it than just funding: those in employment will likely have to take PTO to attend any meetings, which in the TAG case with about four meetings per year, once you include travel days, could easily amount to twenty days of PTO per year.

There's likely people around the W3C who don't *have* twenty days of PTO (especially those working in the US), and for many people it'll be almost their annual holiday entitlement. I don't think we can expect people to use us their entire holiday entitlement to attend F2Fs, even if we are paying them to be there.

**Comment by bkardell** [comment]
@gsnedders Was I lacking something in the initial description?  I feel like I acknowledged this, perhaps not?  The current "ask" is effectively something like 136 days of your work over 2 years, plus 8 weeks travel time/budget.  That is an incredibly tall ask if you don't work for a really wealthy org with standards being a really significant part of your job.  When it comes to TAG and AB which aren't the primary reasons orgs join, this is a really significant additional ask of even smaller _orgs_.  The idea is simply that should acknowledge that and either say we're ok with the implications or work to lower the barriers to make it more plausible it is for more people to cross them.  

My own involvement in standards has been largely possible only because smaller concessions are spread out between myself, my employer and my member org - each lowering the bar a little.  As I said, I don't think it is plausible to remove all of the barriers, but it does seem to me that more individuals and employers would find it easier if we lower barriers.  I've certainly spoken to good potential candidates for whom this may have helped encourage to run.

But, idk... Like I say, simply acknowledging that w3c is OK with the implications is another way to go - but it feels like it plays into a whole lot of things.

**Comment by nrooney** [comment]
@bkardell - @TzviyaSiegman and I have been speaking about this a little; the people in elected positions are extremely keen to do work but often time limited, and we're trying to find ways to make it a little easier to get work done without impacting our normal working and non-working lives too much. Further, I wonder often whether we miss out on some dynamite people because they cannot afford or get funding for travel; some people for the TAG in particular. Despite the dilution of work issue, I do believe increasing the number of people in the AB would help (but there is some other things to do here), I also think experimenting with new ways of holding and managing meetings would be good. Tzviya and I have both brought this up - with little traction. We'll keep trying. Any other concrete suggestions which may help? I want to make sure the right people get into the right group positions.

**Comment by chaals** [comment]
There are a lot of people who are eminently qualified for TAG and AB in every way except they don't have time, so won't do the work required. I'm not sure we have a solution for that, but I am pretty certain we won't solve it well by offering payment out of W3C's always stretched budget. If we did, we would likely have a far better focus on people from places where a lot of the Web is built, at relatively low salaries, than we do.

There is a real expectation that more work gets done face to face than remotely, which explains the resistance to dropping physical meeting requirements. Where it is clear that something other than a face to face meeting is required, there is plenty of appetite for improving our systems - but little for changes that people have good reason to believe are not going to improve anything.

Self-funding participation is generally less unrealistic for someone from a wealthy high-paying country than it is for someone from a low-wage country to get the necessary funding from a medium-size employer, particularly when we continue to hold meetings in relatively expensive locations because they are convenient to the wealthiest and best-represented members, thus further skewing the issue of who pays how much.

The basic math is that if your disposable income is greater than someone else's total income, you're unlikely to find it as hard as they do to participate. This is a real issue, although I have seen evidence that some participants in W3C do not believe so.

**Comment by jeffjaffe** [comment]
@bkardell you have raised a really tough issue here.  On the one hand, the Team truly gets enormous value from having a set of folks who find the time to work with us on tough issues, and have the continuity to work with us for a two year period.

On the other hand, if the time requirements are so demanding that it detracts from the AB ability to truly represent our diverse  stakeholders, that is a problem.

I offer two thoughts for consideration.

1. I'm not sure that one day a week; which generates 104 of the 136 days you cite is an absolute requirement.  When we don't have F2F meetings, we meet one hour every two weeks; and there is additional time in prep and mailing list/github discussions.  But probably less than 1 full day per week.  I'm interested in what current and previous ABers actually spend.

2. The AB is not the only forum for participation on governance issues; nor TAG membership for technical issues.  We need to further open up discussion avenues.  On the AB, side, The W3C process CG is a great example - participation in our entire process evolution does not require an AB badge.  TPAC, ac-forum, and AC meetings are other venues.  If there are other areas for current stakeholder feedback to the team - we can invent ad hoc efforts - I'm  open to suggestions. Not everything needs to be serialized through the AB.

**Comment by chaals** [comment]
As an AB member, I think being a continuously worthwhile contributor requires something in the order of half a day per week and being really productive in getting work done does require something in the ballpark @bkardell suggests. It's possible to spend less time by not being very engaged, or by being a speed-reading genius, of course...

My experience of the TAG, as a non-member, suggests that broadly the same would be true. @plinss, @torgo, care to (ask TAG members to) comment?

A high level of engagement is not always a good thing (it can mean I write too much, burning time of my colleagues who read it), but I don't think asking the AB and TAG to make less effort is the right path. (We should always aim to improve the value of effort we do spend, of course).

**Comment by chaals** [comment]
Yes. At the expense of getting much work done, as I noted...

**Comment by dwsinger** [comment]
I reckon I must be closer to the day/week average at the moment, alas. But I think 1/2 is sustainable.

**Comment by dwsinger** [comment]
This has no process consequences, but the AB wishes to keep this on their radar. Transferring to AB.

**Comment by nrooney** [comment]
We've elevated this topic into the AB. We will open this issue within the AB tracker and close here. When the AB have some comments / suggestions on this issue they will send to the people who have started and commented on this issue as well as any relevant mailing list. Thanks all!
