### ISSUE TITLE
AB and TAG nominations should be announced as they occur and not wait until close of noms

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#193]
At the moment, nominations are announced with the call for votes, after nominations close.  As a result the community is unaware of (a) how many nominations there are (and even whether there are enough)  (b) whether there are representatives of communities they think should be represented (e.g. "we need a good security person on the TAG" -- we don't know if one is running) and (c) whether there are, um, problematic, people running ("oh help, Sauron has been nominated, representing Mordor") and they would like to ensure that problematic people are not, at the very least, automatically elected because they stand unopposed.

Can we clarify what the motivation for the current policy is, and what the unintended consequences of announcing nominations as they occur, might be?

Cloned from #190 as this is a separate issue.

**Comment by chaals** [comment]
I think the original Mordor example is misleading - it seems unlikely that there are even theroetically viable candidates who are **generally** recognised as needing to be opposed, and the more likely situation is a polarisation within the membership. I think the proposal would exacerbate such tensions.

One concrete thing that would change is the social pressure not to nominate.

As an AC representative I received requests not to nominate a candidate, in order to clear the way for others. I consider that a very serious undermining of the intended democratic nature of the elections. Under the old system, it was more important because splitting the vote amongst "desirable" candidates could lead to none of them getting elected, whereas we have now minimised that problem. But there are further reasons to be wary:

A candidate who is uncertain of their chances is placed in an invidious position. If they declare at the beginning, the announcement of further candidates may be taken as a direct affront - a public statement that they are not good enough and there is a need to run against them. If they wait, they risk making that statement about the existing candidates, or inviting speculation that they are in fact "Sauron the bad" representing Mordor. 

A system that occasionally casts such aspersions on our members in the interests of transparency seems to me unjustified, since I do not see the commensurate benefit obtained. It unnecessarily politicises what is meant to be an exercise in providing service to a community.

Equally, the announcement of a reasonable quality "slate" of candidates can put social pressure on others who may actually have more support not to nominate against those candidates, thus depriving the AC of an option they would have preferred and which _a priori_ is available.

Introducing "strategic political considerations" into the timing of a nomination announcement just makes it harder to get good candidates. Having a single announcement date removes the stress of thinking about that, and having a longer period in which to submit nomination meets the requirement for asynchronous work that being a global consortium imposes.

**Comment by chaals** [comment]
The "Mordor" situation, modulo my warning above that it is unrealistic, is what the "no other candidate" option on the ballot was designed to identify, and if actually implemented to provide a defense based on a somewhat secret ballot rather than requiring someone to act in a way that can be taken as a public statement that a candidate is "Sauron representing Mordor".

**Comment by dwsinger** [comment]
> On Jun 14, 2018, at 1:41 , chaals <notifications@github.com> wrote:
> 
> The "Mordor" situation, modulo my warning above that it is unrealistic, is what the "no other candidate" option on the ballot was designed to identify, and if actually implemented to provide a defense based on a somewhat secret ballot rather than requiring someone to act in a way that can be taken as a public statement that a candidate is "Sauron representing Mordor”.

But that’s my original point; I’d rather have Sauron simply fail to get elected, than be publicly humiliated with “the community prefers an empty seat over you”.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by michaelchampion** [comment]
I'm not sure this is a Process question or a team policy question, but either way I support informing the AC when a nomination is made.  I think we should be transparent throughout the election process unless there is a clear and compelling reason to keep information confidential.  
We can imagine all sorts of hypothetical scenarios involving fictional beings where transparency has adverse side effects, but I don't find them compelling.    If examples of gaming the system emerge, presumably those will be taken into account by the electorate to mitigate the damage, or if necessary we can change the process/policy later if the prophets of doom turn out to be correct.

**Comment by TzviyaSiegman** [comment]
I support transparency of identifying candidates as they are nominated. One could say that this could compel people to run when they see that there is less competition. If there is a lot of competition, it could scare people away from running. I think people might like to know what they're up against.

**Comment by frivoal** [comment]
I support the transparency in general. My only reservation is that I think it interacts poorly with STV as implemented, as it discourages candidates from running if someone already somewhat close to their position is already running (or worse, it could make other people put pressure on them not to run).

However, I think that's mostly down to not being happy with STV, rather than not being in favor of early disclosure of candidacies.

So, I support this, and will take my STV griefs to the relevant issues. (TLDR: I'm increasingly favorable to approval voting)

**Comment by LJWatson** [comment]
I don't know the answer, so putting this here for consideration: does being announced earlier give someone an advantage or vice versa?

**Comment by chaals** [comment]
Mike might mean me when he says "prophets of doom". I comented above on [why I think this is a bad idea](https://github.com/w3c/w3process/issues/193#issuecomment-397216973).

I think the discouragement for people to nominate if there are candidates they think are acceptable is a general problem with this proposal - exacerbated by some **non**-STV voting systems (since they mean "splitting a vote" is a real issue). 

A real problem is it is hard to reason about things that didn't occur but might have, which makes testing what happened an exercise in interpretation - "what the data says" is meaningless on its own :S

**Comment by dwsinger** [comment]
Pro:
P1) Everyone can see whether we have too few or just enough candidates, or a competitive election;
P2) Everyone can see whether certain sectors of the population are represented by candidates;
P3) Everyone can see whether candidates that they would prefer not be elected unopposed are running.

Con:
C1) Once someone has nominated, nominating another might be seen as implicit disapproval of the existing nominee.
C2) It introduces strategic timing considerations into the nomination process.

I think C1 is only a problem for single-seat elections, and they are rare for us.

P1 is easily addressed by declaring *how many* are nominated as nominations occur.

**Comment by chaals** [comment]
Dave wrote:

> ...nominating another might be seen as implicit disapproval of the existing nominee.
> ...
> I think [that] is only a problem for single-seat elections...

My experience is that **each time** I nominated a further candidate when there were just enough, I got pressure to withdraw the nomination... in multi-seat elections.

It's a thing that can only be hypothetical I suspect, but I think it **is** likely to be a big problem. That's the basis of my discomfort with this proposal.

**Comment by michaelchampion** [comment]
Thanks @dwsinger .  As you note, C1 is not likely to be a problem in practice, and  I don't think C2 is at all compelling.    As @LJWatson notes, it's not clear what the strategic timing considerations are.

**Comment by dwsinger** [comment]
Chaals, agreed, but even then, they cannot tell which of the existing candidates you think insufficient -- or even if that's your reason. For example if, for a TAG election where the only security expert is not standing for re-election, there isn't a security nominee, nominating one doesn't really criticize the other candidates at all.

**Comment by michaelchampion** [comment]
Maybe I'm jaded by living in a company where elected officials exchange juvenile insults via Twitter, by I don't think we need to optimize the election system to avoid pressure or embarrassment. I think we're trying to find a system that generates consensus on a set of candidates with a good mix of skills and backgrounds that reflect the diverse membership.  If there is a compelling reason to think this would be jeopardized by announcing nominees in real time, let's hear them.

**Comment by chaals** [comment]
Since it is hard to tell **which** candidate you think is inadequate, unless you are prepared to say so - which would be a new level of public politicking in W3C - it is reasonable to assume all of them may believe they are being slighted.

For someone already sensitive enough to such perceptions that it affects their decision to run, that seems actively unhelpful.

**Comment by nrooney** [comment]
Oh the voting "discussion" again! 

To answer the original question in this post: yes transparency on nominations is a great idea. 

I wrote a larger reply to the voting thing, then deleted. I'll save that for another time!

**Comment by nrooney** [comment]
@dwsinger suggestion for updated text:

```
A nominee is not required to be an employee of a Member organization, and may be a W3C Fellow. Each nomination should include a few informative paragraphs about the nominee.

The Advisory Committee is notified of any eligible nomination by email to the AC mailing list when a nomination is made and the nominee's eligibility to run has been confirmed. 
```

**Comment by chaals** [comment]
For clarity, I am opposed to the proposed change, because as I outlined above I think it has serious costs and brings little real benefit, being more about what might be called "transparency theatre" than solving real problems. That said, if the consensus is to do it anyway I will accept that as the collective decision and be sad about it on my own time rather than raising further objection.

**Comment by nigelmegitt** [comment]
> A nominee is not required to be an employee of a Member organization

Sideshow question: Is a nominee required to be affiliated to a Member _at all_? 

In the UK (and I'm sure in other places too) it is commonplace for organisations with boards of directors to appoint non-executive directors  purely to act in an external advisory role with greater independence than executive directors. It's not a precise analogy but in the sense that the AB and the TAG act in a strategic guidance role, it's close enough.

This isn't a trolling comment, and I haven't discussed it with my own AC rep for example, and _I'm not even sure what I think about it myself_, but it might make sense to consider the question if W3C AB and TAG could and should allow members from non-W3C Member organisations - Invited Experts, if you will, purely for AB and TAG purposes. Could be from completely different industries; role would be to ask the questions that people deeply involved might not even think of. If anyone here thinks it is worth considering, probably it should be raised as a separate issue. (For all I know, this has been discussed at length in the past and the conversation is well concluded, in which case apologies)

**Comment by frivoal** [comment]
> it might make sense to consider the question if W3C AB and TAG could and should allow members from non-W3C Member organisations - Invited Experts

It does. I have just been elected to the AB as an Invited Expert. I realize that's not quite what you meant, as you were speaking of total outsiders, while I have prior involvement with W3C as an IE to other groups within W3C, and am sponsored by a member for the time I spend on the AB, but I am not affiliated with anyone in the usual sense. But from a rules point of view, I don't think it makes a difference, and I don't see any reason why a total outsider would be denied, as long as there was someone to nominate them and as long as they did the required disclosures. The election campaign might be challenging, but that's something else.

**Comment by nrooney** [comment]
+1 to @frivoal. At present one only needs to get an AC member to nominate them; which shouldn't be difficult for someone who has the potential to win as the AC will be the collection of people who vote. @nigelmegitt's comment may be bringing up a larger issue of whether someone completely unaffiliated with the W3C in any way could run for AB and TAG; but in our current system they would still need to campaign with the AC to win votes. This, brings up the election question again!

**Comment by chaals** [comment]
@nigelmegitt wrote

> it might make sense to consider the question if W3C AB and TAG could and should allow members from non-W3C Member organisations

currently, this is allowed and is the case in practice for both TAG and AB. As @frivoal says it might be challenging to get elected if you know nothing about W3C, but that's up to the membership to decide in an election...

I don't think we should change that aspect of the process. I also don't think we should worry overly about the fact that an organisation can nominate an employee, and another candidate who is not an employee in the alternate cycle. (Again, this does happen in practice).

**Comment by dwsinger** [comment]
I am inclining to NOT supporting this change, as changes in this area are proving susceptible to unintended effects. I'd rather leave elections and voting alone, in case we open (another) can of worms.

**Comment by michaelchampion** [comment]
I am inclined to support it. I favor transparency unless there are compelling reasons for something to be hidden. The abstract possibility of unintended consequences doesn't seem like a compelling reason to me. The possibility that a sensitive person might be embarrassed if their nomination triggers competing nominations doesn't seem compelling to me (it might just as easily trigger "thanks, since you're running I won't bother" responses).  And it's not at all obvious what strategic timing considerations might be -- nominate early, nominate at the last minute.

If we want to really eliminate the various opportunities for elections to create hurt feelings and invite bikeshedding about such things as STV algorithms, let's eliminate competitive elections with a NomCom or go to an approval ballot for a flexible number of seats.

**Comment by dwsinger** [comment]
closing as not reaching consensus
