### ISSUE TITLE
Allow AB to choose its own chair

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#223]
https://www.w3.org/2018/Process-20180201/#ABParticipation
> The Advisory Board consists of nine elected participants and a Chair. The Team appoints the Chair of the Advisory Board, who is generally the CEO.

It seems to me that having the CEO chair the AB meeting isn't the best organization. It would make more sense for the AB to appoint someone else as the chair, to optimize for best chairing rather than best CEOing, and let the CEO be free to participate as a regular opinionated participant without having to balance the group.

My suggested wording:

> The Advisory Board consists of nine elected participants, the CEO, and a Chair, who is generally one of the participants of the AB. The AB by consensus (or by vote if that fails) appoints the Chair of the Advisory Board, who sets the agenda with the advice and consent of the AB and the CEO.

This means technically that the AB can choose a chair who is not an elected member of the AB, but I think that's a feature not a bug. :) It might sometimes be useful.

**Comment by cwilso** [comment]
The link is for the chairing of the _AC_ meeting, not the chair of the AB.  I think you meant https://www.w3.org/2018/Process-20180201/#ABParticipation?

There's no requirement to have the CEO chair the AB - in fact, it was only as I joined the AB that that became true (prior, the appointed chair was Steve Zilles).  I agree that it's probably sub-optimal that the CEO *is* the chair - although I think it's very useful and important that the CEO participate in the board (which isn't explicit in the Process; the Chair could allow them, but it's not a "right" of the CEO).  I'm not sure I'm supportive of the AB selecting the chair; there are a lot of term length/continuity tradeoffs.  I might suggest the better solution would be that the Team appoints a chair that is not the CEO, but the CEO is invited.

**Comment by TzviyaSiegman** [comment]
I recommend allowing for co-chairs of the AB.

> The Advisory Board consists of nine elected participants, the CEO, and Chair(s), who are generally participants of the AB. The AB by consensus (or by vote if that fails) appoints the Chair(s) of the Advisory Board, who sets the agenda with the advice and consent of the AB and the CEO.

**Comment by cwilso** [comment]
It would be good to explicitly enabling co-chairing, yes, as that's become the norm in WGs.

**Comment by nrooney** [comment]
I support the change and the suggested addition of co-chairs.

**Comment by LJWatson** [comment]
>I might suggest the better solution would be that the Team appoints a chair that is not
the CEO, but the CEO is invited.>

+1 to this suggestion.

**Comment by cwilso** [comment]
> I support the change and the suggested addition of co-chairs.

By "the change", you mean specifically the AB selecting its own chair?

**Comment by fantasai** [comment]
> he link is for the chairing of the AC meeting, not the chair of the AB. I think you meant https://www.w3.org/2018/Process-20180201/#ABParticipation?

Yep, fixed. :)

>  I'm not sure I'm supportive of the AB selecting the chair; there are a lot of term length/continuity tradeoffs.  I might suggest the better solution would be that the Team appoints a chair that is not the CEO, but the CEO is invited.

I strongly prefer the AB selecting its own chair, since it's in the interests of the AB to choose one that best helps it make progress on the issues. It's not clear to me what motivation the Team has in that respect. Certainly the Team can make recommendations. But the members of the AB have the most motivation to choose a good chair, and will not feel the need to make that choice e.g. out of deference to upper management (which are the people the AB is supposed to be overseeing).

As for term length/continuity, I'll observe that we at W3C tend to default to continuity in the choice of chairs, so while the AB *could* change chairs after every election, it seems quite unlikely that they will. :) And since as proposed, the AB can choose a chair who is not a current member of the AB, if the chair is not re-elected but the AB finds them competent and helpful, it can choose that person to chair the next session anyway.

**Comment by frivoal** [comment]
Made PR #225 corresponding to this proposal.
This effectively does 3 things:
* Allow the AB to have co-chairs
* Allow the AB to chose its chair(s)
* Makes sure the CEO is an ex officio member of the AB, rather than as a side effect of being common choice for chair.

**Comment by jeffjaffe** [comment]
I disagree with making this change at this point in time.

First some history.  When I joined W3C, my instincts were exactly the same as Fantasai's.  Namely, that it would not be a feature for the CEO (full disclosure - that's me) to be the Chair.

Many people urged me to be a Chair, but I declined.

Three years later, pressures increased for me to take the Chairing role.  I was told that we would get more work done, it would be more directed to the needs of the consortium, and it would be more impactful - if I chaired.  So I agreed.

I have now chaired for many years.  My self-assessment is that in these years, we have gotten more done.

So my reason for not wanting to change the process now is that I would like to first understand what problem we are solving; and whether we have tried to solve the problem in the context of the current setup.

In the description of this issue, I see a vague notion that some people believe that the AB would be more effective with a different chair.  I do not see any specific example of a problem.  I do not want to replace an effective system with an ineffective system.

But, as I said at the beginning, my initial instincts were the same as fantasai's.  So if there were a problem that this would be solving, I'm open to the discussion.  But we should discuss the problem and its potential solutions first.

**Comment by michaelchampion** [comment]
The problems I see that having an elected chair might solve are:
- Evolving best practice in industry seems to be for the "chair of the board" function to be separated from the executive function.  This helps ensure that the board broadens and balances the perspective of management, not amplifies it (or is dampened if it doesn't agree).
- The CEO inevitably speaks for the team, which is only one of the key stakeholders in W3C.  The AB is chartered to speak for the membership. While the team has a lot of important information, the AB's job is to ultimately to advise on what's best for the consortium as a whole, and the larger web for which we all serve as stewards.   The AB needs to be free to say, for example, that the team is too large or that management's priorities are wrong. That seems unlikely when the management team literally controls the agenda and has the ability to declare consensus (the traditional powers of a chair). 
- The TAG seems to be working better than the AB these days at addressing the problems in its scope.  The fact that the Director is only nominally chair of the TAG probably helps: He can influence by the strength of his knowledge and reasoning, but not by authority alone.   If electing the AB chair is unacceptable to W3M, we should consider a TAG-like model where the team appoints chair(s) they trust, but who aren't actually part of the management team.
- Finally, whether or not the current system has worked in the past, it is not a good model for the future where W3C is a self-governing legal entity. It will be more important than ever for the AB to be elected *and operated* to serve the interests of the membership rather than the management.

**Comment by jeffjaffe** [comment]
@michaelchampion I think all of your points are reasonable points in theory.  In theory, the CEO controlling the agenda of the AB is unhelpful.

But I'm asking about problems in practice.  For example, the way that I address the issue of "controlling the agenda" is by sending out agendas well in advance; asking for comments; and making sure there is time for everyone's agenda items.  I've done that for topics that were important for the Team, less important for the Team, and even uncomfortable for the Team.

**Comment by TzviyaSiegman** [comment]
I also think that we should consider a co-chair. Most W3C groups have 2 chairs now, and it seems to benefit the chair and the groups. It eases the burden on the chair, allows for time away (vacation or otherwise), and can allow co-chairs to split responsibilities (formally or informally).

**Comment by fantasai** [comment]
Agree with @michaelchampion and @TzviyaSiegman.

I think that you, @jeffjaffe, should be free of the need to remain an impartial agent of the agenda so that you can be an active advocate of W3M's interests. And I think the AB should have a chair who will be able to actively manage the agenda in support of the interests of the AB at large and to more actively drive discussions to conclusion, so that the AB can make swifter and more definitive progress on the issues. You are more hampered in driving issues to conclusion than a more independent chair would be, and less able to serve as a neutral switchboard since you are one of the key inputs. We want you be a strong advocate, and we want the chair to be a strong creator of neutral, but effective discussion space.*

I don't doubt that the AB has been more productive since you took on the role of chair. It means the previous chair was not a very effective chair, and you are a more effective one. But I think the AB's workload becomes more and more critical, and we need to do the best we can... which includes finding the most effective chair for the AB that we can. Opening up the chairing role to finding the best chair, rather than pegging it to the same person as the CEO, broadens the possibilities to get there, and I think removes some of the self-cancelling effects of having both roles be occupied by the same person.

* This is in fact one of the reasons why I am not chair of the CSSWG. And personally, I find it very convenient that Alan and Rossen are effective chairs who are not me. :)

**Comment by jeffjaffe** [comment]
Good food for thought.

I actual don't think that the CEO's role on the AB should be an active advocate of W3M's interests.

The CEO's role on the AB, imho, should be - like all other AB Members - wearing the AB hat while sitting on the AB.  That is, representing what he/she believes are the best interests of the web and the consortium.

At the AC meeting, I was asked the question whether the WHATWG partnership might cause us to lose members.   I gave several answers; one of which is that our job was not to Lead the W3C to its Full Potential, but to Lead the Web to its Full Potential.  If leading the Web is suboptimal for the W3C - so be it.  A recent example of not optimizing for the team.

That's not to say that W3M's voice shouldn't be at the AB.  I often express W3M's opinions on certain topics; recently W3M's views about a NomCom.  (Correspondingly, at W3M, I also often express AB opinions as well.)

I agree that it is a challenge to both have opinions and also be the neutral creator of discussion space.  So, certainly food for thought.

**Comment by nrooney** [comment]
I agree that co-chairs is something we should employ in the AB. I also agree with @fantasai’s statements below.

Natasha Rooney | Technologist, Web and Internet, W3C & IETF | GSMA | nrooney@gsma.com<mailto:nrooney@gsma.com> | +44 (0) 7730 219 765<tel:+44%207730%C2%A0219%20765> | @thisNatasha | Skype: nrooney@gsm.org<mailto:nrooney@gsm.org>

On Nov 6, 2018, at 22:19, fantasai <notifications@github.com<mailto:notifications@github.com>> wrote:


Agree with @michaelchampion<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelchampion&data=02%7C01%7Cnrooney%40gsma.com%7C1e2e07489d5a4ccc128608d64435eadc%7C72a4ff82fec3469daafbac8276216699%7C0%7C0%7C636771395702195232&sdata=UEQVu2oSX%2BVmHQ2cwCMG5KYZFWFRFCqhaipH%2BrcQKz4%3D&reserved=0> and @TzviyaSiegman<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTzviyaSiegman&data=02%7C01%7Cnrooney%40gsma.com%7C1e2e07489d5a4ccc128608d64435eadc%7C72a4ff82fec3469daafbac8276216699%7C0%7C0%7C636771395702195232&sdata=DZzmi%2BxjHFaLhiZMLiJuvzuzRXmZHUJKJ7EZop7UBIA%3D&reserved=0>.

I think that you, @jeffjaffe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeffjaffe&data=02%7C01%7Cnrooney%40gsma.com%7C1e2e07489d5a4ccc128608d64435eadc%7C72a4ff82fec3469daafbac8276216699%7C0%7C0%7C636771395702205242&sdata=L11t6kIP24wiwFDzslkFEnNJ991ZuK7slNXTr9mrros%3D&reserved=0>, should be free of the need to remain an impartial agent of the agenda so that you can be an active advocate of W3M's interests. And I think the AB should have a chair who will be able to actively manage the agenda in support of the interests of the AB at large and to more actively drive discussions to conclusion, so that the AB can make swifter and more definitive progress on the issues. You are more hampered in driving issues to conclusion than a more independent chair would be, and less able to serve as a neutral switchboard since you are one of the key inputs. We want you be a strong advocate, and we want the chair to be a strong creator of neutral, but effective discussion space.*

I don't doubt that the AB has been more productive since you took on the role of chair. It means the previous chair was not a very effective chair, and you are a more effective one. But I think the AB's workload becomes more and more critical, and we need to do the best we can... which includes finding the most effective chair for the AB that we can. Opening up the chairing role to finding the best chair, rather than pegging it to the same person as the CEO, broadens the possibilities to get there, and I think removes some of the self-cancelling effects of having both roles be occupied by the same person.

  *   This is in fact one of the reasons why I am not chair of the CSSWG. And personally, I find it very convenient that Alan and Rossen are effective chairs who are not me. :)

**Comment by dwsinger** [comment]
I think this is a worthy discussion of a point of governance principle, but I am concerned that it's not going to get enough consideration if we try to do something in Process2019.

**Comment by fantasai** [comment]
@dwsinger I disagree, I think if the AB wants to maintain Jeff Jaffe as the sole chair of the AB, certainly it can do so with this change, however by not making the change we constrain what the AB would be able to do for the next year.

**Comment by caribouW3** [comment]
@fantasai Currently there's nothing that prevents the AB member from asking for a chair change. Formalizing it in the process2019 or not does not seem critical. That said, given that WGs/IGs have a 'non-team chair' practice (not mentioned the process either), it should be the same for the AB.

**Comment by frivoal** [comment]
> W3C appoints the chair, on the recommendation of the AB

If W3C should always follow the recommendation of the AB, then there's no need for an intermediary, and the AB could pick the chair directly.

Since that's not what you're asking for, presumably you have some situations in mind where the W3C should not follow the recommendation of the AB. Can you elaborate?

> term to begin when nominations for AB election open

That seems suboptimal: it allows for an AB on its way out to impose a chair to the incoming one. When they're mostly the same, that's alright, but if a large number of members got ousted and replaced by new ones, having the new ones be stuck with the old ones' choices seems undesirable.

> I believe that neither the CEO nor serving AB members should be chair, for essentially the same reasons.

Even if it is only advisory, the AB supervises what what the team and CEO do. This is not true in the other direction. Some individual AB members may be too strongly partisan or opinionated to be effective brokers of consensus, but the inherent conflict of interest isn't the same. The AB isn't an actual board, but it bears some similarities to one. It is often argued that the CEO shouldn't be the chair of the board. I've never heard the argument that the chair of the board shouldn't be a board member.

**Comment by chaals** [comment]
>>term to begin when nominations for AB election open

> That seems suboptimal: it allows for an AB on its way out to impose a chair to the incoming one. When they're mostly the same, that's alright, but if a large number of members got ousted and replaced by new ones, having the new ones be stuck with the old ones' choices seems undesirable.

A 3-year term provides for stability over freedom for each new AB. It also makes the commitment to chair a clearer one, less subject to the vagaries of an individual election, which I think will be important in attracting a good chair rather than settling for one whose primary virtue is being available to do the job.

The outgoing AB are probably not the best AB we could have, but I they have more experience of how the AB works and what it does, and while they may bias for poor existing practice I think the 10 months of being on the AB provides insight that enables them to make a good choice.

Personally, I strongly value institutional memory, which is held by people, and maintained by not turning over all the apple-carts at once.

**Comment by chaals** [comment]
> > I believe that neither the CEO nor serving AB members should be chair, for essentially the same reasons.

> Even if it is only advisory, the AB supervises what the team and CEO do. This is not true in the other direction. Some individual AB members may be too strongly partisan or opinionated to be effective brokers of consensus, but the inherent conflict of interest isn't the same.

Chairing is a distraction from participation and vice versa. That is the same principle on which the CEO should not be chair. Effectively the chair *is* a member of the board - just not one of the 9 elected members whose primary purpose in being there is to represent the members, and who should be unambiguously the people whose advice is being given.

In the pathological case, this also stops a member of the AB being pushed to chair as a means of muting them. (Which is incidentally how I cam down against b locking a chair and an AB emmber from the same organisation).

**Comment by chaals** [comment]
>> W3C appoints the chair, on the recommendation of the AB

> If W3C should always follow the recommendation of the AB, then there's no need for an intermediary, and the AB could pick the chair directly.
>
> Since that's not what you're asking for, presumably you have some situations in mind where the W3C should not follow the recommendation of the AB. Can you elaborate?

Actually, I doubt the team will ignore the recommendation of the AB. The primary rationale is a formalism, because only every 3rd AB recommends a chair under my proposal.

There is a tension in the arrangement. If the AB picks a chair the Team (or CEO at least) simply cannot work with, there is the possibility to ignore them. Equally, if the team does ignore AB recommendations, it is a fair bet they will get a lot of pressure to do that again, so it is a precedent to avoid if at all possible...

**Comment by frivoal** [comment]
> If the AB picks a chair the Team (or CEO at least) simply cannot work with, there is the possibility to ignore them.

A chair that the CEO cannot work with would be problematic (so would a chair that the AB cannot work with, for that matter).

I think this is better addressed by including the CEO, who would be an ex-officio member of the AB, in the group of people who have to be in consensus about who the new chair(s) is. If the proposed chair(s) is unacceptable to the CEO, then we don't have consensus.

**Comment by frivoal** [comment]
> this also stops a member of the AB being pushed to chair as a means of muting them. 

I don't believe this is a case we realistically need to block against, nor that becoming a chair would actually prevent someone from expressing opinions should they wish to.

**Comment by fantasai** [comment]
Strong +1 to @frivoal's points in https://github.com/w3c/w3process/issues/223#issuecomment-438581753:

> That seems suboptimal: it allows for an AB on its way out to impose a chair to the incoming one. When they're mostly the same, that's alright, but if a large number of members got ousted and replaced by new ones, having the new ones be stuck with the old ones' choices seems undesirable.

> Even if it is only advisory, the AB supervises what the team and CEO do. This is not true in the other direction. Some individual AB members may be too strongly partisan or opinionated to be effective brokers of consensus, but the inherent conflict of interest isn't the same. The AB isn't an actual board, but it bears some similarities to one. It is often argued that the CEO shouldn't be the chair of the board. I've never heard the argument that the chair of the board shouldn't be a board member.

Insofar as chairing impedes participation, this is why Tzviya recommended that this clause allow for co-chairs. A good pair of co-chairs can pass chairing back and forth as needed for each to effectively participate. glazou and plinss were very effective at doing this in the CSSWG: I don't think anyone can say that being pushed into chairing diminished their participation. (If anything it strengthened it, because chairs are required to always show up and pay attention!)

Wrt 3-year terms and election by the outgoing board: that is an extremely pathological system. I have no idea why you think it's a good idea. The purpose of the election is that the new board best represents the interests of the membership. If incoming members decide that a change in chairing is necessary for them to effectively do their job, then they should absolutely be able to make that change. Your concern for stability is already addressed by the fact that the AB has a very strong tendency to have a significant overlap between new/old members, and the fact that W3C groups in general do not see the need to frequently change their chairs and therefore don't do so. The strength of institutional knowledge isn't lost in changing chairs, it's inherent in the membership. A chair cannot replace that; its role need not be conceived of as its embodiment.

I think it's very important that the AB be able to effectively set its agenda and effectively drive issues to conclusion, and facilitating this is part of what an AB member is elected for. If a particular member can do this best by chairing, that is totally part of fulfilling his/her responsibilities as an elected AB rep. And if they can do it best by supporting some other chair, whether drawn from the AB, or the Team, or the W3C community at large, then that's also fulfilling that responsibility.

**Comment by cwilso** [comment]
I do want to be transparent that I have a severe objection to essentially using STV to select the AB chair.  (Since AB members are elected by STV.)

**Comment by michaelchampion** [comment]
I don't object at all to ranked choice voting when there is a single winner, it's useful way to avoid (hypothetical?)   "Jill Stein voters electing Trump" scenarios.  The Meek algorithm's lower threshold for election when there are multiple winners is IMHO a bad way to elect groups that operate by consensus.

**Comment by chaals** [comment]
I'm convinced by @fantasai and @frivoal here (and others offline) that there is no reason the AB should not be free to choose its chair at any time. I therefore suggest we move to a procedure where the chair serves at the pleasure of the AB.

I am unconvinced that having an AB member as regular chair is a good idea. The AC electing someone because they could be a good chair doesn't make much sense unless the AC chooses the chair - in which case that should be done separately to electing other representatives.

With respect to "the chair should not be a member of the board", there is plenty of precedent for this princiuple. Speakers in Westminster parliaments are probably the "textbook" example. Basically, while it is possible for an active participant in discussions to chair them reasonably (and it happens all the time at W3C), doing so is a distraction. 

It also unfortunately happens all the time at W3C that a chair feels their role gives them a special place in the speaker queue of "whenever they want to weigh in". Combined with a general principle that the chair sets the agenda, frames proposals and declares the resolutions of the group, this doesn't help an active participant in a debate to ensure a fair and impartial procedure to find consensus - at best, good participant chairs achieve that **despite** the inherent bias in the setup.

**Comment by cwilso** [comment]
@michaelchampion But this isn't ranked-choice voting by the constituency of the W3C (the AC) - it's a vote by the AB, who are elected in STV votes.  The "voters" in this case are not the AC, nor are they necessarily representative.

I would DEFINITELY vote against the chair serving at the pleasure of the AB itself.  I think the chair should either be elected by the AC, or should be appointed by the Team.  I have a relatively strong preference for the latter.

**Comment by fantasai** [comment]
> I would DEFINITELY vote against the chair serving at the pleasure of the AB itself. I think the chair should either be elected by the AC, or should be appointed by the Team.

@cwilso Why? Why do you think the Team or the AC has a better ability or incentive to pick a good chair than the AB itself?

**Comment by cwilso** [comment]
Yes, I do.  I think the Team is motivated by the long-term needs of determining the direction of the W3C, and what it needs advice on.  I think the AC isn't really set up to make single-person selection decisions, to be honest - the engagement is too low.  I think the AB has an incentive to choose someone who would be a "good" chair for the people on the AB - that may or may not be the same as effective for the long-term health of the W3C.

**Comment by fantasai** [comment]
@cwilso I agree with you that the AC isn't the right body to make this decision. That's why I was suggesting the AB does it. But you're the one suggesting the AC elect it, but now arguing against that, so I'm confused what you mean here?

**Comment by cwilso** [comment]
@fantasai Sorry, I wasn't very clear.

I think the AB would choose a person they'd be happy with.  I don't think that is going to result in the best chair to organize the group's work in advising the Team - I think they'd choose someone they'd like to work with, and that may not match with "get the AB to advise the Team on the most important topics."

I don't think the AC is a great way to select a singular chair in this manner - because of the low election turnout, and because, well, they don't elect single people - so this would seem like a big deal, and I don't think it is.

My preference, thus, is basically the status quo that the Team should pick the AB chair - although with the caveat that I agree that the CEO personally chairing is probably not ideal.

**Comment by cwilso** [comment]
(as I'd said above, I have a relatively strong preference for the Team selecting the chair, although if the AC were given the power, I wouldn't really object.)

**Comment by frivoal** [comment]
The AB has discussed this issue at length, and concluded that we want to experiment with variations on how the AB is chaired. We feel that this can be done under the current Process, and that it would be premature to change the Process to enforce any particular arrangement.

The consensus of the AB is to defer #223 from Process 2020 and put it under consideration once the AB sees how the experimentation works out.

—Florian (on behalf of the AB)

**Comment by fantasai** [comment]
The current Process does not allow both the CEO and a chair who is not the CEO to be on the AB, though, so it still needs fixing. Minimal changes here would be:

```diff
diff --git a/index.bs b/index.bs
index 15020b4..69ee86b 100644
--- a/index.bs
+++ b/index.bs
@@ -580,9 +580,8 @@ Advisory Board (AB)</h3>
 <h4 id="ABParticipation">
 Advisory Board Participation</h4>
 
-       The [=Advisory Board=] consists of nine to eleven elected participants and a Chair.
-       The [=Team=] appoints the Chair of the <a href="#AB">Advisory Board</a>,
-       who is generally the CEO.
+       The [=Advisory Board=] consists of nine to eleven elected participants and the CEO.
+       The [=Team=] appoints the Chair(s) of the <a href="#AB">Advisory Board</a>.
        The team also appoints a <a href="https://www.w3.org/Guide/staff-contact">Team Contact</a> for the [=AB=],
        as described in <a href="#ReqsAllGroups"></a>.
```

This makes the CEO ex officio part of the AB and allows the Team to independently choose a chair (or co-chairs). This allows the AB to experiment without having to bend the rules of the Process.

**Comment by chaals** [comment]
The AB can invite people to meetings. For a decade or so it invited Steve Zilles, with the explicit request to chair for them. We have invited a scribe for about 2 decades. If the appointed chair is not the CEO, the AB can still invite the CEO (that is my marginally preferred model for how it happens, but I don't think it is a very important issue). 

If we make a change I agree we should reflect it in the process, but I think we already have sufficient latitude to experiment until then.

**Comment by jeffjaffe** [comment]
+1 that we don't need to "fix" the process to allow a non-CEO chair and a CEO chair to both attend the AB meeting.

**Comment by LJWatson** [comment]
I think @fantasai  is heading in the right direction on this, but agree with @chaals' comment that the AB has always invited participation from other people.

Proposed variation of Fantasai's original and more recently amended text (sorry for the lack of correct markup):

"The Advisory Board consists of 9 to 11 participants elected by the Advisory Committee. The Team appoints the Chair(s) and Team Contact for the Advisory Board.

The appointment of the Chair(s) MUST be consistent with 3.1.1 Conflict of Interest Policy.

The Advisory Board MAY invite other people to participate in Advisory Board meetings at its discretion."

**Comment by chaals** [comment]
If we redefine the AB without the chair as an _ex-officio_  (in principle voting) member, I think we should clearly note that the CEO will generally be invited to attend AB meetings and should expect to be available for all meetings.

(@LJWatson's proposed text seems to imply such a decision and @fantasai's doesn't, but the rest of @LJWatson's text are improvements I like that aren't contingent on any such decision).

I don't have precise wording for this because we have not taken any such decision.

**Comment by fantasai** [comment]
OK, so depending on whether the Chair(s) are granted voting rights even if not elected members of the AB., we have the following proposed wordings:

Proposal A: “The Advisory Board consists of 9 to 11 participants elected by the Advisory Committee. The Team appoints the Chair(s) and a Team Contact for the Advisory Board as described in [5.1]. The appointment of the Chair(s) MUST be consistent with 3.1.1 Conflict of Interest Policy. The Advisory Board MAY invite other people to participate in Advisory Board meetings at its discretion, and usually invites the CEO.”

Proposal B: “The Advisory Board consists of its 9 to 11 participants elected by the Advisory Committee and its Chair(s). The Team appoints the Chair(s) and a Team Contact for the Advisory Board as described in [5.1]. The appointment of the Chair(s) MUST be consistent with 3.1.1 Conflict of Interest Policy. The Advisory Board MAY invite other people to participate in Advisory Board meetings at its discretion, and usually invites the CEO.”

**Comment by frivoal** [comment]
I don't think the fix is urgent, as the current wording does let the team pick, and the team can pick whoever, and as we can indeed invite the CEO should they not be chair. But I do think making the CEO a member out of right, rather than someone we might want to invite if the chair was someone else, is the right thing to do. An AB that wouldn't invite the CEO to its meetings would be pretty broken, so I see no reason to allow that. @fantasai's proposed edit in https://github.com/w3c/w3process/issues/223#issuecomment-505347408 does fix that, while not changing the practice that the Team picks the chair, so I'd support that. If we want to wait so see if we can say something more specific as a result of the experiments mentioned in https://github.com/w3c/w3process/issues/223#issuecomment-490326127, that's ok with me too, but @fantasai 's suggestion still looks correct, and does not in contradict that.

**Comment by chaals** [comment]
@fantasai your proposed wording above captures most of it, but right now the practice is that the CEO is a member (something that effectively changed when Jeff took up chairing - before that the longstanding practice was that the CEO was actually just an observer, but attended pretty much every meeting).

**Comment by nigelmegitt** [comment]
@fantasai I think Proposal B needs tweaking to allow for the Chair to be either a member of the AB _or_ an invited non-member. Right now it looks like the Chair is _always_ an invited non-member.

**Comment by chaals** [comment]
@nigelmegitt said 
> Right now it looks like the Chair is always an invited non-member

That's **my** preference - I think the chair should not be an AB member for the same reason I think it should not be the CEO. Again, we haven't made any decision here, and the AB is in a holding pattern while it experiments.

**Comment by dwsinger** [comment]
(I cannot remember why I added the label)

**Comment by fantasai** [comment]
Note: The AB provided feedback and wording is being drafted in https://github.com/w3c/w3process/issues/514

**Comment by frivoal** [comment]
https://github.com/w3c/w3process/issues/514 has been accepted, so I believe this is solved. @fantasai do you confirm we can close?

**Comment by dwsinger** [comment]
effectively addressed in p2021
