### ISSUE TITLE
Director can dismis a AB or TAG participant without giving a cause?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#23]
Transferred from https://www.w3.org/community/w3process/track/issues/160
State: Raised

**Comment by chaals** [comment]
> Section 2.5.3 now says that an AB or TAG seat is vacated when "the Chair asks the participant to resign”, without any context or limitation. That seems like an unusual amount of power for the Chair to have at their disposal.
> [From: Mark Nottingham](https://lists.w3.org/Archives/Public/public-w3process/2015Mar/0068.html)

**Comment by chaals** [comment]
The Director is almost never, in historical reality, the chair of the TAG or AB.

For elected participants, it might be reasonable for the AC to have some means of removal, but I agree that it is a bad idea to allow W3C to unilaterally refuse to deal with someone the members have chosen to represent them. I suggest we remove this stipulation.

**Comment by dwsinger** [comment]
I think that this mechanism is how rules on participation in the TAG and AB are enforced, so as long as there are those rules, we need something. Also, the Director can remove (for cause) anyone from any group, as I understand it, so in the places in the process where that is stated, we could make it explicit that that includes TAG and AB. I also have a vague preference for avoiding euphemism here; if we mean "may remove a member" then let's say it, or we risk the perverse "I asked you to resign" getting the reply "and I refused".

**Comment by chaals** [comment]
I am OK in principle with a specific concept of Good Standing to be (re-applied) to TAG or AB, but in practice I'm not sure it is worthwhile.

And absolutely, it is a power to remove. Although under the old process, once you were asked to resign, that was the trigger, whether you agree or not :)

**Comment by dwsinger** [comment]
It's not so much good standing, as the possibility of violations of agreements (e.g. member), policies, processes or codes (e.g. code of conduct). Also, we should think about non-performance for TAG and AB: we can't afford passengers who don't turn up to meetings or participate in the debates, IMHO. The closest I can find in the process is 3.1.2 "In exceptional circumstances (e.g., situations that might jeopardize the progress of a group or create a conflict of interest), the Director may decline to allow an individual designated by an Advisory Committee representative to participate in a group." but this doesn't really cut it.

**Comment by chaals** [comment]
Hmm.

Agreed that the current power of the director to remove people from WGs doesn't seem to extend to the AB/TAG.

===

While I find it frustrating when there are "passengers" in groups who don't do a share of the work, I think the situation in Working Groups is that we tolerate them on the basis that we end up getting more work done that way. For the AB and TAG, if the members elected someone and they do no work, I think it should generally be up to the members to remove them. 

IMHO both groups have successfully "carried passengers". I have not seen an example where a chair is likely to actually remove someone elected by the members, in part because that is a very big step for a chair to take in practice, and I cannot see it actually happening for "not pulling your weight" in debates.

Besides, motivating people to speak for the sake of maintaining their position has nasty unintended consequences.

===

Removing people for a gross violation of the code of conduct *does* seem like the Process should explicitly enable it. Except with reference to the insufficient Director's power noted above, the Procedures part of the Code of Conduct doesn't actually provide anything beyond "contact the W3C ombuds", who 

> operate by procedures appropriate to their sites and jurisdictions

to 

> to work toward resolving complaints between any internal or external constituent

I think this is where we should be focusing our attention. 

My initial thought is that we should update the Procedures to provide a little more operational advice, including some mechanism for relatively urgent resolution such as being clear that people can be kicked out of a meeting, or even have an elected position taken away, and note in the Process that this is normally a responsibility of a chair in the case of a Working Group, the TAG or AB, allowing for appeal to W3C ombuds and the Director. Feedback wanted…

**Comment by jeffjaffe** [comment]
I think mnot's question is more general than the way Issue #23 is phrased.

1. The question was about the Chair of the AB and TAG; not the Director.
2. I think Mark's question was whether the Chair should have the authority to ask people to resign at all - not whether they needed to supply some reason while asking the elected person to resign.

**Comment by dwsinger** [comment]
see also https://github.com/w3c/w3process/issues/30

**Comment by dwsinger** [comment]
Lots of points here.
1) I prefer to avoid euphemism and say "dismiss" rather than "ask to resign" if that's what we mean. What if we ask and the person says no?
2) We need a blanket statement (which we're getting) about requiring CEPC across the entire W3C. 
3) If there are other reasons to dismiss AB or TAG members, they need spelling out. We already have rules against continued dual participation from the same member body. Do we need any rules about engagement/productivity?

Overall, perhaps this statement should say that TAG or AB members that no longer meet the criteria for being such may be dismissed?

**Comment by chaals** [comment]
As a a general principle, I think the people who put someone in a position should be the ones to determine that the person isn't doing what they were put there to do.

This means that for something other than an obvious breach of the process - including its requirements to be reasonable and follow the terms of CEPC - it should be up to the AC to remove someone.

The director could always request a review on such a decision, which would satisfy me, but I'm not sure what constitutes sufficient grounds for dismissal mid-term. While there are always people who do more, and people who do less work, there are not very good rules for identifying them.

I understand the term of elected members to be a balance between enough time for them to do stuff, even if for some unforeseen reason they need to take some time off - as has happened to me in most of my terms as an AB member - and not so long that the AC is burning with impotence because it cannot vote them out. 

And that assumes that all the AC have the same goals for each person they elect, which of course is laughably untrue.

In the case of a breach of process, I think it is reasonable to allow chairs, including those of the TAG and AB to sanction members with exclusion for some period, up to and including "the duration of their elected term". I'm actually reasonably happy to rely on social pressure to ensure that isn't done arbitrarily, reluctant to try specifying specific rules, and prepared to rely on W3C to select chairs who ensure it is done if it needs to be.

**Comment by dwsinger** [comment]
Ooh, Chaals hints at impeachment proceedings at the AC for AB/TAG members. I don't think we need to go there, though.

I think perhaps all we need is the explicit statements (a) a Chair can suspend or remove any participant in their group for violations (of the Process, Member agreement, or documents linked therefrom). (b) In case of doubt, this rule also applies to the AC, TAG, and AB. (c) Such suspension or removal can be appealed using the appeals procedure described in the process.

Given an explicit link to CEPC in the process, would this suffice?

**Comment by dwsinger** [comment]
I note that there is a consistency issue. 

2.5.1: If after 30 days the situation has not been resolved, the Chair will declare one participant's seat to be vacant.
2.5.3: 
An Advisory Board or TAG participant's seat is vacated when either of the following occurs:
•	the participant resigns, or
•	the Chair asks the participant to resign.

I think 2.5.3 should match 2.5.1 and say "the chair declares the seat to be vacant, according to 2.5.1" (which leaves the question over whether they can dismiss for other reasons as well).

**Comment by chaals** [comment]
Essentially I think we should be clear that the chair is not given arbitrary power to refuse people the right to participate, but that there are certain circumstances which involve failing to abide by the obligations in our governing documents, under which the chair is explicitly empowered to admonish, or even exclude, participants, with the check on that power being the ability to appeal (in the plain language sense of ask) to others for justice and fair treatment. As described, for example, in CEPC.

I note that in cases where people *have* been excluded for some period, a **common** phase is a chair telling someone their behaviour is unacceptable, and the person replying by questioning the chair's authority to make such a statement.

My point about something like impeachment is precisely that I doubt we want to go there. The issue has been considered by some of the best legal and political minds in the world for centuries, and their current conclusion seems to be "it's hard. You probably want some kind of emergency mechanism, but you probably don't know what it is until you actually need it". And I suspect we're not likely to improve markedly on that.

**Comment by dwsinger** [comment]
I think we're converging. 
1) Add text somewhere that anyone, in any group (including elected groups such as the TAG and AB, and representative groups such as the AC, as well as WGs, IGs, BGs, etc.) can be removed from the group by the Director for cause, where cause includes violating conditions of the process, membership agreement, and applicable laws. If we then link CEPC into the process, that covers it.

2) Revise the wording of 2.5.3 to say 

An Advisory Board or TAG participant's seat is vacated when either of the following occurs:
•	the participant resigns, or
•	the seat is declared vacant according to 2.5.1, or
•	the Director dismisses the participant for cause according to x.y.z.

**Comment by chaals** [comment]
So if this gets agreed to, I'll do the legwork.

**Comment by jeffjaffe** [comment]
On 7/5/2017 6:02 PM, David Singer wrote:
>
> I think we're converging.
>
> 1.
>
>     Add text somewhere that anyone, in any group (including elected
>     groups such as the TAG and AB, and representative groups such as
>     the AC, as well as WGs, IGs, BGs, etc.) can be removed from the
>     group by the Director for cause, where cause includes violating
>     conditions of the process, membership agreement, and applicable
>     laws. If we then link CEPC into the process, that covers it.
>

Thanks for remembering to link CEPC into the process.  I had sent an 
email last month to this list with my priorities for Process 2018. I had 
neglected this one, but I agree, it should be on the list.

**Comment by dwsinger** [comment]
An Advisory Board or TAG participant's seat is vacated when any of the following occurs:
•	the participant resigns, or
•	the seat is declared vacant according to 2.5.1, or
•	the Director dismisses the participant for cause according to x.y.z.
•      when their expires

**Comment by dwsinger** [comment]
Add text "somewhere" that anyone, in any group (including elected groups such as the TAG and AB, and representative groups such as the AC, as well as WGs, IGs, BGs, etc.) can be removed from the group by the Director for cause, where cause includes violating conditions of the process, membership agreement, and applicable laws. If we then link CEPC into the process, that covers it.

Revise the wording of 2.5.3 to say:
An Advisory Board or TAG participant's seat is vacated when any of the following occurs:
•	the participant resigns, or
•	the seat is declared vacant according to 2.5.1, or
•	the Director dismisses the participant for cause according to x.y.z.
• when their term expires

**Comment by dwsinger** [comment]
Add in 3.1 before 3.1.1:

The Director may remove for cause a participant in any group (including the AB and TAG), where cause includes violating conditions of this process, the membership agreement, or applicable laws.

Revise the wording of 2.5.3 to say:
An Advisory Board or TAG participant's seat is vacated when any of the following occurs:
•	the participant resigns, or
•	the seat is declared vacant according to 2.5.1, or
•	the Director dismisses the participant for cause according to x.y.z.
• when their term expires
