### ISSUE TITLE
Section 1 Introduction, general overview

### ISSUE THREAD

**Issue by RachelComerford** [w3c/w3process#232]
In the introduction under the 4 step general overview of how W3C standardizes a Web technology, Step 1 it says the W3C is likely to organize a Workshop. The link through to the Workshop says that they are arranged by the Team. Suggest updated the language to reflect that the Team arranges the Workshops to make it clearer for those trying to work through the process for the first time.

**Comment by frivoal** [comment]
I am generally in favor of making responsibilities more clear and the process less ambiguous.

At the same time, the team certainly plays a (large) part in arranging workshops, but workshop preparations tend to involve more than just the team, and I wouldn't want to accidentally suggest (or require!) that this is not how things should work.

Given that we are in the middle of the final review period for the 2019 Process, and very close to a vote, I'd rather avoid making any change that isn't clearly 100% editorial, unless doing so is necessary to resolve objections.

I certainly want to continue this discussion, but can you confirm that it is OK with you that we do so with the understanding that any fix that comes out of this would go into the subsequent iteration of the process?

**Comment by RachelComerford** [comment]
Sorry - it wasn't clear to me from @dwsinger email that you were only looking for glaring issues? I was planning a full text review. If that's the case I won't review. I'm fine with this being put off to another iteration.

**Comment by frivoal** [comment]
Any issue is fine to report, and we'll get to anything you find, but as this has been edited in the open and we're trying to wrap up, I'd like to separate the "fix this or I will object to publication" type of issues from the "it would be good to address this eventually" type of issues.

> I'm fine with this being put off to another iteration.

Thanks for the clarification.

**Comment by frivoal** [comment]
@RachelComerford this was marked as being part of process2020 because it came late in the 2019 cycle. If you'd like us to address this this year, we're going to need to talk some more about this issue.

To me, the intro makes a vague statement about the facts that workshops are a thing we do, and following through the link gives more details about how they happen. To be clear, is your proposal to change "W3C is likely to organize a Workshop[...]" to "The Team is likely to organize a Workshop[...]" in the intro? If so, I have no strong objection, but I also don't really see much of a difference, and would rather keep the status quo.

If I've misunderstood, can you explain?

**Comment by RachelComerford** [comment]
As someone who has had little involvement with the process in the past, it's entirely unclear to me, even after reading these documents, who organizes these workshops, how, and with what purpose. And so, I have no objection to not changing the language as I don't see the document as having much value to someone in my position, ie: someone who does not already have vast experience within the W3C and knowledge of the processes and terms outlined within. I don't feel as though I am the appropriate audience to review or comment.

**Comment by frivoal** [comment]
I think it boils down to the fact that the Process is not the document that describes how everything works, but more like the set of rules that must be followed. Things which aren't particularly bound by rules aren't described in the Process. Generally, they should still be documented, and http://www.w3.org/guide is a good place for that though.

With that said, ultimately the Process should be made easily readable by anyone, since these are the rules of our community. It could certainly use a significant amount of editorial improvements, but these are time consuming, and difficult to make without risking introducing subtle changes in the rules.
