### ISSUE TITLE
WDs are incorrectly characterized in 6.2.1

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#235]
"Working Drafts do not necessarily represent a consensus of the Working Group, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology."

There are (at least) two kinds of consensus.

Indeed the technical content of a WD may not yet have reached WG consensus, and there may well be unsolved problems, and unresolved conflicts. 

But we do require that the document represents the consensus of the WG that that is their current focus of work, represents their current best (if incomplete) thinking, and so on.  Personal and editor's drafts do not have that status, so WDs have more status than a random document.

**Comment by frivoal** [comment]
I agree. The trick is to rephrase this in a way that does not lead some groups / editors to think that they should reject publication as a WD when there are any unresolved (and potentially contentious) issues.

It probably needs some further tweaks, but here's a first attempt.

> Working Drafts do not represent the final consensus of the Working Group, as there can be unresolved issues or contentious points. They do represent the Working Group's latest thinking on the topic at the time of publication. Other than that, they do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology.

**Comment by nigelmegitt** [comment]
I think the distinction to make here is that although the WD does not necessarily represent a consensus of the WG as a final specification, the WG _did_ resolve by consensus to publish it in its current form. @frivoal I would not add wording to point towards unresolved issues or contentious points.

To be constructive, here's an alternate proposal:

> Working Drafts do not necessarily represent a consensus of the Working Group with respect to their content, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology. Nevertheless the Working Group has resolved by consensus to publish this document in its current form to provide an opportunity for wide review.

**Comment by dwsinger** [comment]
Not even sure every WD is for Wide Review. How about

Nevertheless the Working Group has resolved by consensus that the working draft reflects their current status and is the focus of their attention, and that it provides an opportunity for review by others.

**Comment by chaals** [comment]
The purpose of requiring regular Working Drafts is to facilitate review, as work is done rather than all at the end.

I'm not that perturbed about the precise wording, although I like [Nigel's proposal](https://github.com/w3c/w3process/issues/235#issuecomment-449347229). Given the magic nature attached to the words "wide review" perhaps it should just say something like "to enable timely review, especially of recent work on the spec".

**Comment by dwsinger** [comment]
sure, if we leave "wide" out and reflect that the WD has the status of being the WG's WD, I'm fine.

**Comment by nigelmegitt** [comment]
Leaving "wide" out would be okay I suppose, but I think it is true that all CR transition requests must demonstrate wide review of a WD, therefore it seems to me like an improvement to bring the Process terms together here and use the phrase "wide review" rather than just "review".

Even if no CR transition request demonstrates wide review of a particular WD, the purpose of the WD was nevertheless to permit wide review to happen. Otherwise why publish it? 

If there's a separate issue about the definition of "wide review" that's not something we should be tackling here.

**Comment by dwsinger** [comment]
Not every WD is expected or intended to be a CR, surely

**Comment by dwsinger** [comment]
Happily I think we can deal with the issue (which we should file separately) "does the process assume all WDs are on the Rec. Track?", and just drop the 'wide' here, as 'wide review' is a technical term in the process which is used associated with certain transitions.

**Comment by nigelmegitt** [comment]
OK works for me I think.

**Comment by frivoal** [comment]
(just for the record, this issue isn't being ignored, merely handled as part of Process 2020, since it is not an objection against Process 2019)

**Comment by frivoal** [comment]
Not every WD is meant to trigger horizontal review by the various group who perform that service (although they're welcome to), but wide review is always desirable (if you don't want the general public and the industry at large to review your draft, it's probably a bad time to put out a WD). So I'm generally OK with Nigel's phrasing. However, “Working Group has resolved by consensus to publish“ isn't necessarily true, since [6.3.2](https://w3c.github.io/w3process/#revised-wd) says:
> To publish a revision of a Working draft, a Working Group:
> *    must record the group’s decision to request publication. Consensus is not required, as this is a procedural step

So, I'd propose tweaking your wording to:
> Working Drafts do not necessarily represent a consensus of the Working Group with respect to their content, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology. Nevertheless the Working Group has <s>resolved by consensus</s> **decided** to publish this document in its current form to provide an opportunity for wide review.

**Comment by frivoal** [comment]
Agenda+, as I think we're close enough to try and conclude.

**Comment by nigelmegitt** [comment]
That tweak looks good to me @frivoal even though it has made me look at that wording in 6.3.2 which itself seems looks very strange. The way WG's make decisions is by consensus. As a Chair I don't know of a way to declare a _decision_ without such consensus, and if I thought there was no consensus I would feel hindered in doing so; at least I would have to register that I was overriding an objection.

Any clues about what is meant by that "Consensus is not required" statement, before I raise an issue?

**Comment by chaals** [comment]
@nigelmegitt you've hit on a large issue - "Working Group decision" actually isn't defined, so the way groups make decisions is equally undefined. At the moment in practical terms where there is an obvious consensus nobody questions it, and where there isn't and a decision is needed chairs generally call one and then the howling starts, and we find out whose objections are treated how...

The idea behind the statement that consensus is not required is to allow for some procedure in the WG that says "we're just doing this" without needing to show consensus, as a placeholder until we have a clear way of knowing what a WG decision is.

**Comment by nigelmegitt** [comment]
@chaals thanks for that. Some groups have a decision policy in their Charter (e.g. the [TTWG Charter](https://www.w3.org/2018/05/timed-text-charter.html#decisions)) which I guess defines _decision_ in the context of that WG.

Perhaps we could state that whatever a "Working Group decision" is SHOULD be defined in the WG Charter, otherwise [default definition], where [default definition] is "anything declared as a WG decision by the Chair".

**Comment by dwsinger** [comment]
after "Nevertheless the Working Group has" I would like to add "agreed that this is the draft they are working on and "

**Comment by nigelmegitt** [comment]
@dwsinger no problem with that addition from my perspective, but I'm now curious to know the story of when a WG had more than one view amongst its members about which draft they were working on!

**Comment by dwsinger** [comment]
I guess I am not trying to disambiguate as much as make clear that the WD has more status than say an Editor's draft or individual draft, inasmuch as the WG has decided that it is THEIR current draft and the focus of work.

**Comment by frivoal** [comment]
In that case, how about:
> Nevertheless the Working Group has decided to assert ownership of the draft, and to publish[...]

**Comment by dwsinger** [comment]
Trying again; I don't think we need to state that 'wide review' is expected on every WD

Working Drafts do not necessarily represent a consensus of the Working Group with respect to their content, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology. Nevertheless the Working Group decided to adopt the Working Draft as the basis for their work at the time of adoption.

**Comment by dwsinger** [comment]
Working Drafts do not necessarily represent a consensus of the Working Group with respect to their content, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology. Nevertheless the Working Group decided to adopt the Working Draft as the basis for their work at the time of adoption. A Working Draft is suitable for gathering wide review prior to advancing to the next stage of maturity.

**Comment by dwsinger** [comment]
adopted in the May 2019 call
