### ISSUE TITLE
Does the process assume all WDs are on the Rec. Track?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#236]
Arises from #235: the Process seems to be somewhat ambiguous about whether all Working Drafts must be for Rec track documents originally or whether non-Rec Track documents can be published as WDs.

**Comment by frivoal** [comment]
(just for the record, this issue isn't being ignored, merely handled as part of Process 2020, since it is not an objection against Process 2019)

**Comment by frivoal** [comment]
Which bit of phrasing seem ambiguous to you about that?

My assumption is that all WD are attempts at making a REC, even if not all are successful. I don't see much of a use for making a WD out of something that isn't even trying to get to REC eventually.

**Comment by michaelchampion** [comment]
Today documents that are intended  to be come Notes are called Working Drafts, right?  "Working Draft" means literally means some draft that is still being worked on, and that seems orthogonal to the question of whether its ultimate state is a Rec, Evergreen Rec, Note, Registry, or whatever. 

Also First Public Working Draft (a bit of a misnomer since all drafts are public at this point) is only needed by documents that are developed under the IPR policy.  First Exclusion Opportunity Draft is probably a more accurate name -- it's the first chance for a WG member to say "here is a patent I'm not willing to make an RF commitment on that seems to be in scope of the current draft".  I think that FPWD state is needed for eventual Recommendations and Evergreen Recommendations, but not Notes, Registries, etc.

**Comment by nigelmegitt** [comment]
> Today documents that are intended to be come Notes are called Working Drafts, right?

I've not seen this pattern used in practice, even if the technical language in the Process might consider this to be the case. In reality there are Editor's Drafts and WG Notes that are effectively snapshots of those EDs from time to time. There's no sensible mechanism or place to publish a WD of a Note that I've seen. If a WG wants to publish an ED of a Note, they just publish it as a Note, knowing that later they can amend it at low cost.

**Comment by frivoal** [comment]
I agree with Nigel. I've seen WD's that become Notes, but that's WD that attempted to become REC, and became Notes when they failed. For things that are meant to be notes from the get go, I believe I've always seen them be published directly as Notes, and updated as needed.

Evergreen and registries are kind of interesting, but neither of them exist in the process yet.

I think we should sit on this issue for a while. Their is an ambiguity with Notes, but it's not causing actual problems, and we can revisit how we caracterise WDs with regards to ER or Registries once the dust settles on these topics.

**Comment by chaals** [comment]
I have seen WDs that are explicitly developed intending to become notes, where people wanted e.g. to put something up for review at a "notable" stage of development. But like @frivoal and @nigelmegitt I have mostly seen the patterns of "publish a Note directly, you can change it when you want", and Working Drafts becoming Notes as work on them was abandoned.

I agree with @frivoal - I don't see a concrete problem here.

**Comment by frivoal** [comment]
I suggest closing this with no-change. @dwsinger ?

**Comment by dwsinger** [comment]
Ping @nigelmegitt to ask whether he's OK with closing (or please point out specific problems or propose specific edits)

**Comment by dwsinger** [comment]
will close on the August call if no action

**Comment by dwsinger** [comment]
closing, will re-open if activity happens

**Comment by nigelmegitt** [comment]
I just noticed this while going back through old unprocessed emails, and see that it's almost a year old! So huge apologies for the ridiculous response time. I think this was buried in an enormous pile of incoming messages that came in during my vacation.

The concrete issue with Working Draft right now is the ambiguity arising from the fact that the Working Draft section is placed within, and therefore at first glance scoped by, the Recommendation Track section, even though its defined scope is broader than Rec Track.

[§6.2.1](https://w3c.github.io/w3process/#maturity-levels) is titled "Maturity Levels on the Recommendation Track" and includes a subsection on "Working Draft (WD)" that is actually the _definition_ of Working Draft, and includes both:

> Some, but not all, Working Drafts are meant to advance to Recommendation

and the line:

> For all Working Drafts a Working Group:
> [some rules]

This text in itself is not problematic, but given the scoping implied by the placement of this section, it is not as clear as it could be if these rules this truly apply to _all_ WDs, or only those WDs for Rec Track documents.

I suspect the cleanest thing to do here is to take the definition of Working Draft out of the "Recommendation Track" section altogether and put it in its own section. As far as I can tell no other change would be needed to resolve this, and it would be a purely editorial change that would avoid the potential misunderstanding.

**Comment by frivoal** [comment]
I am not aware of any problems arising in practice from the fact that the REC track and the Note track share the WD stage, so I don't think there is any urgency in fixing this, and we're very late into the 2020 cycle.

At the same time, I do think it's odd that the REC track and the Note track share the WD stage, especially given that the WD stage has patent policy implications, but that these only matter if we go onto the REC track from there. And while I don't know of real problems arising from that, it is confusing, both when reading the Process, and when reading a the status section of a WD which is intended to become a Note (e.g  "this is a FPWD, please exclude patent claims that you're not willing to license when this becomes REC. Also, this will become a Note, not a REC."). Furthermore, this confusion of having some shared states on tracks with different properties would get worse when/if we add a third track to handle registries.

So, I think we should reopen this issue, but we should address it after the P2020 cycle.

From a Process standpoint, I don't think there's anything that is accomplished by publishing a WD of a Note rather than a Note directly, other than signaling that it isn't final. But that could be done in the status section without needing a separate document category. So we could just abolish the notion of Working Draft being a stage on the Note track. If that's not OK, I'd suggest renaming Working Drafts of Notes into "Draft Notes".

**Comment by nigelmegitt** [comment]
@frivoal that makes sense to me. I think if all we were doing is addressing it editorially by putting WD into its own section (e.g. §6.2, bumping the current 6.2 down to 6.3 and so on down) then that could be done quickly on P2020 but I agree it wouldn't deal with the other oddities you point out. Perhaps we could do it as a two stage thing, with a quick editorial change now and a more proper splitting out in the next iteration?

**Comment by frivoal** [comment]
I'd rather leave it alone for now, since the previous versions of the Process were messy as well. Also taking WDs out of the REC track would be odd too: WDs, and the First Public WD, are stages of the REC track, and as far as I can tell (but it is a little ambiguous / non obvious), while it is possible for a WG to produce an FPWD and possibly more WDs on the way to a Note, an IG cannot do that, and they must do Notes directly. And the FPWD of a Note still invokes the patent policy, even though the later stages of the Note track do not.

So, whether WDs are both part of the REC track and the Note track, or whether they really are part of the REC track but a document meant to become a Note can start by using the tools of the REC track only to later continue its path to Note track is fuzzy.

In practice, I think P2020, though organized differently than P2019, is no worse off that its predecessor, and since we're trying to wrap up and send it off the the AC, this isn't really the time for editorial changes.

**Comment by nigelmegitt** [comment]
That's reasonable @frivoal

**Comment by frivoal** [comment]
Have a look at https://github.com/w3c/w3process/pull/488, it would solve this.

**Comment by nigelmegitt** [comment]
Thanks @frivoal I've looked, but have the usual problem that updates to bikeshed files aren't easily reviewable, especially for folk who don't generally use bikeshed. I separately opened a PR to address this (#417), by enabling pr-preview.

**Comment by frivoal** [comment]
I believe that having merged #488 (as well as https://github.com/w3c/w3process/issues/509), this issue has been addressed, and we can close. Agenda+ to confirm

**Comment by plehegar** [comment]
Q: Does the process assume all WDs are on the Rec. Track?
A: Yes, if the proposed process as of May 2021 gets adopted
