### ISSUE TITLE
new "currently vacant" rule seems to preclude resignation in advance that is coincident with an AB/TAG election

### ISSUE THREAD

**Issue by dbaron** [w3c/w3process#238]
While reviewing the proposed process document, I'm not entirely happy about the use of "currently vacant" in the new wording in [section 2.5.2](https://w3c.github.io/w3process/#AB-TAG-elections) that comes from #204.  This is because I'd like it to be clear that a vacancy can be created by a resignation that becomes effective when the election results are in.  This sort of future vacancy could be due to a change of affiliation (the rule in [section 2.5.3](https://w3c.github.io/w3process/#AB-TAG-vacated) that "that participant's seat becomes vacant at the the next regularly scheduled election for that group") or just due to a voluntary resignation that a member of the TAG or AB would like to time with the election to reduce process overhead.

It could be improved, I think, by changing both occurrences of "plus any seat that is currently vacant from the prior year" to something like "plus any vacancies in seats expiring in the alternate year".  But more explicit wording (as there is for the special elections case in 2.5.3, which explicitly says "The group Chair may request an election, and the election may begin, as soon as a current member gives notice of a resignation, including a resignation effective as of a given date in the future." from #62) may also be desirable.

**Comment by frivoal** [comment]
A clarification along these lines seems reasonable to me. I think it matches the intent of the current wording, and would remove some fuzziness at the edges.

However, given when we are in the Process update cycle, and that I don't believe you're opposing the 2019 Process on these grounds, I think it would be a lot easier to address this as part of Process 2020, rather than try and rush in a change and get it approved by everybody who has already voted.

Is it OK with you if I mark this as Deferred in the [DoC for Process 2019](https://w3c.github.io/w3process/issues-20180201), and triage it into Process 2020?

**Comment by dbaron** [comment]
I'm OK with deferring, although I thought that this might be small enough to be addressable this cycle.

**Comment by dwsinger** [comment]
I fear we have learned that precise wording is hard to do, and I'd rather not try at the last moment. The intent is clear for now.

**Comment by dwsinger** [comment]
We need precise wording in order to move on this.

change 

In the case of regularly scheduled elections of the TAG, the minimum and maximum number of avaiable seats are the same: the 3 seats of the terms expiring that year, plus any seat that is currently vacant from the prior year.

to Fix the spelling of available (!), and 

In the case of regularly scheduled elections of the TAG, the minimum and maximum number of available seats are the same: the 3 seats of the terms expiring that year, plus the number of seats that are or will be vacant from the alternate year.

**Comment by fantasai** [comment]
Shift "from the alternate year" to after "seats" so that it's clear what it's modifying, and lgtm. Maybe something like

> In the case of regularly scheduled elections of the TAG, the minimum and maximum number of available seats are the same: the 3 seats of the terms expiring that year, plus the number of seats expiring the next year that are currently or will be vacant in the coming year.

**Comment by dwsinger** [comment]
we're making heavy weather of this. "in the coming year" might suggest that the vacancy happens within a year, but no, the vacancy happens at or before the close of this election; the seat belongs to the coming year.

>In the case of regularly scheduled elections of the TAG, the minimum and maximum number of available seats are the same: the 3 seats of the terms expiring that year, plus the number of other seats that are vacant or will be vacant by the close of that year's election.

**Comment by chaals** [comment]
@dwsinger:

> the vacancy happens at or before the close of this election

In the situation that arose with me, that still would not have covered it. "At or before the end of the term of the current AB/TAG", or "by the time the newly elected members take their seats", or something like that would have been near enough to be unambiguous, if someone can say that more clearly.

**Comment by chaals** [comment]
(If we want to make heavy weather of this we could anticipate resignation at any point during a term, but that seems unlikely to provide a good return on the effort invested. So I think we should focus on other problems, unless someone has an elegant solution to hand)

**Comment by frivoal** [comment]
Mixing @dwsinger's and @chaals' phrasing gives this, which I'd be happy with:
> In the case of regularly scheduled elections of the TAG, the minimum and maximum number of available seats are the same: the 3 seats of the terms expiring that year, plus the number of other seats that are vacant or will be vacant by the time the newly elected members take their seats

**Comment by dwsinger** [comment]
Not going to argue about the small interval between election close and members being seated.

**Comment by frivoal** [comment]
Corresponding PR created: https://github.com/w3c/w3process/pull/286

Waiting for confirmation from the chair to merge.

**Comment by frivoal** [comment]
@dwsinger We seem to be in consensus. Can you call this resolved so that I can merge?

**Comment by dwsinger** [comment]
yes. I deem this editorial
