### ISSUE TITLE
Further automating transition requests

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#260]
This is not strictly an upper-case P Process issue, but it is a lower case p process issue. Starting it here for the lack of a better place.

I think moving form emails to github issues was a step forward for transition requests, but I'd like to go further and turn that into a semi automated form integrated with echidna: if you're trying to publish a CR, you get ask to certify that you've done a number of things by ticking boxes, (such as getting cross-functional review, compiling a Disposition of Comments, writing an implementation report, having a WG resolution for the publication, having a shortname, having decided on the length of the review period), and to provide evidence for them by writing prose or pasting links. If all the boxes are ticked, (and maybe validated by the WG's chair and team contact, who would be automatically contacted by the system), the publication should be able to go forward with minimal central verification.

If some of the boxes aren't ticked but the person requesting the publication has a provided reasons for why they think the publication should go ahead anyway, then it can be examined closer.

By making this into a piece of software integrated with echidna, a lot of the overhead both in filling transition requests and in reading them could be eliminated. For instance, transition requests should list the document title, the url for the change section, the abstract, or the status, but these things can be extracted from the spec automatically, (at least to prefill the form, even if we leave them open for further manual editing).

This way, we keep the flexibility of the current system which allows considerable latitude to judge each spec on a case by case basis, while moving closer to an automated system for routine publications.

**Comment by nigelmegitt** [comment]
I think this would be better targeted at the Working Group Effectiveness task force. @plehegar ?

**Comment by frivoal** [comment]
Well, I think it should really go to the systems team. The Working Group Effectiveness task force, as currently frame, seems focused on what WG can do themselves to be more effective. Discussing improvements to tooling would not be unreasonable for the task force to discuss, but I don't think it's been consider part of its scope. Or has it? @nrooney ?

**Comment by plehegar** [comment]
https://github.com/w3c/echidna/wiki/CR-publication-workflow describes how we're doing CR automatic publishing with Director and Comm approvals. We're using GH comments rather than tick boxes.
Are you looking for something more than than?
In practice, very few Groups have used this so far but we haven't advertised this widely either, simply due to the fact that the use of GH for transitions hasn't been made official yet.
If you're looking for Echidna improvement would go in https://github.com/w3c/echidna/issues but maybe the WGE TF is interested in giving some input here.

**Comment by frivoal** [comment]
> Are you looking for something more than that?

Yes. Instead of having a side channel where the editor must store information in freeform / plain text and refer to it off-band, I would like that when you attempt to publish a CR with echidna, it directs you to a web form (replacing the github info) that asks for all the relevant information. I imagine that when you've provided it (together with some machine readable way to either say "nothing unusual to declare" or "some exceptions will need to be granted"), it automatically pings (in an automated way) the WG chair and team contact for confirmation (via some automated form) that the statements are accurate. After that, the director or his delegate could publish with a single button press. And maybe if we're in the "nothing unusual to declare" and the chair & team contact do confirm, it could be published fully automatically.

@nrooney, do you feel this discussion is useful to bring to the WGE TF? If not, https://github.com/w3c/echidna/issues is indeed probably the right place to go for this.

**Comment by plehegar** [comment]
Actually, the right place for this would be https://github.com/w3c/transitions/issues . The idea of providing a tool to generate transition requests instead of using GH templates has been a wish for sometimes but never managed to get to the top of the queue in the past 18 months. See for example https://github.com/w3c/transitions/issues/62 as a weak idea to improve from what we have today. It does require some serious amount of time to develop, due to the need for authentication, etc.

**Comment by frivoal** [comment]
This is effectively being handled with everblue. Closing
