### ISSUE TITLE
Can a group member represent more than one organisation?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#27]
Transferred from https://www.w3.org/community/w3process/track/issues/175
State: Raised

**Comment by chaals** [comment]
This is a trivial issue. In various practical cases it has happened, and I think we should simply allow it.

The only practical impact I can find is on voting, which is rare. Since voting other than for TAG and AB - where people have historically been allowed to cast multiple votes if they have them, as already allowed - is more or less left to chairs to implement and regulate, I don't think we should keep this constraint.

**Comment by dwsinger** [comment]
I think we should think about what 'representing' means. It is linked to voting (which rarely happens, and even more rarely on a member-by-member basis, it's usually on an individual basis), it's linked to 'Contributing' (in the formal sense). Anything else?

**Comment by sandhawke** [comment]
Is this the same as #9 ?    Or is this one "Can person X represent Members A and B in WG Y?" while issue #9 is "Can person X represent Member A in WG Y and Member B is WG Z?"

A related issue which I currently have is "Can person X represent Member A in WG Y and be an IE in WG Z?"   (answer from team-legal was Yes, if they disclose COI.)

**Comment by vfournier17** [comment]
The concern here is that a single contractor/agent might "represent" several companies in a W3C WG.  That agent then makes patent licensing commitments on its own behalf, and not on the represented companies' behalf.  The agent then gets contributions from the represented companies, which the contractor then funnels through to the WG.  Those "contributing" companies haven't made any patent licensing commitments (so there would be no patent license), and the contractor hasn't contributed any of its own material (so its patent license commitment doesn't mean much).  This is a bad situation all around.  We should leave the language as is - even if this hasn't happened yet, the potentiality could create IP vulnerabilities for the other members of the WG who may not end up with a license to the contributions made through the agent to the WG.  If the language doesn't create a problem, why change it?

**Comment by chaals** [comment]
@vfournier17 my understanding is that the issue is the other way around. Someone "represents" an organisation in a Working Group because that organisation sponsors them as a member - in practice, by joining the working group.

So the rationale for the change is to simplify the process of getting IPR commitment from each organisation from which an agent is actually contributing to a WG.

In the case you describe (which is the one I am also working from and I think the relevant one), Agent99 could be nominated to a WG by Agency - a W3C member, but contracting for both Control and Chaos, two other W3C members. While Agency is required to tell W3C of these "significant relationships" there is no formal mechanism for Control and Chaos to directly nominate Agent99 as their representative, which is the default mechanism through which they would commit IPR.

It *is* still possible for them to independently join the Working Group to make an IPR commitment, without naming a representative. Likewise, in principle it is possible for a non-member organisation who is not represented in the Working Group to make a commitment, but the actual procedures are bureaucratic in theory and ill-defined in practice (ping @wseltzer).

**Comment by dwsinger** [comment]
#9

**Comment by dwsinger** [comment]
see also issue #9

**Comment by dwsinger** [comment]
closing and merging into #9
