### ISSUE TITLE
Can the Evergreen state be permanent or should ERs eventually become Recs?

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#273]
The argument in favor of assuming ERs become Recs seems to hinge on Horizontal Review.   Will HR groups feel that total HR is never done, and thus not be motivated to engage in reviewing ERs?

I believe that ERs are "done" when they are no longer relevant, so it's futile to require that ERs eventually become Recs....

**Comment by jeffjaffe** [comment]
I think we need to be sensitive to the needs of the Horizontal review communities, as well as other communities that rely on our specs (e.g. JTC1) that would like a "final" spec at some point.  Therefore I think it is beneficial for ERs to become RECs.  This is essentially the approach we are taking with HTML, working with WHATWG.

It is an open question in my mind how forceful we should make the assertion that ERs become RECs.  Some choices are:

- Must
- Should
- Must happen upon a valid request (where valid request could be JTC1 request, government request, etc.)

**Comment by michaelchampion** [comment]
I think it has to be MAY to get some of the specs on PLH'S list on board. I've hear (indirectly) that the WebIDL folks are interested in the Evergreen track ONLY if they don't need to go through the nightmarish tedium of getting to Rec.

Wide review is the Hard Problem we have to solve to create an Evergreen Recommendation. If we don't solve it to the satisfaction of the HR communities, we've failed. If we fail, WHATWG Living Standards will be the preferred route for those who have to write standards for Evergreen browsers.

But I think there's something to be said for adopting the Working mode described in the WHATWG MoU (which by the way the SG has signed off on and we're waiting for W3M to do likewise).  ERs would be developed by a WHATWG  like process; a WG would have the ability (but no obligation) to take a snapshot, get it to meet the PR criteria, then get AC/"Director" approval and make it a Rec.  That would satisfy the rare (IMHO) use cases where a final" spec for a still-viable  technology is warranted.

**Comment by cwilso** [comment]
I disagree that the approach with HTML is that the ER *becomes* a REC.  A *snapshot in time* of a living standard may become a REC, but it's not "the standard".  HTML will become "final" when it is no longer used and maintained.

I'm not sure what review community would really like to have a REC to start with - they would want to impact the direction of the spec, no?  It seems very off base to consider a HR community would want a final standard to start with.  Obviously, they will want somewhat-stable checkpoints, but that seems like an inflection point that is easily identified by the spec community.

**Comment by nigelmegitt** [comment]
>  HTML will become "final" when it is no longer used and maintained.

This is a fallacy I've seen a few times, sorry to pick on this one @cwilso but there are specs for technologies that are widely used and understood and mature enough that any maintenance tasks are not significant enough to warrant the effort needed to do them. For example there seems to be little motivation or need to update the XML specification. This does not imply it is no longer used; to the contrary it is extremely widely used, and those who use it attach value to its stability. 

It's not a great idea to punish spec-editors and writers who achieve a very high quality level that matches the users' needs well and therefore have fewer issues to address. It's arguably a _better_ result if the evergreen/living version has a low volume of update activity than a high volume, for some constituencies anyway.

I mention this in the context of this issue because it is at the core of the debate about ERs and Recs, and I think the key is to ensure that there is always a reasonably up to date Rec available to act as a stable reference, _and_ to allow ongoing editing activity where it is needed, while keeping spec users informed about what they're seeing. 

> what review community would really like to have a REC to start with

"REC" does not imply "we want to stop work on this". Anyone writing mission-critical systems, or software that will be deployed in environments where updates cannot easily be made wants a REC.

From this perspective, I disagree with the either/or premise of the issue. In my view, yes, ERs should become RECs (ideally with as low delay as is reasonably possible) _and_ the evergreen state should be available for continuing work as needed.

Perhaps we should be asking another question: what's the path for creating ERs from RECs to allow for ongoing development where it's needed?

**Comment by dwsinger** [comment]
> I think we need to be sensitive to the needs of the Horizontal review communities, as well as other communities that rely on our specs (e.g. JTC1) that would like a "final" spec at some point. Therefore I think it is beneficial for ERs to become RECs. This is essentially the approach we are taking with HTML, working with WHATWG.
> 
> It is an open question in my mind how forceful we should make the assertion that ERs become RECs. Some choices are:
> 
> * Must
> * Should
> * Must happen upon a valid request (where valid request could be JTC1 request, government request, etc.)

If there are bodies that need a formal reference to a Rec., OK.

But if the horizontal review communities are (a) not noticing issues as they arise and (b) not noticing Pull Requests before they are taken and (c) not reviewing material within the 180 days, then they are doomed, hopelessly behind the curve.  They cannot rely on waiting for a Rec. transition. Even the 180-day period is pretty doubtful, and should only be used when the consequence of a change and the way it interacted with the rest of the spec. wasn't obvious from the pull request.

WHATWG observes that Pull Requests are subject to much greater scrutiny and are *often* returned for rework; once a Pull Request on an ES is enacted, that *is* the Living Standard.

**Comment by TzviyaSiegman** [comment]
@dwsinger I wonder if there is some way to communicate the Evergreen snapshot process to JTC1. The need for referencing "final" documents has been an issue with documents I've worked on in the past.

**Comment by dwsinger** [comment]
I think we'd need to work with old-style bodies (like JTC1) that want a stable reference, to determine how to proceed, and it may well be that we need to publish periodic Recs for them. That's one of the very few reasons I can think of.

**Comment by nigelmegitt** [comment]
> once a Pull Request on an ES is enacted, that is the Living Standard.

It implies implementation commitment though, not implementation experience, right? Assuming that's correct, there must be a non-zero likelihood that merged PRs will be subject to further change later, if they're in the class of "it seemed reasonable but then we found we couldn't implement it".

> if the horizontal review communities are (a) not noticing issues as they arise and (b) not noticing Pull Requests before they are taken and (c) not reviewing material within the 180 days, then they are doomed, hopelessly behind the curve.

Right, we need a holistic solution to this, rather than just pushing back on the HR groups who may not be adequately resourced. Bypassing them because they can't go as fast raises the danger of quietly migrating from "they're not responsive" to "they don't care enough to keep up" to "the concerns they have are not legitimate".

**Comment by dwsinger** [comment]
@nigelmegitt completely agree; the proposed tooling, tracking, and so on improvements are all designed to make it much easier to track issues as they arise and work as it happens, so that HR groups can more easily comment when work is still 'malleable' and under way. Expecting early/active review to happen without helping it happen is too optimistic. ES relies very much on good tooling improvements (which i18n have done a great job of doing off their own bat).

**Comment by michaelchampion** [comment]
The entrance criteria to the ER state are not yet defined, AFAIK.  WHATWG's Working Mode criteria for adding a feature https://whatwg.org/working-mode#additions are a good starting point, but note that is uses the word "support" not "commitment" or "experience."  It does say "There should already be a prototype implementation or one being worked on side-by-side with the change to the standard." 

WHATWG's criteria don't say anything about horizontal review, but W3C ER entrance criteria presumably would have to.  I believe the ER HR criteria should be something like:
- Proponents of a feature have documented an engagement with appropriate HR experts and made them aware of the feature and given them an opportunity to review 
- Any widely used automated testing tools that can test for the various horizontal criteria are incorporated into the spec build process.
- There is a plan in place to mark changes with known labels and a liaison established with the various HR review entities at W3C so they CAN know when something changes and do review within the timeline noted in the ER process.   (I'm open minded on whether that should be a snapshot or a sliding window after a label is set).

If HR communities have a liaison relationship with a WG doing an ER and a process that alerts them when review opportunities occur, then I firmly believe that silence means assent.  That doesn't mean they can't raise a horizontal issue at any time in the future, just that for the purposes of the W3C Process, the ER criteria have been met.

**Comment by frivoal** [comment]
I don't think the transtion between ER and REC makes a whole lot of sense. If ER's are as high quality as RECs, with the only difference being that RECs are harder to update, I have a hard time seeing anyone doing the work needed for that transition. If the entry criteria for ER are lower than for REC, but they are still considered "good enough" by implementers, and RECs are still harder to maintain, then I don't see that transition happening a lot either.

The way I see it:
1. From incubation until right before CR, the REC Track as it exists today is effectively identical to the proposed evergreen (aside from some IPR rules that we could apply to the REC track as well if we wanted to)
2. There is value in the things we enforce at the CR transition, but the way we enforce them is very heavy, take a lot of time and effort, and this discourages people form using the REC track. Most of this however is a problem that can be solved by better tooling, without needing Process reforms. I've posted about this in the AB privately before, but for the benefit of those who don't have access to that, I've [blogged it too](https://florian.rivoal.net/blog/2019/05/REC-track-transitions-are-too-heavy/).
3. Going from CR to REC, or updating a REC, is discouragingly heavy:
    1. a good chunk of it is for the same reasons as for CR transitions, and can be addressed the same way
    2. in addition the process is insufficiently flexible about incremental updates to a REC or otherwise post CR spec. **This** is where REC track specs stop being evergreen, and where evergreen reforms would be useful. But if we do that part right, we just make all RECs evergreen, and then the question that this github issue raised goes away.

**Comment by michaelchampion** [comment]
The use cases for transitioning from ER to Rec generally involve some outside party such as JTC1 or a government that need a static, authoritative standard to reference.  Yes it's a heavyweight process, but the ISO/IEC or government regulation/procurement process is even more heavyweight and unable to accommodate frequent change.  So having it as an option seems reasonable even if rarely used

**Comment by dwsinger** [comment]
Jeff wants it as normal business; Florian doesn't want it at all (as neither would Living Standard purists). I agree with Michael, it needs to be an option, possible but not always expected.

**Comment by frivoal** [comment]
It's not really that I don't want transitions between the two states, it's the existence of the two states that troubles me.

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
