### ISSUE TITLE
What to do when there's no consensus in the Council

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#280]
The ability of the chair to call a vote may act as a disincentive to participants to try and reach consensus. However, removing it would mean that failing to reach any decision would be a possibility.

Alternatives suggested have included always using a 2/3 majority, or letting the problem escalate into an AC appeal if too much time passes.

See https://www.w3.org/Consortium/Process/Drafts/director-free/#addressing-fo

This probably relates to #279

**Comment by chaals** [comment]
It does relate to #279 IMHO, but I think the two can be dealt with separately.

**Comment by chaals** [comment]
I would suggest that a super-majority of AB members and a super-majority of TAG members is required to sustain a formal objection.

By supermajority I mean something like 2/3 majority of all votes - so if there are 9 people on the AB and two are recused, you still need 6 positive votes to sustain the Formal Objection. Given the relatively small numbers, a simple majority plus one additional vote might be a reasonable alternative.

**Comment by nigelmegitt** [comment]
@chaals your suggestion means that if around half the members are recused then the formal objection can never be sustained, because the supermajority cannot be achieved. Is that what you intended?

**Comment by dwsinger** [comment]
This is kinda like the state where the Director can't decide. Well, they keep arguing. If a decision is nonetheless needed (and the lack of a decision is a decision of sorts, at some point), then I think the question to ask is how do we force a termination? Allow them to vote? A majority vote is easy; If it's a super-majority, we have to decide which way it's biased (an FO requires a super-majority to be sustained, or the original decision needs a super-majority to be sustained and otherwise the FO is sustained)?

I agree with @nigelmegitt we have to do the arithmetic after recusals, so a supermajority of those members not recused. We don't expect recusal to be heavily used, mind you.

**Comment by avneeshsingh** [comment]
This also depends on how we see the participants who raise formal objections. Usually people who raise formal objections are minority in the working groups. Would 67% of votes to sustain their objection result in the perception that it is very hard to get formal objections accepted?

**Comment by michaelchampion** [comment]
It's currently hard to get a formal objection sustained; one has to convince the Director that a WG consensus (as determined by the chair) is somehow wrong.  There aren't many examples I recall of the Director intervening to overturn a consensus, and whatever he decides is likely to drive away some proponents of the losing side.

**Comment by fantasai** [comment]
@michaelchampion I think @dbaron has an example of a case where the Director overturned the CSSWG in the distant past. (Presumably this was the correct action: @dbaron is usually right on things.) So it's not common, but it does happen.

**Comment by frivoal** [comment]
Not all the things that can be formally objected to are consensual decisions. For example this is objecting to a previously established consensus:
* Objection by a someone who is not a WG/IG member to a consensual WG/IG decision to publish something

But these are not:
* Objecting to a Team's decision that the CR exit criteria are / are not fulfilled
* Objecting to a Teams's decision that a Member submission should be acknowledged / rejected
* Objecting to a proposed charter for a new Working Group
* Objecting to a Chair's decision to appoint an Editor
* Objecting by a WG member to a proposed decision of the WG 

I would suggest that we could require a two thirds supermajority of the Council to sustain an objection against a per-established consensus, but that a simple majority should be enough to sustain a formal objection otherwise.

If this principle seems palatable, we may need to look at details, as maybe not all cases necessarily neatly fall into one or the other category, but on a high level, that seems workable to me.

**Comment by hober** [comment]
I don't think we should constrain the Council's working mode much, including when & how it votes. I'd rather the Council be able to figure out for itself how to best get its work done. If the resulting decisions seem bad, maybe it'd be worth revisiting in the future.

**Comment by palemieux** [comment]
@hober Consider the viewpoint of those faced by an FO whose result might undo years of work and/or substantially delay work (have you ever been in that situation?): how would you react if the process was not predictable?

Also consider if you were a member of the FO council. How would you feel if rules changed for each FO? Would you spend the time to get up to speed with the myriad previous decisions and precedent?

**Comment by dwsinger** [comment]
The process is no less nor more predictable than today's decision by the Director. Yes, we have been in this situation. The _rules_ are not changing, please don't introduce strawmen. We have requested the team that documentation of all FOs and decisions be built so that the entire community can see precedent and previous wisdom, it's under way.

Overall, we are trying to replace the Director here with a body that represents the membership. We are not trying to eliminate, weaken, or re-define what FOs are and how they work.

**Comment by palemieux** [comment]
> The rules are not changing, please don't introduce strawmen. 

Maybe this is the disconnect: the rules should probably change because the conditions are changing. Instead of a single individual, who was ultimately responsible to the membership and the community, we now have a group of individuals with each their own allegiances.

Regarding the specific issue raised here, my recommendation is that, as detailed at #631, that, in the event that a voting procedure is specified and when there is no unanimity, that a simple 2/3 majority rule be applied.

Do you disagree with this proposal, and, if so, why?

**Comment by dwsinger** [comment]
Yes, I do. The playing field of formal objections is already tilted against the minority player. We should be ready to listen to a lone voice, and not set the bar so high as to deter raising questions. Supermajority requirements are also very sensitive to the phrasing/direction of questions and decisions. A chair might make an unpopular decision if they think that more than a 1/3rd of the Council would not vote to overturn, for example, even if a majority of both their WG and the Council disagree strongly.

**Comment by dbaron** [comment]
> @michaelchampion I think @dbaron has an example of a case where the Director overturned the CSSWG in the distant past. (Presumably this was the correct action: @dbaron is usually right on things.) So it's not common, but it does happen. I don't think this case drove anyone away, either.

Since the recent traffic on this issue caused me to notice the older ping to me:  I think the issue @fantasai was referring to was issue 3 in [CSS 2.1 issues-4](https://www.w3.org/Style/Group/css2-src/issues/issues-4) which was [about defining the table model differently for HTML and XHTML](http://lists.w3.org/Archives/Public/www-style/2006Sep/0065.html), also see [the w3c-css-wg thread](https://lists.w3.org/Archives/Member/w3c-css-wg/2007AprJun/thread.html#msg181) on the directors decision (which was held during an AC meeting welcome reception).  I can't find the actual formal objection.

**Comment by caribouW3** [comment]
> @hober Consider the viewpoint of those faced by an FO whose result might undo years of work and/or substantially delay work (have you ever been in that situation?): how would you react if the process was not predictable?

In most cases FO are quite predictable (except in some rare cases where an AC rep would use FOs quite often for rather small issues, because somewhat misunderstood the meaning of FO but this always got resolved easily by a simple talk). WG tend to know in advance where strong disagreements lay and they can't be truly surprised by a FO if they followed the review process all the way. I'm not saying it's their fault if they ultimately get the FO in their face at the end, I'm saying that controversial matters are visible from afar. Then the fact it is going to take time to get to a final decision, be it by the director or by a council, can't be helped.

> Also consider if you were a member of the FO council. How would you feel if rules changed for each FO? Would you spend the time to get up to speed with the myriad previous decisions and precedent?

I don't think that a member of an FO council necessarily has to know how previous councils resolved previous FOs. Arguments and situations can be very different. If WGs refer to precedents as argument points, they would certainly need to document those but constraining the FO council discussions too much seems rather undesirable (and impossible, in fact).

**Comment by dwsinger** [comment]
> WG tend to know in advance where strong disagreements lay and they can't be truly surprised by a FO if they followed the review process all the way.

Sometimes, unfortunately, people do realize things late in the process. But indeed, if someone raises an FO 'late' I expect eyebrows to be raised, and it may weaken the case: "why didn't you say all this in the WG?" "if you object to a spec. on this subject, why didn't you object to the Charter, and instead wait to PR?".  Now, it may be that something new has come to light, or there is some new realization, of course, so these are not diagnostic, but they are questions to ask.

**Comment by palemieux** [comment]
>  A chair might make an unpopular decision if they think that more than a 1/3rd of the Council would not vote to overturn, for example, even if a majority of both their WG and the Council disagree strongly.

Are you saying that, under the current W3C process, a Chair can make a decision without the consensus of a group and without violating the W3C Process? It is the second time I hear this today and find it extremely surprising.

> Supermajority requirements are also very sensitive to the phrasing/direction of questions and decisions. 

Making decisions by super-majority tends to generate clear positions -- esp. on a topic of importance.

Asking that the majority (super or simple) support the objection avoids the situation where an objection is sustained due to the apathy of Council member -- based on the assumption that the objection is overruling the opinion of a consensus body.

> The playing field of formal objections is already tilted against the minority player.

I would hardly describe the current playing field as tilted against the objector: as it stands, an objector can unilaterally, with minimal justifications and with minimal consequences, (a) slow down a project and (b) consume a large number of community resources.

**Comment by fantasai** [comment]
The current proposal is, the Council decides

- By unanimity if possible
- By consensus otherwise
- By a simple majority vote if all else fails

I believe this is the correct outcome, and that a supermajority vote in particular would be a poor mechanism to adopt for the reasons mentioned by @frivoal in https://github.com/w3c/w3process/issues/280#issuecomment-688604751 and by @avneeshsingh and @dwsinger in https://github.com/w3c/w3process/issues/280#issuecomment-502343564 and https://github.com/w3c/w3process/issues/280#issuecomment-1254367035

Regardless I think this discussion needs to be escalated to the AB.

**Comment by palemieux** [comment]
@fantasai The proposal at https://github.com/w3c/w3process/issues/631 had two aspects:
(1) what kind of voting method: super-majority
(2) what would the motion be "should the FO be sustained"

The proposal at https://github.com/w3c/w3process/issues/280#issuecomment-1255664340 tackles only (1).  What about (2)?

**Comment by chaals** [comment]
I still agree that a 2/3 majority requirement is reasonable. A Formal Objection is asking to overturn something intended to approximate consensus, and the playing field **should** be heavily tilted against them.

If a chair has resolved a decision against the wishes of a majority of a WG, that's a pretty obvious violation of the decision policy. A council that does not understand and support an objection to that had better have some pretty clear reasoning if they want to be trusted. (There are such cases, e.g. the group has alienated everyone who was not "toeing the line", but if they reach the council we have issues with the Team Contact and chair, CEPC, and the clear reasoning seems feasible to establish).

**Comment by chaals** [comment]
@nigelmegitt asked

> @chaals your suggestion means that if around half the members are recused then the formal objection can never be sustained, because the supermajority cannot be achieved. Is that what you intended?

If the council reaches consensus, it isn't an issue. If they are too small to be viable, the current draft says they should be dissolved and a new council formed. I would consider a council that can only resolve with a vote, and can't get enough votes to make a decision either way, is too small to be viable.

**Comment by dwsinger** [comment]
Reminder: not all decisions are required to be backed by consensus. Indeed, one possible ground for an FO is that there should have been consensus and it was not, in fact established.

Any vote needs to be of those not dismissed or renouncing, i.e. of those qualified to serve, and I suspect that it should simply compare yes vs. no and not consider abstains.

**Comment by dwsinger** [comment]
A situation we were keen to avoid was requiring super-majority to make any decision, as that could leave us decision-free indefinitely. I agree, that "in the case of a vote, the FO is sustained by a super-majority, otherwise it is overruled" avoids that problem.

**Comment by nigelmegitt** [comment]
> > ?
> 
> If the council reaches consensus, it isn't an issue. If they are too small to be viable, the current draft says they should be dissolved and a new council formed. I would consider a council that can only resolve with a vote, and can't get enough votes to make a decision either way, is too small to be viable.

This seems like a recipe for endless forming and re-forming without ever being able to resolve.

**Comment by dwsinger** [comment]
They can always get a vote; the requirement is based on those not dismissed or renouncing, and excludes abstains. Whether they'd _like_ to issue a decision if many also abstain is another question. I prefer, as you know, a "majority of those voting yes/no" and maybe can live with "supermajority of those voting yes/no to sustain the objection, otherwise it is overruled".

An obvious problem with the super-majority is that we could be asking the Council to write supporting material for a decision that a majority (but not super-majority) disagree with. In that case, the "minority opinion" is actually the majority opinion.

I am opposed to any rule that could leave the Council without any decision. That includes, for example "A majority of those serving is required to make a decision to sustain or overrule" as then if a majority abstains, no decision is made. A super-majority to make either decision also leaves area in between the two super-majorities. Lack of a decision can be the deadliest thing.

**Comment by mnot** [comment]
FWIW, I agree with David - a simple majority is appropriate here.

**Comment by michaelchampion** [comment]
I'm a bit torn: in general I believe supermajority voting is a way to break impasses when there is dissent but an issue SHOULD be decided by some semblance of consensus.  If we were talking about a situation where there was't a concept of a Formal Objection and the AC voted on whether to approve a Charter or Proposed Recommendation, a 2/3 supermajority requirement seems reasonable.

But assuming FOs and Councils, a simple majority of a group of experts who have spent time investigating decide a FO has merit, the FO has enough credibility to request that the proponents address the issues before getting W3C's imprimatur.

**Comment by palemieux** [comment]
> But assuming FOs and Councils, if a simple majority of a group of experts who have spent time investigating decide a FO has merit, 

@michaelchampion By "group of experts" do you mean the FO Council? If so, in the case where the FO is technical in nature, have you considered the possibility that the group of experts might not in fact be experts in the technical topic and the domain it is intended to address, e.g. they spent orders of magnitude less time studying the topic than the group whose subject to the FO. I do not the FO Council can be expected to become technical experts in the time they are provided.

**Comment by michaelchampion** [comment]
Yes  I mean "experts" == "FO Council"

Here's a scenario:
- A WG that does NOT REALLY have sufficient technical expertise gets agreement on a spec.  Actual experts did not join the WG, perhaps because of the patent commitments, perhaps they suspected the charter was flawed but didn't know/care enough to formally object to the charter.  So there is no dissent in the WG to advancing to Proposed Recommendation.
- in the AC ballot, some number of actual technical experts (or people concerned about the social impact of standardizing the technology, whatever) formally object.
- A FO council is formed from AB and TAG members (elected on the basis of their expertise/experience/understanding of web technologies)
- A simple majority of the Council concludes that the concerns raised in the FO are warranted

I am very comfortable with the FO being sustained in that scenario.

>  I do not the FO Council can be expected to become technical experts in the time they are provided.

TimBL was not a technical expert in every issue for which he adjudicated a Formal Objection. But he did have a broad and deep general understanding of web technology and invested sufficient time  to make reasonable, informed analyses of FOs.  That's what we can ask of an FO Council: they use their knowledge and information to assess an FO, and if there is sufficient evidence it is warranted, request the proposers of the spec or charter to go back and address the concerns.

**Comment by palemieux** [comment]
@michaelchampion 

> I am very comfortable with the FO being sustained in that scenario.

Here's the same scenario as above recast in a different light:

- members A form a WG
- members B choose to not join the WG because (i) they are not paying attention, (ii) the WG does not fit the product plans of their respective companies, (iii) their boss does not believe the standard will succeed, (iv) their companies do not wish to commit patents, etc.
- the WG advances to Proposed Recommendation with a specification that meets all Process criteria, including editorial quality, multiple implementations, etc.
- members B wake up and formally object to the specification on a technical basis, e.g. a technical choice made in the specification would require modifications in X millions of their devices
- the FO Council decides by simple majority to sustain the objection, undoing many years of work from members A and potentially jeopardizing the adoption of the specification

In that scenario, the bar to sustaining the FO should be extremely high.

It should be difficult for a minority group of members to ignore work and then object to it at the last minute on the basis of input they could have provided earlier.

The incentive should be for members to provide input/raise concerns from the beginning, and not to sit on the sidelines and delay their input until the bitter end (this makes for a haphazard standards process, at best).

Recall that (a) W3C standard are voluntary and (b) members B can always develop their own specification.

> that's what we can ask of an FO Council: they use their knowledge and information to assess an FO, 

There is a fundamental difference between the FO Council and TimBL:

- TimBL was a single individual who was completely invested in the W3C in terms of reputation, network, knowledge, etc.
- the council is made of individuals that come and go (sometimes at the whim of their employers), some are employees of corporation with interests that go beyond the specific FO, some do not represent members (invited experts), some only have a small amount of time dedicated to the council, etc.
 
As a result, decisions will be made differently by a council than they would have been made by TimBL.

The bar for the FO Council to sustain an FO should be high and the FO Council should not be encouraged to revisit WG technical consensus but in the most egregious cases.

P.S.: Thanks for engaging in the discussion. Happy to continue here and/or privately, whatever you prefer.

**Comment by michaelchampion** [comment]
First, sustained FO’s do not “undo years of work.” If the work is valuable it will be recognized by another SDO, implementers, markets, governments, etc. without W3C’s imprimatur. HTML and DOM  after w3c stopped work on them are the obvious examples. Had the EME FOs been sustained, the world would look very much like it did after 2107, except for fewer Emmy awards at TPAC I suppose🥴

Second, if the AB and TAG were as cynical, unmotivated, and incompetent as in your scenario, w3c would have WAY worse problems than missed opportunities to standardize some controversial spec🤔

**Comment by palemieux** [comment]
@michaelchampion It sounds like we disagree. I appreciate your sharing your opinion.

>  the work is valuable it will be recognized by another SDO, implementers, markets, governments, etc. 

My objective is to encourage work to take place in the W3C, not push it away.

> Second, if the AB and TAG were as cynical, unmotivated, and incompetent as in your scenario,

Your words, not mine.

**Comment by michaelchampion** [comment]
How about this formulation: I agree work that advances W3C’s mission, is consistent with its values, and meets it quality criteria belongs at W3C. Who holds the burden of proof that those criteria are met by some charter or spec? I’d say that if someone formally dissents and simple majority of a Council agrees with the dissenter, the bar has not been met  and the spec should go back for more work to meet W3C’s criteria

**Comment by nigelmegitt** [comment]
> I strongly believe the reputation of the organization and the integrity of the web would suffer worse from a "bad" Recommendation that slips through the process and politics than from a "good" spec or charter that fails to get W3C's imprimatur.

Do you have any data points to support that belief?

**Comment by chaals** [comment]
@michaelchampion suggested

> How about this formulation: I agree work that advances W3C’s mission, is consistent with its values, and meets it quality criteria belongs at W3C. Who holds the burden of proof that those criteria are met by some charter or spec? I’d say that if someone formally dissents and simple majority of a Council agrees with the dissenter, the burden of proof has not been met.

I don't think so. I think a significant supermajority of council is a requirement. I'd like to see consensus being honestly sought, at great effort. I would contrast my impression of real incidents where it has seemed to me that some participants were happy just to wait for the numbers game to play out instead of trying to reach a stronger consensus.

I believe in the individual integrity of people elected to TAG and AB. It is also the case that they are generally there because somebody is funding them. I don't think any TAG/AB member is simply a mouthpiece for their organisation, but that same integrity and independence suggests that if they regularly disagreed with their employer on important questions they would leave. So there is probably a substantial "unconscious bias" to particular views of what is or isn't part of the web. The council members are primarily elected for something other than being on the council. The power to reject work, much more than to allow it, is a significant market power. This leads me to want a very strong effort to reach consensus, and at minimum a large majority to overturn a decision of those doing the work.

@michaelchampion also said

> I strongly believe the reputation of the organization and the integrity of the web would suffer worse from a "bad" Recommendation that slips through the process and politics than from a "good" spec or charter that fails to get W3C's imprimatur.

and @nigelmegitt asked in reply

> Do you have any data points to support that belief?

I don't have clear data either way, but I believe that the opposite has been true in practice. 

I have various ways to judge Recommendations, as do others who have made formal objections to them. But I do not see evidence that W3C has suffered from things people don't like (and even less that it has suffered from doing things some people think are irrelevant) than it has benefitted from doing things people do like, and my interpretation of what I see is that the benefits for W3C have generally outweighed the harms substantially. (I also see that often different people weigh the same things on opposite sides of the balance, like Semantic Web, EME, or VCs).

**Comment by cwilso** [comment]
@chaals, your statement "I don't think any TAG/AB member is simply a mouthpiece for their organisation, but that same integrity and independence suggests that if they regularly disagreed with their employer on important questions they would leave" actually gets to the core of the issue - it is better to have different views on important questions represented.

**Comment by michaelchampion** [comment]
> I do not see evidence that W3C has suffered from things people don't like (and even less that it has suffered from doing things some people think are irrelevant) than it has benefitted from doing things people do like,

I had the opposite experience during my time at Microsoft, 2005-2015.  Early on, there was a sense -- or at least I argued without getting laughed at -- that the default decision should be to implement  W3C Recommendations that were in scope for a product, and update the products as the Recs evolved.  But over time it became more and more clear that actual customers cared more about things that work in the real world than whether some specific technology had W3C's imprimatur.  

W3C's process and community was valuable as a venue to collaborate with customers and competitors, but the formal maturity --member submission without formal standing, a WD, CR, or Rec -- was not a good predictor of technical quality or customer demand.  So I personally witnessed W3C's reputation suffer from the various irrelevant, buggy but unfixable,  and over-complicated stuff that got to Rec.  By the time I retired, the perceived value of getting a widely used and interoperable spec from CR to Rec was negligible.

**Comment by michaelchampion** [comment]
> The power to reject work, much more than to allow it, is a significant market power. This leads me to want a very strong effort to reach consensus, and at minimum a large majority to overturn a decision of those doing the work

"Those doing the work" in a WG or in proposing a charter are seldom neutral experts just trying to improve the web.  They typically have personal and economic investments in a spec's acceptance.  (My pre-Microsoft engagement at W3C was with smaller companies hoping to gain credibility  the market by visibility in W3C and leadership on emerging standards, so again my "data points" come from personal experience).

**Comment by nigelmegitt** [comment]
> the perceived value of getting a widely used and interoperable spec from CR to Rec was negligible.

@michaelchampion This tale appears to be one of "we had extremely high expectations of what others would do, without necessarily verifying those expectations during specification development, and when those expectations were not met, we discredited the entire operation". One might say that this reflects more on Microsoft as it was at that time than on W3C: perhaps a hint of principle winning over pragmatism, or internal politics being biased towards "strong" positions?

I hope (and believe) it is more common today for members not to swing the needle from extreme to extreme, but to have a more nuanced view and to participate in the things they care about and be relaxed about the things in which they have no direct interest.

Indeed this is my experience, and the result is that I have not seen W3C being discredited for "bad" Recommendations: perhaps such Recommendations themselves are discredited; I'm not sure such beasts actually exist.

However the converse risk, of W3C's relevance being diminished by non-participation, is very real, and leads to worse outcomes for users, globally, since no other SDO I've been involved with has had such a strong focus on transparency and IPR freedom, not to mention the horizontal review disciplines.

**Comment by plehegar** [comment]
"RESOLVED: simple majority" - AB - October 20, 2022.

**Comment by fantasai** [comment]
Closed by AB resolution.
