### ISSUE TITLE
Diagrams call Editorial changes "minor changes"

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#29]
Transferred from https://www.w3.org/community/w3process/track/issues/177
State: Raised

**Comment by chaals** [comment]
This is not editorial. There are 5 occurrences of "editorial change" which includes the definition - something that doesn't change conformance. 3 are linked to that definition, the last is to say that Member Submissions have to be presented again even for editorial changes, which I will raise as an issue but since there's no normative import to what it means there I don't see any urgent need to change.

"Minor change" is used in noting that a PR can be published as a Recommendation "with minor changes" - that should probably be defined as "editorial changes" but IMHO that is a substantive change to the document, and in any event I think it reflects a change in practice over the last decade or so.

"Minor change" is also used to describe allowable changes to charters between review and publication. I believe that is part of #28

It is also used in diagrams of the TR development process, where I think it is entirely informative and doesn't need a definition.

**Comment by dwsinger** [comment]
It seems that in the text of the process, "minor change" is only used to refer to Charter changes. Perhaps the diagrams that aid understanding of the Rec track should not use "minor change" but instead use appropriate words from the Rec track process sections ("editorial change" for example)?

**Comment by chaals** [comment]
Changing the images is on my radar - I would like to check they are up to date and add one for Ends of Life, too...

**Comment by chaals** [comment]
Closing in favour of #91
