### ISSUE TITLE
Add note to Process about flexibility of consensus

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#296]
We should add a note to https://w3c.github.io/w3process/#Consensus that better expresses what https://w3c.github.io/w3process/evergreen/#procedural-consensus attempted to do, which is to highlight the fact that consensus at W3C doesn't have to be bureaucratic and can encompass a range of "strong editor" work modes.

**Comment by wseltzer** [comment]
Proposed Note: Chairs have substantial flexibility in how they obtain and gauge consensus among their groups. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus; polls of participants; "lazy consensus" in which lack of objection after sufficient notice is taken as assent; or delegation of consensus-finding to a document editor.

**Comment by dwsinger** [comment]
Nice, but I don't think they delegate the consensus finding. Can we replace the last phrase?

Proposed Note: Chairs and working groups have substantial flexibility in how they define and gauge consensus in their group. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus; polls of participants; "lazy consensus" in which lack of objection after sufficient notice is taken as assent; or for documents, allowing the editor to edit to what they believe has or will gain consensus, and assessing the consensus of (and if necessary correcting) those edits after the fact, in the resulting documents.

**Comment by wseltzer** [comment]
I think we do delegate the consensus-finding. If the editor accepts a PR to which no one has objected, that's a finding of consensus.

**Comment by michaelchampion** [comment]
I don’t mind replacing “delegation of consensus-finding to a document editor” with  “allowing the editor to edit to what they believe has or will gain consensus“   but they don’t seem substantially different to me. 

Adding “and assessing the consensus “ seems reasonable; the chair may delegate consenus-finding to the editor but is ultimately responsible / accountable to ensure there really is some flavor of consensus behind the edits.

But “and if necessary correcting) those edits after the fact” doesn’t sound like a chair role to me.  The chair can direct the editor to respect some WG statement of what consensus is, or replace the editor if they do not.

What about a case where a chair is also an editor?  Is that forbidden by the process?  I hope not; we assume people can “wear multiple hats” in W3C work, and it may be efficient in some cases to have the chair and editor be the same person (essentially what WHATWG workstreams do), especially if the work is very technical and the editor is chosen for their deep expertise. Of course that means that the “chair hats” have an extra responsibility to ensure they really are acting fairly in that case, but there are a number of specs (WebIDL comes to mind) that have been maintained by one person.  So long as there is an appeal mechanism if some on the WG believe the chair/editor is not fairly assessing consensus or handling dissent, I see no reason to forbid it.

**Comment by dwsinger** [comment]
I think a careful read indicates that they are the same; I just want to avoid a casual read resulting in an editor saying "the only consensus we care about is mine, and I have consensus".


I meant chairs and working groups can do correction post-facto; this could be clearer

**Comment by wseltzer** [comment]
How about delegation of *interim* consensus finding? I want to enable a work-mode such as: the Chair and WG say "this document represents our consensus, even as the editor accepts new PRs." If someone challenges a particular decision the editor makes, they can appeal and, if successful, override the editor's choice. It's important that there can be a consensus document without particularized action by the chair at each update.

Proposed Note: Chairs have substantial flexibility in how they obtain and gauge consensus among their groups. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus; polls of participants; "lazy consensus" in which lack of objection after sufficient notice is taken as assent; or delegation of interim consensus-finding to a document editor.

**Comment by frivoal** [comment]
I'm not opposed to Wendy's wording, but I don't find that the word interim makes things all that clear. If you already know what me mean, it's fine, but I don't think it makes the situation clear for someone who is coming at it with fresh eyes.

How about this:

> Chairs have substantial flexibility in how they obtain and assess consensus among their groups. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus, polls of participants, "lazy consensus" in which lack of objection after sufficient notice is taken as assent; they may also delegate assessment of consensus to a document editor, whether in general or for per-determined circumstances (in case of disagreement, the chair's assessment prevails over that of the editor).

I would also make a small tweak to the following sentence already found in the process:

> Decisions may be made during meetings (face-to-face or distributed) as well as through email.

change to:

> Decisions may be made during meetings (face-to-face or distributed) as well as asynchronously (such as over email or in the issue tracker).

**Comment by fantasai** [comment]
I think that last parenthetical “(in case of disagreement, the chair's assessment prevails over that of the editor)” is more confusing than helpful. Maybe “(e.g. in non-controversial situations, or for specific issues)”?

**Comment by frivoal** [comment]
Iterated a bit more with @fantasai, and landed on this:

> Chairs have substantial flexibility in how they obtain and assess consensus among their groups. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus, polls of participants, "lazy consensus" in which lack of objection after sufficient notice is taken as assent; they may also empower a document editor to assess consensus on their behalf, whether in general or for specific pre-determined circumstances (e.g. in non-controversial situations, for specific types of issues, etc.)

**Comment by chaals** [comment]
I think chairs are assumed to be the arbiters of consensus / decision, although we don't actually describe and mechanism to determine that a decision has been taken.

I think that rather than rewrite the parenthesis, we should simply remove the parentheses and be more explicit about it.

**Comment by fantasai** [comment]
@chaals Looks like a race between you and @frivoal in posting a comment, can you clarify what exactly you're proposing in light of the previous comment?

**Comment by dwsinger** [comment]
I would not make it a parenthesis; if questions arise during "lazy consensus" for example, we expect the chair to manage the discussion and resolution to true consensus; if people question the editor's judgment about consensus, it's the chair's job to manage it. So, add to the end something like Chaals wrote:

>Chairs have substantial flexibility in how they obtain and assess consensus among their groups. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus, polls of participants, "lazy consensus" in which lack of objection after sufficient notice is taken as assent; they may also empower a document editor to assess consensus on their behalf, whether in general or for specific pre-determined circumstances (e.g. in non-controversial situations, for specific types of issues, etc.)

In all cases, it is the task of the chair to determine consensus and to manage the work of the working group on a consensus basis.

**Comment by frivoal** [comment]
> something like Chaals wrote [...]

The text you quoted after that was word for word the one Elika and I wrote (in [this comment of mine](https://github.com/w3c/w3process/issues/296#issuecomment-513598637)). I guess that means we agree?

**Comment by dwsinger** [comment]
I mean to add the sentence after the text I quoted

**Comment by frivoal** [comment]
I understand why you propose that sentence: to make clear that the delegation of authority from the Chair to the Editor is not irrevocable, and that the Chair can still take back control if needed. However, I think that fact is already established by the rest of the process, and that the attempt at clarifying risks undermining the claim that we're trying to make here: that the chair can indeed delegate, and that they don't have to be in the loop for every edit / assessment of consensus that the Editor makes when the editor has been empowered to.

This is a subtle balance, but I'd leave it out.

**Comment by dwsinger** [comment]
I think we need to state clearly here that if lazy consensus turns out to have failed, or the editor's perception of consensus was wrong, or anything else arises, the chair can't say "I delegated that, it's done", the chair does have to manage the consensus actively at that point. If they delegate or use lazy, and nothing comes up, then they do nothing. I guess you're concerned that someone will insist "we have to formally confirm the lazy/editor/whatever consensus"?

**Comment by frivoal** [comment]
>I guess you're concerned that someone will insist "we have to formally confirm the lazy/editor/whatever consensus"?

Yes. Including the risk that "someone" is the potential editor, who chooses to work elsewhere because they think that's too much overhead.

> I think we need to state clearly here that if lazy consensus turns out to have failed, or [...], the chair can't say "I delegated that, it's done" [...]

We already say:
> W3C process requires Chairs to ensure that groups consider all legitimate views and objections, and endeavor to resolve them

Isn't that enough?

**Comment by dwsinger** [comment]
> We already say:
> 
> > W3C process requires Chairs to ensure that groups consider all legitimate views and objections, and endeavor to resolve them
> 
> Isn't that enough?

No, because it leaves an ambiguity over whether they delegated this entire responsibility when they delegated to the editor or lazy consensus. I think we need to be explicit; if you use expedited methods like lazy or editor-guesses consensus, the chair MUST be the person who manages course correction when they fail.

**Comment by frivoal** [comment]
> No, because it leaves an ambiguity over whether they delegated this entire responsibility

I don't see how you get there. We say "[...] W3C Process requires Chairs to ensure that [...]" and "they may use [various] modes [for doing so]". Recognizing that they have flexibility in how they accomplish their task doesn't absolve them of the clearly expressed responsibility in anyway.

**Comment by dwsinger** [comment]
Let me try to explain. If we allow chairs to delegate, that might be seen as delegating the entire task and responsibility. "I was allowed to delegate that, and I did, and the decision and the management of it are no longer mine." Or indeed, someone might bring that argument against the chair "you delegated this to me, you can't continue to manage it."

**Comment by frivoal** [comment]
Unless you also recuse yourself, delegation doesn't really work this way generally. It remains your responsibility, and even if you don't expect to have to handle the responsibility on a day to day basis, it's still yours, and you're still expected to take control when necessary.

**Comment by frivoal** [comment]
In other words, I think it's sufficiently clear as is. I do understand the worry you have, and if we find a sentence that lifts that worry without risking the opposite interpretation, I'd be fine with it.

**Comment by dwsinger** [comment]
OK, I will try a complete re-write as the base text doesn't use the word "delegate".

Chairs have substantial flexibility in how they obtain and assess consensus among their groups. Unless otherwise constrained by charter, they may delegate or use modes including but not limited to explicit calls for consensus, polls of participants, "lazy consensus" in which lack of objection after sufficient notice is taken as assent; or they may also delegate and empower a document editor to assess consensus on their behalf, whether in general or for specific pre-determined circumstances (e.g. in non-controversial situations, for specific types of issues, etc.)

In all cases, the final determination of consensus remains with the chair, particularly if the delegation or mode used fails, or disagreement arises.

**Comment by frivoal** [comment]
Since I don't see how "delegate and empower" (or either word alone) could mean that the chair is no longer able to intervene, especially given what the surrounding paragraphs say about consensus, I continue to feel that the final sentence feels like saying that no consensus can be declared until the chair validates it, which is not what we're trying to say.

Lacking a better alternative, and given the context which I think gives sufficient clarity, I'd go without the last sentence. I understand why you want it though, but I don't have a better suggestion for phrasing it. I've tried, but couldn't come up with something that didn't have the same flaw. :-(

**Comment by dwsinger** [comment]
> Since I don't see how "delegate and empower" (or either word alone) could mean that the chair is no longer able to intervene,

The definition of "delegate" is (for example): "to assign responsibility or authority" and there is nothing there that says "and take it back once it's been assigned", I have the opposite problem, and worse, I am sure that if we don't make this crystal clear an editor will claim one day that he determined consensus and it's too late.

We could make it clear, and conditional "If questions or disagreements arise, the final determination of consensus remains with the chair."

**Comment by frivoal** [comment]
> We could make it clear, and conditional "If questions or disagreements arise, the final determination of consensus remains with the chair."

Not bad. It's a small tweak on the previous versions, but I think it works better. I'd like to hear if other people think you got the right balance here, but I'm (finally) leaning towards yes.

**Comment by frivoal** [comment]
Ok, so putting things together, I think we are now on this:

> Chairs have substantial flexibility in how they obtain and assess consensus among their groups. Unless otherwise constrained by charter, they may use modes including but not limited to explicit calls for consensus, polls of participants, "lazy consensus" in which lack of objection after sufficient notice is taken as assent; or they may also delegate and empower a document editor to assess consensus on their behalf, whether in general or for specific pre-determined circumstances (e.g. in non-controversial situations, for specific types of issues, etc.)
> 
> If questions or disagreements arise, the final determination of consensus remains with the chair.

I'm ok with it. Other opinions?
