### ISSUE TITLE
[Evergreen] Retiring an evergreen REC by rescinding vs via republishing as Note

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#297]
Evergreen RECs can be turned into Notes (as per [6.9](https://w3c.github.io/w3process/evergreen/#evergreen-rec) and [6.11](https://w3c.github.io/w3process/evergreen/#Note)), which effectively rescinds them, but the process for doing so has fewer checks than the process for rescinding a classic REC. Is this intentional? Given that Evergreen RECs are expected to be depended on by implementers and various other third parties, and that they are appropriate to use as normative references, we probably should not allow pulling the plug too lightly.

**Comment by swickr** [comment]
Process 2019 provides us options to Obsolete, Supersede, or Rescind each with distinct semantics.  For the first two, the previously-published spec can continue to be depended upon by those who wish to do so.  And a light-weight mechanism is consistent with Evergreen.  The third case is expected to be used when a serious flaw is discovered and is not expected to be used lightly.  Some mitigation in the event of inappropriate use of Rescind is warranted.

**Comment by dwsinger** [comment]
@swickr not sure if you see the problem here. Scenario: W3C was publishing an Evergreen Document "Nuts and Bolts", and the WG decides, for some reason, to make it a note. There is at that point no longer an Evergreen Rec at all; there is no "prior version" (evergreen documents are not periodically versioned, at most one has a date). So I agree with @frivoal that once you're publishing an Evergreen Rec., moving out of that state takes more than a WG decision "oh, let's just make it a note". I think you need to decide whether it's been obsoleted, superseded, rescinded, or should be marked discontinued, or something.

**Comment by frivoal** [comment]
@dwsinger I agree with your clarification, but as a side point:
> (evergreen documents are not periodically versioned, at most one has a date)

In the sense that there isn't going to be a 5.1, 5.2, 5.3, 5.4, etc that's true. But otherwise, publishing an updated Evergreen Rec works like publishing any other version of a spec, and I would expect to see a This version / Latest published version / Previous Version(s) links in the header just like for any other spec. But that doesn't really change the point at hand.

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
