### ISSUE TITLE
Consensus in the TAG Appointment Committee - Formal Objections

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#314]
in the directorless process, the TAG Appointment Committee makes its decisions (chair appointment and nominee selection) by consensus -- with a hyperlink to this definition:

> A substantial number of individuals in the set support the decision and nobody in the set registers a Formal Objection . Individuals in the set may abstain. Abstention is either an explicit expression of no opinion or silence by an individual in the set.

Is a FO really part of this process?

**Comment by chaals** [comment]
I think it makes sense to clarify the difference between "I want to note, for the record and as a last effort to convince others, that I think we are making the wrong decision. However, if it's just me who has my concern I can live with the outcome in the interests of getting things done" and "I want to do everything in my power to hold up this decision, even at the price of [whatever happens if the decision cannot be formalised]".

"Formal Objection" is the term generally used in W3C for the latter case.

Is your question related to the name we use, or to the idea that we would allow one individual to block consensus resulting in some appeal-type procedure?

**Comment by handywhite03** [comment]
Then by all means why the hell knot!!!!!

**Comment by handywhite03** [comment]
Or Why the Hell KNOT????

**Comment by mnot** [comment]
I was wondering whether it was intentional. E.g., this:

> These nominations are confidential to the TAG Appointment Committee.

could come into conflict with:

> A record of each Formal Objection must be publicly available.

**Comment by dwsinger** [comment]
I think that that is the wrong link; council members are not filing FOs over council decisions, that's nuts. We should provide an explicit definition in this case. Something like:

"Consensus in this context means that the majority support the decision, and the remainder either abstain (or recuse themselves), or note that while they do not support, they do not block the declaration of consensus. A single member may declaring that they object to the decision and block consensus."

Note that if the chair is unable to achieve consensus, they can call a vote.

**Comment by frivoal** [comment]
Note: this also applies to:
> Participants in the TAG choose by consensus their Chair or co-Chairs; in the absence of consensus

**Comment by dwsinger** [comment]
My sense is that the TAG appointment committee doesn't get to appoint until they have consensus. Which does make it possible for one member to block all appointment. Perhaps if they fail, a new TAC has to be formed, and it must be differently composed?

**Comment by cwilso** [comment]
I would suggest a less stringent definition of consensus, e.g. a 2/3 supermajority after discussion by all parties.

**Comment by frivoal** [comment]
`consensus`, in the Process is currently defined by the lack of Formal Objection. I agree that this isn't what we're trying to do here. We want a lack of sustained disagreement, but Formal Objections shouldn't be part of this, we could try to use some different term, or we could do as was done in the section about the Council, and locally override it:

> […] in this section, the terms “consensus“, “unanimity”, and “dissent” have slightly different meanings compared to the rest of this document: dissent—and therefore the lack of consensus—occurs when a member of the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) opposes a tentative conclusion, even though they cannot register a [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection).

However, I think the better solution may actually be to adjust the general definition of consensus. Beside it's formal definition of a lack of formal objection, consensus is a term frequently used in our community to refer to a lack of sustained disagreement. Clearly, filling a formal objection is a sign of sustained disagreement, but in common usage, it isn't necessary to escalate things that much. For instance, we often say that the AB makes decisions by consensus, and often conclude that we do not have consensus when some people indicate that they disagree

Note that this would not prevent chairs from making decisions where they can today. The process states:
> In some cases, even after careful consideration of all points of view, a group might find itself unable to reach consensus. The [Chair](https://www.w3.org/Consortium/Process/Drafts/director-free/#GeneralChairs) may record a decision where there is [dissent](https://www.w3.org/Consortium/Process/Drafts/director-free/#def-Dissent) […] so that the group can make progress

I've gone through the Process, and I think the one case where we do want to necessarily gate consensus on the absence of formal objection is AC reviews.

So here's my proposal: 
1. Adjust the definition of consensus (respectively, of dissent) to be based on the lack of (resp. presence of) sustained disagreement, rather than of Formal Objection specifically. An FO always indicates sustained disagreement, but as per current practice, an FO isn't necessary to express dissent. (Mere dislike for a proposed decision, however, doesn't constitute sustained disagreement, as one could still be willing to accept the compromise).
2. Indicate in the section about AC Reviews that in that particular context, Formal Objections are the way to express sustained disagreement.
3. Note in the sections about the TAG choice of chair, about TAG appointment committee, and about the Council that Formal Objections aren't available in those contexts.

If that sounds plausible, I'll make a pull request to show how that'd work in detail.

**Comment by nigelmegitt** [comment]
Speaking as a Chair, not as a member representative, +1 to @frivoal on this: too many times I've been in discussions where a WG member has leapt from to "formal objection" as the mechanism to ensure a proposal is not made a decision. This has the impact on meetings of escalating tension and closing down discussion too quickly. A less confrontational option would be very welcome, in the Process - noting that of course it is regardless Chair's role to try to set the tone of the discussion.

**Comment by plehegar** [comment]
Formal Objections may also be raised during the review of a specification, not just during an AC Review. Sustained disagreement in a Working Group should not be considered a Formal Objection unless it explicitly says so.

**Comment by dwsinger** [comment]
see #315 as there no longer is a TAG appointment committee

**Comment by fantasai** [comment]
Closed as no longer relevant, since we no longer are proposing a TAG Appointment Committee.

Also, the definition of Consensus was fixed in #634. :)
