### ISSUE TITLE
add references to "Open Stand" principles

### ISSUE THREAD

**Issue by masinter** [w3c/w3process#325]
https://open-stand.org/about-us/principles/
is a concise statement of purpose that could be linked to in the Introduction and also the CONTRIBUTING.md guidelines.

I think it doesn't hurt for reviewers of the process know these explicit requirements

**Comment by michaelchampion** [comment]
What problem would this address?
IIRC, the OpenStand Principles were not developed by a Process consistent with the OpenStand Principles 🤔

**Comment by masinter** [comment]
There are no principles or guidelines that I can find for the kinds of characteristics  that changes to the process should still insure. If you don't like citing OpenStand guidelines, then copy them in. I think at the time that W3C, as a signatory to it, believed it met.

Is there any of the OpenStand principles you think shouldn't be included?

**Comment by dwsinger** [comment]
I'm not at all convinced that the Process document is the place for the W3C to make these broad statements of principle.

**Comment by michaelchampion** [comment]
> Is there any of the OpenStand principles you think shouldn't be included?

"No one party dominates or guides standards development. "  That's not obviously consistent with the W3C Director's vast authority (on paper) to shape Recommendations.  W3C abides by this principle in practice, to a great extent.  But some complain that the big-company implementers of W3C Recommendations are the ones who "dominate" in practice.  So it's not at all obvious that stating this principle in the Process would improve its operation. 

"Broad consensus. Processes allow for all views to be considered and addressed, such that agreement can be found across a range of interests."  This is the W3C ideal, but in practice non-consensus happens and dissent is over-ridden. The Director (in practice, the W3C Management team collectively) is the ultimate determiner of "consensus" from a process perspective.  Adding this OpenStand Principles language could complicate the resolution of dissent in practice (or be seen as a meaningless platitude by those whose dissent is ignored). 

"are chosen and defined based on technical merit, as judged by the contributed expertise of each participant".  In practice, technical merit is NOT the ultimate criterion for W3C Recommendations, technical feedback by experts doesn't over-ride a preponderance of opinion by non-experts.   I'm not sure how to balance "democratic" and "technocratic" considerations in standards development but W3C definitely doesn't operate as a technocracy or meritocracy (well, since the highly meritorious founding Director disengaged from the day to day activities anyway).

My bottom line remains: Unless there is a clear problem with the current process that could be improved by incorporating or normatively referencing the OpenStand principles, I see more potential harm (or at least in time and distraction from more important matters) than good from doing so.

**Comment by masinter** [comment]
OpenStand gives you a set of objectives against which a reviewer could judge a process change.
Without it, there is no statement against which you could try to judge one 'director-less' branch vs another.  @michaelchampion doesn't seem to argue that W3C shouldn't aspire to the OpenStand goals, even if you think they're not met in practice. The process document originally relied on the Director as an ultimate fallback for cases where goals were in conflict.

Take the [Media Extension rechartering case,](https://www.w3.org/blog/2016/04/html-media-extensions-to-continue-work/) for example. Without a Director to cut the knot, how would such a case be resolved?

**Comment by dwsinger** [comment]
Our feeling is that statements of general principles, and so on, do not belong in the process document, and we prefer that the process is merely the rather dry 'how to run the consortium'.
