### ISSUE TITLE
Undefined: rationale for "short term(s)" for AB/TAG elections

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#333]
Neither the Process nor [How to Organize an Advisory Board or TAG election](https://www.w3.org/2002/10/election-howto) document the rationale for assigning "short term(s)" in AB/TAG elections.

I would like to remove that to simplify things unless it's critical.

**Comment by frivoal** [comment]
If someone who was supposed to be elected for 2 years vacates their seat during the first year, they are replaced at the next election, but that replacement doesn't serve a new two year, they just serve until the end of the original term. That's what short terms are for. I don't think we should drop them, as otherwise, election cycles could get very unbalanced after a while.

However, I agree it is very unclear from the Process that this is what short terms are about.

So I don't think we should drop them, but I think we should define them better.

**Comment by dwsinger** [comment]
I agree with Florian; it makes life much simpler if the seats have a regular cadence/life, and seats filled after resignations are for the remainder of the life of that seat, i.e. a short term.

**Comment by dwsinger** [comment]
I believe this is editorial; 2.3.1 and 2.4.1 use the phrase "incomplete term" and we should replace the occurrences of "short term" with that.

**Comment by frivoal** [comment]
As per https://www.w3.org/2020/01/29-w3process-minutes.html and https://www.w3.org/2020/02/12-w3process-minutes.html, this issue is deferred to a subsequent cycle of the Process.
