### ISSUE TITLE
Link to document on formal objection processing

### ISSUE THREAD

**Issue by samuelweiler** [w3c/w3process#337]
Add an in-line informative reference to: https://www.w3.org/2017/12/formal-objections.html

(Alternatively, deprecate that document.)

**Comment by dwsinger** [comment]
astonishingly, the process says nothing at all about _processing_ FOs, only about recording and reporting them. We probably need a short section somewhere.

I'd rather not deprecate; when we go Dir-Free, we'll need an improved version of this.

**Comment by jeffjaffe** [comment]
For Director-free, the AB has been working on a draft improved version of this: https://www.w3.org/2019/06/W3C%20Council%20guidelines%20for%20formal-objections.html

**Comment by frivoal** [comment]
@samuelweiler, The whole handling of formal objections is being reconsidered, in order to figure out how to make it work in a director-free w3c. In the present state of things, the suggestion you're making here seems reasonable, but I am not sure we want to draw attention to things that are about to change, so I'd rather defer this issue. Are you ok with that?

**Comment by frivoal** [comment]
Closing as out of scope in favor of https://github.com/w3c/Guide/issues/166
