### ISSUE TITLE
Why can AC comments on CR be ignored?

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#339]
> must show that all issues raised during the Candidate Recommendation review period other than by Advisory Committee representatives acting in their formal AC representative role have been formally addressed, 

Why are the AC rep's comments during the CR review period not required to be formally addressed alongside everyone else's comments?

**Comment by dwsinger** [comment]
I think the sense might (?) have been that the requirement to address AC comments is stated elsewhere. Maybe. This appeared in the major re-write of 2014, and does not seem to be in 2005

[2005] https://www.w3.org/2005/10/Process-20051014/
[2014] https://www.w3.org/2014/Process-20140801/

@chaals ?

**Comment by chaals** [comment]
Comments based on the review role of AC reps are addressed by the Director (and in principle should not be technical comments since those should be made by someone acting in the role a a Working Group participant, or a reviewer). So the Working Group may choose to ignore them, since they will be reviewed subsequently.

This was inherited from section 7.3 in the 2005 process - https://www.w3.org/2005/10/Process-20051014/tr.html#doc-reviews

There is a risk that AC reps promise a formal objection at PR if some technical objection is not resolved the way they want, and that the Working Group is cowed into making a bad decision instead of passing it to the Director to deal with the question. There is a risk that the Working Group can be delayed for a long time dealing with an issue that properly belongs to the Director's review, instead of completing their technical work.

I expect groups will talk to the Director about how to handle such issues if they arise and I have seen it happen in practice.

I think the exception is vaguely useful (if the Director tells a group that he considers a given AC objection unlikely to change his mind, it's probably better for them to focus on dealing with technical issues than getting sidetracked), but I also think we could survive without it.

**Comment by dwsinger** [comment]
so, do we need a parenthesis in the quoted statement? like this?

>must show that all issues raised during the Candidate Recommendation review period other than by Advisory Committee representatives acting in their formal AC representative role 

(which are addressed by the Director, possibly in consultation with the working group)

>have been formally addressed,

**Comment by chaals** [comment]
I don't think we **need** anything. Given that "we decided against acting on this" is one way for the Working Group to address an issue, and if the commenter is not satisfied that information has to get to the Director, I don't think we need the exception clause either, although my very slight preference is to keep it.

**Comment by frivoal** [comment]
I agree with @chaals we don't strictly need it, and since people these days are looking for ways to make the process shorter / simpler, my inclination would be to drop the exception.

**Comment by jeffjaffe** [comment]
Since there is some controversy here (i.e. Chaals would like to keep the exception) and we should only make pure editorial changes at this point, I would recommend we defer to P2021.

**Comment by frivoal** [comment]
>  I would recommend we defer to P2021.

Of course. I commented on this issue as I was triaging things and ran into it, but I consider it already deferred to P2021 (or later) based on the last process CG call.

**Comment by chaals** [comment]
Rather than postpone I think we could resolve this. I don't see controversy, I see mildly divergent preferences - i.e. no very strong objections being generated to whatever we decide. Which makes deciding more valuable.

**Comment by frivoal** [comment]
Solved by #563
