### ISSUE TITLE
Should W3C adopt the separate Evergreen Track?

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#343]
The features of the [Evergreen Track](https://www.w3.org/wiki/Evergreen_Standards) are:
* It is a separate track to the REC track. WGs can choose which one to use per spec.
* It allows continuous updates to /TR, and requires periodic snapshots to be designated for IPR protection.
* The editor is responsible for the content on /TR, and is responsible for maintaining quality, representing WG consensus, and responding to feedback including wide review.
* There is no external oversight or approval in this publishing process: Horizontal Review Groups and other reviewers are responsible for filing formal objections if their issue is not addressed or otherwise dismissed.

Advantages of this approach:
* Editors can do (or not do) whatever they want without being slowed down by “process”

Disadvantages of this approach:
* Editors can do (or not do) whatever they want without being checked by “process”

Note: One of the primary motivators for the development of the Evergreen Track was to allow opting into a new Patent Policy that did not apply to the REC track by virtue of applying to this separate track. It is worth noting that the AB [surveyed the AC](https://lists.w3.org/Archives/Member/w3c-ac-members/2019JulSep/0024.html) about amending the Patent Policy. Of the 40 answers received, 19 said they do not find “Experiment by allowing Working Groups to opt into the new patent policy by developing their specifications under a different name / process track than W3C Recommendation” to be acceptable, and 13 of those who said it was acceptable said they preferred not to. Only 4 respondants preferred this option, and of those 3 found a per-charter opt-in to a new patent policy without a separate track equally preferable.

Note: The Horizontal Working Groups had a joint meeting to discuss improving agility and fidelity in light of the increasing agile spec development processes as well as the increasing volume of work for their limited staff. They did not discuss the proposed Process changes, but noted that many groups continue to forget Horizontal Review. Therefore there is interest from the HRG community for the Process to include some minimum requirements for wide and horizontal review that serve as a backstop for when HR fails to happen organically, and the Evergreen proposal does not include such a backstop. See [minutes](https://www.w3.org/2019/09/16-i18n-minutes.html#item09).

**Comment by jeffjaffe** [comment]
Although I initially supported the Evergreen track (before Everblue/teal was invented), I think the AC survey was pretty decisive that there is no member consensus for this approach.

**Comment by wseltzer** [comment]
I don't believe that the member survey reflected upon this issue, and not conclusively.

**Comment by TzviyaSiegman** [comment]
> I don't believe that the member survey reflected upon this issue, and not conclusively.

I agree with @wseltzer. The poll was about patent policy, not about whether ever* should be separate. (Some people who are very concerned about Living Standards might not have even opened it because patent policy does not excite them.)

**Comment by astearns** [comment]
I interpreted the survey questions as probing the idea of a separate track, and I arranged my answers (as far as I could) to indicate that I preferred a single track with ever* options over separate tracks. Having multiple tracks is more confusing and prone to allowing problems fixed in one track persist in the other. Doing the work to integrate continuous development into the existing track will allow us to fix more problems. And having separate tracks includes the additional work of specifying how a document can transition from one track to the other.

**Comment by michaelchampion** [comment]
I've been opposed to a separate track for a long time now, since as @astearns notes, that adds complexity and confusion.  

But I also understand that many in W3M  feel it is very urgent to offer some sort of living standards option in 2020.  I don't want to get into a "best is the enemy of the good enough" situation -- if it is possible to get agreement an experimental  living/evergreen/extensible/evolutionary track and an experimental patent policy to go with it much faster than it would be possible to get agreement on a single process and patent policy that meets the demand for "living standards", that might be an acceptable tradeoff.  I've been advised that the patent policy in particular probably could be updated much more quickly if the Evergreen/whatever features are supported in an experimental track rather than in an update to the main patent policy. If there's an experimental PP, it would probably be cleaner to use it in an experimental process track.

W3C will pay down the road for taking such shortcuts today: You'll have to continually explain which track to use for specific purposes, define more process to move from one track to the other, and you're just postponing the inevitable complexities of integrating them into a single process.  But it's  the Director's, and AC's call whether the short-term gain is worth the long-term pain, I suppose.

**Comment by dwsinger** [comment]
> Although I initially supported the Evergreen track (before Everblue/teal was invented), I think the AC survey was pretty decisive that there is no member consensus for this approach.

I think the AC survey was too abstract to be indicative of anything.

**Comment by nigelmegitt** [comment]
+1 to https://github.com/w3c/w3process/issues/343#issuecomment-554587625 

I would prefer a single track approach, but _if_ we end up going down a 2 track approach where one is experimental, then I would want to see:

* clarity over what the experiment is and how long it should last for. The risk with experimenting with the patent policy is that it might look fine for, say, 2 years, and then just when everyone thinks it's good to go ahead with permanently, some strange situation occurs. Where "2" could be any number, in reality. If we don't have faith that it's probably good enough, we shouldn't be running the experiment, and if we do have faith, we may as well go with it for everything.

* an as-easy-as-we-can-make-it mechanism for WGs to switch tracks for a REC so that the existence of two tracks doesn't come to be seen as a barrier or, worse, a qualitative signifier of good vs bad. Whenever I see a pattern that a somewhat artificial division is constructed, I fear that down the line it will lead to a fight, or people getting upset with each other, or an even bigger division: don't make a crack that might become a chasm, but do make a bridge.

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
