### ISSUE TITLE
What aspects of Registries should/may/should-not be published together?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#354]
Background at <https://lists.w3.org/Archives/Group/ab/2019OctDec/0306.html>

see also #353 as answers to that impact answers to this.

Registries have

a) one or more specifications (Recommendations) that have a field, value, or something, which is amenable to extra values being defined; we call this the Referencing document (not that we need it in this discussion)
b) Definitions of what that ’table’ looks like (what are acceptable values, what is in the definition, what are the rules around each row, how do you ask for or propose a new entry, can entries be deleted, can values be re-used after deletion, and so on); the Registry definition
c) The registry’s working space, e.g. a Github repository or (often today) a Wiki; the maintenance place for the published values
d) Registry publication; the published registry itself.

Which of the above documents are you allowed to publish separately, or together? In other words, are there things you must publish separately, or you must publish together in one document?

**Comment by dwsinger** [comment]
My default is not to write rules unless they are clearly needed, and allow groups to do what makes sense for them. But there are considerations here as well. The Referencing document and the Registry definitions are both Rec.-track and should not, nay must not, be changed except by conforming to the W3C process for document changes. In contrast, we want to allow the published registry to be updated ‘lightweight’ as long as the agreed rules of that registry are followed. Also, the largest, most stable, registry operation I know — IETF and IANA — operates with the referencing document and registry definition being RFCs, and with the registry published tables at the official iana.org.

So my feeling is that the Registry publication should _not_ include the normative version of anything else, even if it's published on /TR (because even then you'd have the question of whether the update is to the registry tables or something more tightly managed). Informative quotes are OK, and links back would be expected, of course.

**Comment by swickr** [comment]
👍 with the nit that "else" in
> ... the Registry publication should not include the normative version of anything else ...

refers to "other than the content of each row".  I.e. the table is precisely as normative as the Registry definition states for those things that are contained in the table.

**Comment by frivoal** [comment]
I've been asked to explain the rationale for not allowing to publish the rules and values of a registry in different places, and thought that sharing my answer here may be helpful.

It boils down to three parts:

(1) I have not heard (or not understood) compelling reasons for wanting the ability to split

(2) I see concrete downsides to doing the splitting

(3) If we want to allow that possibility, we have to describe how it works, which I believe is possible but not as trivial as others seem to assume it is

Now in more details:

(1) I have not heard (or not understood) compelling reasons for wanting the ability to split

I've heard a suggestion that unless we allow values to be hosted in a separate documents, we wouldn't be able to update them easily. But the [proposal that @fantasai and I wrote](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fw3process%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fw3process%2Fregistries) does allow updating the values in a combined document as easily as updating values in a separate document, with no Process requirements other than following the rules of that registry. And it's not just the Process allowing it, it can also be done in practice, with automation. So this justification is false.

Another argument has been IANA does it. Which proves that it's doable, but not that it's desirable.

(2) I see downsides to doing the splitting

Splitting also makes things more complicated for the reader. The values document isn't usable unless you go read the definitions document as well, to understand what the values in the different fields mean. I find it quite telling that [David's proposal](https://www.w3.org/wiki/Registries#Proposed_Process_Text_.E2.80.93_Registries) has [a clause](https://www.w3.org/wiki/Registries#Published_Registry_values_requirements) that suggests including informative descriptions of what the fields of the tables mean and the methods of submitting changes in the values document. But these descriptions already exist in the rules document: the need to duplicate them (as informative prose) in the values document confirms that they're very much needed alongside the values, not in a publication separate from them.

There's also the issue of keeping them in sync. There is very strong logical coupling between the rules and the values, as the rules define not only how you can add or change values, but also what they mean. If the rules governing the format are updated, the values need to be updated in sync. If the values need new or different information than is allowed, the rules need to be updated in sync. If informative annotations about what the rules are exist in the values document (ahem), they need to be kept in sync. If there is such a tight coupling between these, why should they not be the same publication (even if they are in separate files within the publication)?

Additionally, how is referencing the registry supposed to work? Should referencing specs point to the rules document, or the values document, or both? It may be more natural to point to the values, but you cannot make sense of them without finding the corresponding rules first. If you get to the rules, you know what the values would mean, but you need to go fetch those somewhere else. Since we expect people to reference both, why are they separate in the first place?

(3) If we want to allow that possibility, we have to describe how it works, which I believe is non trivial

The only types of technical reports that exist are those that are defined: Notes, various stages of a REC, and, in our proposal, the various stages of a Registry Report. If we allow the values to be published in a separate document that is still a technical report, it doesn't seem to fit with any of the existing types, so we need to define the new type. At the very least that requires a name, and maybe there needs to be additional rules about what such a technical repport may/should/must/must-not contain in addition to the values themselves. 

If we allow the values to be published as something that isn't a technical report, we probably want to define more criteria it needs to fulfill, to compensate for things that we'd be able to take for granted if it were one: required to be accessible, required to be backed up, required to not contain advertisement or JS-based BitCoin miners or whatnot, required to be possible for the Team to maintain/take over if the original hosting service goes out of business…

On top of rules related to how we publish it, we'd also need rules to cope with the fact that they're now separate documents.

Such as: to be able to make sense of the values document, you need to look up the rules document. Whether you're looking at the current version or a dated historical version of the values, you need to be able not just to find the corresponding rules document for these values that was in effect when the values were published. Note that a single rules publication will typically apply to a range of values document publications, so it's not a simple two-way cross-reference. Do we need to require something (what?) in either or both documents to enable users to find the matching rules/values to the values/rules they're looking at?

Such as: if the rules document gets revised to something different (say, you added a field/column to the table), then you need to also revise the values to match the new definition, lest the old table make no sense under the new definition. So we might need a rule in the Process requiring that a value document *must* be corrected and republished (simultaneously?) when the rules document is modified, and that you're not allowed to republish the rules document until you're able to make that matching update in the values. Maybe.

We could define all of this, but so far we haven't, and I don't think we've even fully explored the space. Maybe the answer will be simple, but it isn't obvious to me that it will be. Either way, before spending time and effort in figuring out how to make that work, I'd like to be sure it is worth it. And as discussed above, I don't think it is.

That said, if we do want to do it, it is not fundamentally incompatible with the proposal @fantasai and I made. We'd just need to add additional Process text describing how these types of publications work. But since this is just an addition, it could also be added in a subsequent revision of the process.

**Comment by dwsinger** [comment]
Hi everyone, sorry to be slow.

> On Jan 23, 2020, at 15:22 , Florian Rivoal <notifications@github.com> wrote:
> 
> I've been asked to explain the rationale for not allowing to publish the rules and values of a registry in different places, and thought that sharing my answer here may be helpful.
> 
> It boils down to three parts:
> 
> (1) I have not heard (or not understood) compelling reasons for wanting the ability to split
> 
> (2) I see concrete downsides to doing the splitting
> 
> (3) If we want to allow that possibility, we have to describe how it works, which I believe is possible but not as trivial as others seem to assume it is

(1) This is odd, I thought I had explained before, but I am happy to do it again.

(2) I see concrete downsides to combining.

(3) I don’t think it’s at all complex.

So, here we go.

A) A big motivation for keeping them apart has already been stated; that Registries are not Technical Reports per se, but exist on the borders: their existence and rules are TRs subject to consensus, but their contents are subject to their rules and document reality. 

B) If you combine them, then any update by the custodian has to be verified that only the parts that represent values is being updated, that they are not changing the parts of the document that ARE subject to W3C consensus and Director review. That’s messy and an unnecessary overhead. If instead the custodian manages values in a separate location, then no checking is needed at all; just (the same) post-facto verification that the custodian isn’t running wild with the values. Also, the update frequency of the definitions is way less frequent than the values; if you combine, the document date changes for both, and it’s now hard to work out which  document revisions merely changed the values (normal) or when there was a revision of the definitions themselves (rare but important).

C) If you combine them, then everyone has to reduce their registry to what Echidna can handle, and make it static. That’s an unnecessary bottleneck and overhead.

D) The largest, most successful, registry operation I know, IANA, publishes values at IANA, but the definitions and rules as RFCs at IETF.org. Some of our proto-registries do the same; they’re defined in rec track documents but the value publications are elsewhere. For example, even though the XPointer Registry <https://www.w3.org/2005/04/xpointer-schemes/> is published at w3.org under a dated URL, it makes no appearance of being a TR, no pretence of being one, and does not appear if you search w3.org/TR for XPointer.

E) The vast majority of the time I am interacting with a registry, I want to know what a value means. The next most common is making some update. For the registry I run, the site answers the first and second questions (look here, or fill in this form, which is soon to go to Github). It’s very rare I need to go back to the formal definition of the registry. I visit IANA.org quite often to look things up; very rarely do I look up the associated defining RFC (which, admittedly, isn’t a hyperlink for the IETF because they don’t trust anything as newfangled as the web, and still use plain text, ahem).

F) If you want to know the rules of a registry, the defining Rec. should be linked from the registry value site, so it’s only a click away (we can use URls at the W3C, unlike IETF). The strongest reason I have heard to combine is that “it’s confusing” to publish separately, but I think we can all follow links.

G) The natural combination is actually to publish the rules in a section/annex of the spec. that needs the table. “The value ’none’ for the X-come-from field MUST be supported. Other values are registered at the <a href>come-from registry</a>. New values can be added following the requirements and process in <a href>Annex C</a>.

> (1) I have not heard (or not understood) compelling reasons for wanting the ability to split
> 
> I've heard a suggestion that unless we allow values to be hosted in a separate documents, we wouldn't be able to update them easily. But the proposal that @fantasai and I wrote does allow updating the values in a combined document as easily as updating values in a separate document, with no Process requirements other than following the rules of that registry.

I’m sorry, neither the checking that only values are being updated, nor echidna, are as easy as (e.g.) updating a wiki or database.

> (2) I see downsides to doing the splitting
> 
> Splitting also makes things more complicated for the reader. The values document isn't usable unless you go read the definitions document as well, to understand what the values in the different fields mean.

This is false. The vast majority of the time I go to iana or mp4ra I want to know what something means; what’s the definition of image/jp2k, for example, or what is the avc2 sample-entry code, and where are the specs that define them. I don’t need to know anything about the registry rules to answer these questions. I don’t care what the restrictions are on 4-character-codes in MP4, or on what’s allowed in the the standards-tree for MIME registrations, or who I have to convince to enter a new value.

The registry can be self-describing easily; and for those that want all those details, they can be only a click away.

> Additionally, how is referencing the registry supposed to work? Should referencing specs point to the rules document, or the values document, or both?

That rather depends on what you want to say. “This field can take any value registered for <a href=dont-come-from-values>x-dont-come-from</a>.” 

“The dont-come-from field defines forbidden origins; the value “none”, which must be supported, allows any origin. New values are registered according to the procedures in the <a href=ComeFromRec>Come from and Going Nowhere</a>.”

> It may be more natural to point to the values, but you cannot make sense of them without finding the corresponding rules first.

That’s a misapprehension. vastly more people visit mp4ra.org than read ISO/IEC 14496-12.

> (3) If we want to allow that possibility, we have to describe how it works, which I believe is non trivial
> 
> If we allow the values to be published as something that isn't a technical report, we probably want to define more criteria it needs to fulfill, to compensate for things that we'd be able to take for granted if it were one: required to be accessible, required to be backed up, required to not contain advertisement or JS-based BitCoin miners or whatnot, required to be possible for the Team to maintain/take over if the original hosting service goes out of business…

Those rules are drafted (wiki). We ought to have them for anything we rely on, so starting with registries is not a bad idea.

> Such as: to be able to make sense of the values document, you need to look up the rules document. Whether you're looking at the current version or a dated historical version of the values, you need to be able not just to find the corresponding rules document for these values that was in effect when the values were published. Note that a single rules publication will typically apply to a range of values document publications, so it's not a simple two-way cross-reference. Do we need to require something (what?) in either or both documents to enable users to find the matching rules/values to the values/rules they're looking at?

I would push back on a registry definition update that invalidated previous registrations, as I thinking all of us would. That would be nuts. You should be able to read the current values of the registry against the current definitions without needing to know what rules and definitions were in place when a registration was made. (Nonetheless, such historical analysis would still be possible, as Recs are dated, and we insist that registries keep history).



Well, this is a good start.


David Singer
Manager, Software Standards, Apple Inc.

**Comment by cwilso** [comment]
The Immersive Web Working Group maintains a registry of Input Controller profiles (https://github.com/immersive-web/webxr-input-profiles).  It is currently versioned, but a goal is to make the schema definition much more stable than the assets themselves (as new controllers are added frequently, when new or revised devices are released.)

**Comment by frivoal** [comment]
Resolved as part of accepting https://github.com/w3c/w3process/pull/335
