### ISSUE TITLE
"Evolution of the Governing Documents" incorrect

### ISSUE THREAD

**Issue by wseltzer** [w3c/w3process#355]
Not all governing documents are managed by the AB, even by delegation. It's incorrect to lump CEPC, Patent Policy, and Process together in [Section 11](https://w3c.github.io/w3process/#GAProcess).

**Comment by dwsinger** [comment]
OK, but what IS correct?

**Comment by TzviyaSiegman** [comment]
CEPC is written by [PWE CG](https://www.w3.org/community/pwe/). The review process is the same as the Process doc.

**Comment by wseltzer** [comment]
The Patent Policy gets AC review. Per [charter](https://www.w3.org/2004/pp/psig/charter-2019.html), PSIG will review, but is not responsible for formally documenting or implementing, W3C IPR policies.

**Comment by dwsinger** [comment]
Yes, but just like the Process CG, that's where CEPC is developed; I think that like the Process (from which it is linked, by the way), decisions to offer it for adoption by the AC and Director properly go through the AB...

**Comment by wseltzer** [comment]
Does AB have a role in Patent Policy?

**Comment by dwsinger** [comment]
For Patent Policy, inasmuch as it needs to mesh with Process, AB at least has a role there. I would not be comfortable with a change which the AB has not reviewed, endorsed, and agreed to offer for adoption. So I think yes...

**Comment by wseltzer** [comment]
at the same time, I don't want to enshrine extra hoops in the Process

**Comment by chaals** [comment]
@wseltzer wrote:

> I don't want to enshrine extra hoops in the Process

Nor do I. On the other hand, since the Patent Policy and CEPC are incorporated to the Process Document (by explicit reference), changing them without going through the AB who formally manage the Process seems like a bad idea, so I don't think this is a valid bug.

In practice, it seems the mandated AB review is far less painful than the relatively newly mandated AC pre-review or the W3M review that is put in place by W3C.

On the other hand, there are governing documents such as the membership agreement that as far as I know are not within the bailiwick of the AB - even if the AB might consider changes, it is not required to agree to changes made or not rejected. So I think the section is incorrectly named.

**Comment by fantasai** [comment]
@chaals I think we weren't very happy with the name, but couldn't come up with a better alternative. Do you have one to suggest?

**Comment by chaals** [comment]
What about "The W3C Process"?

**Comment by frivoal** [comment]
That's one specific document, it's not a great term to cover that document as well as the other documents which ought to be handled similarly to it. The fact that they're normative dependencies of the Process gives a strong hint as to why it makes sense to handle them that way, but people don't generally consider references to be a part of the document that references them.

**Comment by chaals** [comment]
There is a Process Document, that describes in normative terms a number of features of how W3C functions. It explicitly incorporates by reference a couple of other documents. So

"The W3C Process consists of the Process Document, Patent Policy, ..."

**Comment by frivoal** [comment]
I suppose it can work, but I am not a huge fan of having "the Process Document" and "the W3C Process" mean related but different things.

**Comment by frivoal** [comment]
Agenda+ to decide if we should address as part of Process 2020 or defer to a subsequent cycle.

**Comment by dwsinger** [comment]
Perhaps the section should revert its title to "Process Evolution", and say that the W3C process and some related documents (and list them) are managed in the following way…

I think that the Patent Policy is sent for formal AC review by someone, and it's not PSIG, and it's not the team, so it must be the AB.

**Comment by jeffjaffe** [comment]
I believe the Director sends the Patent Policy for formal AC review.

**Comment by dwsinger** [comment]
Ah. But at a time when we're working on **removing** mentions of the Director, I'd rather not insert one now that we'll later have to remove.

**Comment by jeffjaffe** [comment]
Good point.  We may just want to label this issue as director-free.

**Comment by chaals** [comment]
The patent policy is managed like other "big" W3C decisions. Which currently means a director's decision following an AC review - although the one time we actually did this it was completely ad hoc since we had no defined process. (Like we have no definition of working group decisions).

I think we can live with it being similar, but if we are actively trying to clean up we might want to write down that it's a W3C decision following AC review.

**Comment by frivoal** [comment]
The process defines the Patent Policy and CEPC to be normatively incorporated into itself by reference. The Process is managed by the AB (by delegation), then sent to AC review with a W3C decision at the end of it (which currently involves the Director).

Since they are part of the Process, the Patent Policy and CEPC should be the same. Clearly the actual development involves different experts, and it is appropriate that the CEPC be delegated to a different CG (PWE-CG) focused on that kind of topics, and that the Patent Policy goes through PSIG. But in terms of who's in charge, I think the way this is set up in the master branch following https://github.com/w3c/w3process/pull/309 is right, and the only problem is how to call these things.

@dwsinger said:
> Perhaps the section should revert its title to "Process Evolution", and say that the W3C process and some related documents (and list them) are managed in the following way…

I think it's a good idea, and I'll make a PR to that effect.

**Comment by frivoal** [comment]
See https://github.com/w3c/w3process/pull/367

**Comment by dwsinger** [comment]
awaiting feedback from Wendy and the matching PR
