### ISSUE TITLE
7.1.1 Charter reviews on a public communication channel?

### ISSUE THREAD

**Issue by wseltzer** [w3c/w3process#38]
The Process says team MUST provide member- and team-confidential channels for charter review comments, and that one of those must be the communications default. As we conduct more conversation in public, should we permit a public list to be used and designated for default communications? 

That possibility could be useful where we're chartering based on work that has been incubated in public.

**Comment by chaals** [comment]
Splitting the formal AC review across member-visible and team-confidential discussions is already problematic. Assuming there is a legitimate reason for the Team to accept feedback in confidence, and I believe that is a reasonable assumption, a member who provides such feedback restricts the Team in how they can manage the subsequent discussion of issues. Moreover, it enables an asymmetric discussion to occur, where someone opposed to the substance of the objection has an enhanced scope for "politicking", by for example seeking support from some significant number of members without needing to engage with the issues that were raised, just relying on the number of AC reps who were convinced to go along with an argument.

Adding to this a dimension that recreates the same capacity for chasing up random public statements - given the enormously self-selecting nature of those who would thus be surveyed - seem like a terrible idea.

**Comment by wseltzer** [comment]
And yet, we want to encourage and participate in discussion in public, since many of the charters come from public community discussion and some members discuss with their communities on public lists (Mozilla, for example). Encouraging members to give their feedback in public helps the conversations to stay synchronized.

**Comment by chaals** [comment]
>Encouraging members to give their feedback in public helps the conversations to stay synchronized.

If they *do* have conversations in public. I have certainly spent a lot of breath and hand cartilage encouraging W3C to hold conversations with members rather than in private. And encouraging 2 levels of confidentiality to turn into 3 **does not** help synchronise anything I can think of.

**Comment by chaals** [comment]
> Encouraging members to give their feedback in public helps the conversations to stay synchronized.

If they *do* have conversations in public. I have certainly spent a lot of breath and hand cartilage encouraging W3C to hold conversations with members rather than in private. And encouraging 2 levels of confidentiality to turn into 3 **does not** help synchronise anything I can think of.

**Comment by wseltzer** [comment]
We're trying to become better at public conversation, so thanks for your encouragement.

Several groups are now drafting charters in public repositories, and working through the issues raised there, in public. That's the mode we're recommending all groups use. In those public discussions, it's hard to incorporate "based on team-confidential or member-confidential input, consider this change."

**Comment by dwsinger** [comment]
Can the team provide examples/statistics on how often and how usefully the 'team only' option has been used? does anyone have a good list of reasonable use-cases for this option? It certainly makes consensual resolution rather hard...

**Comment by chaals** [comment]
@wseltzer:

> it's hard to incorporate "based on team-confidential or member-confidential input, consider this change."

The model is that W3C members by and large do the work, and that they pay the associated costs of getting it done at W3C.

We welcome public input, particularly as a way to reality-check what the members are saying is important, but we're not actually running a global democracy here - not least because the way we get public input makes that pretty much impossible and therefore a silly goal under our current model.

Responsiveness to and respect for the "public" (the non-members who choose to offer their opinions, guidance, and sometimes very significant contribution) is of course the right thing to do. 

At the same time it is fairly straightforward to note that the members and the Director negotiate the final charter.

Which means that you have shown a very concise and clear way of explaining where a change may have come from when it is not otherwise visible from the public record, in a way that provides visibility even for proposed changes, allowing for further public input before a decision is made.

**Comment by wseltzer** [comment]
Some statistics over the last two years:

For charter/activity proposal reviews:
1508 responses member-visible,
66 team-only,
1574 total responses in the past 2 years

For All AC questionnaires (including the above):
2089 member-visible, 
705 team-only,
2824 total responses in the past 2 years

**Comment by paulbrucecotton** [comment]
Currently charter reviews are sent to [AC members](w3c-ac-forum@w3.org) and sometimes to [WG Chairs](chairs@w3.org).  Does it make sense for AC members to make their responses public if the context in the original "Call for Review" is not itself public?  

Looking at a sample of recent Member-only responses, some of them would very hard to understand without access to the original "Call for Review" email or the Review survey itself.

/paulc

**Comment by wseltzer** [comment]
It would make sense to send the calls for review to a publicly archived list too.

**Comment by dwsinger** [comment]
I think that the comments from the public should be themselves public, as should be the final resolution of them. How we handle that gracefully I am not sure.  We may need better tooling for this (I find the form-based response kinda clunky anyway). Discourse? Can GH issues have differing levels of visibility?

**Comment by michaelchampion** [comment]
Sorry to rain on the parade towards openness, but I'm not real comfortable with where this is going.  Public input on charters is of course fine, but the discussion of problems with charters OFTEN gets into member-confidential and team-confidential territory.  For example, those who are not very familiar with how the W3C patent policy works tend to not understand why it is critical to have very clear scope statements in charters that restrict what a WG can do.  Likewise the whole question of which features in products such as operating systems and browsers are candidates for standardization and which are reserved for competitive differentiation is not likely to productively advance via social media. 

Also the points @chaals makes above are good ones -- "The model is that W3C members by and large do the work, and that they pay the associated costs of getting it done at W3C....We welcome public input, particularly as a way to reality-check what the members are saying is important, but we're not actually running a global democracy here".

So I'm OK with having calls for review publicly archived so CGs, BGs, and members such as Mozilla who need to have public discussions can inform non-members about the issues, but leery of doing everything in public by default.

**Comment by dwsinger** [comment]
I am fine with the discussion of public comments being, for the most part, normally public as well.  But let’s keep the ability to make comments within the consortium on consortium matters, a matter of consortium discussion.

> On May 22, 2017, at 10:03 , Michael Champion <notifications@github.com> wrote:
> 
> Sorry to rain on the parade towards openness, but I'm not real comfortable with where this is going. Public input on charters is of course fine, but the discussion of problems with charters OFTEN gets into member-confidential and team-confidential territory. For example, those who are not very familiar with how the W3C patent policy works tend to not understand why it is critical to have very clear scope statements in charters that restrict what a WG can do. Likewise the whole question of which features in products such as operating systems and browsers are candidates for standardization and which are reserved for competitive differentiation is not likely to productively advance via social media.
> 
> Also the points @chaals makes above are good ones -- "The model is that W3C members by and large do the work, and that they pay the associated costs of getting it done at W3C....We welcome public input, particularly as a way to reality-check what the members are saying is important, but we're not actually running a global democracy here".
> 
> So I'm OK with having calls for review publicly archived so CGs, BGs, and members such as Mozilla who need to have public discussions can inform non-members about the issues, but leery of doing everything in public by default.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by iherman** [comment]
The [original comment](https://github.com/w3c/w3process/issues/38#issue-225223497) referred to the fact that, per process, a team-, and member-confidential mailing list *MUST* be provided with one of them being a default. It is not even clear, reading the process, whether it is allowed to add a public mailing list as an alternative in the first place. In other words, the clarification may be of two steps:

1. Is it allowed, per process, to have a public mailing list *as well* as a response mechanism? Note that I personally refer to a mailing list that is publicly *archived*, and not that anybody can send a mail to that mailing list.
2. If the answer to the previous question is 'yes', is it allowed to use the public list as a *default* mechanism?

My personal opinion is that the answer should be 'yes' on both grounds.

@michaelchampion, I fully agree that there are cases where a discussion concentrates on issues that are very member specific. Ie, we *must* maintain the possibility of having a member or team confidential response the the AC rep can choose; I have no problems with that.

However, as @wseltzer [pointed out](https://github.com/w3c/w3process/issues/38#issuecomment-299932935), the current situation, when the charter is often drafted by members of an interest group, a community group, or even WCIG groups, leads to unnecessarily awkward situations for everyone involved.  

@chaals, I understand it *may* come to an extra level of complexity if we have three instead of two options. But there is no evidence that a resulting chaos would indeed be the typical case. What I expect to happen (yes, I know, I do not have an evidence either) is that most of the discussion would indeed happen on the public mailing list and/or the github repository for some of the details, and there would be *some* comments, touching upon IP or process issues, that the commenters would feel more comfortable restricting to member space. And that sounds all right to me.

**Comment by chaals** [comment]
@iherman:

> The original comment referred to the fact that, per process, a team-, and member-confidential mailing list MUST be provided with one of them being a default. It is not even clear, reading the process, whether it is allowed to add a public mailing list as an alternative in the first place. In other words, the clarification may be of two steps:
>
> 1. Is it allowed, per process, to have a public mailing list as well as a response mechanism? Note that I personally refer to a mailing list that is publicly archived, and not that anybody can send a mail to that mailing list.
> 1. If the answer to the previous question is 'yes', is it allowed to use the public list as a default mechanism?
>
> My personal opinion is that the answer should be 'yes' on both grounds.

I think the part of the process you point to makes it clear that one of the member- or team-confidential channels must be the default. That means the public one cannot.

Having represented members for a long time, my experience is that there is a high disincentive to enter into a confidential discussion when there is a parallel version of it that is more public - and that the more public "more public" means, the stronger the disincentive. While this can be a good thing in that it clarifies reality for more people, it can be harmful because it means the discussion doesn't happen at all - members just decide instead to walk away.

For relatively uncontroversial charters, I don't see anything more than an increase in the amount of feedback - and largely feedback unaccompanied by commitment to do work in the relevant area. That strikes me as mostly harmless, although not cost-free.

However, controversial work, and is more than just EME although it is a recognisable flashpoint. Opening all those discussions to general participation, as if they were newspaper articles where we wanted to increase our social media profile through an active comments section, strikes me as actively harmful.

W3C is a broad, if not entirely representative, cross-section of most relevant industries. We have many mechanisms already for getting public feedback - not least, members campaigning for the general public to get involved, whether to promote accessibility or tell W3C that they don't support proposals. I believe there is real value both for W3C as a whole, and for its members, in havng the actual review of chartering, that leads to a Directors' decision to invest W3C resources, as a process essentially restricted to the membership. After all, it is partly in their name that resulting work will be published, having been developed overwhelmingly using their resources. Ensuring that members have the clearest opportunity to provide meaningful feedback, and that they believe in the mechanism, seems an important way to value the members and their contributions.

**Comment by michaelchampion** [comment]
@chaals wrote:

> and that the more public "more public" means, the stronger the >disincentive. While this can be a good thing in that
> it clarifies reality for more people, it can be harmful because
> it means the discussion doesn't happen at all - members just
> decide instead to walk away.
+1

> . I believe there is real value both for W3C as a whole, and for its members,
> in havng the actual review of chartering, that leads to a Directors' decision
> to invest W3C resources, as a process essentially restricted to the
> membership.

Strongly agree.

**Comment by iherman** [comment]
@chaals (and @michaelchampion): it is not clear to me whether, per charter, it is allowed or not to add an _option_ for a public mailing list as a reply target in the first place. Although the practice has been, lately at least, to add such a mailing list, in my reading the process document is a bit ambiguous, and could be read as saying that _only_ member and team confidential lists can be used. As a somewhat side-issue, it may be useful to make this clear in the document. As I said, my personal preference would be to _allow_ that option, and I am not really sure whether we agree on that or not.

We clearly do not agree on whether that public mailing list could be used as a default, and I am not sure I could add any new arguments:-(

**Comment by dwsinger** [comment]
There's an operational/UI question here too. Whatever the WBS form sets as the response default tends to be what gets used (member-visible or team-only). Introducing a third option in there is unlikely to be used...

**Comment by chaals** [comment]
@iherman wrote:
> it is not clear to me whether, per charter, it is allowed or not to add an option for a public mailing list as a reply target

As it is not prohibited, and subject to the requirement that the default feedback be either the member- or team-confidential channel, I see no reason it would not be allowed.

For the reasons noted above, and based on experience, I think it is usually not a very good idea, but that's an operational question for the Team.

> We clearly do not agree on whether that public mailing list could be used as a default

Hmm. I think the process is clear that it cannot be used as a default, since it specifies what can and any such list isn't one of the specified options. Do you disagree with that interpretation?

We may well disagree on whether it **should**. While W3C is a fee-paying member consortium which enables member-confidential discussions, I think it is a bad idea to allow a public channel to be the default for member reviews of a charter.

**Comment by koalie** [comment]
Dear all,

I just commented on #39 that we have already been doing this in practice since December 2014, by giving AC reps 4 visibility options:
> Starting with the next review form that we publish, you will find the following options for sharing your review comments in the first drop-down menu of the review form:
>
> - Member-visible
> - Member-visible and send email to w3c-ac-forum
> - Public and send email to both w3c-ac-forum and [public-new-work](https://lists.w3.org/Archives/Public/public-new-work/)
> - Team-only

See [my comment](https://github.com/w3c/w3process/pull/39#issuecomment-320018150) in #39 .

**Comment by koalie** [comment]
Replying to @paulbrucecotton [May 18 comment](https://github.com/w3c/w3process/issues/38#issuecomment-302487393) and @wseltzer [May 19 response](https://github.com/w3c/w3process/issues/38#issuecomment-302802755).

We already share with the public when the Advisory Committee starts a Charter review.
See the Guidebook: [2nd part of section "5.1 Organizing the Call for Review"](https://www.w3.org/Guide/Charter#cfr):
>Once the Head of Communications has approved (or explicitly delegated approval of) the Call for Review and the questionnaire, the Communications Team:

    Sends the Call for Review to w3c-ac-members@w3.org.
    Sends a version of the announcement to public-new-work@w3.org (archive). Use this template (and see the example). The announcement must include:
        The URI of the (public) charter.
        The end date of the Member review.
        That W3C invites public feedback on public-new-work@w3.org (archive).
        That we make no guarantees of replying to feedback.
        That people who work for a Member organization should coordinate their comments through their Advisory Committee Representative.
    Send the same email new-work@ietf.org. Note: public-new-work@w3.org used to cc new-work@ietf.org but due to mailing list configuration issues, we stopped that practice.

>Note: Starting in January 2007, W3C makes all charters public during Advisory Committee review.

**Comment by dwsinger** [comment]
see also #63

**Comment by dwsinger** [comment]
we ask the community to comment on their transparency needs on this and #63

**Comment by dwsinger** [comment]
see also #39

**Comment by frivoal** [comment]
As per https://www.w3.org/2020/01/29-w3process-minutes.html and https://www.w3.org/2020/02/12-w3process-minutes.html, this issue is deferred to a subsequent cycle of the Process.

**Comment by frivoal** [comment]
We've decided to close #39, which is the same issue as this. It probably means we should close this one too.

**Comment by dwsinger** [comment]
agree to Document (in the Process) existing public comments practices (e.g. GitHub comments) as allowed and encouraged for wider review of charter proposals and revisions.

**Comment by dwsinger** [comment]
We need a PR. Something like after

> The Team must provide two channels for Advisory Committee review comments:
> 
> * an archived Team-only channel;
> * an archived Member-only channel.
> 

add

The Team may provide the ability to take public comment, and for AC Reps to allow public visibility of their comments.

**Comment by wseltzer** [comment]
Do you mean https://github.com/w3c/w3process/pull/39/files @dwsinger?

**Comment by dwsinger** [comment]
It seems that we indeed abandoned that mandate and detailed text, but the practice has developed that we do indeed make a public option available. So the residual question is whether the process needs to state explicitly that the mandated list is not exhaustive...

**Comment by dwsinger** [comment]
closed as addressed via #526
