### ISSUE TITLE
Limit scope of delegation on Process, Patent Policy, and CEPC evolution

### ISSUE THREAD

**Issue by swickr** [w3c/w3process#388]
New text in [11. Process Evolution](https://w3c.github.io/w3process/#GAProcess)  was inserted by #309 that could lead to confusion over roles.

> Revision of the W3C Process and related documents (see below) undergoes similar consensus-building processes as for technical reports, with the Advisory Board—__or another group acting under delegation from the Advisory Board__—acting as the sponsoring Working Group.

While it has been the AB's practice to pass the editorial pen to other groups; [W3 Process CG](https://www.w3.org/community/w3process/) for the Process, [PSIG](https://www.w3.org/2004/pp/psig/) for the Patent Policy, and [PWE CG](https://www.w3.org/community/pwe/) for CEPC, I recommend that the text of this sentence not suggest that any group other than the AB has the authority to "act as the sponsoring Working Group".  In particular, though the AB can expect that a delegated group conducts reviews of "editor's drafts", I believe the AB must reserve to itself the authority to formally propose revised documents to the Membership (e.g. publish "working drafts").

I suggest striking "—or another group acting under delegation from the Advisory Board—" from that sentence and adding a sentence just prior to "The Advisory Board initiates review as follows:" along the lines of:

> The Advisory Board may delegate discussion, editorship, and (public) review of editor's drafts to another group but only the AB may formally propose new revisions of these documents to the Advisory Committee.

**Comment by dwsinger** [comment]
we'll leave this to handle during AC feedback on P2020, seeing what the community says

**Comment by TzviyaSiegman** [comment]
I take issue with this section as well, but in the opposite direction. If the AB delegates the authoring of a document such as CEPC to another group, then why is the AB involved in the approval process for such a document? The PWE CG expressed concern that future iterations of CEPC will be caught up in bureaucracy. There is a great deal of context and nuance that goes into authoring. Why should the AB have a separate review period from the rest of the AC?

**Comment by dwsinger** [comment]
I think that the answer is that the AB can delegate development and discussion, but not responsibility. And it's also more practical to get vetted by a small body like the AB, than to go straight to the AC. And the AB was elected to be responsible and responsive.

**Comment by frivoal** [comment]
> The PWE CG expressed concern that future iterations of CEPC will be caught up in bureaucracy.

Short version: the goal is not to constrain what this PWE CG or future equivalent groups can do, but to make it clear that such updates to the CEPC can happen at all, and how.

Long version:

> Why should the AB have a separate review period from the rest of the AC? 

Why should the PWE CG have the authority to change documents that are contractually binding on member companies? The PWE CG has done great work here. But it's a CG. Anybody, including non members, can form/join a CG.

Independently of the quality of the content and the seriousness of the preparation work, we cannot update the CEPC (or the Process, or the Patent Policy) just because someone says so, so enactment of a new CEPC (or of the Process, or of the Patent Policy) must come through some process that makes it legitimate to the membership at large, both from a moral standpoint, and from a legal/contractual standpoint.

legal/contractual legitimacy of an AC review initiated by the AB in order to update the Process is established because the Process says so, and because members are contractually bound to the Process.

Having a formal AC review also accomplishes moral legitimacy. 

But saying that we can update the CEPC as long as we have an formal AC review only shifts the problem: unless we modify the Process to allow any person or group to call for an AC Review for the purpose of changing documents that are binding on all members, we can't have formal AC review just because someones thinks we should, regardless of how genuine their motivations are. AC reviews are anchored in, and governed by, the Process, including what they can affect, how they are started, how they are conducted, how they are resolved in case of disagreement, how they can be appealed…

Some specific body must be, through an existing legitimate means, empowered to call for adoption of a new CEPC/Process/Patent Policy. Existing bodies that could fill this role are:
 * The PWE CG
 * The Director
 * The Team
 * The AB
 * The TAG

The current PWE CG has done good work, but anybody can join CGs and they aren't bound to any particular way of making decisions, so putting one formally in charge of governance documents seems risky. The TAG seems irrelevant for questions of governance, and assigning responsibilities to the Director is not the right thing to do these days.

This leaves us with the AB and the Team.

We could have the Process officially put the team in charge of this, but of the two, I think the AB is a better choice.
1. The Process already is under its purview, and adherence to the CEPC and Patent Policy are not only required by the Process, they are binding *because* they are required by the Process. If validated by an AC Review, the AB could already write a new document and change the Process to require adherence to that instead of the existing CEPC/Patent Policy. So in effect, the AB already had this responsibility.
2. Placing this sort of responsibility in elected bodies seems healthier to me. If they empower / delegate to the wrong group or push for the wrong ideas, or conversely if they silence legitimate calls for change, an elected body can be sanctioned for that at the next election. If this is up to the team, course-correction is much harder (especially while we don't have a board of directors, but even if we did).

Leaving it unwritten entirely has its issues:
* if we do an update of such governing documents outside of provisions established in these same governing documents to which members are contractually bound, someone who disagrees with the update could later challenge its legitimacy, claiming they neither agreed to the document itself nor to a process that makes it binding.
* if someone in the future wants to propose an update, it would not be clear what the path for doing so is.

**Comment by jeffjaffe** [comment]
Thanks, @frivoal for the comprehensive analysis.

Re-reading this section in light of your analysis, I notice that the Team/W3M/Director does not have any formal decision role as this is written.  Looking back, that seems to be true in the previous version of the Process as well.  The Team's role seems limited to mechanically running the surveys.

That is not how we have ever operated - not for CEPC and not for Process revisions.  We have always looked for Director approval (often delegated to W3M) along the way.

I'm not saying that W3M should run the process, but that there needs to be Director approval along the way.

Given Florian's analysis, however we address Tzviya's issue, I think we should clear up the Director/W3M/Team role in this exercise.

**Comment by frivoal** [comment]
@jeffjaffe We've had a very similar conversation before: https://github.com/w3c/w3process/pull/309#issuecomment-520410564

**Comment by jeffjaffe** [comment]
@frivoal imho this is a different conversation.

CEPC was always managed by W3M for the Director and Tzviya seems uncomfortable that Process 2020 hands this to the AB.  Your analysis made me realize that not only does Process 2020 hand it over to the AB, it actually removes W3M from its existing role in approving CEPC changes.

**Comment by dwsinger** [comment]
OK, this feels like a new question "Does the Director have a formal role in approval?". I think the answer is yes, today, because of the A in AB and AC; only the Director can make almost any Decision today.

What I thought we have discussed and decided was that we would not insert a new mention of the Director into the process at a time when we're planning to take them all out. But perhaps we need to put it in, or decide what the approval process for documents is in a future Director-free consortium. Is it AC, or do we need a formal Board approval? Once we know where we're going, maybe there is a way to 'phrase it once' so it won't need revision.

**Comment by frivoal** [comment]
> Your analysis made me realize that not only does Process 2020 hand it over to the AB, it actually removes W3M from its existing role in approving CEPC changes.

* Process 2019 (and earlier) required comments about the Process to be formally addressed before sending to an AC review. This makes it impossible to ignore the opinion of the Team (which includes the Director), should they wish to express it. Process 2020 retains this requirement, and extends it to the CEPC and Patent Policy. Also, Process 2020 explicitly mentions the Team among those whose input should be solicited.

* The CEPC is made enforceable due to its inclusion in the Process, whose evolution the AB is responsible for. That effectively made the AB in charge of the CEPC already, even if we didn't say so explicitly, as the AB could already have proposed to update the Process to point to a new CEPC. In practice, even if the Team controls the publication of content at the CEPC's URL, the AB and the team did need to be in agreement about any change to it: in a hypothetical situation where the Team would replace the existing CEPC in place in a way that had displeased the AB, the AB could also have proposed updating the Process to point away from that rewritten document.

* At the end of an AC Review Period, the Director can decide anything. 

So, in practice, I think that all that Process 2020 does on this topic is:
- clarify that the CEPC and the Patent Policy can indeed be updated
- solidify the existing practice that an AC review is needed for doing so
- make no real change to the fact that both W3M and the AB need to be onboard
- make no real change to the fact that this can be developed in a CG or some other group appointed to that task

Unless we want to be able to update the CEPC or the Patent Policy without an AC review, and/or want to make it possible for the Team to drive this kind update against the will of the AB or AC even in the absence of a director, I don't see what the downside of this text is.

**Comment by jeffjaffe** [comment]
> Unless we want to be able to update the CEPC or the Patent Policy without an AC review, and/or want to make it possible for the Team to drive this kind update against the will of the AB or AC even in the absence of a director (or against the will of the director), I don't see what the downside of this text is.

@frivoal 

- there is no proposal to update CEPC or the Patent Policy without an AC review.

- there is no proposal for the Team to drive these updates against the will of the AB or AC

I don't see where you are getting this from.

The Team has faithfully driven these processes to ensure AC review and approval.  Indeed, the Team has made sure that the AB has reviewed CEPC prior to AC ballot both times this has come up.  Even without any language in the process document.

So I don't understand your points at all.

You also assert that your proposal makes no change that W3M needs to be on board with CEPC changes (which in my view is part of Tzviya's point above).  That is clearly not true.  Today, CEPC is driven by W3M, although the work has been put in the CG.  It gets W3M approval on the way to AC review.   Your proposal removes the requirement for W3M approval to CEPC changes.

**Comment by frivoal** [comment]
> I don't see where you are getting this from.

I am not at all claiming this is what you indent to do. I am very sure you do not. What I am saying is that _if_ this were your intent, the proposed text would make a difference, but given that I don't believe it is, I don't see a reason for concern.

> You also assert that your proposal makes no change that W3M needs to be on board with CEPC changes (which in my view is part of Tzviya's point above). That is clearly not true. Today, CEPC is driven by W3M, although the work has been put in the CG. It gets W3M approval on the way to AC review. Your proposal removes the requirement for W3M approval to CEPC changes.

The proposed text explicitly says that input from the team needs to be sought to assure fitness for purpose, _and_ that comments must be formally addressed. So the Team's approval is very much to be expected. Now, technically, the feedback from the Team could be formally addressed by explicitly rejecting it, and the AB could send to AC review over the objections of W3M. But that would be a very silly thing to do:
* The team can trivially alert the AC about its concerns, and if they are at all reasonable (and I see no reason why they wouldn't be), finding some sympathizer would be easy.
* At the end of the AC review, the Director decides what to do. If concerns from the Team have been unduly ignored, certainly he wouldn't let that fly. Especially given that the Director delegates this back to the Team.
It is not in the AB's interest to make this messy, so it wouldn't. Just like it is not in the Team's interest to make it messy by alienating the AB, so it wouldn't either.

The way I see it, we can:
1. Say nothing at all, and hope that nobody later questions the legitimacy/unforceability of any update we do.
2. Put W3M formally in charge, and live with the fact that if W3M and the AB disagree, the AB could push for an update of the Process that no longer refers to the W3M-endorsed new CEPC
3. Put the AB formally in charge, and live with the fact that if W3M and the AB disagree, W3M could attempt to undermine the AB in the AC Review.

None of these variants change how we work in practice. All 3 variants have a risk that things get ugly if W3M and AB fail to cooperate. Variant 1 also has a risk that things get ugly when we try to enforce it. So I think we should pick between 2 and 3, and I'd rather have accountability for such things on an elected body.

Now, all that's to say that I think the concerns about the current text are not warranted. That does not mean that I'm opposed to improving it. So, if you have a better idea for this section, I'm all ears.

**Comment by jeffjaffe** [comment]
> Now, all that's to say that I think the concerns about the current text are not warranted. That does not mean that I'm opposed to improving it. So, if you have a better idea for this section, I'm all ears.

I believe that Tzviya's "better idea" was to drop CEPC from the list.  That resulted in a long discussion, not an acceptance of her suggestion.

It seems that we should probably discuss this at a Process CG call.

**Comment by dwsinger** [comment]
I fear we need to clarify two things.
1. Insert Director Approval at the end of Chapter 11 by linking to 'W3C Decision' (which is currently the Director).
1. Revise paragraph one to make it clear that in terms of responsibility, the AB is the responsible 'sponsoring group' but that it may delegate development of the documents (e.g. to the CGs as we do for CEPC and Process). I don't think responsibility can be delegated, alas.

So, paragraph one:

>Revision of the W3C Process and related documents (see below) undergoes similar consensus-building processes as for technical reports, with the Advisory Board acting as the sponsoring Working Group. The documents may be developed by the AB or another group to whom the AB has delegated development. Review includes soliciting input from the W3C community, and in particular the Team.

and bullet 3:
>After the Advisory Committee review, following a [W3C Decision](https://w3c.github.io/w3process/#def-w3c-decision) to adopt the document(s), the Team does so and sends an announcement to the Advisory Committee. Advisory Committee representatives may initiate an Advisory Committee Appeal to the W3C.

**Comment by wseltzer** [comment]
I'm going to renew my dislike of this section entirely

**Comment by dwsinger** [comment]
Putting it together:

* * *

Revision of the W3C Process and related documents (see below) undergoes similar consensus-building processes as for technical reports, with the Advisory Board acting as the sponsoring Working Group. The documents may be developed by the AB or by another group to whom the AB has delegated development. Review includes soliciting input from the W3C community, and in particular the Team.

The documents covered by this section are:

* the W3C Process (this document)
* the W3C Patent Policy [PATENT-POLICY]
* the W3C Code of Ethics and Professional Conduct [CEPC]

The Advisory Board initiates review as follows:

1. The Team sends a Call for Review to the Advisory Committee and other W3C groups.
2. After comments have been formally addressed and the document possibly modified, the Team seeks endorsement from the Members by initiating an Advisory Committee review. The review period must last at least 28 days.
3. After the Advisory Committee review, following a [= W3C Decision =] to adopt the document(s), the Team does so and sends an announcement to the Advisory Committee. Advisory Committee representatives may initiate an Advisory Committee Appeal to the W3C.
