### ISSUE TITLE
[meta] Eliminate role of The Director and redistribute authority from The Team to W3C members & community

### ISSUE THREAD

**Issue by tantek** [w3c/w3process#393]
This is a meta issue following-up from participating in the [AB meeting on Tuesday](https://www.w3.org/wiki/AB_Agenda_Wiki_Feb2020#T1500) with the overall goal of eliminating the role of The Director from [the Process](https://www.w3.org/2019/Process-20190301/) (as an individual, delegated, or renamed) and redistribute authority from The Team in the process to W3C members &amp; community. These changes will likely be incremental, and require additional significant changes (e.g. considering elimination of Formal Objections and their processes instead of [#331](https://github.com/w3c/w3process/issues/331)).

There are several existing issues that cover aspects of this issue. Here are a few of them:

  * [#392](https://github.com/w3c/w3process/issues/392)
  * [#360](https://github.com/w3c/w3process/issues/360)
  * [#316](https://github.com/w3c/w3process/issues/316)
  * [#223](https://github.com/w3c/w3process/issues/223)

Additional follow-up issues will be filed for specific changes and sets of related changes.

(Originally published at: https://tantek.com/2020/058/b1/redistribute-authority-w3c-members-community)

**Comment by michaelchampion** [comment]
@tantek, let me ask a clarifying question.  There's been rough consensus for awhile now that the roles the Director fills now should be transferred to others.  And I assume you're not saying that the totally routine roles nominally performed by the Director (such as announcing things) shouldn't be assigned to the CEO or Team, right?

What I think you're saying is that rather than giving someone else the real decision making roles (such as those @mnot identified in #316  or I identified in #392) that the Director held, the process should be changed to make those collective decisions of the community or membership rather than inventing a new body to decide them or give the Team that power.  For example, if the Process eliminated Formal Objections, there would be no need for a Council or Technical Director or whatever to adjudicate them.  Instead, have the community or membership decide whether to create a WG, advance a spec to Rec, approve a MoU, etc.  by voting or some other mechanism to determine rough consensus or the preponderance of opinion.

Is that about right?

**Comment by dwsinger** [comment]
I believe that this _is_ the plan of record: re-assign to the team only 'routine' operations that they handle today, and that all questions of judgment and authority need to be re-architected.

So is the new thing about this is that this should be done incrementally?

**Comment by michaelchampion** [comment]
> So is the new thing about this is that this should be done incrementally?

If the question is directed at me, I don’t think this is a “new thing”. The thinking when I was in the AB was to try new ways of fulfilling the Director tole while TimBL is still somewhat available to mitigate failed experiments. 

I share @mnot’s thought in another issue:“responsibility should be added gradually, and the community should get as much advance warning as possible”.

So getting the community used to having routine 
Things done by the Team rather than nominally by the Director would help get people used to the idea that the Director is going away.  Possibly changing the TAG charter to anticipate a more strategic role might encourage members to nominate people with the broad expertise and commitment to neutrality that the Director role has implied.  Don’t radically change the power and responsibility of the AB and TAG until the electorate have had a chance to understand what kinds of people are now needed to meet those responsibilities.

**Comment by frivoal** [comment]
We should close this issue when we land the change the removes the definition of the Director from the Process.

**Comment by fantasai** [comment]
We have removed the Director from the Process!
https://github.com/w3c/w3process/pull/644

**Comment by frivoal** [comment]
お疲れ様、ティムさん :)
