### ISSUE TITLE
Clarify W3C Decision

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#404]
A W3C decision is one where the Director (or the Director's delegate) has exercised the role of assessing consensus after an Advisory Committee review.

We should clarify that the Director assesses consensus by looking at all inputs from the broad community, not just the AC.  Improved wording might be:

**A W3C decision is one where the Director (or the Director's delegate) has exercised the role of assessing consensus of the W3C Community after an Advisory Committee review.**

**Comment by dwsinger** [comment]
It should also say that the Director *decides* (and therefore has discretion). That the Director decides is currently (maybe) implied, or maybe one could read it that the AC decides and the Director merely has to agree that they have.

A W3C decision is one where the Director decides, after exercising the role of assessing consensus of the W3C Community after an Advisory Committee review.

I would rather leave the ability to delegate in the section that talks about delegation and not replicate it here.

**Comment by nigelmegitt** [comment]
A decision made by a group is one where a _Chair_ assesses consensus.
A decision made by the Director is one where, after assessing consensus, the Director decides.

Two very different things, and there's an important role for both in W3C.

**Comment by dwsinger** [comment]
@nigelmegitt we're talking explicitly about the defined term in the Process, not the general concept. see <https://w3c.github.io/w3process/#def-w3c-decision>

**Comment by nigelmegitt** [comment]
Thanks for the extra context @dwsinger - my point remains though, that sometimes a Decision is required but there is no consensus. The Director still has the option to decide, and it's important that option is available, to prevent stasis.

**Comment by frivoal** [comment]
I think there are 3 questions in here:
* consensus of who? AC only or broader community? I'd go with whole community. If ACs have voted yes, but someone who's not an AC has raised a valid concern, the Director should feel empowered to listen to—and if appropriate, act on—that concern, even AC Reps hadn't noticed.
* can the director decide even if there is no consensus => I'm convinced the answer is yes, otherwise making a W3C decision in the face of formal objection is a logical impossibility.
* If there *is* consensus, can the director decide to do something else anyway => I believe this is currently possible, but I have a hard time thinking of cases where it'd be justified.

**Comment by dwsinger** [comment]
agreed, but the sentence suggested covers all this, no?

> A W3C decision is one where the Director decides, after exercising the role of assessing consensus of the W3C Community after an Advisory Committee review.

**Comment by nigelmegitt** [comment]
> A W3C decision is one where the Director decides, after exercising the role of assessing consensus of the W3C Community after an Advisory Committee review.

What do we call a Director's Decision that didn't involve an AC review, like a decision to transition a document's maturity from CR to PR, for example?

**Comment by plehegar** [comment]
@nigelmegitt , for decisions that don't involve an AC review, the process says "[must obtain Director approval.](https://w3c.github.io/w3process/#transition-reqs)", ie it doesn't point to Director's decisions. So, I think we're fine.

**Comment by nigelmegitt** [comment]
Ah, thank you @plehegar that helps move things on. I don't think it's particularly obvious that "Director approval" is something different from a Director's Decision. "Director approval" is not a defined term.

Supporting the idea that a Director's Decision might be the outcome of "Director approval"  the text at [AC Appeal](https://w3c.github.io/w3process/#ACAppeal) :

> Advisory Committee representatives may also initiate an appeal for certain Director's decisions that do not involve an Advisory Committee review. These cases are identified in the sections which describe the requirements for the Director's decision and include additional (non-reviewed) maturity levels of Recommendation Track documents, group charter extensions and closures, and Memoranda of Understanding.

seems to imply that Director approval for advancing maturity level (plus the other listed things) does in fact result in an (appealable) Director's Decision.

As it stands, a global search and replace of "Director's Decision" for "W3C Decision" as defined by https://github.com/w3c/w3process/issues/404#issuecomment-634069934 would not resolve this ambiguity.

I propose that we resolve by including those things currently covered by "Director's Approval" in the class of things defined by "W3C Decision", if we are removing "Director's Decision". Conversely, for as long as we are retaining "Director's Decision", then "Director's Approval" should be included in the class of things defined by "Director's Decision".

The easiest way to do this is probably to globally s/Director approval/Director decision.

**Comment by nigelmegitt** [comment]
To add, I don't have permission to reopen this issue, but I think it was not adequately resolved by the change made, and should be reopened. Alternatively someone may want to open a new issue based on my comments at https://github.com/w3c/w3process/issues/404#issuecomment-635245250

**Comment by jeffjaffe** [comment]
@nigelmegitt I need some clarification of your point..

A W3C Decision is when the Director decides after an AC review.

Some Director approvals (for example when a spec advances on the REC track) do not require AC review.  Were you proposing that we add AC review for those?

**Comment by nigelmegitt** [comment]
Hi @jeffjaffe no I am not proposing that we add AC review for Director approvals, but that the definition of "A W3C Decision is when the Director decides after an AC review" be changed to make the AC review part optional, since it appears that a Decision can be taken in some circumstances without an AC review.

**Comment by jeffjaffe** [comment]
@nigelmegitt why would we make AC review of a spec going to REC optional?

**Comment by nigelmegitt** [comment]
@jeffjaffe I never suggested that we should make AC review for going to REC optional. My point is that there are _already_ decisions that can be made by the Director without AC review, and that if we define all decisions to require AC review, then we introduce an inconsistency. See the text I quoted at https://github.com/w3c/w3process/issues/404#issuecomment-635245250

**Comment by frivoal** [comment]
I think there's some confusion here. A W3C Decision and a Director's decision are deliberately different things. W3C Decision is AC Review + Director acting as the arbiter. Director's decision is in the plain English sense: the director has made a decision.

We have the parallel construct with a Working Group Decision being different from a chair's decision. In the first one, the chair has acted as the arbiter of the consensus of the working Group, in the later, they decide for themselves.

Different situations call for different things. going to REC or approving a charter? -> W3C decision. Appointing people to the TAG, or taking disciplinary measures? Director acting on his own authority.

If you think we should firm up the various ways that decisions made by the director under his own authority are called throughout the document, I don't necessarily disagree, but I think that's a separate issue from this one, and I would add, not one that I believe is urgent to fix.

**Comment by dwsinger** [comment]
I'm lost. 

* W3C Decision: made by the Director after an AC review
* Director decision: a decision made by the Director
* Director approval: a Director decision to approve something

If there is anything described as a Director Decision/Approval right now that is in fact a W3C Decision, I suppose we could clean up and link it formally. But we should not make things that are today Director decisions into W3C Decisions, because that would insert new AC Reviews.

What exactly is wrong with the clarification of who makes a W3C Decision?

**Comment by frivoal** [comment]
I don't think anything is wrong, and the things @nigelmegitt was talking about in https://github.com/w3c/w3process/issues/404#issuecomment-635245250 are correctly not described as W3C Decisions, since they are not things that happen after an AC review. That text is talking about charter extensions, not charter approvals, and other things that don't involve and AC Review. That text just says that these things too can be appealed.

While @nigelmegitt may have a point that having having an actual `<dfn>` around Director Decision and Director approval might make them easier to distinguish from W3C decisions, but this is very much a separate issue, from this rephrasing the definition of W3C Decisions, which is already a defined term, and is being used correctly.

**Comment by nigelmegitt** [comment]
OK, thanks all for helping me understand this, and apologies for the noise.

Yes, I agree @frivoal that defining "Director Decision" and "Director Approval" would have made this easier, and is likely to make other readers find it easier to navigate the spec.

Now I think I've understood that:
* Every W3C Decision is a Director's Decision following an AC Review
* Some Director's Decisions are not W3C Decisions
* Director Approval is an example of a Director's Decision that is not a W3C Decision

FWIW I was also slightly wrong-tracked by imagining (I'm not sure why) that this is somehow related to transitioning to Director-free, and that Directors Decisions were being replaced by W3C Decisions. Again, sorry! It might be worth a mental note that unpicking this in the event of the role of Director ceasing to exist will need some work. I'm sure the Editors already know this.
