### ISSUE TITLE
Increasing voter turnout in AC reviews with incentives

### ISSUE THREAD

**Issue by anssiko** [w3c/w3process#410]
There has been a soft rule that 5% of the members of the Advisory Committee need to support a proposal (typical case: new/revised charter) in its AC review to pass.

However, experience has shown it often requires an active push with a direct connection from either W3C Staff or other active participants to ACs to get there. This is not surprising. Voting means work for the AC reps, who in many cases are busy and need to conduct a legal review internally and possibly do other paperwork before casting a vote.

Can the W3C Process create better incentives for AC reps to cast a vote? I'd prefer carrot over stick. Example proposal: active ACs get a badge of honor next to their profile ("Pro") if they have voted in X% of AC reviews annually.

**Comment by dwsinger** [comment]
I also prefer carrot over stick, but the tricky part is finding something that is one but not the other. In this case, the lack of a "pro" sticker might be seen as implying a criticism, an "amateur" status. We wondered about marking voting statistics, but decided that had a greater shaming effect than incentive. We wondered about modifying the guidelines to say "5% of the normally active AC Reps" but then we're back with the marking (and calculating) problem.

**Comment by nigelmegitt** [comment]
Do we have any data about what AC members feel their AC reviews should be testing? I'm guessing most of the AC reviews are for CR->PR transitions, and I know from experience that getting a high voter turnout is difficult. Perhaps we need to check the things we're asking AC to vote on during reviews are things they care about and want to have a say in?

**Comment by palemieux** [comment]
I think it is expected (and healthy) to (usually) see low engagement from the AC, which is a diverse group:

* during charter review, since new projects are often in novel areas where only few AC members have expertise. I would in fact argue that, for charter reviews, the question really is _does anyone object to this new work item?_

* during PR transition review, since the technical work is complete and the AC should not delve in detailed technical comments. In fact, I would argue that the AC review should be focused on whether the process was followed.

**Comment by chaals** [comment]
There's not much incentive to vote for something unless it matters to you. It takes work to analyse  any issue, so if it isn't directly relevant to your company, you might find it hard to justify the work. I find it equally hard to justify expressing an opinion that has been hastily formed about something that matters little to me but much more to others, as a "vote".

I am not sure this should really change. The soft rule has the (slightly perverse) effect of meaning that well-known individuals can start work more easily, because the important question becomes how many AC reps you can rally to support it. It probably should not become a hard-and-fast rule: 

At least as long as we have a technical director and staff, it makes sense to allow W3C a certain amount of latitude to direct some resources to work they consider will be important to the Web. But I think if we have a mechanism in place for W3C to lean on the scales somewhat, we will end up with an actual rule for determining when we commit the resources that members fund, to work that is intended to be issued and adopted with the recommendation of the collective membership behind it.

I conclude that this isn't a problem we can solve without insisting people do what amounts to busywork in order to simplify our own lives. That doesn't seem like a good plan.

**Comment by TzviyaSiegman** [comment]
I was going to say what Chaals said. I don't think we should push people to vote on topics with which they are not familiar. (Separate topic, I think we need to simplify the voting process.)

**Comment by nigelmegitt** [comment]
Seems like AC review turnout needs to be thought about separately for a) CR -> PR reviews and b) Charter reviews [and by extension, for c) anything else].

## CR -> PR reviews

Reasonable grounds for saying "no" should be limited to things like:
* due process has not been followed.
* AC disagrees with WG's handling of objections, e.g. if a Chair has decided to proceed despite an objection, but disagrees with the rationale or the outcome.
* some kind of "force majeure" scenario where events have overtaken the work but the WG has decided to proceed despite them, or process was initiated before them, and AC thinks it would be better to shelve the work anyway. 

<details><summary>Force majeure examples?</summary>I suspect this has never happened - I'm not sure what a good example would be, maybe [thinks out loud] a spec based around an encryption technique for which a new mechanism has been recently found to break it, and the WG thinks "it's still worth advancing for cases where the new mechanism is impractical" but the AC thinks "sorry we have to go back to the drawing board now we have this new mechanism".</details>

Unreasonable grounds for saying "no" might include technical objections, which should have been raised earlier by interested parties.

### Turnout? Default vote?

The assumption should be silence is assent. 

The need for a minimum number of AC reviews seems pointless. However, this could be made stronger by entering a _default vote_ for AC members, of "no objection" unless it is deliberately overridden, with one of the override options being "abstain". This would nudge AC members to express a view, if they have one, but give minimal work if they do not.

## Charter review

Reasonable questions to ask the AC are:
* Do you agree with the strategy team that W3C should be doing this work next?
* Do you agree that we should spend this much team resource? (and if no, what would be a better amount?)
* Is this Charter adequate and appropriate in terms of scope, specificity, architectural approach (TAG review of the scope of Charter deliverables, anyone?), proposed timeline, links with other groups, internal and external to W3C, success criteria?
* Are the proposed policies acceptable in breadth and detail, e.g. Decision Policy?

### Turnout?

Here I think it makes more sense to require a minimum voting level, and would not enter a default vote. Positive support at the Charter stage is much more useful than at the PR transition stage.

**Comment by dwsinger** [comment]
Note that charters are normally subject to greater scrutiny when they fail the appallingly low 5% threshold.

**Comment by palemieux** [comment]
> Positive support at the Charter stage is much more useful than at the PR transition stage.

I expect few explicit votes of support at charter review: a more diverse membership means a broader range of interests and relatively fewer experts in each domain, especially if the domain is on the cutting edge. Some groundbreaking efforts sometime start with just a few visionaries.

I would therefore assume approval unless explicit objections are raised.

I would also suggest that these objections need to clear a high-bar, e.g. "contrary to the mission of W3C", "outside of the scope of W3C", "cannot result in a deliverable under any circumstance", etc... In the case of charter renewal, lack of measurable progress could be grounds for objection.

**Comment by dwsinger** [comment]
we are going to leave this to practice, guidelines and the AB and not change the formal process
