### ISSUE TITLE
Consistency issue: is it 28 days or four weeks?

### ISSUE THREAD

**Issue by iherman** [w3c/w3process#44]
The time limits for candidate recommendations is set to four weeks, as in:

> must specify the deadline for further comments, which *MUST* be **at least** four weeks after publication, 

In section 6.4.1. Just a few lines below (in 6.5), it says:

> deadline for Advisory Committee review, which _MUST_ be **at least** 28 days after the publication of the Proposed Recommendation...

Can we try to be consistent and speak either of four weeks or of 28 days? Actually, neither of the two are optimal, if there are, say, Xmas vacations in between, so I believe the ideal would be to say “**at least** 20 business days”. (This, I believe, is actually the current practice used by the Working Groups.)

**Comment by chaals** [comment]
"business days" are ill-defined, because they vary widely around the world, and because what I observe in practice is that Working Groups extend the time when it covers major holidays of their members - whether those are local holidays or not. But sure, I am happy to look through a make everything a number of days...05.06.2017, 16:10, "Ivan Herman" <notifications@github.com>:The time limits for candidate recommendations is set to four weeks, as in:

must specify the deadline for further comments, which MUST be at least four weeks after publication,

In section 6.4.1. Just a few lines below (in 6.5), it says:

deadline for Advisory Committee review, which MUST be at least 28 days after the publication of the Proposed Recommendation...

Can we try to be consistent and speak either of four weeks or of 28 days? Actually, neither of the two are optimal, if there are, say, Xmas vacations in between, so I believe the ideal would be to say “at least 20 business days”. (This, I believe, is actually the current practice used by the Working Groups.)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Private Mail. chaals is Charles McCathie Nevile.

**Comment by iherman** [comment]
@chaals I think my main point is to use the same term in both (all, if this appears elsewhere). I am mildly in favour of using "at least 4 weeks", possibly with an additional comment referring to the fact that the team should consider extending those if there are major holidays that may affect the ability of the AC members to vote. (I understand the ambiguity of the "business days".)

**Comment by dwsinger** [comment]
Let's keep editorial questions (28 days vs. 4 weeks) separate from operational or material questions (should we make allowance for holidays?)...

**Comment by vfournier17** [comment]
I'd prefer to use the number of calendar days - i.e., 28 calendar days.

**Comment by chaals** [comment]
@vfournier17 wrote:

> I'd prefer to use the number of calendar days - i.e., 28 calendar days.

Me too, and that's what I will try to do unless the group explicitly decides otherwise.

**Comment by vfournier17** [comment]
Why would we wait until 2018 to make a simple clarifying change like this?

**Comment by dwsinger** [comment]
by the time we present it at TPAC, and then have the formal vote, it'll take effect in 2018, that's all
