### ISSUE TITLE
Proposal for a Directorate

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#457]
[updated to take a clearer stance in the strawman proposals...]
I've reviewed the various director-free issues and discussion, reconsidered the positions I've taken, and offer another proposal for the AB's consideration and the community's feedback: 
1. Explicitly change the Process and Member Agreement to reassign the  Director's formal leadership / ultimate authority roles to the Board of Directors in a future legal entity;
2. Explicitly assign the Director's administrative roles that have always been delegated to the Team to the CEO/W3M/Team, especially the operation of the process and ensuring that its provisions are followed; 
3. Create a "Directorate" (3 people) to take on the Director's technical/strategic roles.  

The boundaries of "technical/strategic roles" are fuzzy and open to discussion.  Technical matters definitely include 
- deciding whether creating a particular IG or WG is in the organization's best interest before proposing it to the AC and by resolving any formal objections; 
- resolving formal objections to advancing documents along the Process stages
- filling appointed TAG seats

How to choose the Directorate?  The current proposal of record for a W3C Council has [various issues](https://github.com/w3c/w3process/issues/391#issuecomment-593642740)  but it does make sense to leverage the elected bodies to choose the Directorate. 

Strawman proposal: ***W3M, the TAG, and AB can each appoint one person to the Directorate for a fixed term.***

Open Questions: - 
- ***How long are the fixed terms?*** Strawman answer: 1 year.   That lets the appointing bodies ensure people with the appropriate neutrality and expertise are on board for the controversies that might be expected in the coming year, and allows quick replacement of an appointee who doesn't do a good job. 
- ***Should the Process dictate how the appointing bodies decide, whether by consensus, majority ballot, or whatever?*** (Strawman answer: no)
- ***Must the person each body appoints to the Directorate be a member of the appointing body?*** (Strawman answer: no, any of the appointing bodies could appoint anyone they think could do a good job)
-  ***Can the appointing body replace their appointee before the end of the term?*** (Strawman answer: Yes)
- ***Should the AC get a say in the composition of the Directorate?*** (Strawman answer:  Yes, run an AC approval ballot for  nominees whenever an appointment or re-appointment happens).
- ***Must the Directorate work by consensus, or is majority rule OK?*** (Strawman answer: with 3 people, a simple majority is a 2/3 supermajority, so allowing a majority of the Directorate to make a decision seems fine.)

Additional thoughts:
- I personally think it would be a good practice for the AB and TAG to have a supermajority in favor of the Directorate member they appoint, but am reluctant to have the Process insist on that.  Especially since the Process can't dictate how W3M choose their appointee ... 

- The original draft of this proposal  agonized about whether the Directorate terms should be staggered, and offered a possible complication: first year, the AB, TAG, and W3M each appoint 1 person for a 2-year term; the second year the AB and TAG appoint another person for a staggered 2-year term.  Upon reflection, that seems to add more complexity than is justified by the problems that a discontinuity might plausibly raise.  Likewise, adding more than 3 people might make some sense in terms of diversity, ensuring all the stakeholders get a voice, etc.  But ultimately it's the job of the appointing bodies to appoint people to the Directorate in a way that optimizes the diversity, experience, expertise, etc. of the Directorate.

- There's all sorts of permutations of how the AC might approve the Directorate as a whole, or each member separately, or how to respond if someone doesn't get approval.  I suspect that's not something worth bikeshedding about until there is an actual problem.  And if the problem happens, it's probably a symptom of a much deeper problem that tweaking the Process can't fix.

**Comment by dwsinger** [comment]
Interesting. can you clarify?

> W3M, the TAG, and AB can each appoint one person to the Directorate for a fixed term.


OK, so it's 3 people.

But later you have the AB and TAG appointing a person every year for staggered 2-year terms, so 5 people. Which?

**Comment by michaelchampion** [comment]
Sorry, I guess I was thinking while writing and didn’t go back to make a consistent proposal.

Having 5 people after the 1st year is one mitigation for all the terms expiring at once, if they is a problem worth solving.

On reflection, I think a 3-person Directorate is the simplest and cleanest approach.  The appointing bodies can worry about balancing continuity, diversity, etc. rather than complicating the Process in hopes of addressing potential problems that might arise.

**Comment by dwsinger** [comment]
So, major questions. If I get elected to the TAG or AB, am I required to be available for election to the Directorate, or can I choose? If it's the latter, what happens if the TAG or AB can't find anyone, inside or out?

Frankly, the amount of time I spend on the AB is already high. If I were the only person, or one of only two people, from the AB on a two-year stint handling all FOs and appeals, that could be a high workload. I am not at all sure I'd sign up for it, or that anyone would.

I'm not at all comfortable with the AB or TAG picking (from the membership's point of view) a random person of no status, elected or appointed, to do this.

Also, it leaves possible that we select people for this two-year stint who'd have direct interest – conflict of interest – in one or more cases brought to the Directorate. Can or must they recuse?

Perhaps we need a hybrid: that each case is heard by a Directorate that is appointed from the TAG and AB members and from the team, for that case, and that the final result is endorsed by full council? I can imagine people agreeing to be the AB or TAG person leading on a case; and I think if it's case by case, we could say that it's a consequence of AB/TAG election that you handle cases in rotation (with adjustments for recusal for conflict of interest).

**Comment by michaelchampion** [comment]
> If I get elected to the TAG or AB, am I required to be available for election to the Directorate

I'd say 'no'.  But under the W3C Council proposal, aren't all AB/TAG members required to be available for technical appeals, and generally expected to be on top of strategic issues that generate formal objections?  Under the Directorate proposal, the AB/TAG works to find ONE person with the bandwidth and qualifications to deal with such issues in the upcoming year.  

> what happens if the TAG or AB can't find anyone, inside or out? 

A  scenario I worry about is that the AB or TAG find TWO people who are qualified/available, and can't get real consensus on either.  If they're truly deadlocked, I guess they don't appoint anyone that iteration; the threat of that happening will probably lead to consensus (or compromise ... "we'll appoint Sally this year and Ali next year").  But it seems unlikely that they'll not find anyone inside or out so long as W3C maintains its prestige as the place where web standards get ratified.

> I'm not at all comfortable with the AB or TAG picking (from the membership's point of view) a random person of no status,
 
I don't think that either the AB or TAG would plausibly appoint someone with "no status". From the membership's PoV, a former team member or AB or TAG member, experienced Chair or Editor, or even respected Invited Expert could have the status to be on the Directorate for a year.  Also I do propose that the AC have the chance to not approve the AB or TAG appointee, so that would give even an outsider some "status."

>  Can or must [someone with a conflict of interest] recuse?

Good point I didn't cover in the proposal. I'd say Yes they should recuse, and the other two Directorate members could insist that someone recuse.  If all 3 have a conflict of interest, I have no solution to propose.

 > Perhaps we need a hybrid ... the final result is endorsed by full council? 

I didn't mention this in the proposal, but presumably the AC can run an appeal of a Directorate decision just like they can appeal a Director ruling today.  What problem does adding a AB+TAG review/appeal step solve?

> I think if it's case by case, we could say that it's a consequence of AB/TAG election that you handle cases in rotation (with adjustments for recusal for conflict of interest).

I suspect this will create lots of corners for Devils in the Details to hide in. I prefer to keep things as simple as possible while trusting the AC to select people with good judgment to the AB and TAG, and to trust the AB and TAG to appoint qualified but generally neutral people to the Directorate.  I propose keeping the terms short (1 year in my updated proposal) and giving the AB, TAG, and W3M the ability to change their appointees if there are too many conflicts of interest or new issues requiring different expertise coming up.

**Comment by cwilso** [comment]
I wanted to explicitly say my "thumbs-up" above was to express support for the idea of a Directorate.  I do disagree with a few of Mike's detail answers, but not to the level of "objection".  I think primarily I would say recusals are not required, simply because I think conflicts of interest at this level will be common.  The Directorate must be trusted to apply the Principles even-handedly.

**Comment by michaelchampion** [comment]
@cwilso my detailed suggestions are  discussion starters, not well thought out suggestions.  Thanks for the discussion! 

I don’t have strong  feelings about recusal other than:
- it should rarely be needed with good appointments
- there could be cases where a Directorate member simply can’t be objective because of a financial or reputation stake in a particular issue.
There should be some expectation they won’t engage when they can’t be  neutral

**Comment by dwsinger** [comment]
I'm willing to run with it and explore, but I think that at least the following are deeply questionable:
* there is a non-empty set of people who'd both do a good job and would be willing to sign up for a whole year of FOs that rise to Director-level-decision; that could be a very large workload
* that the community would be willing, or even asked to, accept a decision co-written by someone with obvious conflict of interest (heck, we've had grumbling about some TimBL decisions that involved topics dear to him); and a Directorate of 3 can't afford recusals; a decision of 2 or 1 is weak; and a group of 0 can't decide.

Under the council proposal, we expect the entire TAG/AB to endorse a decision, but that they'll ask a smaller group to go away and help form it, case by case, so the expectation is that you'll be willing to serve sometimes on the small group, and always willing to consider the proposed outcome and endorse it or push back.

**Comment by mnot** [comment]
First impressions:

* Having the AB and W3M appoint 1/3 each of technical oversight feels like it's perpetuating existing power structures to avoid conflict ("all problems can be solved by adding a layer of abstraction"), not making the best decision on technical leadership according to any principles. E.g. why does the AB have anything to say about who's most qualified to make technical decisions? Why W3M?

* We should acknowledge that TAG appointed seats were a one-off because of Tim's special status; it doesn't make sense to try to carry them forward.

* For a while, I've advocated building the TAG up to become a body worthy of filling this role. What distinguishes it from the TAG, and what blocks the TAG from doing this? If a directorate is instantiated, how does it relate to the TAG?

**Comment by fantasai** [comment]
- Minor comment on recusals: we could say that if a member of the Directorate feels they need to recuse themselves from a case, the appointing body could appoint a temporary replacement.
- @mnot Many issues that rise to the level of FO have both technical and procedural components, so you'll want to be looking at the problem from both perspectives. ... For the scope of tasks @michaelchampion listed (which I think are the right ones), I think the composition is actually quite appropriate, presuming they're people who believe in respecting each other and working together (which should be qualities the appointing bodies should require).
- I share dsinger's concern about finding volunteers, since this is presumably an unpaid position. I think you'd want _more_ continuity on the Directorate rather than less, and (aside from the W3M appointee) I'm afraid you'll get something close to 1-year turnover for various reasons.

One of the benefits of having a Director that belonged to W3C itself was that the position wasn't under any particular Member company's management. With the TAG and the AB, influence is sufficiently diluted across all the members that I'm not too concerned, but with a three-person Directorate two of whom are Member employees... I'm a bit more concerned. It's too easy to not really care about the things your management and colleagues don't really care about.

I like the idea of three such people working together in theory. I don't know how/if we can make it work well in practice as proposed.

I think... on the whole, my current position would be to either define such three-person teams as a formalism of the "ad-hoc sub-group of the W3C Council" idea rather than an independent fixed-term position, since at least that way the W3C Council as a whole serves both as a resource and a backstop; or insulate the Directorate more from the demands of external management and support more long-term, independent investigation and thinking, e.g. by making it a 3-year salaried position (even if part-time) at W3C.

**Comment by mnot** [comment]
@fantasai that presupposes that technical people can't make process decisions, and yet chairs do it all the time.

To me, a more sensible arrangement would be to have the TAG make decisions, and the AB act as an appeal body.

**Comment by michaelchampion** [comment]
The sorts of people who have been elected to the TAG are indeed  the sorts of people who are best equipped to handle appeals, formal objections, and consult on overall strategy (which charters, and thus charter objections, instantiate).  

I like the way @mnot put it:
> building the TAG up to become a body worthy of filling this role.

But I'm not convinced the TAG as it exists *today* is ready to fill the "Directorate" role:

1. The current TAG charter limits its scope to 
> technical issues about Web architecture. The TAG should not consider administrative, process, or organizational policy issues of W3C, which are generally addressed by the W3C Advisory Committee, Advisory Board, and Team.   

The Directorate needs a broader mandate than that.

2. When I was on the AB, conversations with TAG members indicated a reluctance to become the "appeals court", especially (IIRC) for matters that have policy, process, and strategy issues confounding "technical issues about Web architecture".  It would be good to hear from current TAG members to see if that is still the case.

3. I get the sense the TAG already has more work on its plate than it has bandwidth to handle.  

@dwsinger and @fantasai seem to prefer the current proposal for a W3C Council consisting of the AB+TAG+CEO.  I've argued against that in https://github.com/w3c/w3process/issues/391#issuecomment-593642740:
- too big a group, so there will be a de facto subset doing most of the work
- the people who sign up to do the work on an issue are more likely to be advocates for a position than neutral judges
- the TAG and AB are elected by Meek STV, which tends to select for partisans rather than consensus seekers
- all that will tend to make the Council a *political* body rather than a good replacement for TimB's neutral, well-informed judgment.

Maybe a better way than my proposal above would be a Directorate hired by / accountable to the Board just as they will presumably manage a CEO.   It's probably not a full-time job (or even 1 FTE among the 3 of them), but compensation should be adequate to make sure the people selected have the bandwidth to quickly and thoroughly handle the expected workload.  (Or a 1-person Technical Director, but I've been told that's not a politically viable idea).  People who have served on the TAG (and perhaps current TAG members, not sure) are likely to be a good pool of candidates.  But there are people who have served on the AB, and the Team, and as Chairs, etc. who would also be well-qualified, so I'm not convinced that restricting the Directorate to present or past TAG members is optimal.

So, I don't object to @mnot's proposal to build up the TAG to fill the role of the Directorate, but I do think the TAG charter and selection mechanism need to substantially change for that work well.

**Comment by mnot** [comment]
> but I do think the TAG charter and selection mechanism need to substantially change for that work well.

Big +1 to that. I tend to think that responsibility should be added gradually, and the community should get as much advance warning as possible, so that we can get the right people on the TAG. That said, you're right that selection is really key -- just letting Members vote may well not cut it.

**Comment by cwilso** [comment]
I think adding that to the TAG charter would take a lot of bandwidth and focus away from the valuable work the TAG does today.  I think a large part of what is needed here is not technical or architectural leadership - it is, in essence, making the principled choices for the W3C as an organization.

**Comment by jeffjaffe** [comment]
I support the general direction for a Directorate.  Since Mike made the original proposal in September of last year, we have run an experiment of the W3C Council, for a Formal Objection related to the chartering of the Device and Sensors Working Group (see [1] for the results of that experiment).  In my view the experiment was largely successful in that it illustrated how the W3C Council could come together to resolve Formal Objections in a Director-free W3C.

But the experiment was imperfect (as we might expect all experiments to be).  The Council participants were at various levels of expertise - something which would be ameliorated if we had a more "professional" set of deciders - who were most expert at this task.  In my mind, that gave increased credence to the Directorate proposal discussed here.

In the Council experiment, the issue of recusals came up, as has been discussed above.  I think recusals will happen frequently, so I believe that we need more than three people in the Directorate, because recusals might deplete the three identified people.

Here are my current thoughts on how we could structure a Directorate, based on the discussion here to date, based on my comments above, and based on some other observations about the experiment.

**Directorate composition.**  I propose that the Directorate should be comprised of 5 individuals and 4 alternates.  The AB and TAG each elect two individuals to serve one year terms, soon after AB or TAG elections.  We need at least 4 people to ensure that the Directorate has sufficient diversity of perspective in: technologies, business perspectives, geography, gender, etc.

The fifth person selected for any formal objection is appointed by W3M, but that position rotates from objection to objection as follows.  W3M appoints a team of four senior W3Mers.  They bring massive institutional knowledge about the processing of formal objections.  For any particular objection, W3M selects one of these four people - specifically the one who is the best subject matter expert for the particular objection.

The AB and TAG also each elect two individuals to serve one year terms as alternates.  They have two primary roles:
 
-  Step up to resolve a formal objection due to recusals of Directorate members

-  Learn, so they are better qualified to be future Directorate members

We have 4 alternates because we expect to have strict recusal rules (see recusals below) - so there is a need for backups.  When alternates join a formal objection due to recusal of a regular member of the Directorate, they are full members of the team for that formal objection.  If they are only alternates for a particular objection, they are encouraged to attend as observers to get trained as future Directorate members.

None of the eight TAG/AB members or alternates should be from the same organization (see [3]).

**Qualifications for the Directorate.**  When the AB/TAG elect Directorate members, they are empowered to elect whoever they want.  But they should have the following considerations in mind.

-  Breadth.  There is a wide swath of web technologies and the impact of the web on the world is huge.  People who are expert in that breadth are valuable in the Directorate.
-  Depth.  Some formal objection topics can be rather deep.  The Directorate needs people who can go deep.
-  Open mindedness and good listeners.  It is critical that the Directorate develops a reputation of objectivity, fairness, and lack of bias.  Having individuals who can approach any problem with an open mind and can listen to both sides of an argument is essential.
-  Independent thinking.  An advantage of having a small Directorate rather than a large Council is that we can be more certain that each member of the decision team is providing their own analysis, rather than just listening to others and going along with a consensus.
-  Experience in handling formal objections.  This could be through previous terms on the Directorate, or previous terms as an alternate.
-  Have enough time.  Many people have posted the concern above that it will be hard to find people  who can give so much time to be on the Directorate.  This is a real problem, and we should not put people into this role if they do not have the time.  I actually think the Directorate is an improvement on the Council.  The Council asks 20+ people to make enough time - the Directorate is less demanding.  True, a Council member could drop out of an objection if they don't have the time - but that just weakens the concept of a Council if scattered people drop out because they don't have the time.
-  Diversity.  This is not a characteristic of an individual member of the Directorate, but the AB/TAG should be thoughtful that across the Directorate there is diversity of perspective in: technologies, business perspectives, geography, gender, etc.  

**Decisions.**  It is preferable if decisions are by consensus, but in the absence of consensus the Directorate can decide by majority vote.

**Recusals.**  The Directorate's decisions will only get community buy-in if they are both absolutely free of bias and also free of the perception of bias.  Accordingly, any member of the Directorate whose organization has a business interest in the result of an objection MUST recuse.  While it may be difficult to have precise criteria for "business interest", as a minimum, if a company is implementing the technology that is being objected to, employees of that company have the appearance of bias and MUST recuse (see [4]).  Similarly, a member of the Directorate MUST recuse if their company employs a Chair or Editor of the relevant Working Group.

In this proposal, I also add a few other suggestions for "how" the Directorate handles formal objections, based on the experience of the aforementioned experiment.  These suggestions are motivated by three other considerations:
 
- Ensure that the Directorate is free of bias or the perception of bias.
- Ensure that processing formal objections do not become such a time-sink that qualified people are discouraged from being on the Directorate
- Ensure that the Directorate does not interfere with the empowerment of Working Groups and the TAG in the decentralized development of web technology.

Here are the other considerations:

**1. Burden of proof:**  It is the responsibility of the objector to provide the rationale as to why the Decision being objected to should be overruled.  It is not the responsibility of the Directorate to develop new logic and arguments to support the objector.

- Rationale: 
        If the Directorate merely evaluates arguments of the objector, it is easier to see that they are bias-free; whereas if the Directorate develops new logic and arguments, it can create the perception that they were biased to begin with.
        If the Directorate develops new logic and arguments, it will take more of their time.
        If the Directorate develops new logic and arguments for one objection, then to remain bias-free, they will need to similarly develop new logic and arguments for all objections, exacerbating both bias and time issues.
        If the Directorate develops new logic and arguments, objectors might increase the processing load by being encouraged to object without facts - in the hope that the Directorate finds new facts to support their pov.

**2. Light touch decision making.**  The role of the Directorate is limited to deciding on the objection, and not to provide additional recommendations beyond the objection.  Thus their response should be limited to one of the following three decisions:

-  The Directorate may overrule the objection
-  The Directorate may sustain the objection and ask for a change from those that issued the W3C Decision.
-  The Directorate may sustain the objection and make specific suggestions to those that issued the W3C Decision how they could amend their work to make it acceptable.
   
- Rationale for not allowing additional recommendations beyond the three decisions above:
        The more that the Directorate gets into the details of how the Working Group should do their work, the more that they are centralizing architectural control for the web.  That is not the design point for W3C.  We expect that the Working Groups are responsible for their work.  The TAG provides a mechanism for architecture review and we have several horizontal review groups.  The Directorate should not usurp those roles.
        If the Directorate goes beyond the three decisions above it will increase the Directorate's workload.
        The more that the Directorate gets into the details of designing solutions, the more it will be challenging to maintain the perception of lack of bias.

**3. Review**.  Since the credibility of the Directorate is always looked at, it is prudent for the Directorate to stage their decisions as follows:

- They verbally reach a conclusion.  In reaching this decision they follow best practices similar to what we have been developing for the Council [5].
-  They prepare a draft report that they all agree to.
-  They share this report with AB+TAG+W3M for review and input.  The AB, TAG, and W3M have no authority with respect to the report, but they are an effective sounding board.
-  The Directorate evaluates the review and makes changes if they decide they are merited.
-  The Directorate publishes their decision.

[1] https://github.com/w3c/dap-charter/issues/103#issuecomment-744446928

[2] https://github.com/w3c/w3process/issues/497

[3] https://github.com/w3c/w3process/issues/327

[4] https://github.com/w3c/w3process/issues/278#issuecomment-767600289

[5] https://www.w3.org/2019/06/W3C%20Council%20guidelines%20for%20formal-objections.html

**Comment by cwilso** [comment]
I think this is one rational approach to take to form a Directorate.  I'm not convinced it will result in a more "professional" set of deciders - more expert at this task - because I think you will have a more limited set of people, pre-selected.  That means you will have a smaller set.

Likewise, although I think I see the implications - the TAG and the AB each elect two members plus two alternates, but you don't explicitly state they elected them FROM the TAG/AB; I presume that's the idea? It's also not clear how they are elected, exactly - and in particular, how you avoid two directors from the same Member company (recusal?  David Singer and Tess O'Connor are both great candidates, e.g.; does one have to recuse up front prior to the elections? Does one step aside and the elections are re-run?)

I confess, when I was thinking of a Directorate, I suggested longer terms, and directly elected by the AC, to avoid such conflict.  I'm not necessarily opposed to this kind of plan instead, but I will say off the cuff that I think the Council experiment provided better results than I would expect from this.

**Comment by dwsinger** [comment]
I think that there are some serious problems here. One of the criteria would be willingness to serve; I would not volunteer to handle every FO in the course of a year. In the council design, we can expect reasonable variation in who is engaged, depending on the nature of the FO. I may feel able to be more helpful in some and less in others. I don't see how to get around this. Nor do I see why the team should be allowed to change their mind from FO to FO but the AB and TAG members have to do it for a year.

Also, the recusal rules are lop-sided. You want to force recusal of anyone from "a company [that] is implementing the technology that is being objected to" but give a free pass to all the companies that refuse to implement, i.e. stand perhaps equally forcefully on the opposite side of the question; and a free pass to non-implementers, which is giving pre-eminence to academics. As written, this could force recusal of almost anyone who actually has a stake and experience in implementing web standards.

I'd suggest we take recusal rules as  orthogonal

I still think that to have the weight we want, the entire TAG and AB should approve the recommended position, preferably by consensus, but if needed by voting. I don't think a 3-2 vote of a 5-member council carries enough weight.

So, I suggest that we look at advising that the council proceed something like this on an FO by FO basis; select some leaders who will recommend a position, rather than designing this way. Leaving it as "the council works out on an FO-by-FO basis how to proceed" is more flexible.

**Comment by jeffjaffe** [comment]
> Likewise, although I think I see the implications - the TAG and the AB each elect two members plus two alternates, but you don't explicitly state they elected them FROM the TAG/AB; I presume that's the idea? It's also not clear how they are elected, 

I was not overly focused on "how" they are elected in my remarks.  It could be from the TAG/AB or could be from outside the TAG/AB.  I'm also OK with direct election from the AC.

exactly - and in particular, how you avoid two directors from the same Member company (recusal? David Singer and Tess O'Connor are both great candidates, e.g.; does one have to recuse up front prior to the elections? Does one step aside and the elections are re-run?)

Indeed David and Tess are both great.  But just as we disallow having two folks from the same organization on the TAG or AB, for the same reason, I would discourage it here.

> 
> I confess, when I was thinking of a Directorate, I suggested longer terms, and directly elected by the AC, to avoid such conflict. I'm not necessarily opposed to this kind of plan instead, but I will say off the cuff that I think the Council experiment provided better results than I would expect from this.

**Comment by jeffjaffe** [comment]
> I think that there are some serious problems here. One of the criteria would be willingness to serve; I would not volunteer to handle every FO in the course of a year.

Most Formal Objections are resolved before they get to the Director/Council/Directorate.  I have some level of confidence that there are qualified people who would be willing to do this for a year.

 In the council design, we can expect reasonable variation in who is engaged, depending on the nature of the FO. I may feel able to be more helpful in some and less in others. I don't see how to get around this. Nor do I see why the team should be allowed to change their mind from FO to FO but the AB and TAG members have to do it for a year.

The rationale was that the Team representatives would be doing it for many years.

> 
> Also, the recusal rules are lop-sided. You want to force recusal of anyone from "a company [that] is implementing the technology that is being objected to" but give a free pass to all the companies that refuse to implement, i.e. stand perhaps equally forcefully on the opposite side of the question; and a free pass to non-implementers, which is giving pre-eminence to academics. As written, this could force recusal of almost anyone who actually has a stake and experience in implementing web standards.

I don't understand your math.  A typical charter has about 10 Members saying they will implement the technology.  About 400 Members don't implement the technology.  I would not call all 400 Members not implementing the technology of a particular WG to be academics (not that I have any objection to academics if they are elected to resolve formal objections, either).

> 
> I'd suggest we take recusal rules as orthogonal
> 
> I still think that to have the weight we want, the entire TAG and AB should approve the recommended position, preferably by consensus, but if needed by voting. I don't think a 3-2 vote of a 5-member council carries enough weight.

**Comment by cwilso** [comment]
> Indeed David and Tess are both great. But just as we disallow having two folks from the same organization on the TAG or AB, for the same reason, I would discourage it here.

I wasn't suggesting we should enable multiple directors from the same Member; merely that the mechanics of ensuring that doesn't happen across two separate simultaneous elections (one by the AB, one by the TAG) would be a lot more complex.

**Comment by cwilso** [comment]
> I don't understand your math. A typical charter has about 10 Members saying they will implement the technology. About 400 Members don't implement the technology. I would not call all 400 Members not implementing the technology of a particular WG to be academics (not that I have any objection to academics if they are elected to resolve formal objections, either).

I think David's point was more "companies that are in a position to implement, but would explicitly choose not to, but are not the source of the FO".  E.g., Apple in the Devices and Sensors objection.

**Comment by jeffjaffe** [comment]
> I think David's point was more "companies that are in a position to implement, but would explicitly choose not to, but are not the source of the FO". E.g., Apple in the Devices and Sensors objection.

In that case we are in complete agreement.  I don't think that Apple is implementing the DAS technology, and I didn't suggest that they needed to recuse.

**Comment by dwsinger** [comment]
Then I think you're missing the point. The recusal rule would allow all the entities that bitterly oppose something to serve on the Directorate, and ban all those who support it and intend to ship it. That's not neutral.

**Comment by jeffjaffe** [comment]
> Then I think you're missing the point. The recusal rule would allow all the entities that bitterly oppose something to serve on the Directorate, and ban all those who support it and intend to ship it. That's not neutral.

I think you are raising a valid point.  The recusal rule that I quoted was not the only recusal rule, it was just an example.  I would expect that all the entities that bitterly oppose something would have raised an issue and probably joined the formal objection.  **Objectors need to recuse as well.**

It is possible, of course that two objectors could try to game the system.  One would raise a formal objection.  The other would quietly say nothing, but as a member of the Directorate would push hard to sustain the objection.  I would hope that the tiny number of esteemed people elected to be on the Directorate would not have that behavior, but no system is foolproof.

**Comment by michaelchampion** [comment]
Hmm, the proposal for a Directorate is getting awfully complex -- 5 members, 4 alternates, a rotating W3M representative, and a lot of recusal language.  I understand the rationale:  "The Directorate's decisions will only get community buy-in if they are both absolutely free of bias and also free of the perception of bias."  But inventing a complex process won't engender the trust that Sir Tim earned while he was active. 

I suspect it will be more useful to select  3, 5, or whatever number of people who really do have the attributes needed to be a member of the Directorate.  Jeff gives a long list of desirable qualifications; I'd stress:
- expertise in web platform  technology and familiarity with the challenges it faces (and has created) for the world
- sufficient available bandwidth and commitment to carefully analyze the issue at hand and help craft a compelling resolution
- enough financial independence and personal integrity to be neutral, e.g.  to rule against current or former employers' positions

I don't have strong feelings on how to select such people.  Having the AB, TAG, and W3M appoint representatives to a "search committee" seems workable.  I agree with @cwilso that the Directorate should ultimately be elected by the AC, perhaps with an approval ballot for a slate of people the search committee found or to select the N most qualified people from a larger set of nominees.

Sure, people may have to recuse themselves from discussions they have some personal stake in.  Rathe than the system of alternates and rotating W3M people @jeffjaffe proposes, it would be simpler to have the Directorate itself decide on a case by case basis if any of their members would be seen as not being sufficiently neutral.  In a 3-person Directorate, any one member could request someone recuse themself; in a 5-person Directorate, maybe it's 2.  

Finally, making the internal proceedings of the Directorate confidential *to the Directorate itself* could help ensure that people are willing to stand up to "the mob" or their bosses.  Plausible deniability, e.g. "Sorry boss, the others made me recuse myself so I couldn't push our party line" or "I pleaded with them but was outvoted" (ahem, even when the actual truth is a bit more nuanced) could be useful.  That is, the rest of the consortium MUST know what is the issue going in and decision coming out, but now  how individuals voted how or who asked whom to recuse themselves, or how initial positions evolved during the discussions.

I do think Jeff's "light touch", "burden of proof", and "review" considerations above are quite useful and should be included in the Process or supporting documentation defining a Directorate.

**Comment by TzviyaSiegman** [comment]
I agree with most of what @michaelchampion wrote. It's worth considering how transparent things ought to be, but that is a detail for the future. The details of Formal Objections and recusals can be worked out in a separate thread as well. The question here boils down to can a directorate of X people take on the role of the director?

**Comment by dwsinger** [comment]
> The question here boils down to can a directorate of X people take on the role of the director?

Sorry to correct you, the the Director has a central role in many aspects of the consortium operation. This is solely about hearing Formal Objections. Not approving accounts or appointing to the TAG or...

**Comment by fantasai** [comment]
@michaelchampion The role of resolving Formal Objections has been assigned to the Council, and other roles in the Process to other entities, and we've tightened up a lot of the decisionmaking rules as well. Can we close this issue?

**Comment by michaelchampion** [comment]
Closing for lack of support, and the AB/TAG seem convinced  the Council mechanism can work.  We shall see.
