### ISSUE TITLE
Increase size of the TAG?

### ISSUE THREAD

**Issue by cwilso** [w3c/w3process#465]
We'd mentioned this before (https://github.com/w3c/w3process/issues/190), but given that the current election has > 2x candidates standing for the number of open seats on the TAG, perhaps it's time to ask again: should we increase the size of the TAG?  Given the TAG's workmode at this point in its history, it might be easier to scale up than previously.

**Comment by mnot** [comment]
If you're going to expand the size of the TAG, it should be explicitly re-fashioned as a review board (e.g., "Specification Review and Coordination Directorate") and NOT be able to issue findings.

**Comment by dwsinger** [comment]
> If you're going to expand the size of the TAG, it should be explicitly re-fashioned as a review board (e.g., "Specification Review and Coordination Directorate") and NOT be able to issue findings.

Curious to understand what you see as the linkage between size and ability to issue findings?

**Comment by mnot** [comment]
The dynamics of a large board are well-known to be different -- including an increased tendency towards compromise. Combined with a pool of candidates that may not be very deep and the current (at least non-pandemic) requirement for a significant amount of travel, and it seems to me that this may be a recipe for issuance of dubious findings -- especially if the TAG attracts some participants who aren't as representative as they've been in the past.

**Comment by michaelchampion** [comment]
@mnot wrote
>The dynamics of a large board are well-known to be different -- including an increased tendency towards compromise.

This makes sense, but I'm not readily finding authoritative references to that fact.  Can you give us  some, Mark?

**Comment by cwilso** [comment]
@mnot "Representative" is an interesting word to use here; I think the TAG has had two primary roles in the past, and yes, I was thinking of the specification review role explicitly when I was questioning if the TAG should be expanded.  However, I would point out that the TAG is likely to have a problem with reaching consensus on Findings (that is, for global statements of value like the Design Principles) in the near future anyway.  We have a related issue (https://github.com/w3c/AB-memberonly/issues/35) on whether the TAG can produce REC-track documents, and how; that probably has bearing in this as well.

**Comment by michaelchampion** [comment]
I'm hoping @mnot means "representative of the kinds of people elected to the TAG over the last 10 years", that is, people with deep expertise in the web platform and its architectural principles."

**Comment by mnot** [comment]
@michaelchampion correct, apologies for the ambiguity.

@cwilso I found some pretty easily, e.g., Shijun Cheng, "Board size and the variability of corporate performance" [2008] 87(1) _Journal of Financial Times_.

The conclusion there -- that 'it takes more compromises for a larger board to reach consensus, and consequently, decisions of larger boards are less extreme' -- might be comforting at first, but I strongly suspect (based on experience in several standards bodies) that the opposite outcome might eventuate, because of exhaustion and/or inattention of some board members. E.g., it's easier to let someone publish a finding that you might not agree with, if it lets you do other work that would otherwise be blocked by that discussion. I.e., the compromise is in _quality_.

**Comment by frivoal** [comment]
> it takes more compromises for a larger board to reach consensus, and consequently, decisions of larger boards are less extreme

I don't seem that as saying that large board compromise more, but that they would need to compromise more in order to decide. It may very well be that that they don't decide as much because they fail to reach acceptable compromise.

**Comment by dwsinger** [comment]
Needs TAG input (including TAG alums) please @plinss @torgo

**Comment by darobin** [comment]
My primary concern with expanding the TAG based on the recent number of candidates is that that's something that will likely change again at some point. And it's best to avoid candidates getting in by default, just because there's room.

One way to address this is to have optional extra slots and to use both STV and approval voting. Candidates are ranked as per usual; those who match the extra slots only get in if they have an approval vote above a given threshold.

More generally, is the goal here to address the fact that there is more work than the TAG can carry out? If so, I wonder if that wouldn't be best approached by keeping the TAG as is, being a group that can issue Findings/Statements, but supplement it with an Architecture Review Group that is the TAG+participants nominated by members, and that's the group that does reviews. The TAG would retain decision power over what goes into a review, so that we don't get people playing stupid games. I think there'd be enough lost souls willing to contribute time to that (and who might otherwise have no interest in seeking election).

— What's the next step?
— Send it to the AaaaaaaaGH…

**Comment by cwilso** [comment]
Re-pinging this issue, and bringing it to the attention of the TAG.

**Comment by michaelchampion** [comment]
@darobin makes some good points:
- " it's best to avoid candidates getting in by default, just because there's room."  Right.  And with Meek STV, extra open seats will not only make room, but will lower the threshold to win in the first round, so some could get elected with minimal support from the AC as a whole.
- "the extra slots only get in if they have an approval vote above a given threshold." Makes sense, although at the cost of complexity.  Hmmm.
- "I think there'd be enough lost souls willing to contribute time to that (and who might otherwise have no interest in seeking election)."  This is something I've wanted for both the AB and TAG: There are people out there who are willing to do the work but don't want to run in an election to get "power" or commit to be available for all the duties. It would be good to find a way to include such people so long as they are qualified, aligned with the values the elected bodies are supposed to promote, and actually do the work they sign up for.

**Comment by mnot** [comment]
I'd much rather see the TAG delegate its duties appropriately, finding folks who are willing to put in effort with appropriate expertise, but not requiring yet more people to step forward and make a long-term commitment for high effort. The latter filters out people that would arguably be more qualified.

**Comment by plinss** [comment]
One problem we've run into in the past is that people's employers are less willing to sponsor work they do for the TAG (and especially travel) if they're not officially affiliated with the TAG (and therefore get the recognition).

I think I'd like to see the TAG be a bit bigger, but not so large that a random slate of candidates all get elected because there are seats. That defeats the purpose of the election.

Random thoughts I've had: 
* Keep the minimum number of seats at 9, but possibly have an algorithm that adds seats during an election cycle based on the number of candidates (with some human oversight). (e.g. in this election I'd love to have 2 more seats to grant)
* Create an 'associate TAG membership' (or whatever you want to call it), where people can get 'drafted' by the TAG and receive an official position to do specific work (and get listed on the membership page, etc). Possibly unelected candidates are given first consideration since they already made the time commitment, had an AC nomination, etc.

**Comment by mnot** [comment]
The 'associate' might have legs -- in the IETF, there are 'review directorates' that help Area Directors review documents, and being on one is an indication of expertise.

**Comment by plinss** [comment]
Another thought, possibly allow a variable number of appointed seats (maybe 3-6?). So if there's an election cycle with too many well-qualified candidates (like this one), some of those that aren't elected can be appointed instead without disrupting existing members.

**Comment by michaelchampion** [comment]
> Create an 'associate TAG membership' (or whatever you want to call it), where people can get 'drafted' by the TAG and receive an official position to do specific work 
+1
I've long thought the TAG and AB need a ["farm system](https://www.mlb.com/news/the-mlb-farm-system-explained)" (sorry for the US-centric metaphor) to help people ramp up to do the work these bodies do and to give the AC visibility into their abilities.

**Comment by darobin** [comment]
I'm not a huge fan of @plinss's pool of appointed seats for those who can't get elected. It puts several people in bad situations. For someone who loses, it can be disappointing enough not to win an election, but now the TAG chairs have gone and nominated two of the other losers but not you. Not only are you less popular (which could happen for various reasons) but your peers don't consider you competent. And all of this is publicly documented in front of the community you belong to. That sucks. For the TAG chairs, who understand this dynamic, it's not great either. No one wants to make people miserable. Losing candidates might be sort of okay, or just sort of unknown quantities — why no err on the side of inclusion not to hurt their feelings? Not that I ever want to be a TAG chair but if I were I wouldn't want to have to make that kind of call.

I kind of like the model that we used for the Privacy Task Force: the TAG, as a legitimately elected body, chose to delegate work on a specific document to a small group of people who it considered competent on the topic. We could use the (other) @plinss idea of an associate membership that is topic-specific, eg. "TAG Associate for Privacy". It's a recognition of competence but one that might be circumscribed to a subfield of Web architecture, which I find interesting. It means that you could, say, have a "TAG Associate on Content Moderation" who's a free speech scholar without implying that they are competent at web technology.

**Comment by michaelchampion** [comment]
> I'm not a huge fan of @plinss's pool of appointed seats for those who can't get elected.

There's a few distinct categories of people here:
1. Those who are well qualified for the TAG but didn't get as many high ranked votes as others
1. Those who are well qualified for the TAG but don't have the time / energy to do everything a TAG member is expected to do (FO Councils, travel to meetings, whatever)
1. Those who have potential to be good TAG members but need experience, mentoring to broaden their current zone of expertise
1. Those who think they deserve to be TAG members but the electorate disagrees 

I agree with @darobin that that category 4 is not a great pool of people to draw on, but the categories 1 and 2 are untapped resources.  And category 3 needs some way to be cultivated for the future.

> @plinss idea of an associate membership that is topic-specific, 

Agree, that seems like the best way forward for now

**Comment by fantasai** [comment]
The AB resolved:

> RESOLUTION: The AB supports the addition of 2 elected seats to the TAG, but prefers deferring any increase to appointed seats until after we have some experience with the updated appointment process.
