### ISSUE TITLE
TAG nomination and election period are at poor times of the year

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#487]
The TAG election currently spans New Year, which is problematic for many people, and Christmas, which is a problem for western nations. And the nomination period currently spans Thanksgiving, which is a problem for the USA. We need better timing.

I realize that the TAG and AB are deliberately half-year offset, with the TAG starting in Feb and the AB in July:

> Regular TAG terms begin on 1 February and end on 31 January.

Perhaps we could move to April and September (though that would mean summer nominations for the AB). Failing that, how about running the TAG elections so that they close before Christmas, i.e. back it all up a bit? The process doesn't actually mandate how much in advance of the term start, the elections are.

**Comment by frivoal** [comment]
We don't seem to have a problem getting nominations, and I don't believe the number of votes to be significantly lower than that of the AB, so from those points of view, the admittedly unpleasant calendar doesn't seem to be causing actual problems.

However, I suspect that this is a very rough time to be running an election campaign, and that for example, people who have family obligations may be at a systemic disadvantage during this period. So yes, it could be nice to find something better.

Having terms start in April would likely mean that depending on the year, the corresponding nomination / election period is likely to clash with the Chinese new year, so I am not sure how much of an improvement that would be. I suspect backing up the election so that it closes before Christmas is more effective (and less disruptive of the rest of the cycle).

**Comment by jeffjaffe** [comment]
@dwsinger thanks for raising this issue.  I've felt this for a long time; addressing this is long overdue.

**Comment by TzviyaSiegman** [comment]
+1 to @dwsinger. I recall mentioning this last year or the year before when I learned that the number of votes in the TAG election was about half the number of votes as in the AB election. Another possibility is having the AB and TAG elections at the same time because the two bodies do limited work together.

**Comment by bkardell** [comment]
+1 - I've mentioned this before.  Even if turnout remains somehow comparable, it feels unnecessarily stressful to make sure that is true and that ACs have time in between holidays to consume necessary information.

**Comment by jeffjaffe** [comment]
To address the TAG specific issue, I recommend that we not change the starting date of the TAG term, but we modify when we do nominations and elections.

Specifically, I propose: Open TAG nominations on the Tuesday nearest to October 10th and close nominations four weeks later.  We then open elections on the following Tuesday and close elections 4 weeks later.  This 9 week period will take place between 7-13 October and 9-15 December depending on the year.  US Thanksgiving will be in the middle of the election - but not at the very end of the election.  The election completes before the major December vacations.

**Comment by koalie** [comment]
Todo: make any necessary update to https://www.w3.org/2002/10/election-howto which is linked from the process doc.

**Comment by jeffjaffe** [comment]
Seeing some support for my proposal and no pushback, I took this proposal to W3M today.  W3M approved this proposal, and as @Koalie indicates above, she plans to update the "howto".  I propose closing this Process issue.

**Comment by koalie** [comment]
> Seeing some support for my proposal and no pushback, I took this proposal to W3M today. W3M approved this proposal, and as @koalie indicates above, she plans to update the "howto". I propose closing this Process issue.

I have now done so in place, right above https://www.w3.org/2002/10/election-howto.html#nominations

**Comment by koalie** [comment]
(@dwsinger or others, feel free to close this issue.)

**Comment by dwsinger** [comment]
Closing with gratitude. Thanks!
