### ISSUE TITLE
Define a role of "Alternate AC Rep" & enable them to perform AC duties when necessary

### ISSUE THREAD

**Issue by hober** [w3c/w3process#505]
Each Member organization has one AC Rep. That rep is the only person who can do a number of things, including voting on AC ballots & joining / leaving groups. But AC Reps, like any other W3C participants, go on vacation, take sick days, and are otherwise periodically unavailable for work-related tasks.

It would be fairer to AC Reps if they could each have a designated alternate or substitute for such times, so that they don't have to file ballots etc. while not at work.

(A sufficiently motivated Member organization could simulate this currently by temporarily changing AC Reps to the alternate every time the normal AC Rep is out, but that requires a level of coordination amongst the two of them and the W3C Team that seems far too heavyweight and cumbersome.)

**Comment by hober** [comment]
Filed this after a conversation with @tantek and @dwsinger on this topic.

**Comment by TzviyaSiegman** [comment]
This is a great idea

**Comment by dwsinger** [comment]
I have such residual guilt feelings from when I took vacation and didn't alert my colleagues to ballots in a timely fashion, and wasn't able/willing to respond to them from the beach.

**Comment by cwilso** [comment]
Strong, STRONG +1 on this idea.  I was just discussing the same thing with someone internally this week.

**Comment by cwilso** [comment]
It seems, though, like this should be able to be handled at the sysops level - swapping out or enabling a backup responder - rather than having to detail it in the Process?

**Comment by dwsinger** [comment]
I think that the ideal would be that an alternate is permanent, and that either the AC Rep or alternate can act on any ballot. Whether the balloting system can handle that I do not know. I wondered if it was a process change, or just practice, but the process doesn't mention any idea of alternative AC Voters.

**Comment by jeffjaffe** [comment]
I support having this capability.  Anything that helps and simplifies engagement is good, and this is a terrific example.

We need to work out the details of the empowerment and then, as David says, the complexity of implementation.  Here are some example details.

- In terms of designating and empowering the backup AC rep, I assume that the primary AC rep has the authority to empower when they go on leave, and end the empowerment when they come back.
- Do both the primary and backup have posting privileges in ac-forum  (I assume yes, Section 2.1.3.1 already empowers an AC rep to request an additional person to be on ac-forum)?
- Do both primary and backup have permission to attend the semi-annual AC meeting?
- I presume that for any AC poll (e.g. charter review, PR review, MoU review) that only one of the two has the ability to Vote.  We need a mechanism to make that happen.  If a Call for Review comes out the day before the primary leaves on a month-long vacation, we need a mechanism to ensure that only the backup Votes (if indeed that is the preference of the primary).

**Comment by dwsinger** [comment]
Thx Jeff. I doubt that it needs to be time-limited. I would have cheerfully had Tess as a permanent alternate; I trust her. If you don't trust your alternate not to vote when you are around, find a better relationship, or endure the mechanics of establishing and cancelling it manually yourself.

Yes, the mechanics of the vote need a systeam check; when going to the ballot, they should see whether the other has already voted (and be able to change up to the deadline, as usual). It's not two people voting independently; it's one ballot form that they can jointly handle. That way if one votes and the other disagrees, they see that and can fight it out.

**Comment by cwilso** [comment]
I would also be fine not having this time-limited or temporary.  If the system doesn't support having one ballot form that they can jointly handle (as per David, I think that would be ideal), it would be fine to have the Primary always override the backup, as well.

**Comment by mnot** [comment]
This might be good for some companies, but for others it effectively means they'll have to find *two* people to get engaged in the W3C's administration, when they struggle to find one. So I'd suggest this be optional.

**Comment by dwsinger** [comment]
surely optional.

**Comment by fantasai** [comment]
How about we add to https://www.w3.org/2020/Process-20200915/#advisory-committee-representative the following sentence:

> The AC representative may delegate any of their rights and responsibilities to an alternate.

and then suggest that systeam handle that by allowing the AC to designate a deputy as described above?

**Comment by plehegar** [comment]
* should notifications to AC Reps (joining a Group, etc.) be sent to the alternate as well?
* can the alternate can the org to join a Group, and nominate individuals?

**Comment by wseltzer** [comment]
The notion of one representative is deeply embedded. The [W3C Member Agreement](https://www.w3.org/2009/12/Member-Agreement) says:  "The Member shall appoint one representative to serve on the Advisory Committee and to participate in the Standards Review Process." While subsequent agreements can alter or override that, we need to be careful that we're delegating the authority with legal effect (e.g., for the Patent Policy).

**Comment by frivoal** [comment]
I think that for legal reasons, we don't want the systems to be actually switching between the two people, as that could open a possibility that the "primary" AC Rep fails to get notification of something important (like an exclusion period notice), and uses that as grounds for wiggling out of responsibilities they ought to have.

Instead, if the AC Rep designates an alternate, then the systems gives equal notifications and permissions to both the primary and the alternate, and if they both end up saying something different, whoever speaks last wins, just like an AC Rep can re-respond to a WBS poll to update and replace their previous response.

If the AC Rep doesn't trust their alternate to behave properly enough for this to be acceptable, then that person should not be their alternate.

Note: The system needs to not only allow an AC Rep to designate an alternate, but also to easily remove an alternate that they had previously designated, so that designating an alternate only while you're on vacation vs designating a permanent alternate is an actual practical choice for the AC Rep.

The ability to limit the powers that are being delegated to subset of an AC Rep's powers might be a nice-to-have feature of the system, but I don't think it's necessary in general. The most likely cases where this would be useful (e.g. allow this alternate to attend the AC meeting in my place but not delegate anything else) can be handled manually.

The only thing I could imagine as an exception is the ability to join Working Groups, as that has non-revocable consequences under the Patent Policy. Maybe the system that should have an exception for that.

**Comment by TallTed** [comment]
I would strongly advise that the Alternate/Secondary be a set-and-forget role, similar to the existing (Primary) ACRep, rather than one that needs near-term attention each and every time it's needed (and done with).

Either one should be able to take ACRep actions, including RSVP to AC Meeting -- and ACRep should receive notice of and be able to over-ride Secondary's action up to final deadline on that action, just as ACRep can do today with (some of) their own actions.  So each Member still gets one vote, etc., and there's no need to delegate before every (planned) vacation, (unplanned) illness, etc.

@frivoal's point about joining WGs (or CGs or other) is relevant (and there may be similar concerns), where there should be some period within which the Primary may rescind or ratify the Secondary's action/decision, and upon expiration of which the Secondary's action/decision is automatically ratified.

Possibly there should also be an escape clause, which probably already exists regarding the ACRep, whereby the Member, through explicit action of CEO or similar level officer, may cancel/revoke the Secondary's appointment... And similarly, may promote Secondary upon ACRep's termination or departure for whatever reason.

This will not be a simple thing to set up properly, and will require significant support from W3M, but I think that investing the time and energy will be well worth doing.

**Comment by dwsinger** [comment]
I agree about the set-and-forget, but I think we should leave it to the team to work out how it works. I'm fine with the principle that the two are equal and sorting out how they work together is the member's problem, not the W3C's. If the practical way to implement it is that they act independently but the formal AC Rep overrides the alternate, fine; but I'm also fine with them having dual access to a singular vote/form.

Th establishment of an alternate can simply be a form for the primary, and revocation of the alternate can be something they both have access to.

In essence, we're looking for something simple and practical; we tend (as engineers) to want to specify everything, but I think we should try not to here....

**Comment by TallTed** [comment]
Minimum Viable Spec is my goal as well. We needn't specify every possible scenario, but trying to cover the basics of most if not all scenario classes seems worthwhile, along with some escape clause(s) to allow for handling any class(es) we fail to imagine (a la, the W3C buck ultimately stops with the Director).

**Comment by wseltzer** [comment]
I've had some conversations among the W3C team and conclude we can make this work operationally under the language @fantasai proposed [above](https://github.com/w3c/w3process/issues/505#issuecomment-797266570).

**Comment by dwsinger** [comment]
> I've had some conversations among the W3C team and conclude we can make this work operationally under the language @fantasai proposed [above](https://github.com/w3c/w3process/issues/505#issuecomment-797266570).

Great! Would this be additional, i.e. both can act on anything, or will we need to swap back and forth?

**Comment by fantasai** [comment]
I think one of the ideas we'd floated was the concept of a "list of persons who can change the AC rep assignment of this Member", which would allow anyone on that list to "take" the AC rep role and perform actions in that capacity. W3C would additionally, as a courtesy, put all of those people on all AC rep notification lists. At any given point in time, there would be only one AC rep so the role could not be shared with different tasks handled by different people, but this would handle all the "unexpected absence" cases. This would not require any Process changes. I wonder if this would not be sufficient?

My main concern with the language I proposed is that, while it gives maximum flexibility to the AC to assign tasks to coworkers, it implies that literally any such task can be delegated, which could put the Team in a difficult position. So if we want to go down that route, I wonder if we should some language that limits it to what the Team is reasonably able to coordinate.

**Comment by wseltzer** [comment]
Team thinks it would be feasible to implement as a "secondary AC rep" who can perform all the duties of the AC rep except changing them. This would be additional: either the primary or secondary could perform any AC rep action, and in case of multiple actions, the last one controls (ideally, the interfaces will show what's already been completed and permit updates until e.g. the closing date of a poll). 

If organizations want to impose additional constraints, they can do so internally with guidance to their reps, without tooling changes.

**Comment by dwsinger** [comment]
@wseltzer sounds great. I would be fine with the short sentence in the process itself, I think.

**Comment by frivoal** [comment]
I think this sounds good, and I like the short sentence as well.

Just one clarification: can someone (possibly @wseltzer ) put their lawyer hat on, and confirm that this arrangement is robust, even in the face of irreversible actions from the secondary AC rep? Specifically, if the secondary AC rep causes their company to join a working group, and later the primary AC rep notices, disagrees, and backs out of that working group, there should be no ambiguity that this company did join, and then leave, the WG, with all the patent policy consequences that joining and leaving a WG normally implies.

I think the answer should be that yes, this is exactly the same as if the primary AC rep did join and then leave (and if you don't trust your colleague on such things, don't appoint them as your deputy), but I'd like an opinion not about how things should be, but whether existing contracts (member agreements, etc) support that interpretation. Ambiguity on this point would be problematic.

(The opposite situation, i.e. irreversible lack of action, such as forgetting to respond to an exclusion notice when you wanted to, seems a non issue as long as we do not deprive the primary AC Rep from the ability to perform this action or from receiving the relevant notices, which we're not proposing to do here)

**Comment by dwsinger** [comment]
from Wendy: 
Proposed implementation:
An organization's AC Rep may designate an Alternate AC Rep, which designation persists until the AC Rep changes or revokes it. Any other action the AC Rep is entitled to take (e.g. responding to AC reviews, voting in elections, joining a group, approving participation requests) may be completed by the AC Rep or Alternate, and binds the organization to the same extent as if the AC Rep had acted. In the event of multiple responses to a request for organizational input, the last response before deadline controls. (Ideally, a shared dashboard helps them coordinate.)

Alternates receive the same email notifications and list subscriptions as AC Reps, and may attend meetings and calls. All participants are asked to ensure that people know "with which hat" they are speaking when commenting, and to avoid overwhelming message frequency.

Questions on the implementation:

* Should the number of alternates be a maximum of 1?
* Should alternates and AC Reps both be able to speak on ac-forum, or only one in a given timeframe?
* Should team communicate by default with both AC Rep and Alternate when reaching out to a member?

**Comment by dwsinger** [comment]
question:

* will the alternate(s) and primary be able to see when someone has responded, and how?
* 
answers:

* yes, I think so, because of the representation and involvement, max P+A
* I think we ask them to coordinate, and surely not disagree with each; but it's an ask
* yes, formal AC communications should always include both; that's part of the point

**Comment by jeffjaffe** [comment]
> Questions on the implementation:
> 
>     * Should the number of alternates be a maximum of 1?

I recommend that we start with a maximum of 1 to keep it simple initially.  One is already infinitely better than zero.  If after having one alternate we discover that there are use cases for more, we can address that in the future.

> 
>     * Should alternates and AC Reps both be able to speak on ac-forum, or only one in a given timeframe?

I recommend that both be able to speak.  Some ac-forum conversations are long lasting.  We can get into some pretty stilted conversations if an AC rep passes formal responsibility to the alternate, and can no longer participate in a discussion they started.
