### ISSUE TITLE
Proposed changes to TAG makeup

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#52]
A proposed set of changes to the makeup of the TAG, as part of #4 

* Be explicit that the chair(s) does not need to be a member of the TAG
* Suggest that the Director nominate appointees **after** the TAG election, rather than before
* Add one elected member to the TAG

This suggestion will be reviewed by the TAG at its July 2017 face to face meeting.

**Comment by dwsinger** [comment]
following TAG and AB review, change 2.4.1 to read: 

The TAG consists of the following participants:
•	The Director himself, an ex-officio member of the TAG; the permission to delegate in clause 2.2 does not apply to this position, but it may be filled by an Acting Director;
•	Tim Berners-Lee, a life member of the TAG;
•	Three TAG participants appointed by the Director. Appointees are not required to be on the W3C Team or from member companies, but may be W3C Fellows or Individual Experts;
•	Six TAG participants elected by the W3C Advisory Committee following the AB/TAG nomination and election process.
The Chair is appointed by the Team, and is required to be from one of the above groups. The TAG also has a Team Contact, as required by <<5.1>>, who is not a formal member of the TAG.

With the exception of the Director and Tim Berners-Lee, the terms of all TAG participants are for two years. Terms are staggered so that each year, three elected terms, and either one or two appointed terms expire. If an individual is appointed or elected to fill an incomplete term, that individual's term ends at the normal expiration date of that term. Regular TAG terms begin on 1 February and end on 31 January.
The Director should announce appointments no later than the start of the term of the seat they are filling, and may announce appointments after the election.

insert into 2.3.1, to match:

The AB also has a Team Contact, as required by <<5.1>>, who is not a formal member of the AB.

**Comment by chaals** [comment]
> The Chair is appointed by the Team, and is required to be from one of the above groups

You mean 
> and is **not** required ...

right?

That is the proposal I recall from all of the discussion.

**Comment by dwsinger** [comment]
No.  The TAG was quite insistent that the Chair must be someone who's qualified; they don't want a person selected from the outside. This was their most significant and strongest pushback. They insist that the Chair be appointed from the body that is selected.
