### ISSUE TITLE
Grace period for attending meetings

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#527]
https://www.w3.org/2003/12/22-pp-faq#start

> Individuals who were in good standing before that Call for Participation may attend any meetings held within forty-five (45) days of the Call for Participation even if they have not yet formally rejoined the group (i.e., committed to the terms of the charter and patent policy).

It's been suggested that this paragraph or something roughly equivalent should move to the Process.

**Comment by wseltzer** [comment]
To @dwsinger , this 45-day window is in the Patent Policy FAQ, but we (PSIG discussants) thought it belonged in the Process instead, as the FAQ shouldn't be the source of normative guidance.

**Comment by dwsinger** [comment]
Perfect, I agree, so this L G T M!

**Comment by frivoal** [comment]
I suggest not doing this at the tail end of P2021. Based on the mail which starts this, this has been open since 2005, so it's hard to argue we're in a rush.

While I agree this text doesn't belong in an FAQ, I think there's more thinking needed before we make it normative. What happens to the contributions made by people who participate during that 45 day window where they haven't yet joined, especially if they don't end up joining? Or are they to be treated as guests (See https://www.w3.org/2020/Process-20200915/#GeneralMeetings) and can merely observe, until they rejoin?

I suspect these questions are solvable, but I don't think they are trivial enough to be handled in a couple of minutes in a call where we're trying to sign off on the Process, so I'd suggest removing (for now) the agenda+, and deal with it (early) in the 2022 cycle, rather than right now.

**Comment by chaals** [comment]
There is no concept of "good standing" in the process document, and not a single currently active WG charter mentions it (I checked them all).

There is a concept of participant - someone whose AC rep (themselves, if they are an invited expert) has committed to abide by the patent policy. These are tracked so it's easy to base something on it.

There is a bigger issue, which has come up repeatedly: The Patent Policy is unclear whether a rechartered group is the same as the initial group - because the apparent assumption when it was written was that a group would write a specification and close. That was demonstrably not true at the time, and has become less true since then, but history is hard to change. 

So I think the important question is what exclusion rights and licensing obligations does someone have if they were in a group, it recharters and continues work on a specification, and they leave.

Having an answer clearer than "what the court says if someone actually tests it" seems to require sorting out the issue of a continuing group properly.

**Comment by dwsinger** [comment]
While I appreciate Florian's concerns, I think an argument could be made that this is simply documenting what is long-standing practice. But also, as he says, it's hardly a crisis.

**Comment by wseltzer** [comment]
It came to our attention now in revising the Patent Policy FAQs to meet Patent Policy 2020. PSIG would prefer to move the grace period where it makes more sense.

**Comment by frivoal** [comment]
Closing, as #531 was just merged.
