### ISSUE TITLE
W3C Statement Comment from APA Chairs

### ISSUE THREAD

**Issue by JaninaSajka** [w3c/w3process#535]
The Co-Chairs of the Accessible Platform Architectures (APA) Working Group support the proposal to establish a mechanism to elevate some W3C Working Group Notes to a status that puts the entire W3Con record in support of that document:

https://www.w3.org/Consortium/Process/Drafts/#memo

We suggest providing clear rationale for what content should become a working group note, as opposed to a W3C "Statement" in addition to clarifying the process for each.

Frankly, we would prefer to extend  the existing W3C Notes definitions instead of introducing an entirely new "Statements" category  ... Introducing a third TR category is likely to create more rather than less confusion for the public who are not closely aware of W3C processes. We suggest resurrecting the "W3C Note" variant to indicate that Notes have been reviewed and approved. It would be important to clarify the difference in the Note masthead, in a manner that would be easily seen. Taking that opportunity to redesign the Note boilerplate to make Notes more clearly different from Recomendations would help further reduce potential confusion.

We further advise:

* All potential Notes be first published as Draft Notes for no less than 30 days to provide a reasonable time frame for horizontal (and general) review. We should always leverage organization strengths, and horizontal review is one distinguishing value of the W3C brand. The "Draft Note" status would be an appropriate time for horizontal review regardless of whether the
content is destined to be a working group note, or a W3C publication, though horizontal review is especially critical in the latter instance.

* The current github-based checkoff mechanism for horizontal review could be used to ascertain sign-off by horizontal review groups before a Note is published. We've found it to be an effective tracking mechanism.

* Groups should be advised to expect that it may be relevant to include horizontal review guidance, e.g. an "Accessibility Considerations" section (where relevant).
 
Janina Sajka & Becky Gibson, CoChairs
APA

**Comment by dwsinger** [comment]
Hi Janina

I think there may be some misunderstanding here. Notes are already defined as the output of a WG. So what you are asking for — that we use the existing Note mechanism — is what we're doing. However, the question came up what we should call a Note that gets W3C approval, and we felt that causing it Note might cause confusion with WG Notes. We had a long debate over the name, wanting something clear but generic, and Statement for the name of a WG elevated to W3C status was our best so far. We're open to better!

We also agree that we have an urgent need for better branding of works in progress vs. completed, consensus documents of a working group (WDs) vs. other people's drafts, Notes vs. WDs, and Statements vs. Recommendations. That work is under way (but not a process question).

**Comment by JaninaSajka** [comment]
Thanks, David. Perhaps I should prioritize APA's concerns? Because the actual naming is secondary for APA. Our process concern, applicable both for working group Notes and W3C statements, is that all such publications be published at least once as a draft. That's when we would expect to follow up on any horizontal review concerns, and we would expect to use the fairly new [Horizontal Review Dashboard](https://w3c.github.io/horizontal-issue-tracker/?repo=w3c/a11y-review) to do so. This dashboard has made us more efficient, and we'd like to deliver that to notes.

This is our top priority because we've been burned in the past with documents suddenly showing up as working group Notes with no previous (or no recent) publication cycle that could alert us.

Our second concern is that it be made clear that the outcome of a horizontal review may take several forms including the inclusion of an "Accessibility Considerations" section from APA, and/or similar from the other horizontal review groups should they deem that important.

These two are very important to us. Hopefully they make sense for the, but please advise if I should explain further. Let me close by saying we're very much in favor of the proposed W3C Statement (whatever it's called), and we'd like to see working group Notes tightened up at the same time.

**Comment by dwsinger** [comment]
Hi, thanks, my apologies for misunderstanding.

In this revision of the process, we didn't change the definition of Notes (except for saying that drafts of Notes are different from Working Drafts of Recommendations, so they are on clean separate tracks). 

We suspect that some Notes would have benefited from horizontal review as as result, because they were trying to have more status than 'just a working group product'; but Note was the end of the track. Now with Statements — which do get HR — we hope that documents that intend to have broader, community, status, will become statements and get HR. 

We're willing to look at the question of whether HR is needed for a WG to publish their own Note, but we don't think it's related to what we did this year — add Statements as a possible destination for Notes — and would rather not delay, therefore, to address it. It's possible it becomes less of an issue as Notes with status transition to Statements that get HR, as well.

So, we suggest an issue stays open on whether HR is needed to publish a WG note, or similar. Would you like to file a new issue, or should we rename this one, as we'd like the issue title to indicate what the question is?

**Comment by brewerj** [comment]
There is a related issue potentially needing attention. In further examining the proposed addition of a W3C Statement, and wanting to ensure that potential W3C Statements would receive wide review that includes horizontal reviews, we noted that the section describing "wide review" is loosely defined. So while the new W3C Statements would require wide review, it's unclear what wide review requires, as opposed to simply suggests.

The "[wide review](https://www.w3.org/Consortium/Process/Drafts/#dfn-wide-review)" section was added several years ago when the process was more experimental, and it probably made sense at that time that it was loosely defined. But wide review has since matured, and especially the horizontal review process has been systematized. 

This could be better reflected by updating the description of "wide review" by either changing the emphasis in "wide review" from 
"....the Director will consider who has been explicitly offered a reasonable opportunity to review the document..." 
to the following, or perhaps adding an additional phrase clarifying that...
"... Groups are [required | expected] to have used the horizontal review process, as part of wide review..."

If brief word-smithing could clarify this expectation for this update to the Process Document, great. If it needs more word-smithing, or if the whole section needs tightening, that would presumably need to wait till next round. 
Thanks for considering...

**Comment by dwsinger** [comment]
Hi Judy, we had a long discussion of Wide Review in #130 (now closed, with the filer's consent). However, you are not the first to ask whether there are still questions in there. We hoped that /Guide was a good place to explain wide — including horizontal — review, but perhaps more could be said in the process.

I think a small update along the lines of what you suggest might well be possible, but general changes to W/H review would be a major task for a future update.

**Comment by plehegar** [comment]
Note that the Director do expect horizontal reviews nowadays. See for example https://github.com/w3c/transitions/issues/338#issuecomment-850636248

**Comment by brewerj** [comment]
Hi David, thanks for your consideration on this. I think a small update, clarifying the _expectation_ that horizontal review should be part of wide review, would better match the current reality of W3C Process for wide review now. Therefore, a small update to the Process document, rather than simply in the Guide, would indeed be welcome.

I agree that in next year's Process update, a more substantial review of the wide review section would be in order.

**Comment by frivoal** [comment]
Landed #541 to address this. Closing.
