### ISSUE TITLE
Allow Chairs to suspend an individual temporarily

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#592]
The current [guidelines to suspend or remove participants from groups](https://www.w3.org/Guide/process/banning.html) require the Chairs to send a request to the CEO in order to suspend a participant from the group. The CEO may, after a few steps, temporarily or permanently suspend participation. As such, it may take a few days for the CEO to investigate the situation, allowing the disruptive participant to continue the improper behavior in the meantime. In light of current potential rapid escalation via social media, it would be beneficial to allow the Chairs, in consultation with the team contact, to take temporary measures, before the situation might escalate to a level that requires far more work to recover from. The temporary suspension may be limited in time, such as for 72 hours, and should involve informing the CEO.

Fyi, the current guidelines were established following #312 .

cc @brewerj

**Comment by cwilso** [comment]
(I think you meant "temporarily" in the title, but +1, absolutely)

**Comment by frivoal** [comment]
I support this.

Do you think this needs clarification in the Process, or are guidelines enough?

**Comment by plehegar** [comment]
Since the current practices are guidelines, I don't think a change in the Process is needed. Since the guidelines were drafted by the CG, I brought the issue here instead of [w3c/guide](https://github.com/w3c/Guide/issues).

**Comment by dwsinger** [comment]
I think this is operational and I agree, you should adjust the guidelines to say something like a chair (or team contact?) can temporarily suspend someone (for a maximum of X days) if needed. Do you need Process CG formal endorsement?

**Comment by chaals** [comment]
No, you don't need Process CG formal endorsement (in part because that has no standing anyway). Given the current policy we need the CEO to formally delegate some power of immediate suspension to all chairs, presumably with some time limits including when the CEO will review the situation.

**Comment by michael-n-cooper** [comment]
Regarding the amount of time to get the attention of and response from the CEO, I think 72 hours is insufficient, especially as hour-counted durations generally include weekends and holidays. I suggest indicating 3 business days as the target but allowing for a longer time, perhaps 5 business days. We also would need a delegation procedure for when the CEO is unavailable in the target time.

**Comment by brewerj** [comment]
+1 to 3 business days as a clarified target, but with some discretion for circumstances such as a substantial holiday outage or CEO unavailability.

**Comment by plehegar** [comment]
Proposed wording (modulo time duration):
[[
* To avoid potential rapid escalation of unacceptable behavior, a W3C 
group chair  with the agreement of a team contact, for up to 72 hours, a 
participant from a single group after alerting the CEO (and the Member's
Advisory Committee representative when applicable). Any subsequent 
suspension would need to be requested from the CEO.
]]

**Comment by nigelmegitt** [comment]
On reflection, I realise I thought that Chairs _already_ have the authority to exclude group members temporarily - it seems that changes made over the past couple of years have made that harder to do.

@plehegar I'm not sure where you intend to place that bullet in the current page? If it is a standalone numbered bullet then the wording seems to miss something important, namely suspension itself. Perhaps you meant something like:

[[
* In urgent cases when further unacceptable behaviour seems likely, a Chair of a W3C Group may, with the agreement of a team contact, temporarily suspend a participant for up to 72 hours from the Group for up to 72 hours after alerting the CEO (and the Member's Advisory Committee representative when applicable). Any subsequent suspension would need to be requested from the CEO.
]]

Or perhaps this is an additional point within item 3?

Regardless, there are a few things to get straight:

* What happens if one Chair and team contact agree, but another Chair of the same group disagrees? Does the group of Chairs plus team contacts need to establish consensus regarding the suspension?
* If the temporary suspension expires how/when is the incident considered closed? Does the requirement to request a subsequent suspension from the CEO last forever?
* Is it enough merely to send the CEO a message, or does confirmation of receipt need to be received?
* When is it (not) applicable to alert the Member's AC rep?

**Comment by jeffjaffe** [comment]
@plehegar I think you meant s/for up to 72 hours, a participant/may temporarily suspend a participant for up to 72 hours/

**Comment by TallTed** [comment]
A bit of copy/paste error, I think...

> temporarily suspend a participant for up to 72 hours from the Group for up to 72 hours after alerting

-- should likely be --

> temporarily suspend a participant from the Group for up to 72 hours after alerting

-- and, flowing from the conversation above, *that* should likely change to --

> temporarily suspend a participant from the Group for up to three business days after alerting

**Comment by rachaelbradley** [comment]
Should we add a sentence that says something along the lines of, if a member is temporarily suspended, the CEO will formally make a decision and notify the individual, chairs, and staff contact of that decision by the end of the temporary suspension period?

**Comment by plehegar** [comment]
Thank you @nigelmegitt for the feedback. Changes were done as part of w3c/Guide#160 .

> Or perhaps this is an additional point within item 3?

It was intended as such.

> Regardless, there are a few things to get straight:
> 
> * What happens if one Chair and team contact agree, but another Chair of the same group disagrees? Does the group of Chairs plus team contacts need to establish consensus regarding the suspension?

There is always an expectation of consensus indeed. The PR makes it clear that the Chairs/TCs can go to the CEO to resolve differences/get a decision if needed.

> * If the temporary suspension expires how/when is the incident considered closed? Does the requirement to request a subsequent suspension from the CEO last forever?

I'm proposing a 6 months reset.

> * Is it enough merely to send the CEO a message, or does confirmation of receipt need to be received?

The wording says "alerting the CEO". We thought it was clear enough to indicate that no RSVP is expected from the CEO. Ie, it's up to the Chairs/TCs to figure out what comes first, the suspension or the alert. The emphasis was on taking prompt actions.

> * When is it (not) applicable to alert the Member's AC rep?

I changed that to say "if the participant is not an IE"

**Comment by plehegar** [comment]
> Should we add a sentence that says something along the lines of, if a member is temporarily suspended, the CEO will formally make a decision and notify the individual, chairs, and staff contact of that decision by the end of the temporary suspension period?

I'm not keen in forcing the CEO to make a final decision within a certain time frame. It's up to the CEO to extend the temporary suspension if it's going to take longer imho.

**Comment by plehegar** [comment]
> +1 to 3 business days as a clarified target, but with some discretion for circumstances such as a substantial holiday outage or CEO unavailability.

I used 5 business days at the end. I wasn't keen on trying to come up with exceptions since we can't be exhaustive. If this is a concern, I would encourage the Director to delegate additional authority to the COO if needed.

**Comment by plehegar** [comment]
For proposed changes, see w3c/Guide#160 .

**Comment by brewerj** [comment]
Commenting here that I believe that this is important to move ahead with these planned improvements, even though it appears likely that further refinements may be needed.

**Comment by frivoal** [comment]
As far as I can tell, all expected improvements fall into the guide. Can we close this issue for the Process part of the question, or is something extra needed here?

**Comment by frivoal** [comment]
We've already landed in the draft process the fact that disciplinary action would move from the Director to the CEO. That was https://github.com/w3c/w3process/pull/558. The guide will still need to do some interpretation of how the CEO rather than the director delegates some of their power, but I am not sure that there's more for the process itself to say.

I think open github issues are good for actionable problems, or at least identified issues, but I am less convinced of their effectiveness to merely note "this is an interesting topic, think about it again some day". Too many of those crowd out the actionable ones, and we get lost in the mass.

**Comment by jeffjaffe** [comment]
Thanks, Florian.  I had forgotten about #558.  Yes, I agree we can close this and move the current issues to the guide.
