### ISSUE TITLE
What is and can be Member-Confidential

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#601]
Right now, the only mention in the Process document regarding how something becomes Member-Confidential is [as part of a WG charter](https://www.w3.org/2021/Process-20211102/#confidentiality-levels) -- and that is only an example, implying that there might be other ways something can be deemed as such.

The Process should give clearer guidelines about what is and is not (and cannot) be made Member-Confidential. Right now, it's vague enough that the Team could deem _any_ informational as such, which can harm transparency to those who are not Members. As discussed on the ac forum, it's important that the organisation be transparent to the "outside world" to bolster our legitimacy. 

While we could address this by documenting what's been historically confidential (e.g., finances, ac discussion, FO handling), it would be good if we stepped back and consider what our goals are here and how they are best served. Other organisations like the IETF are transparent on these matters and enjoy more legitimacy in many eyes as a result.

As a starting point, I propose that:

* Team personnel matters are always Member-confidential (if they are even that open)
* W3C finances and governance matters are Public by default
* FO handling is Public (respecting any bars we set for anonymity, etc.) by default
* Proposed or actual classification of anything as Member-confidential (except for personnel matters) can have a FO placed against it (that FO will be considered Member-confidential until it is sustained)

**Comment by frivoal** [comment]
My understanding of how we currently operate is that the level of confidentiality of information is determined by where it is first shared. For information that originates from yourself, you can of course do what you want with it. Otherwise, various meetings, mailing lists, etc, have distinct confidentiality levels, and unless explicitly stated otherwise by the person who shared that information (or later reclassified by the Team), people should assume that information cannot be disclosed to a broader audience.

I don't think we need to change this for information that originates from everybody other than the team. People don't have to share anything, and if they do, we need to respect their expectations about confidentiality.


For information that is shared by the Team, it may be useful to set guidelines about what should be shared at what level, and even if we don't the idea of filing FOs (or some similar mechanism) against the wrong confidentiality level feels like an interesting idea.

For elected bodies like the TAG and AB, it's interesting. They are performing in an somewhat official capacity, and are responsible towards their electorate, transparency is good, and explicit guidelines can help with that. But being able to use FOs to force open some information or opinion that was initially shared (by volunteers) under an expectation of confidentiality feels very wrong, and seems more likely to result in silencing people than in gaining public insights.

For guidelines on what should be shared at what level, that's interesting, but I also suspect that it could quickly grow very complex, especially if we mean them as enforceable rules. For instance:
* Yearly audited financial statements being public is a good thing. Quarterly ones too. Not-yet-audited ones maybe. Some occasional deliberate announcements as well. But anything related to finances having to be public is not practical or desirable. Otherwise, every salary would have to be public, every invoice, every belated payment… This would be a massive privacy violation. No organization behaves like that. I am sure that's not what you meant, but we cannot just say "finances must be public". We need to be clear on what it is about finances that must be public.
* Same thing about Governance. There are a number of things about governance that are good to have in public. But everything said in or about a board meeting, by or about the CEO/CFO/Counsel is arguably governance. Not all of that can be public.

FO handling is an interesting topic on its own. I think the decision about an FO being public is a good thing, and it should be accompanied with a detailed rationale explaining why the FO deciding body made that particular decision. Historical decisions by the Director have been in my opinion under-documented, and I'd expect significantly more. However, I think that the discussions leading to the FO are likely better if held confidential, for mainly two reasons:
  1. FOs are to a varying degree conflictual situations. Tied to conflictual situations, there may be varying degrees of power differential, and confidentiality occasionally allows getting some information you wouldn't get if everything had to be public. "I wouldn't say that to their face because that would likely compromise my relationship with them, but **** is pushing for something very problematic and here's why". Some of the time you can anonymize such things by just redacting the name of the person who shared it. Some of the time they'd be identifiable anyway. If you do end up finding the claim legitimate and want to act on it, you'll have to find a way to make it sharable, if only to provide an opportunity for response, and certainly if that ends up being part of your rationale for the final decision. But if _everything_ has to be public, you may not even hear about it.
  2. Except for things like the previous point, I don't think that the FO deciding body's deliberations are inherently confidential, and this is why I think the decision AND the reasoning behind it must be disclosed. But even if the substance of the deliberations of the FO deciding body probably don't call for confidentiality, I think their form does. Things to be phrased with a very different degree of care when they will be heard by 20 people or 20 000 people. Especially when it comes to conflictual topics, a broad audience requires very deliberate phrasing, being very careful about making everything explicit and not relying on common knowledge shared by the other people in the room. You need to spell everything out and weight your words. I suspect that the degree of care and formalism that would be required to make the deliberations (again, not the conclusions, I support those being public) of an FO deciding body would at least slow it down significantly, and possibly prevent reaching consensus altogether, due to excessive formalism getting in the way of discussion and debate. Or maybe the actual discussion would end up happening outside of the official venue, privately among members who have a good preexisting relationship, but that would be exclusionary, without gaining us any actual transparency.

**Comment by dwsinger** [comment]
Florian's analysis is good. A general guideline to err on the side of caution when people are involved is good. For FOs, we currently let the objector be as confidential as they wish, up to and including team-confidential (which makes running a council rather tricky). I suspect that the result, the decision, should have the same confidentiality as the objection: make it more private, and people who knew the objection can't see the answer, and making it more public 'outs' the objection to people who previously couldn't see it.

Perhaps FOs should always be public, or have a static well-defined confidentiality (e.g. Member-only)?
