### ISSUE TITLE
Continuity of TAG appointments

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#613]
From https://github.com/w3c/w3process/pull/611#issuecomment-1196692082:

> Further to this, we should explore the idea that appointed members put themselves forward for election during the election periods that coincide with their appointments expiring. This will encourage appointed members to go through the same process as elected members on the TAG.

During the Process CG discussions, we came up with two (non-exclusive) options:

* Asking the appointed members to stand for election.
* Limiting the number of consecutive appointed terms.

We believe the TAG and AB should discuss this at TPAC and give their recommendations to the Process CG for drafting.

**Comment by dwsinger** [comment]
It may be helpful to notice the date on [these appointments](https://lists.w3.org/Archives/Member/w3c-ac-members/2013AprJun/0026.html).

**Comment by dwsinger** [comment]
At the August F2F the sense of the AB was that there should be a limit on the number of consecutive appointed terms (probably 2), and that a person can only be appointed to a second term if they also ran for election (and did not get elected).

**Comment by frivoal** [comment]
To be confirmed when the AB minutes are published, but I was under the impression that the resolution was a little less specific than that. As you say, we did agree there should be a limit on the number of consecutive appointed terms (probably 2), but I don't think we had a firm conclusion on the second part (“and that a person can only […]”).

**Comment by dwsinger** [comment]
@frivoal I made a note that it was said and not disagreed with, but whether it was agreed with I cannot say. Probably a Discuss point.

**Comment by frivoal** [comment]
Based on the AB resolution, we're now proposing to go with this as the basis:

> The constraints for appointment to the [=TAG=] are
> the same as for elected participants
> (see [[#AB-TAG-constraints]] and [[#AB-TAG-elections]]),
> <ins>with the additional constraint that
> a person <em class=rfc2119>must not</em> be appointed
> for more than two <em>consecutive</em> terms.
> (Partial terms used to fill a vacated seat do not count towards this limit.)</ins>
> 
> <ins>Note: Individuals who have reached the limit of two consecutive appointed terms
> <em class=rfc2119>may</em> freely run for election
> if they wish to continue serving on the [=TAG=].</ins>

There was a suggestion, about which we didn't resolve either way, that for the second consecutive appointed term, people could only be appointed if they stood for election. Should we include it?

My personal take is no. If you win that election, you no longer need to be appointed, since you won. Which means that losing an election would be a precondition to being appointed a second time. I don't think that's helpful, as I don't see how a person who explicitly lost an election is more suitable than one who did not stand.

If people feel that two consecutive terms is too much, I'd rather simply limit it to a single term, than condition reappointment on losing an election.

@plinss @torgo, could you help us get some TAG feedback on that? (Note that this is separate from the question of who does the appointment. That and the rest of the Director's involvement in the TAG is tracked at https://github.com/w3c/w3process/pull/611)

@cwilso @tzviyasiegman, could you schedule this follow up question for AB discussion?

**Comment by dwsinger** [comment]
Since the specific issue #622 has been closed, copying the comment here:

Both the TAG, as represented by the [comment](https://github.com/w3c/w3process/pull/611#issuecomment-1196692082) in the pull request, and the AB in conversation, have wondered whether we should ease people from appointment into election, by requiring that they stand for election to be eligible for appointment to a second term.

Such a requirement would mean, if you wish to serve on the TAG:
* term 1: you MAY stand for election; if not elected, you CAN be appointed
* term 2: you MUST stand for election; if not elected, you CAN be appointed
* term 3: you MUST stand for election; if not elected, you CANNOT be appointed
* term 4: reset to term 1

**Comment by dwsinger** [comment]
FWIW I mildly disagree with Florian. I think the gradual move from appointed to elected is elegant, and a candidate (and the team) should notice if they aren't achieving the visibility/impact to get elected after one term, and that by making appointment permitted, we are explicitly saying that failure to get elected is not a 'black mark'.

**Comment by plinss** [comment]
&lt;disclaimer&gt;I'm well aware that I'm currently one of the longest serving TAG members ever. I'm also well aware of the irony that one of the main issues I ran on the last time I stood for election was the stagnation of the TAG at the time.&lt;/disclaimer&gt;

That said, I don't see stagnation as a current issue on the TAG, we do have a reasonable turnover during the normal election process these days and it brings in a lot of new perspectives and skills. Back in the day, almost every time an incumbent ran, they got re-elected, that doesn't happen anymore. My guess as to why that's the case is that the TAG is doing more relevant work and the AC pays more attention to the elections than it did in the past.

While stagnation is bad, there is also a benefit from having long-standing members that can carry institutional knowledge. The TAG frequently reflects on how it works and improvements that can be made in our process. We often get suggestions from newer members of things that have been tried in the past and have failed. While we re-examine why that failed and if conditions are different now, it often saves time by pointing out problems that would have otherwise been unforeseen. It's also sometimes useful when similar topics come up again and newer members aren't aware of previous work and discussion (and we can't reasonably expect every new TAG member to study the minutes of every past meeting). So having too much turnover in the TAG IMO would be as harmful as not enough. We need a balance and the current system seems to work well in that regard (at least for now).

While I understand the process of appointing TAG members is going to need to change in the director-free future, I also have concerns about forcing appointed members to stand for election. Many of the AC are (self-described) "low information" voters. My concern is that they may not appreciate the nuance of what you're trying to achieve and feel that appointed members should be given higher precedence to preserve their position, or lower precedence because they seem to not be working out in their appointed role. This could have unintended consequences in the dynamics of how elections play out. If previously appointed members get higher precedence, the TAG will lose the opportunity to gain new members with new perspectives. If they get lower precedence, it may be perceived as a vote of no-confidence and bias whoever is doing the appointments after the election. Furthermore some the the AC may feel they'd be wasting a vote on an appointed member thinking they'll just get re-appointed, so it can be difficult to impossible to gauge the feelings of the AC based on election results (unless a lot of additional polling is done in parallel). All this very much depends on the criteria that the appointments are made under as well, so I see those issues as interdependent.

I also have to ask, is the discussion of effective term limits attempting to solve an actual problem or is it being discussed on general principle? (Please don't be afraid to speak up directly if you think the problem is me, I won't freak out.) Because if there isn't an actual problem, why are we changing things?

**Comment by chaals** [comment]
On each question - should there be term limits, and should appointees be required to lose an election to be reapponted, I suggest the right answer is no.

I am uneasy about this direction in general, with reasons similar to those Peter outlines regarding term limits and Florian regarding making reappointees lose an election.

I'm all in favour of people saying to someone who appoints (or for that matter nominates) people "that person needs to sharpen up their act in such-and-such a way, IMHO, or you might want to reconsider them". I've seen that work pretty well in practice. That's very different from a term limit, and while I'm wary of the situation that appointees don't get changed because of inertia, I have seen that more than one holder of long institutional memory is valuable - in part because after a decade, people's memories of what happened differ, reasonably often in important ways.

**Comment by plinss** [comment]
I agree with @chaals, if there’s an issue with one or more appointed members, or a fear of future issues, a simple direct approach of having a conversation with the member(s), and if that fails, a conversation with those doing the appointments, can be far more effective, and less risky than making structural changes which will have side effects. (And if that member isn’t a chair, then the chair(s) should be in that loop.)

If a TAG member, appointed or elected, can’t have a reasonable conversation about their participation in the TAG, then they shouldn’t be there in the first place.

**Comment by dwsinger** [comment]
@plinss I think there is a problem, but rest assured, it's of principle, and not a comment on you (or Dan). I (and many others) have a high regard for both of you.

The AB has been working on Director-free, and of course TAG appointments is part of that. The motivation for these appointed seats is not entirely clear, but it seemed to the AB that one might well be to enable the TAG to be balanced with respect to diversity and skill sets. But if that were the case, one might reasonably expect (a) the appointments to happen after the election, in order to react to improve balance and (b) the appointments to vary over time, both because of that and to react to changing needs. This is not what's happening.

I think that there's also a concern that it's not just seats, but chairs; the ethos and style of the TAG are being set in a way that the membership has no say over today, for [nearly a decade](https://lists.w3.org/Archives/Member/w3c-ac-members/2013AprJun/0026.html) now. That troubles me, as a question of principle – nothing at all to do with the people concerned.

(Finally, I'll note that the opening message here cites a comment from a current TAG chair!)

Whether term limits are right, I am not sure. But if, after serving some number of terms, someone cannot get elected, should we really have the team nonetheless continue to appoint them?

**Comment by plehegar** [comment]
"RESOLVED: we should not require an appointee to run for election after one term"
"RESOLUTION: yes, have term limits for consecutive appoints"
"RESOLVED: term limit of 2 for appointees"
- AB - 20 October 2022

**Comment by fantasai** [comment]
Closed by AB resolution.
