### ISSUE TITLE
FO Council should not be allowed to delegate its responsibility

### ISSUE THREAD

**Issue by palemieux** [w3c/w3process#630]
The FO Council should not be allowed to delegate its responsibility, as suggested at https://www.w3.org/Consortium/Process/Drafts/director-free/#council.

This is to avoid:
- a special case in the process, e.g. voting
- the situation where after much work by the decider and/or the objector, the council delegates its responsibilities, lengthening the process and requiring incremental by both decider and/or objector.

Instead the FO should reject the FO, stating its rationale and recommending that the substance of the FO be taken up by another group, e.g. the team in the case of an HR or legal issue.

**Comment by plehegar** [comment]
If the FO is rejected, there is nothing to look at, so I'm not sure what you mean by "substance of the FO be taken up by another group". An FO is assumed to be there because other venues failed, so it's at the end of a discussion rather than in the middle of it.

The delegation option is a way for the Council to say: we're not in a position to make a decision ourselves but we know someone (or some group) who can/should. It is expected to happen in exceptional circumstances.

It's different from the Council indicating that more work is needed before they can make a decision. In such case, there would be no delegation.

**Comment by palemieux** [comment]
> If the FO is rejected, there is nothing to look at, 

An FO can be rejected by the FO council because it is out-of-scope of the FO council but in-scope of another group, e.g. the Team in case of HR or legal issues.

**Comment by plehegar** [comment]
> An FO can be rejected by the FO council because it is out-of-scope of the FO council but in-scope of another group, e.g. the Team in case of HR or legal issues.

I don't see how this is different from delegation. The FO is not overruled, but simply passed on to another party.

**Comment by dwsinger** [comment]
I don't know what you mean by "reject". There are only four possibilities I see for an FO:
* the Council sustains the objection
* the Council sustains the original decision
* the Council defers to someone else
* no decision is made, and the FO is left hanging

There are some circumstances in which the Council cannot either hear the information (anonymous FOs, FOs that concern individuals) or it would be better if the decision were made by someone, or a body, with formal standing (and insurance). That's what deferral is for.

**Comment by dwsinger** [comment]
dup of #618 , moving discussion there

**Comment by frivoal** [comment]
@palemieux, since you opened the issue and we are wrapping up this cycle, I'd like to confirm: do you agree that this issue, being about whether or not the Council can delegate its responsibility, is indeed a duplicate of https://github.com/w3c/w3process/issues/618, which was also about whether or not the Council can delegate its responsibility?

**Comment by palemieux** [comment]
The text at https://github.com/w3c/w3process/commit/017511a332880da2ff05acde9762f81efc695755 LGTM. Thanks. Good to close.
