### ISSUE TITLE
What is the CR Review Period?

### ISSUE THREAD

**Issue by gsnedders** [w3c/w3process#637]
https://www.w3.org/Consortium/Process/Drafts/#transition-pr says:

> must show that all issues raised during the [Candidate Recommendation](https://www.w3.org/Consortium/Process/Drafts/#RecsCR) review period have been [formally addressed](https://www.w3.org/Consortium/Process/Drafts/#formally-addressed)

However, I can't find a formal definition of what the CR review period actually is. Following the CR cross-reference tells me CR "[signals] to the wider community that it is time to do a final review", but nothing actually defines a period.

We know from the fact that a CR was published (presumably meaning a CR Snapshot) that the document has received wide review, so we can't be referring to that, but we must instead be referring the "final review".

We should be clear in the PR transition criteria what review we're referring to. If we want to define a CR final review period, we should define that term and cross-reference it from the PR transition criteria.

**Comment by caribouW3** [comment]
Hi Sam,
Good point!
I've always seen CR as more specific about review from implementation experience rather than features, as said in the second point of the definition at https://www.w3.org/Consortium/Process/Drafts/#RecsCR:
-   gather [implementation experience](https://www.w3.org/Consortium/Process/Drafts/#implementation-experience)

What bothers me currently is the lack of incentive for WGs to actually declare it done and move to PR. An awful lot of specs stay in CR forever, even with the ability to amend Recommendations later. I'd be inclined to support a proposal against stagnation in CR, since that is not longer a "review".
I'd also note that automatic publishing tends to give the impression that something is moving even when it's really not progressing, which is confusing people outside WGs even more.

**Comment by plehegar** [comment]
We also have in [Transitioning to Proposed Recommendation](https://www.w3.org/2021/Process-20211102/#transition-pr)
[[
* must not have made any [substantive changes](https://www.w3.org/2021/Process-20211102/#substantive-change) to the document since the most recent [Candidate Recommendation Snapshot](https://www.w3.org/2021/Process-20211102/#candidate-recommendation-snapshot), other than dropping features identified [at risk](https://www.w3.org/2021/Process-20211102/#at-risk).
]]

As such, the "final review" is the review of the latest substantive changes since the last CR Snapshot publication. And each publication of a Snapshot triggers a new review period. So, the "review period while in CR" is one or more review periods depending on the number of CR Snapshot published. I concur that the wording could be improved a bit, something along:
[[
must show that all issues raised during the review period(s) while in [Candidate Recommendation](https://www.w3.org/Consortium/Process/Drafts/#RecsCR) maturity stage have been [formally addressed](https://www.w3.org/Consortium/Process/Drafts/#formally-addressed)
]]

**Comment by dwsinger** [comment]
The charter and process define the exit criteria, I think; typically interoperable implementations of each feature, test suites (and passing them) and so on. Sometimes, indeed, we wait a long while for those to happen.

**Comment by frivoal** [comment]
In https://www.w3.org/2021/Process-20211102/#transition-cr, we have

> To publish a [Candidate Recommendation](https://www.w3.org/2021/Process-20211102/#RecsCR), in addition to meeting the [requirements for advancement](https://www.w3.org/2021/Process-20211102/#transition-reqs) a [Working Group](https://www.w3.org/2021/Process-20211102/#GroupsWG):
> […]
> *   must specify the deadline for comments, which must be at least 28 days after publication, and should be longer for complex documents

I am pretty sure this is what it's talking about. Establishing a term and cross linking does sound like a good idea.
