### ISSUE TITLE
Closing Groups

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#653]
The `director-free` branch only empowers the Team to initiate an AC review to close a group before its charter is fulfilled. Should any other party (e.g., the TAG) have this power?

First raised in #316.

**Comment by frivoal** [comment]
I'd be OK with allowing the TAG (and AB?) as well to make such proposals. In practice, I'd expect AB/TAG/Team to collaborate on such things and be roughly in alignment, and the proposal to have a hard time succeeding in AC review when they are in disagreement, but I don't think broadening the ability to propose this AC review would be a source of problems. The AC decides anyway.

**Comment by mnot** [comment]
Tend to agree re AC. There are other parts of the process that specify multiple ways to initate an action, e.g., [6.3.13.4. Process for Rescinding, Obsoleting, Superseding, Restoring a Recommendation](https://www.w3.org/Consortium/Process/Drafts/director-free/#deactivation). It'd be good to consider where alignment makes sense.

**Comment by mnot** [comment]
#660 Looks good enough for 2022. A future effort might look at aligning this with other mechanisms as per above. Thanks!

**Comment by nigelmegitt** [comment]
I don't understand what problem this is addressing: it seems premature to have an open pull request for this, and I will comment this on #660. This issue is raised as a question, and there haven't been any comments in favour or against, just one "I'd be okay". We should have more motivation for the change.

Right now, if anyone can persuade the team to open an AC review, the team can do it. The idea that other parties can initiate an AC review, without even consulting the team, seems to carry risk unnecessarily, albeit low risk practically. I'm particularly thinking about any requirements that can put different sub-sets of the W3C community at odds with each other.

For example, if Team looks after strategy and the existence of a WG fits the overall strategy, but there is for whatever reason non-alignment between AC or AB and the Team, that's a problem that needs to be addressed first, rather than allowing any of the above sub-sets to take unilateral action.

**Comment by frivoal** [comment]
Opening a PR doesn't necessarily mean it's ready for adoption. I made this just so we could be clear about what the proposal is. If we like it, it's easy to pull in, but it can just as easily be rejected altogether.

**Comment by frivoal** [comment]
Will link to the minutes once they're published, but until then, here's the relevant AB resolution on this topic:

> RESOLVED: Not only the Team, but also the AB or TAG, can propose closing a working group.

**Comment by nigelmegitt** [comment]
@frivoal many thanks for the early heads up. Was any proposal made to change the criteria for such a closure, i.e. from the two in the current Process (i.e. lack of work or early completion)?

**Comment by frivoal** [comment]
Closed by https://github.com/w3c/w3process/pull/696
