### ISSUE TITLE
“Member Consortium” vs “Member Association”—Synchronize with the Bylaws

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#666]
The [W3C Inc.'s bylaws](https://www.w3.org/2022/10/w3c-bylaws-20221019.pdf) use the term "Member Association” to define the same concept as what the Process calls [“Member Consortium”](https://www.w3.org/Consortium/Process/Drafts/#fdn-member-consortium), and reuses the same wording for their definition.

We probably don't want to drop the Process section altogether, because the Process have has rules about Member Consortia/associations that go beyond what the bylaws have to say. However:

1. We should probably use the same term for both, and align the Process to match the bylaws
2. The Process says  that when there's doubt, the CEO makes the determination. The bylaws say that it's the Board. We should make the Process match the bylaws.

We could presumably just delete the definition from the process, introduce a normative dependency to the bylaws, and refer to the definition there, but I don't think we actually want tight coupling between these two documents. Avoiding contradictions (2) and confusing terminology (1) seems more appropriate.

**Comment by jeffjaffe** [comment]
Good catch, Florian.  I agree that there are advantages to aligning the terminology.

On your point #2 (who makes the determination), I would be careful about allowing the Board make the determination - solely because we are trying to firewall the Board from the participation in the W3C Process.  One option is to allow the Board to make the determination vis-a-vis determining whether a Member Association is a Consortium Member (i.e. the interest of the bylaws) and have the CEO make the determination vis-a-vis Process requirements.  While that theoretically could lead to different rulings on who is a Member Association - it maintains the firewall.

Or, we could choose to keep the current terminology, as awkward as that sounds.

**Comment by dwsinger** [comment]
Unfortunately the C in W3C stands for Consortium.  I fear we're going to have to say that the Consortium is formally constituted as a Member Association, somewhere, as we don't want to change our short name.
