### ISSUE TITLE
Clarify AC and BoD priority when signing MoUs and similar contracts

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#670]
(splitting from #658, as this is actually a separate point)

MoUs and similar contractual relationships not necessarily named MoUs currently go through AC review, and are subject to AC appeal. I think that made full sense in the old world, but I wonder about whether this is a point of the Process stepping on the BoD's toes. We might want to think through this interaction. Giving visibility to the AC and getting input makes sense, but tying the Board's hands might not.

**Comment by jeffjaffe** [comment]
I agree that there is a tension between the role of the BoD and the role of the AC vis-a-vis MoUs.  While I agree that we should not "tie the Board's hands", we have also implied that the existence of the BoD should not deprecate the authority of the AC.

Given how busy the Board is these days, it might be fine to have this issue wait until Process 2024.

**Comment by dwsinger** [comment]
I think we need to disentangle _contractual_ relationships, where formal commitments are made, from simple statements of mutual understanding and expectation. The former are contracts and the Board should be able to be involved (but could delegate). The latter are properly memoranda of understanding and could be handled by the AC and team.

So, for example, if we agree with the Taste Consortium that they will work on the standards for defining the aspects of taste, and we will work on the standards for styling and presentation (Cascading Pasta Sheets, anyone?), that's an understanding, not a contract. Fair game for team and AC.

But a contract to fund a staff person at the Taste Consortium, that's a contract, and a Board matter.

**Comment by frivoal** [comment]
Without having that dictate what we ought to do in the future, and just for the sake of figuring out what we're dealing with, it may be informative to list what kind of things have been considered MoUs so far. Based on how the process defines it, MoU is not something lesser than contracts. It rather seems that the term is used for fairly important contracts.

Examples of things considered MoUs so far:
* the [agreement with the WHATWG](https://www.w3.org/2019/04/WHATWG-W3C-MOU)
* the [agreement through which W3C merged with IDPF](https://lists.w3.org/Archives/Member/w3c-ac-members/2016JulSep/0064.html) (or at least tried to).
* the [cooperation agreement with the Open Mobile Alliance](https://www.w3.org/2004/05/W3C-OMA-Agreement-FINAL.html)
* [MoU with COVESA (formerly GENIVI Alliance)](https://lists.w3.org/Archives/Member/w3c-ac-members/2022AprJun/0048.html)
* [MoU with Geospatial](https://lists.w3.org/Archives/Member/w3c-ac-members/2017JanMar/0047.html)
* […feel free to complete my list…]

To, these look very much like actual contracts.

**Comment by dwsinger** [comment]
Right, historically everything has been bundled under this label, from simple statements of understanding up to long-standing contractual agreements. I am saying we need to disentangle that. The Board has to be able to handle or delegate contracts; other 'understandings' can be handled in a variety of ways.

**Comment by tobie** [comment]
(1) I agree with Jeff's statement about wanting to balance AC and BoD roles. However, moving the right to enter into MoUs to either the Board or the CEO doesn't change anything about the AC's role, the AC is informed and has a right to appeal in both cases and that's it.

If there's anything to learn from the concerns expressed by the AC about the MoU process in recent history, it is that part of the membership found it surprising and somewhat unpleasant that the team could proceed with such important and visible agreements with very little say from the membership.

Moving this right to negotiate and sign MoUs to the CEO rather than to the BoD reinforces rather than alleviates this concern (let's not forget that the membership is well represented in the BoD).

(2) I also agree with David that figuring out the exact nature of MoUs isn't urgent at all. However, the Process Document can't assign to anyone the right to enter into contractual obligations on behalf of the organization, as the Bylaws specifically reserves that right to the BoD (Article X, Section 2). So until the nature of MoUs is clarified, I don't think it would be possible for the Process Document to circle around the BoD's signatory prerogative and grant those powers to the CEO.

In light of the above, my suggestion would be to either:

1. make the BoD responsible for both negotiating _and_ signing MoUs, possibly making explicit the implicit right of the BoD to delegate this to the CEO, or
2. make the CEO responsible for _negotiating_ MoUs, and leave the BoD responsible for _signing_ them.

**Comment by dwsinger** [comment]
I think we will need to address the question of whether the AC Review of a contract is definitive, either way. If a contract is proposed, and the AC says one thing, can the Board go the other way? I suspect that the answer is yes: the AC may be fine with a contract, but the Board determines it has legal or financial issues that can't be resolved; conversely the AC may not like a contract, but the Board may determine it's the best course of action from a set of unappealing alternatives.

However, I continue to argue we should distinguish contracts from simple statements of mutual understanding.

**Comment by tobie** [comment]
> However, I continue to argue we should distinguish contracts from simple statements of mutual understanding.

My understanding is that under US law, contractual language is what creates a contract (and would thus require BoD approval). Determining whether something contains contractual language would be the work of a lawyer, so I’d somewhat punt and define MoUs as liaisons agreements which the organization’s counsel declares not to contain contractual language.
