### ISSUE TITLE
Possibly dismissing a Formal Objection before it goes to full Council?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#678]
If we continue to have a lot of FOs, it may help to have a mechanism to dismiss them before Council, similar to the [Dismissal before trial](https://www.rothmanlawyer.com/dismissing-a-lawsuit-before-trial/) procedures in (at least) anglo-american jurisprudence.

It is by no means clear what could be grounds for "early dismissal" however, or who might be authorized to make such a decision, so this is probably not easy to pursue.

**Comment by chaals** [comment]
In principle this sounds good. It is not yet clear how well the Council establishes the trust of the community. "Someone convinced the objector to withdraw", is an existing mechanism which I hope would not be through discussion tinged with "we promise to make your life miserable if you don't withdraw". It's also possible that the Council dismisses some objections very fast, following the actual process laid out for it.

I don't think that working out how else to dismiss objections before they are considered by the council is a higher priority than making sure the council does a good job of resolving the objections that are brought to it, so I suspect this issue won't lead to an acceptable change proposal for a while, if at all.

**Comment by dwsinger** [comment]
I have a personal hope that the number of objections goes down, and the work of forming a Council for a decision that could have fallen into this case is rare and not too much trouble.  And that otherwise, working with the objector to find a resolution so that they withdraw the objection may happen.

I filed the issue mostly to put it on the radar as it's long term and could be easily forgotten.

**Comment by nigelmegitt** [comment]
I support the idea that we should not do the costly process of setting up an FO Council for essentially frivolous formal objections. Defining and assessing frivolity is likely to be difficult though. I have some ideas for possible reasons to dismiss early - probably incomplete list:

1. Objector says they cannot accept a Decision but proposes a resolution that is not substantively different. - in this case, doing nothing should also satisfy the objector.

2. The form of the FO is an instance of [Unacceptable Behaviours](https://www.w3.org/Consortium/cepc/#dfn-unacceptable-behaviors) as defined by the CEPC. (it could also happen to be that an instance of the "proposes a resolution that is not substantively different" is actually in the sub-category of "sustained disruption of discussion" that list)

3. "FO is not well formed", e.g. there's no evidence that efforts were made to resolve by consensus, or evidence that the objector did not participate in such efforts. Or that there's apparently no resolution that would satisfy the objector. "I object on the grounds that the Supreme Being told me in a dream that unstated Terrible Things will occur as a result of this Decision, and it's already too late to save the world."

4. FO seeks to reopen a previous Decision (possibly one made after a previous Director decision or FO Council) with no new information.

5. FO's only purpose is to try to modify the Process - that's out of the remit of the FO Council and should be done via the other available mechanisms, Process CG, AB etc. Might be difficult to decide that this is an FO's only purpose though.

6. FO attempts to do something that's directly contradicted by the Process.

**Comment by chaals** [comment]
The process of getting together a council should be straightforward anyway. If the council determines that there is some good reason to dismiss the FO quickly, by consensus, which can be achieved without a synchronous meeting, that seems a reasonable compromise between making sure that FOs are given a fair hearing and that there is a way to make such decisions without significant pain...

**Comment by nigelmegitt** [comment]
> The process of getting together a council should be straightforward anyway.

Straightforward is different from both "not much work" and "quick to complete" though. In practice what we can observe is that the team has significant work to prepare the Report, then there's an elapsed-time-consuming exercise to work out who should sit on the Council, before potentially a quick agreement. All of this has an opportunity cost.

**Comment by dwsinger** [comment]
Yes, we have to prepare a report, announce the council, accept reasons for dismissal over a period, identify a potential chair, hold the dismisal and chair appointment poll, doodle the remaining people to find a time, select it and plan the meeting (book Zoom etc.), seat the council – only to find that the recommendation is that the FO should be dismissed for an obvious reason, and the actual meeting takes 5 minutes. 

But as Nigel says, it's hard how to see to agree on the triviality without a body authorized to agree.

**Comment by palemieux** [comment]
In order to define the set of trivial FOs, one can define the complementary set of FOs, i.e. substantial FOs.

Substantial FOs are those that detail:
- what exactly is being objected to, including all relevant background information
- how rejection of the FO would:
  - cause irreparable harm to the objector and/or the W3C; and/or
  - result in a violation of the W3C rules
- concrete proposal(s) that would cure the FO
- demonstration that meaningful efforts have been made to resolve the FO

Knowing that trivial FOs could be dismissed in 5 minutes would discourage filing of frivolous FOs and would increase the overall quality of the FOs.

**Comment by mnot** [comment]
> "FO is not well formed", e.g. there's no evidence that efforts were made to resolve by consensus, or evidence that the objector did not participate in such efforts. 

While I agree that ideally people would participate in the process, input shouldn't be dismissed purely because they weren't in the WG. The whole point of the process is to get broad consensus and buy-in for the spec; there are times when a WG comes up something that the 'insiders' are satisified with, but when exposed to broader review is shown to be a bad idea.

**Comment by palemieux** [comment]
>  input shouldn't be dismissed purely because they weren't in the WG.

The objector should demonstrate that no consensus could be found despite their efforts to do so, regardless whether they are in the WG.

**Comment by mnot** [comment]
There's a lot loaded into that 'should'. We should ascertain whether there's adequate chance for them to do so.

**Comment by chaals** [comment]
> Yes, we have to prepare a report, announce the council, accept reasons for dismissal over a period, identify a potential chair, hold the dismisal and chair appointment poll, doodle the remaining people to find a time, select it and plan the meeting (book Zoom etc.), seat the council – only to find that the recommendation is that the FO should be dismissed for an obvious reason, and the actual meeting takes 5 minutes.

Let's unpack this:
- prepare the report

How long does this take? This is the report that creates the council, right? I.e. a summary of the formal objections. Unless the objection was team-confidential, isn't that just pasting the relevant survey answers into a document?

- announce the council

Is that much more than a copy-paste email? 

- accept reasons for dismissal over a period, 

Indeed. This takes a non-zero amount of work too. But nor does it seem likely to be onerous.

- identify a potential chair, 

Yes. If there's an obvious reason why the objection will be dismissed, chairing isn't going to be onerous so this should be easy.

(What's the normal process for identifying a chair?)

- hold the dismisal and chair appointment poll, 

Again, setting up WBS takes time. But not much.

- doodle the remaining people to find a time, select it and plan the meeting (book Zoom etc.), seat the council – only to find that the recommendation is that the FO should be dismissed for an obvious reason, and the actual meeting takes 5 minutes.

If the reason is obvious, and the meeting was only going to last 5 minutes, it should be easy to point that obvious reason out by email and achieve consensus without a meeting. Which saves the pain of a doodle.

I assume that the council has a mechanism already to communicate asynchronously. Is that true?

If, on the other hand, I believe as a council member that the objection is frivolous and without merit, but half the council initially believes otherwise (a realistic situation that has occurred), it's a good thing to go through the process - because it turns out a council will actually need to have a discussion perhaps much longer than 5 minutes...

**Comment by palemieux** [comment]
> There's a lot loaded into that 'should'. We should ascertain whether there's adequate chance for them to do so.

Yes, of course, which why input from the objector is needed. For example: have they been contacted by the target of the objection and have they been given the opportunity to provide input -- especially if they are not WG members?

**Comment by nigelmegitt** [comment]
@chaals 

> Let's unpack this:
> 
>     * prepare the report
> 
> 
> How long does this take? This is the report that creates the council, right? I.e. a summary of the formal objections. Unless the objection was team-confidential, isn't that just pasting the relevant survey answers into a document?

It's unclear how long it actually takes. It is significantly more than pasting survey answers in though: there's a timeline to go back over, links to minutes etc to find and paste, and the report writer needs to understand the decision and objection(s) and summarise them so that folk unfamiliar with them can get a quick understanding.

This is not a trivial task even if the report writer is well practiced.

> ...
>     * accept reasons for dismissal over a period,
> 
> 
> Indeed. This takes a non-zero amount of work too. But nor does it seem likely to be onerous.

This occupies AC and requires a minimum elapsed time.

> ...
> (What's the normal process for identifying a chair?)
> 
>     * hold the dismisal and chair appointment poll,

The dismissal process is vanishingly quick if nobody ever gets dismissed because the pool of members all find it impossible to believe that their colleagues might be influenced by conflicts of interest. This is an area that needs more scrutiny and thought, because right now it appears to be broken. And should probably be a separate issue...

> Again, setting up WBS takes time. But not much.
> 
>     * doodle the remaining people to find a time, select it and plan the meeting (book Zoom etc.), seat the council – only to find that the recommendation is that the FO should be dismissed for an obvious reason, and the actual meeting takes 5 minutes.

Doodles to get available times are likely to take a significant elapsed time to complete, followed by the time until the agreed meeting time occurs.

> If the reason is obvious, and the meeting was only going to last 5 minutes, it should be easy to point that obvious reason out by email and achieve consensus without a meeting. Which saves the pain of a doodle.

Cases like those should have been dismissed already though, to the point of this issue.

> ...
> If, on the other hand, I believe as a council member that the objection is frivolous and without merit, but half the council initially believes otherwise (a realistic situation that has occurred), it's a good thing to go through the process - because it turns out a council will actually need to have a discussion perhaps much longer than 5 minutes...

Agreed.

**Comment by frivoal** [comment]
I agree with Chaals that from the point you have a council appointed and presented with the report, it should be quick, and you don't need to spend time scheduling a meeting and sending doodles around if it's obvious that the FO should be dismissed. Mail will do just fine (and yes, Councils have a mailing list they can use for async communication).

It is true that writing a Team report typically takes time: this is not just copy-pasting the FO, it's also figuring out what's going on, documenting the facts, trying to bring the objector and the objectee to consensus if at all possible (making the FO go away), and documenting why it failed if it does. Complicated cases can certainly take weeks to look into, but we're specifically discussing the case of an FO that should be obvious to dismiss. If it's obvious, writing the report should be trivial. (if not, is it really that obvious?)

The other steps (related to dismissal and chair selection) do take clock time, but not much effort, and they're asynchronous.

So I concur that while quite some time could elapse between filing a ridiculous FO and having a Council dismiss it, I don't think it would take all that much work. So I don't think there's an issue.

And if it isn't all that obvious that the FO is frivolous, and somebody needs to spent the time to investigate it in order to conclude that it is, we're no longer dealing with something obvious that should be dismissed quickly.

**Comment by palemieux** [comment]
>  I don't think it would take all that much work.

I do not know where you get that information.

Preparing for a recent FO required dozens of hours from me, other WG participants and the team.

**Comment by frivoal** [comment]
We're specifically discussing the case of a trivial FO which should be entirely obvious, and be dismissed in 5 minutes. Those should not take dozens of hour to prepare for.

The FO you spent time preparing was not the sort that gets dismissed in 5 minutes.

**Comment by palemieux** [comment]
> The FO you spent time preparing was not the sort that gets dismissed in 5 minutes.

According to what criteria?

**Comment by palemieux** [comment]
To be sure, I recommend that, as [explained earlier](https://github.com/w3c/w3process/issues/678#issuecomment-1335965603), only substantial FOs be considered by a council.

**Comment by frivoal** [comment]
If you need to spend dozens of hours explaining something, then that thing isn't trivial.

----

As far as I can tell, you have a very legalistic, right vs wrong, process violation view of Formal Objections, but I do not believe this matches what they have been so far. Requiring irreparable harm and/or rule violations for an FO to be considered valid would be a massive departure from all W3C historic practice, and amounts to abandoning consensus as our decision making process.

FOs arise when consensus eludes us. There occasionally is a "they didn't even follow the rules" component to them, but that is hardly ever the core of the question. The Council is charged with figuring out if we're better off making an exception and moving forward despite the lack of consensus or not. Causing irreparable harm to someone is certainly likely to result in a lack of consensus, but it is far from the being the only reason anyone might object to anything.

Some things require WG consensus. Some things require consortium wide consensus. I could be mistaken, but I get the impression that you're fine with the former, and not with the later, and would rather have it so that a rule-abiding WG cannot be stopped, even in the absence of (consortium-level) consensus. I don't think this is what we're discussing here. If this is indeed what you would prefer, I suggest you open an issue about that.


For the case at hand, assuming we do continue to strive for (consortium-level) consensus, I believe:
* Formal objections, from anyone, for any reason, deserve, in principle, to be heard. Some may not be very strong cases, but the whole idea of striving for consensus is to listen to everyone.
* Most Formal Objections are not trivial. Most people are not trolls. We may agree or disagree with the objector, but the vast majority of Formal Objections are filed in earnest, by someone who thinks we're about to make a bad decision, and that they have something relevant to say to help us not do that. That's what the Council is for.
* For the occasional troll, it would be nice to find a way to short circuit things, and waste no time at all, but typically, determining if someone is a troll is a judgement call, which raises the question: whose judgement. We could empower the Team to do that, but that does not go in the "member led" direction we're trying for. Also, we'd need a appeal process, in case the Team gets it wrong sometimes, which Trolls would be just as happy to abuse, bringing us back to square one.
* Preparing the team report **for an obvious troll case** should not take much time. Other steps about convening the council does take clock time, but not much effort. Given how rare troll cases are, it's not a major concern if we occasionally take a bit of clock time to dispose of them.
* If not a troll, we could also be facing an earnest but clueless person, making in good faith arguments that obviously don't work (https://github.com/w3c/w3process/issues/678#issuecomment-1335173522 seems like a good first approximation of such things). If the person is in good faith, the Team, who deals with FOs before they get to the Council, should be able to explain away the vast majority of those, and get the FO to be retracted. And anyway, I do not believe this to be a meaningful problem in reality. Earnest clueless participants filing FOs are fairly rare.
* If we're facing an earnest but clueless yet stubborn person, they could resist the Team's attempts at explaining why they should withdraw, and insist on getting to the council. If they are indeed clueless and making arguments that obviously (to all) don't work, then by the very obviousness of it, it doesn't take very much time to dismiss it.
* And if they're not obviously clueless, then they deserve to be heard.

**Comment by mnot** [comment]
+1 to @frivoal. 

I have concerns about how heavyweight the FO process has become, but the solution isn't to hold them to a strict bar that obviates the reason we have a consensus-based consortium. In particular, a W3C Recommendation needs to reflect the consensus of the _entire_ community, not just those who show up in a particular working group. Most people invested in the future of the Web don't have the resources to monitor every single WG proactively.

**Comment by TzviyaSiegman** [comment]
+1 to @frivoal. I think the issue about how heavyweight the FO process has become is a separate issue @mnot - worth raising, recognizing that we are still in early days of this process.

**Comment by michaelchampion** [comment]
A few thoughts since this is on the AB agenda this week:
- +1 to @frivoal's points about "troll cases" above. The team should be empowered to recommend summarily dismissing a trivial / malicious FO, and the AB/TAG could agree to accept that recommendation without the full overhead of a Council.
- @nigelmegitt proposes defining what a "well formed formal objection" looks like.  That seems worthwhile.  Some FO's are long lists concerns and arguments; FOs that don't reference specific process concerns (e.g. implementation experience / interoperability) or specific widely-shared values  (A11Y, I18N, Privacy...).  Such FOs might  be dismissed up front, even if they are not "troll cases."
- Perhaps the FO Council *creation* process MUST require at least one (two? > 10%?) of  council members to advocate for at least considering the arguments in the FO based on the information in the FO itself and the Team's efforts to resolve it. Otherwise the FO is doomed, so why go through the whole time-consuming exercise?
- There's a hard question: are FOs the appropriate mechanism to advocate for un-written values (e.g sustainability, auditability by security researchers, preserving the business models that provide "free" web access)?  Or should those discussions happen in the Process, or when ratifying the TAG Ethical Principles document, or when electing AB/TAG/Directors???   I suppose that if there is a hard core of FO Council members prepared to advocate for an FO on such grounds, the FO Council could be the initial venue for such a discussion. If, hypothetically, a WG that proposed to standardize some aspect of a proof-of-work blockchain had been proposed a year ago and someone FO'd on the basis of sustainability, one might say the "first, do no harm"  consideration trumped the "whatever is not forbidden in the Process/Member Agreement/CEPC/etc.  is allowed" consideration IF a core group of Council members were willing to advocate for making sustainability an explicit value.

**Comment by fantasai** [comment]
> if a Council would have to spend a lot of time even understanding what an FO is actually about, there's no need to accept that burden

The Council is called upon because there was a hard problem and disagreement about the problem and the decision has been escalated to a higher authority. In some cases it will require time and effort to understand the problem; that's just part of the job. The Council can ask the objector for clarifications or more information if necessary, but "this looks hard I don't want to do it" is not an acceptable way to address an FO.

As a spec editor, my job is to address all the comments. Even the ones that are gnarly, the ones that seem confused, and the ones that seem trivial. The Council, likewise, has a job to address all FO, even the ones that are gnarly, that seem confused, or that seem trivial.

**Comment by dwsinger** [comment]
I agree with Elika. "It's going to be complicated" is a terrible reason to dismiss early. 

"This is identical to a previous FO and the ruling on that stands" (i.e. catch troll behavior) or "You are asking W3C to start taking on work in pharmaceutical quality testing and it's out of scope" (i.e. catch things that are obvious) or …

**Comment by mnot** [comment]
Let's be careful with the terminologhy we use here -- by nature 'troll' cases are difficult to identify -- most trolling is disguised as good-faith participation, so it requires some interpretation to identify a troll. Calling someone a troll (even if indirectly) is also a pretty strong accusation, and arguably there should be _more_ process around such a act.

**Comment by michaelchampion** [comment]
> I agree with Elika. "It's going to be complicated" is a terrible reason to dismiss early.

My point was more "An FO that is (perhaps deliberately) long and convoluted doesn't necessarily deserve the benefit of the doubt."  Definitely not "An FO that raises complicated / nuanced concerns can be dismissed because it makes peoples' heads hurt".

**Comment by frivoal** [comment]
Clarification on the above (as it was clear in context, but isn't captured in the wording of the resolution): this check to see if there's unanimity in accepting the Team's recommendation is to be run concurrently with the dismissal / chair selection process (logically, in the same wbs form), so that it does not slow anything down.

**Comment by frivoal** [comment]
Closed by #703
