### ISSUE TITLE
Editorial: dismissal

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#747]
In 5.6.2.3., this sentence isn't very helpful:

> In order to apply consistent criteria, the potential Council members decide collectively which reasons against service rise to a sufficient level for a potential member to be dismissed.

First, the purpose of dismissal surely isn't to just 'apply consistent criteria', is it? 

Also, 'reasons against service' is obscure, especially when the subject of the clause is at the very end of the sentence. 

I also suspect that 'potential Council members' (throughout) is an unnecessary phrasing; the use of 'dismissal' suggests that these people _are_ council members, they just leave, so you can just say that dismissal is the first order of business for a new council.

I'd suggest something like:

> To address potential conflicts of interest, a Council's first order of business is determining if any of its members should be _dismissed_.

**Comment by mnot** [comment]
Also, the following note (regarding the nature of a Council) is very oddly placed; I suspect it should be moved up to the end of 5.6.2.1.

**Comment by mnot** [comment]
... and, `They then consider for each potential member` is ambiguous -- who is 'they'?

**Comment by fantasai** [comment]
Opened a PR at https://github.com/w3c/w3process/pull/757 to address the first and last points here.

I didn't use your wording because dismissal isn't necessarily the first order of business; typically the Council runs several of these prepatory steps in parallel.

Also conflict of interest is only one possible reason for using dismissal; we're deliberately not defining what reasons qualify, only that if the rest of the Council wants you off, you're off.

The note is placed where it is because it's important contextual information for the previous sentence. (Though I agree it feels odd there.)

**Comment by frivoal** [comment]
In response to this issue, the following PR was made and approved https://github.com/w3c/w3process/pull/757/files

@mnot, Please confirm that this outcome is satisfactory.

**Comment by mnot** [comment]
That'll do.
