### ISSUE TITLE
Conflict of Interest in Council composition

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#749]
> Note: Since dismissal is individual, when the decision being objected to was made by the [TAG](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-architecture-group) or [AB](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-board) acting as a body, the entire [TAG](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-architecture-group) or [AB](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-board) is not expected or required to be dismissed.

The optics on this aren't very good; a body that makes a decision that's being appealed should not have oversight of the appeal.

The straightforward thing to do is to use an alternative process for appeals of TAG or AB decisions -- probably have the AB as the appeal body for the TAG, and the Board as the appeal body for the AB.

**Comment by plehegar** [comment]
I would note that the current Process has the same flaw: nothing forces the Director to delegate his authority, even if he has done so in the past on many occasion, such as the WWW 1.0 architecture TAG document moving to Recommendation. We could certainly add to our guidelines on this subject and potentially add to the Process in a future iteration if it remains unsatisfying.

**Comment by jyasskin** [comment]
For what it's worth, I think the method for [Appealing Council Decisions to the AC](https://www.w3.org/Consortium/Process/Drafts/#council-appeals) is likely to be sufficient in the case that a TAG or AB decision is appealed and upheld, but members think the Council's deliberations were unfair because the decision-makers got to vote on the appeal of their own decision.

For contentious decisions, the body that made the decision isn't likely to have made it unanimously, and if the rest of the council is convinced by the appeal, they're likely to be able to join with the minority of the original body to uphold the appeal.

It's true that the optics aren't perfect, but I also don't like the optics of declaring that the Board ([authority over finances and operations](https://www.w3.org/Consortium/Process/Drafts/#bod)) would be more trusted than the AB ([authority over strategy, management, legal matters, process, and conflict resolution](https://www.w3.org/Consortium/Process/Drafts/#ab-role)), which would be more trusted than the TAG ([authority over architecture](https://www.w3.org/Consortium/Process/Drafts/#tag-role)).

**Comment by mnot** [comment]
> but I also don't like the optics of declaring that the Board ([authority over finances and operations](https://www.w3.org/Consortium/Process/Drafts/#bod)) would be more trusted than the AB ([authority over strategy, management, legal matters, process, and conflict resolution](https://www.w3.org/Consortium/Process/Drafts/#ab-role)), which would be more trusted than the TAG ([authority over architecture](https://www.w3.org/Consortium/Process/Drafts/#tag-role)).

It's not about how much we trust people -- it's about being able to handle conflicts of interest in a way that is above reproach; it's about layering in checks and balances to do so.

For example, the IETF [allows appeals of process issues to the Internet Society Board of Trustees](https://www.rfc-editor.org/rfc/rfc2026#section-6.5). That doen't imply that they're more expert in process than (for example) the IESG; it's because they're a body that's broadly constittuted, relevant, and because they're unlikely to be involved in any dispute that comes to them. The same can't be said for the TAG and AB in many cases.

**Comment by nigelmegitt** [comment]
The same applies, i.e. the optics are bad, when a single member of the TAG or AB files an objection, and is then included in the Council that reviews that objection.

**Comment by jyasskin** [comment]
I still think the folks who iterated on this question in https://github.com/w3c/w3process/issues/278 arrived at a reasonable design, with an appeal to the members acting as a backstop in case a Council goes astray. As discussed there, it's very likely that experts on the Web will be somewhat involved in any serious dispute, so we can't assume that Board or AB members will be less partial than the body that deliberated the original decision. (It's also not quite right to say that having been involved in the decision being appealed is a "conflict of interest": conflicts of interest are when people have two different conflicting interests, but the Council-participant's interest in doing what's right for the Web is exactly the same as the TAG- or AB-member's interest that led them to make the decision being appealed.)

If that's not convincing; we don't find @mnot's point in https://github.com/w3c/w3process/issues/293#issuecomment-519782791 convincing (that we shouldn't make the AB handle technical issues); and there's still a lot of interest in having appeals of a body's decisions handled by a different (broadly constituted, relevant, and uninvolved) body, it might make sense to have the TAG handle AB appeals, and the AB handle TAG appeals, to avoid appearing to say that either body is "higher" than the other.

**Comment by nigelmegitt** [comment]
@jyasskin strong disagree. The arguments you cite are tangential to the key point that Council decisions should be fair, and transparently fair. Since it is possible, and there are examples where this has happened, that AC reps are also Council members, and get to participate on the deliberations and votes when reviewing their own objections, in private session, this is evidently not the case. Rather, it appears that there is bias in favour of organisations who happen to have managed to get their affiliates voted onto the Council.

This problem, and its associated optics, is compounded by the fact that the people who get to define the Process that permits this situation are themselves Council members.

**Comment by mnot** [comment]
> it might make sense to have the TAG handle AB appeals, and the AB handle TAG appeals, to avoid appearing to say that either body is "higher" than the other.

As I said, that would be acceptable. @jyasskin this isn't about making an original ruling; it's about an appeal/oversight function to act as a backstop.

**Comment by frivoal** [comment]
I agree the situation is delicate. At the same time, I think @jyasskin is right that with the availability of the appeal, with the council being broader than just the people who made the original decision, and with the growing practice that those council members who were a key stakeholders in the decision should refrain from swinging the vote, it should work out ok.

Also, delegating to the Board seems it wouldn't be very effective. The board may indeed be beyond reproach, but it is also likely to be way out of the loop and under-informed on the matters at hand. Fairness without insight is not useful in this context.

**Comment by dwsinger** [comment]
I can't see how we could assume that the Board would not have similar optics problems

**Comment by mnot** [comment]
Perhaps the best thing at this point would be to remove the Note quoted above -- it gives rather strong guidance that's relatively untested.

**Comment by chaals** [comment]
I think the Board would have similar optics problems. I also note that only the Board can bind the Board to do specific work, so giving them a role in this would turn into a request for them, and I am not sure they are lacking in work to do.

I'm not terribly fussed either way about removing the quoted note

> Note: Since dismissal is individual, when the decision being objected to was made by the [TAG](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-architecture-group) or [AB](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-board) acting as a body, the entire [TAG](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-architecture-group) or [AB](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-board) is not expected or required to be dismissed.

It also isn't obvious to me yet how it would play out if we strengthen the guidance for a body (TAG/AB) that took the original decision to abstain from voting on the final outcome. Not least because for all that individuals on both bodies represent themselves, there is an overlap in the communities from which they are drawn that I doubt will go away, because for the normal work of the two groups it's pretty rational.

This seems like an argument for recording individual votes, to provide transparency - and motivate the council to provide good transparency of the discussions on which they based their votes - as a real mechanism for accountability to the members who elected them.

**Comment by nigelmegitt** [comment]
> This seems like an argument for recording individual votes, to provide transparency - and motivate the council to provide good transparency of the discussions on which they based their votes - as a real mechanism for accountability to the members who elected them.

+1

**Comment by swickr** [comment]
Unlike a Board of Directors, members of the AB and TAG are not required to refrain from commenting openly when they disagree with a decision of the body in which they participate.  I interpret the Note as acknowledging that additional arguments presented in a Formal Objection may result in changes of individual opinions and that the members of each group are sufficiently informed to be able to dismiss colleagues whose participation would risk tainting the outcome so much as to lead to an appeal.

I think the note could be instructive but removing it would not be harmful.  With experience the Membership will be able to decide whether the practices that evolve are sufficient to result in an acceptable number of appeals.  A future edition of the Process can benefit from those experiences.

**Comment by fantasai** [comment]
The AB resolved:

> RESOLUTION: If there is an FO against a proposal of the (AB|TAG), the Council is constituted and deliberates as normal, but if there is not consensus and the Council conducts a vote, the members of the group who made the proposal do not get a vote

**Comment by mnot** [comment]
s/proposal/decision/?

Otherwise, WFM

**Comment by swickr** [comment]
I understand the resolution is intended to be read as "... all members of the AB [TAG] are excluded from voting in a Council vote".

This seems a very large gavel to be bringing down.  For instance, is it meant to apply strictly when the composition of the respective group has changed as a result of an election between the time the original decision was made and the Council deliberates?

If we find that we have numerous AC appeals this does present a risk of reducing the overall legitimacy of the Council concept. But we should allow ourselves to learn from specific cases and not speculate on especially problematic scenarios that could arise from a postulated FO to a decision of either the AB or the TAG.

Let's allow the AB and TAG members to show what they are actually capable of reasoning and writing.  Recent Council reports suggest that the Councils can do a thorough job of explaining their rationale for a decision.  Perhaps transparency in how Council members vote would help more (on all FO Council decisions) than excluding en-masse a large part of the eligible Council participants when the FO is to a decision of one of these two bodies.

We ought to be able to withstand an Appeal or three and thereby learn what we need to adjust in a future Process revision.

**Comment by mnot** [comment]
https://github.com/w3c/AB-memberonly/issues/171 adds an interesting twist to this. The TAG has proposed expanding its size; the AB has decided that it will grant that. If someone FOs, the result will likely be unanimous, because they have both been involved (proposer/decider). Under this proposal, that decision would stand. It hardly seems like legitimate oversight, though.

**Comment by hober** [comment]
Maybe the Process should say something like "if both the AB and the TAG would be excluded from voting, the Council MUST delegate"?

**Comment by fantasai** [comment]
Any FOs on Process 2023 will be decided by the Director, since we're still operating under Process 2022. As for the particular decision to expand the TAG, the TAG might have suggested the idea, but the Process is officially proposed by the AB... so technically I think only the AB needs to abstain from a vote...

But either way, if the Council decides by consensus, there's no vote.
