### ISSUE TITLE
word order "W3C Group Draft Note" -> "Draft W3C Group Note"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3process#779]
In working on messaging a new "W3C Group Draft Note", I struggle with parsing the words in that order. And I think "Draft" -- which is super important -- gets lost in that order.

May I suggest that we consider changing the word order?

best for clarifying draft status:
> Draft W3C Group Note

also OK I think:
> W3C Group Note Draft

**Comment by fantasai** [comment]
would “W3C Draft Group Note” work? Because I think that's probably a better title than the current “W3C Group Draft Note” which is actually kind-of awkward...

(Fwiw, the Process defines Note aka Group Note, and Draft Note, but not Draft Group Note or Group Draft Note--so the ordering of Group vs Draft is a tr-design/specberus issue.)

W3C Group Note Draft is also possible, but then we'd want to define “Note Drafts” rather than “Draft Notes” as currently, and I think that sounds slightly less comfortable? But can live with it.

**Comment by shawna-slh** [comment]
Thanks for stepping in @fantasai and @frivoal 

I think "W3C Draft Group Note" is a little better. Though, I still best is if Draft is first or last word.

**Comment by koalie** [comment]
The core concept is "W3C Group Note" (because it's a note from a W3C Group), so my preference is to put "Draft" first or last, but not to break apart "W3C Group Note".

I have a stronger preference for:

> Draft W3C Group Note

**Comment by fantasai** [comment]
@koalie The problem with that is that _all_ of our statuses currently follow the pattern "W3C [STATUS]". We should not break that pattern for draft notes only.

**Comment by dwsinger** [comment]
Aren't there at least 3 components to the name: W3C (who it comes from), note/recommendation/etc. (what it is), Draft/candidate/etc (what its status is)?

Yes, we tend to leave off some of these some of the time, e.g. we call things Working Draft when they are WDs of Recommendations.

Whether we need to do a wholesale renaming of concepts in order to get a consistent order and put back elided words I rather doubt...

**Comment by frivoal** [comment]
I wonder if we'd be better of simply dropping the word "Group" from this. Not sure it's buying us very much. "W3C Draft Note"?

**Comment by fantasai** [comment]
We could just go through and put "Draft" at the end for all things Draft. The oldest statuses (WD and CRD) already do this, so it'd just be a change to "Note Draft" and "Registry Draft" etc.

**Comment by dwsinger** [comment]
yes, beginning or end of the final name is good

**Comment by csarven** [comment]
"Draft" at the end is both readable and works with most common template/order (`W3C <document-type> <status>`).

**Comment by frivoal** [comment]
Made PR https://github.com/w3c/w3process/pull/819 to implement what seems to be the leading solution to this issue.

**Comment by nigelmegitt** [comment]
@chrisn I think it may sound better to prefix names with draft, but adding it as a suffix isn't too bad, and has the significant benefit of consistency with Working Draft, Editor's Draft (arguably an exception to the pattern because it's the only one whose name appears to assign ownership), CR Draft, Patent Review Draft and Discontinued Draft. On balance my view is that Note Draft and Registry Draft are acceptable names. In some ways the slightly awkward formulation of the name helps draw attention to the status.

**Comment by chrisn** [comment]
I'd personally prioritise readability over consistency, but don't want to block things if you're all in agreement.

**Comment by TallTed** [comment]
I strongly prefer the prefix form to the suffix form. Addressing the examples above....

* To my mind, `Working Draft`, `Editor's Draft`, `Patent Review Draft`, and `Discontinued Draft` are truncations of the prefix form, and all could benefit from added suffixes indicating the document types of which they are Drafts (e.g., CR, PR, Note, Registry, etc.). I think leaving those document type suffixes off of these names actually amounts to an error, because a stack of `Editor's Drafts` could easily include (and mix up) Notes, CRs, Registries, and more.

* `CR Draft` is easily transformed to `Draft CR`, which I think more clearly conveys its intended meaning.

* `Draft W3C Group Note` or `Draft W3C Note` or `Draft Group Note` all read clearly to me.

**Comment by frivoal** [comment]
What I like about the suffix form (in addition to consistency) is that it puts emphasis with the word Draft. Since we do seem to have a bit of a challenge with people thinking that anything coming out of w3c is a standard, highlighting that no, not everything is, and "this isn't a blablablabla, it's a blablablabla DRAFT", seems useful.

Now, that's my preference, but it's not a topic I don't care overly strongly about, and I can live with most any arrangement, including no change.

**Comment by nigelmegitt** [comment]
Another thought about achieving consistency and a logical approach: we tend to omit mention of who "owns" the document in question, usually because there only seems to be one option, which is the (Working) Group. However in the case of an Editor's Draft, we include it. In the case of a Draft _Statement_ we don't say something like "W3C Draft Statement", again because we take it that the only "group" that can publish a Statement is W3C.

So we have three explicit dimensions:
1. Who owns it?
2. Is it a Draft?
3. What Maturity Level is it?

In a complete naming schema we maybe would include all three. I _think_ the best order is the one I just listed above. Switching Draft to be at the end would also work, but the owner has to come first I think.

E.g. Editor's Draft Note, WG Draft CR, etc.

Maybe there's a case for a "shortened" form where the owner is implicit.

**Comment by frivoal** [comment]
> I think consistency can be achieved with either prefix DRAFT blablablabla or suffix blablablabla DRAFT.

Yes, but that would mean renaming many things, which I don't think is advisable.

**Comment by nigelmegitt** [comment]
Both concerns make sense to me @frivoal . I already noted that putting Draft at the end would work for me.

If we are considering any change to the naming scheme then it could imply renaming many things. When considering if it's worth bothering with such a change, this issue needs to be taken into account. However instead of requiring a mass rename we could consider:
* adopting the new name scheme for new documents only
* specifying a default mapping from old name scheme to new name scheme, so people can understand where historical documents would fit in the new scheme, without actually changing any of those historical documents.

**Comment by TallTed** [comment]
My last point: English generally puts adjectives before the noun they modify; `Draft <thing>` is more "natural" than `<thing> Draft`.

This ordering is different in other languages.

**Comment by fantasai** [comment]
Last meeting we resolved to do one of:

- 👍 Do nothing 
- ❤️ Adopt PR #819 to put "Draft" at the end for Note and Registry tracks.

Taking a straw poll here: pick your favorite via GH reaction?

**Comment by dwsinger** [comment]
Yes. The alternatives seem to insert the word "draft" into the middle of the string that is the document type/name, and that's wrong.

**Comment by shawna-slh** [comment]
> Yes. The alternatives seem to insert the word "draft" into the middle of the string that is the document type/name, and that's wrong.

Well, my preference (from the top of this issue), is to put Draft first. Though I'm OK with last.

**Comment by frivoal** [comment]
The straw poll is limited to two options because other alternatives faced objections.

**Comment by TallTed** [comment]
Consistency, even if it's not my favorite, is preferable to the status quo.

**Comment by frivoal** [comment]
resolved by merging https://github.com/w3c/w3process/pull/819
