### ISSUE TITLE
Are the rules for updating Registry Definitions appropriate?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#800]
Following discussion of the practicalities of including Registries in Rec track documents at https://lists.w3.org/Archives/Public/spec-prod/2023OctDec/0003.html it seems like there may be a Process bug regarding the process for updating Registry Definitions.

[§6.5.2](https://www.w3.org/2023/Process-20231103/#reg-pub) says that registry sections are "purely documentational". What does this actually mean? I initially read it as being "informative", or alternatively "can be changed outside the normal Rec track document process" but [§6.5.1](https://www.w3.org/2023/Process-20231103/#reg-def) requires that every registry table has a defined change process.

It would be absurd to require a strict process for how to change a registry data table but then allow that process itself to be modifiable without its own change process; I doubt that's the intention, but it seems to be the effect at the moment.

Another observation is that §6.5.2 refers to a singular Registry Section, but practically, as per w3c/dapt#196 for example, within a Rec track report incorporating registries, it makes sense to split the components of the Registries into different sections. Large parts of the definitions section are best placed away from the registry data tables themselves, which are best placed in the sections of the specification where they're used and relevant, because they're easier to read there.

So some attention is needed to check if the Process gets the cardinality of each type of section right.

**Comment by fantasai** [comment]
The Registry Definition has to follow the same rules as changes to other normative sections of a REC. The tables are subject to the rules in the Definition. The intention of the Process text there is to clarify that the Definition can't be normative on implementations and has no Patent Policy implications, but probably it's not very clearly explained.

**Comment by fantasai** [comment]
Wrt splitting the various parts of the registry for readability... I think that should be fine, and we can clarify that the Registry Section can in fact be split into multiple sections in various parts of the document. (We might want to call it something other than a Registry Section in that case, but I'm unsure what.)

**Comment by dwsinger** [comment]
Let's try to explain the terms here, and I think it will become clear. 

1) There is text in a Rec-track document that _defines_ the registry, its contents, management etc. That's part of the Rec and is subject to rec-track normal change management and approval. That's the Registry Definition.

2) one of the places you can put the registered material, the registry tables, is in the document that is also the Rec. That section needs to be clearly delineated as being the registry contents; from the point of view of the rec-track document it is purely informational and the rules for its revision are not the rules of rec-track documents, but the rules for that Registry. That's a registry section.

I hope I got this right. And that it makes sense.

**Comment by nigelmegitt** [comment]
> probably it's not very clearly explained

I think that's exactly the issue!

**Comment by nigelmegitt** [comment]
@fantasai said:

> (We might want to call it something other than a Registry Section in that case, but I'm unsure what.) It's just got to hang together as one Registry Section thing, even if the relevant text is split up for editorial purposes.

I think the concept of a single Registry Section isn't actually that helpful. Rather, it would make sense to say if the specification includes any (one or more) Registry Definitions, and if it includes any Registry Tables. Since they're separable concepts, what's the Registry Section here?

For example, consider a Rec track report that references an external document for the Registry Definitions, but inlines the Registry Tables for those definitions. (putting aside the conundrum of the two documents somehow cross-referencing each other)

Related, @dwsinger 's comment: 

> There is text in a Rec-track document that defines the registry, its contents, management etc. That's part of the Rec and is subject to rec-track normal change management and approval. That's the Registry Definition.

This makes sense conceptually - the problem is in getting to that result from the Process wording.

**Comment by dwsinger** [comment]
> what's the Registry Section here?

I believe a (not the) Registry Section is the body of a registry, some/the tables, inlined into the document.

**Comment by TallTed** [comment]
I wonder whether just changing `three associated components` to `three components` might be enough to resolve [the confusion described above](https://github.com/w3c/w3process/issues/800#issuecomment-1807984766). There may be no further changes necessary.

**Comment by nigelmegitt** [comment]
@TallTed I'm all in favour of making the smallest changes that achieve the goals; I'm struggling to see how that one change would do so fully in this case though. It doesn't clear up the confusion about which parts of a Registry are subject to which change processes for example.

**Comment by fantasai** [comment]
@nigelmegitt Drafted a PR that tries to address the confusion at https://github.com/w3c/w3process/pull/807 ; let us know what you think?

**Comment by nigelmegitt** [comment]
I just re-reviewed the current draft's section [§6.5 The Registry Track](https://www.w3.org/Consortium/Process/Drafts/#registries). I'm much happier now seeing the recent changes. In particular I found [6.5.3. Updating Registry Tables](https://www.w3.org/Consortium/Process/Drafts/#reg-table-update) clear in defining a specific call-out explaining how registry tables can be changed, and how the technical report that contains them can be republished, and that there is no such equivalent text for registry definitions.

>I wonder, do we lose something if we remove that third bullet, and rephrase the sentence announcing the list to "a registry consists of"?

@frivoal I do not think so, no. In fact, it's a good idea to move that third bullet out of the list, and rephrase to include "consists of". 

Consider the scenario in which a non-W3C SDO maintains the last referencing specification for some registry. It's out of W3C's remit to prevent that SDO from removing their reference, but at the moment when they do, apparently the registry would cease to be a registry, since it only contains a registry definition and one or more registry tables, but there are no referencing specifications. That would be an absurd situation.

My current status on this is that in principle such a change should resolve the issue for me.

**Comment by dwsinger** [comment]
There will always be an interval between the registry creation and its first reference, and this appears to introduce a paradox – the registry doesn't exist until it is referenced, but surely no-one can reference it until it exists.

I also contest the idea that a _reference_ to it is needed. Maybe the code-points in it are merely implemented? I think this might be trying to say that a registry is either embedded in a Rec or referenced by a Rec., but it doesn't say this very clearly.

**Comment by frivoal** [comment]
@dwsinger I think your comment is in support of my suggestion to
> remove that third bullet, and rephrase the sentence announcing the list to "a registry consists of"

but I am not 100% sure. Can you confirm?

**Comment by frivoal** [comment]
Just made https://github.com/w3c/w3process/pull/818, which I think will close the remaining concerns here.

**Comment by darobin** [comment]
For context, I landed here because I have the problem of chartering a registry _definition_ with normative requirements that I think could have PP implications. The general form is "_In order to be eligible for inclusion in table X, an entry must be defined so that it complies with Some Base Interface or Some User Agent Requirements_."

I looked at #818 and I'm still confused. If I track through the notions, here's how I trip up:

1. `6.5.6` says "A [registry report](https://www.w3.org/Consortium/Process/Drafts/#registry-report) or [embedded registry](https://www.w3.org/Consortium/Process/Drafts/#embedded-registry) is not subject to the W3C Patent Policy, and must not define any requirements on implementations."
2. Following the definition links, I get to `6.5.2` saying "[Registries](https://www.w3.org/Consortium/Process/Drafts/#registry) can be published either as a stand-alone [technical report](https://www.w3.org/Consortium/Process/Drafts/#technical-report) on the [Registry Track](https://www.w3.org/Consortium/Process/Drafts/#registry-track) called a registry report, or incorporated as part of a [Recommendation](https://www.w3.org/Consortium/Process/Drafts/#RecsW3C) as an embedded registry." So registry == (registry report | embedded registry) in terms of how they are instantiated. OK.
3. Again, following the definition link for registry, I hop to `6.5` that says (with @frivoal's change) "A registry consists of" and lists definitions and tables.

Presumably, (1) above enumerates all the instantiations of a registry as listed in (2), so that means that registries as a whole aren't subject to the PP. But if a registry cannot be subject to the PP, that means that none of its parts can be either. I think that's true of tables, but I don't think it is of definitions. I think that definitions can (should!) be normative, and given how broad and vague patents can be, I reckon that anything that can be normative could have PP implications.

**Comment by dwsinger** [comment]
Thanks @darobin . I think we may need to do more cleaning up of writing to make this clearer. The *definition* of a resgistry, its rules, content, approval regime, and so on, are all in the Definition, which has to be in a Rec., widely reviewed, subject to the PP, and so on. Anything mandatory is in the definition ("all implementations MUST implement the Nonce method, in order to test interoperability", for example).

the *tables* at that point are simply rows of "The value XX means YY as defined in ZZ". It's the rules for ZZ that tell you what the status (including under what policy, if any) of implementing XX is. So if "AVC" means the H.264/AVC standard as published jointly by ISO and ITU, then you know you're under the joint PP of ISO and ITU.

Now you know what I think the intent is, does it make your case easier to sort out?

**Comment by darobin** [comment]
@dwsinger I understand the intent and I'm glad it aligns with what I want, thanks :) It makes more sense that way. But I think that `6.5.6` contradicts that intent since it applies (transitively) to registry _definition_s as well.

Maybe the easiest fix is for `6.5.6` to state instead: "A registry table is not subject to the W3C Patent Policy, and must not define any requirements on implementations."

**Comment by dwsinger** [comment]
Sounds like a drafting bug in 6.5.6 indeed

**Comment by frivoal** [comment]
@nigelmegitt we've merged #818. Is that good enough to close this issue, or are there lingering concerns?

**Comment by nigelmegitt** [comment]
@frivoal yes, it's good enough for me, for the issue I raised - you may want a separate issue for @darobin 's additional issue, or resolve it here first though?

**Comment by fantasai** [comment]
I think if @darobin or @dwsinger want to raise additional issues, they should do those separately. :) Gonna declare this one closed.
