### ISSUE TITLE
Written notification?

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#83]
In section 3.6 Resignation from a group, it says "On written notification from an Advisory Committee representative...". Does the notification from SysBot (when an AC rep unhooks someone from the WG/IG) qualify as "written notification"?

**Comment by dwsinger** [comment]
I think in this sense the contrast is with verbal. i.e. telling the team over a coffee doesn't work

**Comment by LJWatson** [comment]
Makes sense. Wonder if "When an AC rep withdraws a participant using the XYZ mechanism, or on other written notification..." (where XYZ is the proper name for that thing) would make it clearer?

**Comment by chaals** [comment]
I think what we mean is archived evidence that the member resigns. I certainly believe that unhooking counts.

I would rather leave this as is myself, but others may differ... Looking for a decision before I make a change.

**Comment by LJWatson** [comment]
I think the text could be clearer (suggested text ^^). Not a showstopper if there isn't much conviction for changing though.

**Comment by chaals** [comment]
I agree we should think about how to make it clearer. I'm not sure I want to use 'through the "patent-policy implementation" form or other written notification' in the text though.

**Comment by dwsinger** [comment]
"On written notification from an Advisory Committee representative or Invited Expert to the team, the Member and their representatives or the Invited Expert will be deemed to have resigned from the relevant group."

Does this sentence add anything? Could we just delete it? Or maybe we should say that they are deemed to have resigned when they are not shown as members of the group, but previously were? Or does that leave us open to possible database errors?

**Comment by chaals** [comment]
I think just asuming the database magically gets it right is a bad idea. And sending a note to W3C saying "We are resigning from group X now" should work, IMHO, as well as doing it through whichever baroque interface is currently working or you happened to find through the website search system...

**Comment by LJWatson** [comment]
Perhaps just "formal notification"?

**Comment by chaals** [comment]
Except that's pretty vague in what counts and doesn't. If I stand up at the coffe table and say it formally, or if I am wearing a suit and tie instead of shorts and bare feet, or if I write it on letterhead...

Yes these are silly examples, but the point is that written gives some clearer hints. I think what we mean is in an archivable form, directed to a person or system that should be empowered to act on the notification. But that's something of a mouthful, and not necessarily clear when people read it.

**Comment by dwsinger** [comment]
deferred to next year

**Comment by dwsinger** [comment]
maybe "recorded" notification?

**Comment by chaals** [comment]
The complication might be slightly different. A member joins or leaves a group, but nominates and removes representatives as a separate action - i.e. it  is perfectly feasible for an organisation to formally participate in a group, which crucially has patent policy implications, despite having no actual representative in the group.

I wonder if it is important to make that distinction in the text. Otherwise I am happy with "recorded", or "written", or "reasonably reproducible, e.g. by email or through a tool designed to do so"...

**Comment by dwsinger** [comment]
sounds like we're going with "recorded" notification?

**Comment by dwsinger** [comment]
Can we close this? we now say " The team must record the notification." in 3.6

**Comment by frivoal** [comment]
@dwsinger I'm not sure we need to talk on the call. A PR was made to solve this issue, it has been accepted and merged. We should just close this.

**Comment by dwsinger** [comment]
It probably didn't need discussion. I added Agenda+ to agree this can be closed, but it's busy work. Closing.
