### ISSUE TITLE
Definition of "extraordinary" in 7.2

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#89]
In 7.2 Appeal by Advisory Committee Representatives, it says:
>"Advisory Committee representatives may appeal certain decisions, though appeals are only expected to occur in extraordinary circumstances.">

What does "extraordinary" mean in this context?

**Comment by dwsinger** [comment]
don't we wish we knew. I think it means roughly that the community thinks that the Director has gone off the rails, didn't think, didn't consult, and is generally out to lunch, but others may feel otherwise. I think the word is there as a warning "don't pull this lever frivolously". Without lots of text I can't see how to improve this...

**Comment by michaelchampion** [comment]
Agree with @dwsinger -- I don't think we can define it without a lot of discussion.  I wouldn't mind if we insisted on  evidence that the Director has gone off the rails, but I doubt if a discussion would be fruitful until the wounds surrounding the current appeal have healed a bit.

**Comment by chaals** [comment]
5% of members prepared to state that they think something sufficiently out of the ordinary has happened that the Director's decision should be reconsidered by the membership seems like a workable practical definition to me. And common meanings of "not ordinary, exceptional, unusual" seem sufficient to cover the meaning here.

That we expect the Director's decisions **not** to be appealed in general, even by a mere 5% of members, strikes me as extraordinary - and a positive reflection on W3C.

We could strike the phrase IMHO, since it is hopeful expectation setting rather than any kind of rule or obligation, but I am happy to leave it there.

**Comment by dwsinger** [comment]
I'd like to leave the "extraordinary" there because it gives a tool to other AC reps to ask, when someone asks for the 5% support "OK, please detail what the extraordinary circumstances are, in this case"? i.e. I think the word is a tool for the discussion, not directly for process.

**Comment by LJWatson** [comment]
I like the suggestion that evidence should be provided, but agree this is a thing better left a little while. Happy for this issue to be closed in the meantime...
