### ISSUE TITLE
Should participants in Working Groups be allowed to represent more than one organisation?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#9]
Transferred from https://www.w3.org/community/w3process/track/issues/162
State: Open

**Comment by dwsinger** [comment]
We need to ask for PSIG input and some actual cases.

**Comment by sandhawke** [comment]
One specific data point:

In one of my WGs (call it WG1), there's an IE who's the editor of a core spec.  He works as a contract developer.  I think he had a crowdfunded non-profit contract supporting some of this work, but then he kept doing it when that money ran out, if I understand right.

Meanwhile, in a completely different part of W3C (call it WG2), he recently got a contract with a Member Organization which includes representing them in WG2.  That Member has no interest in WG1 and doesn't want to be associated with it.

So, we're left with him an IE in WG1 and a Member representative in WG2.

team-legal told me this was okay, as long as he disclosed, which he's done in WG1 at least.

Of course we also have the problem that the telecons for both groups are at the same time, but the Process can't help with that!

**Comment by chaals** [comment]
@sandhawke Thanks for the concrete data. As I understand it, since participation requirements - crucially including the patent policy - are generally scoped by Working Group.

So I think this question can be scoped down to cover someone who has 2 employers, and represents them both in the same WG. 

The question of what their patent commitments are, or need to be, is I think for PSIG in the first instance, but my immediate take is that if they make commitments on behalf of both employers nobody will be unhappy.

The question of e.g. member access, and "related members" is, I *think*, reasonably straightforward. I'll follow up with another real case that touches on this.

If a Working Group uses votes to resolve a question, then I think whether a single person can hold two votes is material, although that section of the process is IMHO a mess - there are lots of helpful ideas about getting consensus, but there is nothing about what amounts to a Working Group decision, so it's basically left to the WG to assert that they have one, and the Director to agree or argue the case - which matters primarily in transition requests, and secondarily will be looked at more closely if there is actually dissent.

The Patent Policy can't be changed by this group. Nor is there anyone clearly able to push a change, although presumably at minimum the director could propose a change, ask for AC review and see what happens… This is a live issue given that there are some changes in the Process that affect at least the wording of the Patent Policy, such as moving the Last Call state to CR, although I don't think they are controversial in practice.

**Comment by chaals** [comment]
(Anec)Data point: Web Platform WG has participants who are contracted by other members to do certain pieces of work. They disclose these relationships according to the "related members" procedures, and it all seems OK.

In these cases, the participants do not claim to formally *represent* the related member. One possible outcome is that we actively ask them to do so, or even require it as a condition of participation, by changing the "related members" provisions, as well as removing the constraint that at the moment it is not allowed. There are other possible outcomes…

**Comment by dwsinger** [comment]
I think that we may need to stick with 'they represent the organization whose AC rep appointed them to the WG' since it is that appointment process that confirms the org's involvement and agreement. So, I am curious, what is to stop two or more AC Reps from nominating the same person? I will ask the team.

As to whether their behavior is being controlled by some other entity than the nominating AC Rep's one, that's a question for chairs/team/other-participants. E.g. nominated by the AC Rep for 'Trouble for Hire Consulting Inc.' and then reveals that they are working 100% under contract to 'Nefarious Trolls PLC', one might hope that at that point the team/chair notice and suggest that the AC Rep for NT PLC nominate them, if they are a member. We cannot catch, in the process, all the ways that influence might be acquired.

**Comment by vfournier17** [comment]
I brought this up at PSIG on 6/12.  Some different views were expressed, such as - (i) is this really an issue that needs to be addressed?  (2) Could they provide some that show how the one person/one member language is problematic? (3) If it ain't broke, don't fix it. (4) there really isn't a compelling case either way. (5) this could come up with contractors who might represent more than one (small) company - each company can't afford their own person.  (6) transparency is important - need to know who is representing who.  In the end, PSIG had mixed views, and there wasn't a strong view one way or the other.

**Comment by dwsinger** [comment]
we would prefer to wait for an actual problem here; not taking this up yet. Someone could ask for permission to be nominated by more than one member (AC Rep).

**Comment by chaals** [comment]
There are actual people, who are known to be working for more than one W3C member simultaneously on the same work, in current Working Groups.

As far as I can tell, someone might ask to be nominated by more than one AC rep, but according to the current Process W3C would have to deny that request since it is not allowed.

**Comment by vfournier17** [comment]
Hi Charles,

Would you please provide some examples?

Remember that we proposed a notice requirement so that such a rep would need to disclose that they’re representing more than one member (a person can’t represent more than one member unless they provide notice, etc.).  This does not seem particularly onerous or prohibitive.  Of course, this requirement would only apply prospectively, and not retroactively.


Best regards,

Virginia Fournier
Senior Standards Counsel
 Apple Inc.
☏ 669-227-9595
✉︎ vmf@apple.com <mailto:vmf@apple.com>






On Jul 12, 2017, at 11:20 AM, chaals <notifications@github.com> wrote:

There are actual people, who are known to be working for more than one W3C member simultaneously on the same work, in current Working Groups.

As far as I can tell, someone might ask to be nominated by more than one AC rep, but according to the current Process W3C would have to deny that request since it is not allowed.

**Comment by dwsinger** [comment]
> On Jul 12, 2017, at 11:38 , Virginia Fournier <notifications@github.com> wrote:
> 
> Hi Charles,
> 
> Would you please provide some examples?
> 
> Remember that we proposed a notice requirement so that such a rep would need to disclose that they’re representing more than one member (a person can’t represent more than one member unless they provide notice, etc.). This does not seem particularly onerous or prohibitive. Of course, this requirement would only apply prospectively, and not retroactively.
> 

I think we would want an electronic trace. Say, for example, 

Mordred, the AC Rep of Mordor Inc.
and Lucifer, AC Rep of Purgatory Inc.

want Leovigild to represent them in a group.

I would want it to be possible (a) for them both to nominate him and (b) the membership of the group clearly indicate that Mordor and Purgatory are under patent commitment and therefore (c) exclusion notices to go to Mordred and Lucifer.

I suspect that this is trivially achieved by having Lucifer have two accounts, lucifer@mordor.edu and lucifer@purgatory.net, whereupon it ‘just works’.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by vfournier17** [comment]
This could work.  How do we confirm (b)?

**Comment by dwsinger** [comment]
I would expect the member-visible list of participants, partic. when sorted by Member Organization, to show the same person under two member orgs. <https://www.w3.org/2000/09/dbwg/details?group=42434&order=org> is an example

**Comment by michaelchampion** [comment]
I'm not understanding why there is a problem worth changing the Process to solve. With no changes to the Process or implementation, both Mordor and Lucifer join the WG. Either Mordor or Lucifer appoint Leovigild as a rep, and he/she/it discloses both affiliations.  The AC reps for both get notified of exclusion opportunities. Others can track patent commitments because they come from members who have joined WGS not from reps they may okay not appoint.

**Comment by dwsinger** [comment]
If only Mordred joins the WG, why would Lucifer get notifications? 

I think it's way simple to say "if you want to represent two orgs, get an account associated with each org"

**Comment by michaelchampion** [comment]
Both joined the WG and thus have traceable patent commitments. Only one appoints a rep, but that is procedurally distinct from joining a working group.

I don't object to the one person two email addresses hack... I'm just not sure there is a problem worth the effort to solve here.

**Comment by dwsinger** [comment]
OK, so there are (at least) two no-change solutions:
a) both orgs join the WG, only one nominates the delegate, and the delegate self-reveals the interest
b) the delegate gets two accounts on the W3C site, one for each org, and they each nominate the delegate under their account

Given this, I doubt we need systems or process changes.

**Comment by chaals** [comment]
Your option b) seems to contradict the Process as written:

> A participant <em class="rfc2119">must</em> represent at most one organization

I'm not sure how to read that to allow someone to be nominated by more than one organisation.

I agree that option a) *works* in terms of Process and Patent Policy. 

It seems suboptimal to insist that is the only possible way to do it, and outlaw both b) and actually having a system that just let the one person be recorded as representing two organisations.

**Comment by dwsinger** [comment]
Sorry, I was assuming we went with your PR to delete that restriction, but otherwise, we seem to have two working options.

**Comment by dwsinger** [comment]
This seems worth pursuing but lacking consensus and active worked examples, it's not a 2018 priority.

**Comment by dwsinger** [comment]
see also #9, closed in favor of this one

**Comment by vfournier17** [comment]
So, is the resolution to leave the language as is?  That is our preference.

**Comment by chaals** [comment]
I prefer to make the change, but it is unclear to me if we have a resolution on that. There is not an obvious consensus, but my understanding is that I am the only one who wants to resolve this now, and consequently it is not going to change in the current revision  :(

**Comment by dwsinger** [comment]
I don't think we have consensus on the problem/use cases, or on the scope of the proposed fix, or the urgency, so at the moment it's not on our priority list...

**Comment by frivoal** [comment]
We've had PR #54 as a proposal to this for a while, but could not get consensus on it. Based on the discussions there, I've made https://github.com/w3c/w3process/pull/219 as an alternative proposal.
