### ISSUE TITLE
"next steps" for CR/PR/REC seem out of sync with rules for revising a recommendation

### ISSUE THREAD

**Issue by dbaron** [w3c/w3process#95]
I'm reviewing the [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FConsortium%2FProcess%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fw3process%2F) between the [operational Process](https://www.w3.org/Consortium/Process/) and the [editor's draft](https://w3c.github.io/w3process/), and I noticed that the "next steps" lists at the ends of 6.4, 6.5, and 6.6 seem to be a little out of date.  In particular, they don't seem to reflect the new possibilities in 6.7.2 (some of which are new in this revision, and some from the last one).  In particular:

6.6 (REC) should mention that another possible next step is CR, since 6.7.2 allows that.

6.5 (PR) should perhaps somehow say that 'Recommendation status (the expected next step)' can include Edited or Amended Recommendation (depending on the origin)

6.4 (CR)/6.5 (PR) say that possible next steps are:
 1. return to WD
 2. revised CR / return to CR
 3. PR / REC
 4. WG NOTE

Is it intended that 1 and 4 are possible if the CR exists as a revision of a recommendation?  If it's intended that REC -> CR -> WD is possible, then I tend to think the process should also allow REC -> WD directly.  I guess I'm less worried about NOTE, but it does seem a little weird.

(Or, alternately, maybe 6.4 and 6.5 don't apply to CRs and PRs that result from revising a REC?  If that's the case, it should be more explicit.)

**Comment by chaals** [comment]
Thanks for picking these up. There does need to be an update.

My understanding is that a CR could be sent back to WD if it is a revision of a Rec, e.g. because the Direfctor deems (perhaps on advice) that something is a new feature...

The Note bit is because you can abandon work at any stage. I am not sure that it has happened at PR - there are very few PRs I can think of that got returned for more work, although it has happened.

But I can imagine a PR being proposed, a large proportion of the membership suggesting it is not a good thing, and the Director deciding to park the work done as a NOTE rather than continue at all.
